/** Product brand — multi-tenant ERP platform */
export const APP_NAME = "SecureTrack ERP";
export const APP_SHORT_NAME = "SecureTrack";
export const APP_TAGLINE = "Secure • Intelligent • Connected";
export const APP_SUBTITLE = "Enterprise Resource Planning Platform";
/** Default demo / seed tenant legal name (not product brand) */
export const COMPANY_NAME = "SecureTrack ERP";
export const PRODUCT_VENDOR = "SecureTrack";

/** Core platform module codes (catalog) */
export const PLATFORM_MODULE_CODES = [
  "executive", "bi", "finance", "payroll", "hr", "talent", "attendance",
  "crm", "sales", "procurement", "inventory", "manufacturing", "fleet",
  "assets", "projects", "identity", "audit", "platform",
] as const;

export const PRODUCTION_STATUSES = [
  "draft",
  "in_progress",
  "qc_pending",
  "approved",
  "rejected",
  "packed",
  "completed",
  "archived",
] as const;

export const QR_CODE_STATUSES = [
  "generated",
  "printed",
  "verified",
  "packed",
  "dispatched",
  "sold",
  "recalled",
  "voided",
  "counterfeit",
] as const;

export const PRINT_JOB_STATUSES = [
  "pending",
  "queued",
  "printing",
  "paused",
  "completed",
  "failed",
  "cancelled",
] as const;

export const ROLE_SLUGS = {
  SUPER_ADMIN: "super_administrator",
  MANAGING_DIRECTOR: "managing_director",
  OPERATIONS_MANAGER: "operations_manager",
  PRODUCTION_MANAGER: "production_manager",
  PRODUCTION_SUPERVISOR: "production_supervisor",
  PRODUCTION_OPERATOR: "production_operator",
  QUALITY_ASSURANCE: "quality_assurance",
  WAREHOUSE_MANAGER: "warehouse_manager",
  WAREHOUSE_CLERK: "warehouse_clerk",
  SALES_MANAGER: "sales_manager",
  SALES_EXECUTIVE: "sales_executive",
  DISTRIBUTOR: "distributor",
  RETAILER: "retailer",
  CUSTOMER_SERVICE: "customer_service",
  AUDITOR: "auditor",
  READ_ONLY: "read_only",
} as const;

export const PERMISSIONS = {
  DASHBOARD_VIEW: "dashboard.view",
  SETTINGS_VIEW: "settings.view",
  SETTINGS_MANAGE: "settings.manage",
  SETTINGS_BRANDING: "settings.branding",
  SETTINGS_INTEGRATIONS: "settings.integrations",
  SETTINGS_SEQUENCES: "settings.sequences",
  SETTINGS_WORKFLOWS: "settings.workflows",
  USERS_VIEW: "users.view",
  USERS_MANAGE: "users.manage",
  PRODUCTION_VIEW: "production.view",
  PRODUCTION_CREATE: "production.create",
  PRODUCTION_EDIT: "production.edit",
  PRODUCTION_MANAGE: "production.manage",
  QUALITY_APPROVE: "quality.approve",
  QR_GENERATE: "qr.generate",
  QR_VIEW: "qr.view",
  PRINTING_CREATE: "printing.create",
  PRINTING_MANAGE: "printing.manage",
  PRINTING_REPRINT: "printing.reprint",
  LBL_VIEW: "lbl.view",
  LBL_MANAGE: "lbl.manage",
  LBL_DESIGN: "lbl.design",
  LBL_PRINT: "lbl.print",
  LBL_APPROVE: "lbl.approve",
  LBL_SECURITY: "lbl.security",
  LBL_AI: "lbl.ai",
  LBL_ADMIN: "lbl.admin",
  PACKING_CREATE: "packing.create",
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_MOVE: "inventory.move",
  INVENTORY_MANAGE: "inventory.manage",
  VERIFICATION_VIEW: "verification.view",
  FRAUD_MANAGE: "fraud.manage",
  FRAUD_INVESTIGATE: "fraud.investigate",
  REPORTS_VIEW: "reports.view",
  REPORTS_EXPORT: "reports.export",
  REPORTS_MANAGE: "reports.manage",
  REPORTS_DASHBOARDS: "reports.dashboards",
  REPORTS_KPIS: "reports.kpis",
  REPORTS_AI: "reports.ai",
  REPORTS_REGULATORY: "reports.regulatory",
  REPORTS_DOCUMENTS: "reports.documents",
  REPORTS_SCHEDULE: "reports.schedule",
  REPORTS_INTELLIGENCE: "reports.intelligence",
  REPORTS_SEARCH: "reports.search",
  REPORTS_ASSISTANT: "reports.assistant",
  REPORTS_DWH: "reports.dwh",
  REPORTS_CLASSIFY: "reports.classify",
  NOTIFICATIONS_VIEW: "notifications.view",
  NOTIFICATIONS_MANAGE: "notifications.manage",
  NOTIFICATIONS_SEND: "notifications.send",
  AUDIT_VIEW: "audit.view",
  AUDIT_MANAGE: "audit.manage",
  DISTRIBUTORS_VIEW: "distributors.view",
  DISTRIBUTORS_MANAGE: "distributors.manage",
  PRODUCTS_VIEW: "products.view",
  PRODUCTS_MANAGE: "products.manage",
  SALES_VIEW: "sales.view",
  SALES_MANAGE: "sales.manage",
  SALES_PIPELINE: "sales.pipeline",
  SALES_QUOTES: "sales.quotes",
  SALES_CREDIT: "sales.credit",
  SALES_RETURNS: "sales.returns",
  SALES_COMMISSIONS: "sales.commissions",
  SALES_PRICING: "sales.pricing",
  SALES_CONTRACTS: "sales.contracts",
  SALES_FORECAST: "sales.forecast",
  SALES_AI: "sales.ai",
  SALES_ADMIN: "sales.admin",
  INVOICES_VIEW: "invoices.view",
  INVOICES_MANAGE: "invoices.manage",
  BILLING_VIEW: "billing.view",
  BILLING_MANAGE: "billing.manage",
  BILLING_APPROVE: "billing.approve",
  BILLING_COLLECT: "billing.collect",
  BILLING_TAX: "billing.tax",
  BILLING_DESIGN: "billing.design",
  BILLING_RECURRING: "billing.recurring",
  BILLING_AI: "billing.ai",
  DISPATCH_VIEW: "dispatch.view",
  DISPATCH_MANAGE: "dispatch.manage",
  DSP_VIEW: "dsp.view",
  DSP_MANAGE: "dsp.manage",
  DSP_OPERATE: "dsp.operate",
  DSP_APPROVE: "dsp.approve",
  DSP_AI: "dsp.ai",
  DSP_TRACK: "dsp.track",
  HR_VIEW: "hr.view",
  HR_MANAGE: "hr.manage",
  TA_VIEW: "ta.view",
  TA_MANAGE: "ta.manage",
  TA_RECRUIT: "ta.recruit",
  TA_APPROVE: "ta.approve",
  TA_AI: "ta.ai",
  TA_ADMIN: "ta.admin",
  TA_PORTAL: "ta.portal",
  WID_VIEW: "wid.view",
  WID_MANAGE: "wid.manage",
  WID_DESIGN: "wid.design",
  WID_PRINT: "wid.print",
  WID_ACCESS: "wid.access",
  WID_SECURITY: "wid.security",
  WID_VERIFY: "wid.verify",
  WID_BIOMETRICS: "wid.biometrics",
  PRINTERS_MANAGE: "printers.manage",
  WFM_VIEW: "wfm.view",
  WFM_MANAGE: "wfm.manage",
  WFM_APPROVE: "wfm.approve",
  WFM_FIELD: "wfm.field",
  WFM_SAFETY: "wfm.safety",
  CRM_VIEW: "crm.view",
  CRM_MANAGE: "crm.manage",
  CRM_MARKETING: "crm.marketing",
  CRM_SERVICE: "crm.service",
  CRM_LEADS: "crm.leads",
  CRM_OPPORTUNITIES: "crm.opportunities",
  CRM_AI: "crm.ai",
  CRM_PORTAL: "crm.portal",
  CRM_CREDIT: "crm.credit",
  CRM_ADMIN: "crm.admin",
  CRM_EXPORT: "crm.export",
  IAM_VIEW: "iam.view",
  IAM_MANAGE: "iam.manage",
  IAM_SECURITY: "iam.security",
  IAM_SESSIONS: "iam.sessions",
  IAM_APPROVALS: "iam.approvals",
  PROCUREMENT_VIEW: "procurement.view",
  PROCUREMENT_MANAGE: "procurement.manage",
  PROCUREMENT_APPROVE: "procurement.approve",
  PROCUREMENT_SUPPLIERS: "procurement.suppliers",
  SRM_VIEW: "srm.view",
  SRM_MANAGE: "srm.manage",
  SRM_APPROVE: "srm.approve",
  SRM_CONTRACTS: "srm.contracts",
  SRM_QUALITY: "srm.quality",
  SRM_AI: "srm.ai",
  SRM_PORTAL: "srm.portal",
  SRM_ADMIN: "srm.admin",
  LOGISTICS_VIEW: "logistics.view",
  LOGISTICS_MANAGE: "logistics.manage",
  SCM_VIEW: "scm.view",
  SCM_MANAGE: "scm.manage",
  SCM_SOP: "scm.sop",
  SCM_RISK: "scm.risk",
  FINANCE_VIEW: "finance.view",
  FINANCE_MANAGE: "finance.manage",
  FINANCE_POST: "finance.post",
  FINANCE_APPROVE: "finance.approve",
  FINANCE_BANK: "finance.bank",
  FINANCE_TAX: "finance.tax",
  FINANCE_CLOSE: "finance.close",
  FINANCE_AI: "finance.ai",
  FINANCE_CFO: "finance.cfo",
  FINANCE_COSTING: "finance.costing",
  FINANCE_TREASURY: "finance.treasury",
  FINANCE_CONSOLIDATE: "finance.consolidate",
  FINANCE_ADMIN: "finance.admin",
  INTG_VIEW: "intg.view",
  INTG_MANAGE: "intg.manage",
  INTG_API: "intg.api",
  INTG_WEBHOOKS: "intg.webhooks",
  INTG_WORKFLOWS: "intg.workflows",
  INTG_SECURITY: "intg.security",
  INTG_IOT: "intg.iot",
  INTG_MONITOR: "intg.monitor",
  PROFILE_VIEW: "profile.view",
  PROFILE_MANAGE: "profile.manage",
  PROFILE_SELF: "profile.self",
  PROFILE_MANAGER: "profile.manager",
  PROFILE_PAYROLL: "profile.payroll",
  PROFILE_DOCUMENTS: "profile.documents",
  PROFILE_SECURITY: "profile.security",
  PROFILE_ANALYTICS: "profile.analytics",
  PROFILE_AI: "profile.ai",
  SD_VIEW: "sd.view",
  SD_MANAGE: "sd.manage",
  SD_AGENT: "sd.agent",
  SD_ADMIN: "sd.admin",
  SD_KNOWLEDGE: "sd.knowledge",
  SD_CHANGE: "sd.change",
  SD_AI: "sd.ai",
  SD_PORTAL: "sd.portal",
  SD_APPROVE: "sd.approve",
  SD_MAJOR: "sd.major",
  SD_FIELD: "sd.field",
  HC_VIEW: "hc.view",
  HC_MANAGE: "hc.manage",
  HC_MEETINGS: "hc.meetings",
  HC_ANNOUNCE: "hc.announce",
  HC_AI: "hc.ai",
  HC_ADMIN: "hc.admin",
  BRAND_VIEW: "brand.view",
  BRAND_MANAGE: "brand.manage",
  BRAND_DESIGN: "brand.design",
  BRAND_APPROVE: "brand.approve",
  BRAND_PUBLISH: "brand.publish",
  BRAND_AI: "brand.ai",
  BRAND_ASSETS: "brand.assets",
  PAYROLL_VIEW: "payroll.view",
  PAYROLL_MANAGE: "payroll.manage",
  PAYROLL_PROCESS: "payroll.process",
  PAYROLL_APPROVE: "payroll.approve",
  PAYROLL_PAY: "payroll.pay",
  PAYROLL_SELF: "payroll.self",
  PAYROLL_AI: "payroll.ai",
  PAYROLL_TAX: "payroll.tax",
  PAYROLL_ADMIN: "payroll.admin",
  PAYROLL_COSTING: "payroll.costing",
  PAYROLL_BANK: "payroll.bank",
  TENANT_VIEW: "tenant.view",
  TENANT_MANAGE: "tenant.manage",
  TENANT_ADMIN: "tenant.admin",
  TENANT_SWITCH: "tenant.switch",
  PLATFORM_VIEW: "platform.view",
  PLATFORM_ADMIN: "platform.admin",
  PLATFORM_PROVISION: "platform.provision",
  PLATFORM_EVENTS: "platform.events",
  PLATFORM_FLAGS: "platform.flags",
  PRINT_VIEW: "print.view",
  PRINT_MANAGE: "print.manage",
  PRINT_SUBMIT: "print.submit",
  PRINT_OPERATE: "print.operate",
  PRINT_DESIGN: "print.design",
  PRINT_SECURITY: "print.security",
  PRINT_ADMIN: "print.admin",
  PRINT_AI: "print.ai",
  PKG_VIEW: "pkg.view",
  PKG_MANAGE: "pkg.manage",
  PKG_OPERATE: "pkg.operate",
  PKG_APPROVE: "pkg.approve",
  PKG_AI: "pkg.ai",
  AST_VIEW: "ast.view",
  AST_MANAGE: "ast.manage",
  AST_ASSIGN: "ast.assign",
  AST_AUDIT: "ast.audit",
  AST_PRINT: "ast.print",
  AST_AI: "ast.ai",
  EAL_VIEW: "eal.view",
  EAL_MANAGE: "eal.manage",
  EAL_INVESTIGATE: "eal.investigate",
  EAL_EXPORT: "eal.export",
  EAL_AI: "eal.ai",
  EAL_COMPLIANCE: "eal.compliance",
  EAL_EXECUTIVE: "eal.executive",
  EAL_SECURITY: "eal.security",
  EAL_INFRA: "eal.infra",
  EAL_ARCHIVE: "eal.archive",
  EAL_CONFIG: "eal.config",
  UW_VIEW: "uw.view",
  UW_MANAGE: "uw.manage",
  UW_MERGE: "uw.merge",
  UW_ADMIN: "uw.admin",
  DI_VIEW: "di.view",
  DI_MANAGE: "di.manage",
  DI_PROVISION: "di.provision",
  DI_ORG: "di.org",
  DI_CLEARANCE: "di.clearance",
  DI_CARDS: "di.cards",
  DI_BIOMETRICS: "di.biometrics",
  DI_ADMIN: "di.admin",
  DI_AI: "di.ai",
  EC_VIEW: "ec.view",
  EC_MANAGE: "ec.manage",
  EC_STRUCTURE: "ec.structure",
  EC_GOVERNANCE: "ec.governance",
  EC_DOCUMENTS: "ec.documents",
  EC_RISK: "ec.risk",
  EC_ADMIN: "ec.admin",
  EC_AI: "ec.ai",
  COMM_VIEW: "comm.view",
  COMM_MANAGE: "comm.manage",
  COMM_BROADCAST: "comm.broadcast",
  COMM_TEMPLATES: "comm.templates",
  COMM_ADMIN: "comm.admin",
  COMM_AI: "comm.ai",
  MEDIA_VIEW: "media.view",
  MEDIA_UPLOAD: "media.upload",
  MEDIA_MANAGE: "media.manage",
  FLEET_VIEW: "fleet.view",
  FLEET_MANAGE: "fleet.manage",
  FLEET_DRIVERS: "fleet.drivers",
  FLEET_FUEL: "fleet.fuel",
  FLEET_MAINTENANCE: "fleet.maintenance",
  FLEET_DISPATCH: "fleet.dispatch",
  FLEET_TRACK: "fleet.track",
  FLEET_APPROVE: "fleet.approve",
  FLEET_AI: "fleet.ai",
  FLEET_ADMIN: "fleet.admin",
  PPM_VIEW: "ppm.view",
  PPM_MANAGE: "ppm.manage",
  PPM_PLAN: "ppm.plan",
  PPM_EXECUTE: "ppm.execute",
  PPM_FINANCE: "ppm.finance",
  PPM_APPROVE: "ppm.approve",
  PPM_PORTAL: "ppm.portal",
  PPM_AI: "ppm.ai",
  PPM_ADMIN: "ppm.admin",
  ATT_VIEW: "att.view",
  ATT_MANAGE: "att.manage",
  ATT_CLOCK: "att.clock",
  ATT_APPROVE: "att.approve",
  ATT_DEVICES: "att.devices",
  ATT_FIELD: "att.field",
  ATT_AI: "att.ai",
  ATT_ADMIN: "att.admin",
} as const;

export const REAMS_PER_CARTON = 5;

export type NavGroupId =
  | "overview"
  | "manufacturing"
  | "supply-chain"
  | "commercial"
  | "finance"
  | "projects"
  | "people"
  | "security"
  | "platform"

/** Ordered sidebar navigation groups (grouped nav render order). */
export const NAV_GROUPS: { id: NavGroupId; label: string }[] = [
  { id: "overview", label: "Overview" },
  { id: "manufacturing", label: "Manufacturing" },
  { id: "supply-chain", label: "Supply Chain" },
  { id: "commercial", label: "Commercial" },
  { id: "finance", label: "Finance" },
  { id: "projects", label: "Projects" },
  { id: "people", label: "People & HR" },
  { id: "security", label: "Security & Compliance" },
  { id: "platform", label: "Platform & System" },
];

export const NAV_ITEMS = [
  { title: "Dashboard", href: "/dashboard", icon: "LayoutDashboard", permission: PERMISSIONS.DASHBOARD_VIEW, group: "overview" },
  { title: "Production", href: "/dashboard/production", icon: "Factory", permission: PERMISSIONS.PRODUCTION_VIEW, group: "manufacturing" },
  { title: "QR Codes", href: "/dashboard/qr-codes", icon: "QrCode", permission: PERMISSIONS.QR_VIEW, group: "manufacturing" },
  { title: "Advanced Labels", href: "/dashboard/labels", icon: "Tag", permission: PERMISSIONS.LBL_VIEW, group: "manufacturing" },
  { title: "Printers", href: "/dashboard/printers", icon: "Bluetooth", permission: PERMISSIONS.PRINTING_CREATE, group: "manufacturing" },
  { title: "Printing", href: "/dashboard/printing", icon: "Printer", permission: PERMISSIONS.PRINTING_CREATE, group: "manufacturing" },
  { title: "Print Ops", href: "/dashboard/print", icon: "Printer", permission: PERMISSIONS.PRINT_VIEW, group: "manufacturing" },
  { title: "Packing", href: "/dashboard/packing", icon: "Package", permission: PERMISSIONS.PACKING_CREATE, group: "manufacturing" },
  { title: "Packaging", href: "/dashboard/packaging", icon: "Boxes", permission: PERMISSIONS.PKG_VIEW, group: "manufacturing" },
  { title: "Assets", href: "/dashboard/assets", icon: "Tags", permission: PERMISSIONS.AST_VIEW, group: "manufacturing" },
  { title: "Inventory", href: "/dashboard/inventory", icon: "Warehouse", permission: PERMISSIONS.INVENTORY_VIEW, group: "supply-chain" },
  { title: "SRM / Procurement", href: "/dashboard/procurement", icon: "ShoppingBag", permission: PERMISSIONS.PROCUREMENT_VIEW, group: "supply-chain" },
  { title: "Supply Chain", href: "/dashboard/scm", icon: "Network", permission: PERMISSIONS.SCM_VIEW, group: "supply-chain" },
  { title: "CRM", href: "/dashboard/crm", icon: "Handshake", permission: PERMISSIONS.CRM_VIEW, group: "commercial" },
  { title: "Advanced Sales", href: "/dashboard/sales", icon: "ShoppingCart", permission: PERMISSIONS.SALES_VIEW, group: "commercial" },
  { title: "Contracts", href: "/dashboard/contracts", icon: "FileText", permission: PERMISSIONS.SALES_VIEW, group: "commercial" },
  { title: "Finance", href: "/dashboard/finance", icon: "Landmark", permission: PERMISSIONS.FINANCE_VIEW, group: "finance" },
  { title: "Billing", href: "/dashboard/billing", icon: "Receipt", permission: PERMISSIONS.BILLING_VIEW, group: "commercial" },
  { title: "Invoices", href: "/dashboard/invoices", icon: "FileText", permission: PERMISSIONS.INVOICES_VIEW, group: "commercial" },
  { title: "Dispatch", href: "/dashboard/dispatch", icon: "Truck", permission: PERMISSIONS.DISPATCH_VIEW, group: "commercial" },
  { title: "Fleet & Transport", href: "/dashboard/fleet", icon: "Car", permission: PERMISSIONS.FLEET_VIEW, group: "commercial" },
  { title: "Projects (PPM)", href: "/dashboard/projects", icon: "FolderKanban", permission: PERMISSIONS.PPM_VIEW, group: "projects" },
  { title: "Workforce", href: "/dashboard/workforce", icon: "Briefcase", permission: PERMISSIONS.WFM_VIEW, group: "people" },
  { title: "Attendance", href: "/dashboard/attendance", icon: "Clock", permission: PERMISSIONS.ATT_VIEW, group: "people" },
  { title: "Talent Acquisition", href: "/dashboard/talent", icon: "UserPlus", permission: PERMISSIONS.TA_VIEW, group: "people" },
  { title: "HR", href: "/dashboard/hr", icon: "Contact", permission: PERMISSIONS.HR_VIEW, group: "people" },
  { title: "Payroll", href: "/dashboard/payroll", icon: "Wallet", permission: PERMISSIONS.PAYROLL_VIEW, group: "people" },
  { title: "Profiles", href: "/dashboard/profiles", icon: "UserCircle", permission: PERMISSIONS.PROFILE_VIEW, group: "people" },
  { title: "SecureChat", href: "/dashboard/chat", icon: "MessageSquare", permission: PERMISSIONS.HC_VIEW, group: "people" },
  { title: "Service Desk", href: "/dashboard/service-desk", icon: "Headphones", permission: PERMISSIONS.SD_VIEW, group: "people" },
  { title: "ID Credentials", href: "/dashboard/credentials", icon: "IdCard", permission: PERMISSIONS.WID_VIEW, group: "people" },
  { title: "Verification", href: "/dashboard/verification", icon: "ShieldCheck", permission: PERMISSIONS.VERIFICATION_VIEW, group: "people" },
  { title: "Fraud Alerts", href: "/dashboard/fraud", icon: "AlertTriangle", permission: PERMISSIONS.FRAUD_MANAGE, group: "security" },
  { title: "Reports", href: "/dashboard/reports", icon: "BarChart3", permission: PERMISSIONS.REPORTS_VIEW, group: "overview" },
  { title: "Products", href: "/dashboard/products", icon: "Box", permission: PERMISSIONS.PRODUCTS_VIEW, group: "supply-chain" },
  { title: "Workspaces", href: "/dashboard/workspaces", icon: "LayoutDashboard", permission: PERMISSIONS.DASHBOARD_VIEW, group: "overview" },
  { title: "Boards", href: "/dashboard/boards", icon: "BarChart3", permission: PERMISSIONS.DASHBOARD_VIEW, group: "overview" },
  { title: "Live Ops", href: "/dashboard/live", icon: "Activity", permission: PERMISSIONS.DASHBOARD_VIEW, group: "overview" },
  { title: "Recycle Bin", href: "/dashboard/recycle-bin", icon: "ScrollText", permission: PERMISSIONS.SETTINGS_MANAGE, group: "security" },
  { title: "Distributors", href: "/dashboard/distributors", icon: "Network", permission: PERMISSIONS.DISTRIBUTORS_VIEW, group: "supply-chain" },
  { title: "Identity", href: "/dashboard/identity", icon: "Shield", permission: PERMISSIONS.IAM_VIEW, group: "security" },
  { title: "Enterprise", href: "/dashboard/enterprise", icon: "Building2", permission: PERMISSIONS.EC_VIEW, group: "platform" },
  { title: "Tenants (ERP)", href: "/dashboard/tenants", icon: "Building2", permission: PERMISSIONS.TENANT_VIEW, group: "platform" },
  { title: "Control Plane", href: "/platform", icon: "Server", permission: PERMISSIONS.PLATFORM_VIEW, group: "platform" },
  { title: "All tenants", href: "/platform/tenants", icon: "Building2", permission: PERMISSIONS.PLATFORM_VIEW, group: "platform" },
  { title: "Estate users", href: "/platform/users", icon: "Users", permission: PERMISSIONS.PLATFORM_VIEW, group: "platform" },
  { title: "Companies (estate)", href: "/platform/companies", icon: "Building2", permission: PERMISSIONS.PLATFORM_VIEW, group: "platform" },

  { title: "Background Jobs", href: "/platform/jobs", icon: "Server", permission: PERMISSIONS.PLATFORM_VIEW, group: "platform" },
  { title: "Platform Ops", href: "/platform/ops", icon: "Activity", permission: PERMISSIONS.PLATFORM_VIEW, group: "platform" },
  { title: "Dual Control", href: "/dashboard/security/dual-control", icon: "Shield", permission: "security.dual_control", group: "security" },
  { title: "Workflows", href: "/dashboard/workflows", icon: "Activity", permission: PERMISSIONS.DASHBOARD_VIEW, group: "platform" },
  { title: "Communications", href: "/dashboard/communications", icon: "Mail", permission: PERMISSIONS.COMM_VIEW, group: "platform" },
  { title: "Media Library", href: "/dashboard/media", icon: "Image", permission: PERMISSIONS.MEDIA_VIEW, group: "platform" },
  { title: "Branding", href: "/dashboard/branding", icon: "Palette", permission: PERMISSIONS.BRAND_VIEW, group: "platform" },
  { title: "Integrations", href: "/dashboard/integrations", icon: "Plug", permission: PERMISSIONS.INTG_VIEW, group: "platform" },
  { title: "Users", href: "/dashboard/users", icon: "Users", permission: PERMISSIONS.USERS_VIEW, group: "platform" },
  { title: "Audit & Compliance", href: "/dashboard/audit", icon: "ScrollText", permission: PERMISSIONS.AUDIT_VIEW, group: "security" },
  { title: "Settings", href: "/dashboard/settings", icon: "Settings", permission: PERMISSIONS.SETTINGS_VIEW, group: "platform" },
] as const;
