import type { PpmEntityConfig } from "./types";

function cfg(partial: PpmEntityConfig): PpmEntityConfig {
  return {
    searchCols: partial.searchCols || [
      "code", "name", "title", "project_code", "status", "task_code",
      "request_number", "assignee_name", "manager_name",
    ],
    ...partial,
  };
}

export const PPM_ENTITIES: Record<string, PpmEntityConfig> = {
  portfolio: cfg({
    title: "Project Portfolio",
    description: "Portfolios, prioritization and health scoring",
    table: "ppm_portfolios",
    numberField: "portfolio_code",
    numberPrefix: "PF",
    statusField: "status",
    statusOptions: ["active", "on_hold", "closed"],
    columns: [
      { key: "portfolio_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "owner_name", label: "Owner" },
      { key: "budget_total", label: "Budget" },
      { key: "health_score", label: "Health" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "portfolio_code", label: "Code", required: true, autoNumber: "PF", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "owner_name", label: "Owner" },
      { key: "strategic_theme", label: "Strategic theme" },
      { key: "budget_total", label: "Budget total", type: "number" },
      { key: "budget_allocated", label: "Budget allocated", type: "number" },
      { key: "health_score", label: "Health score", type: "number" },
      { key: "priority", label: "Priority", type: "number" },
      { key: "currency_code", label: "Currency" },
      { key: "status", label: "Status", type: "select", options: ["active", "on_hold", "closed"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", currency_code: "UGX", health_score: 80, priority: 5 },
  }),

  programs: cfg({
    title: "Programs",
    description: "Programs grouping related projects",
    table: "ppm_programs",
    numberField: "program_code",
    numberPrefix: "PRG",
    statusField: "status",
    statusOptions: ["active", "on_hold", "completed", "cancelled"],
    columns: [
      { key: "program_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "manager_name", label: "Manager" },
      { key: "budget", label: "Budget" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "program_code", label: "Code", required: true, autoNumber: "PRG", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "sponsor_name", label: "Sponsor" },
      { key: "manager_name", label: "Manager" },
      { key: "start_date", label: "Start", type: "date" },
      { key: "end_date", label: "End", type: "date" },
      { key: "budget", label: "Budget", type: "number" },
      { key: "health_score", label: "Health", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "on_hold", "completed", "cancelled"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", health_score: 80 },
  }),

  list: cfg({
    title: "Projects",
    description: "Full project lifecycle registry",
    table: "ppm_projects",
    numberField: "project_code",
    numberPrefix: "PRJ",
    statusField: "status",
    statusOptions: ["draft", "active", "on_hold", "delayed", "completed", "cancelled", "closed"],
    searchCols: ["project_code", "name", "manager_name", "customer_name", "status", "project_type"],
    columns: [
      { key: "project_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "project_type", label: "Type" },
      { key: "manager_name", label: "Manager" },
      { key: "percent_complete", label: "%" },
      { key: "health", label: "Health" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "project_code", label: "Project code", required: true, autoNumber: "PRJ", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "portfolio_name", label: "Portfolio" },
      { key: "program_name", label: "Program" },
      { key: "category_name", label: "Category" },
      { key: "project_type", label: "Type", type: "select", options: ["manufacturing", "customer", "ict", "construction", "internal", "rd", "maintenance", "capex", "government", "secure_print"] },
      { key: "methodology", label: "Methodology", type: "select", options: ["waterfall", "agile", "hybrid", "kanban"] },
      { key: "lifecycle_stage", label: "Lifecycle", type: "select", options: ["initiation", "planning", "execution", "monitoring", "billing", "closure", "closed"] },
      { key: "priority", label: "Priority", type: "select", options: ["low", "normal", "high", "critical"] },
      { key: "status", label: "Status", type: "select", options: ["draft", "active", "on_hold", "delayed", "completed", "cancelled", "closed"] },
      { key: "health", label: "Health", type: "select", options: ["green", "amber", "red"] },
      { key: "manager_name", label: "Project manager" },
      { key: "sponsor_name", label: "Sponsor" },
      { key: "customer_name", label: "Customer" },
      { key: "branch_name", label: "Branch" },
      { key: "department_name", label: "Department" },
      { key: "start_date", label: "Start", type: "date" },
      { key: "end_date", label: "End", type: "date" },
      { key: "percent_complete", label: "% Complete", type: "number" },
      { key: "budget_planned", label: "Budget planned", type: "number" },
      { key: "budget_actual", label: "Budget actual", type: "number" },
      { key: "planned_value", label: "PV", type: "number" },
      { key: "earned_value", label: "EV", type: "number" },
      { key: "actual_cost", label: "AC", type: "number" },
      { key: "spi", label: "SPI", type: "number" },
      { key: "cpi", label: "CPI", type: "number" },
      { key: "billing_method", label: "Billing", type: "select", options: ["fixed_price", "t_and_m", "milestone", "progress", "retention", "recurring"] },
      { key: "currency_code", label: "Currency" },
      { key: "sales_order_ref", label: "Sales order ref" },
      { key: "contract_ref", label: "Contract ref" },
      { key: "opportunity_ref", label: "Opportunity ref" },
      { key: "qr_payload", label: "QR payload" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: {
      status: "draft", health: "green", methodology: "hybrid", lifecycle_stage: "initiation",
      priority: "normal", project_type: "internal", currency_code: "UGX", billing_method: "fixed_price",
      spi: 1, cpi: 1,
    },
  }),

  templates: cfg({
    title: "Project Templates",
    description: "Reusable project structures and WBS",
    table: "ppm_templates",
    numberField: "template_code",
    numberPrefix: "TPL",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "template_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "project_type", label: "Type" },
      { key: "methodology", label: "Method" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "template_code", label: "Code", required: true, autoNumber: "TPL", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "project_type", label: "Project type" },
      { key: "methodology", label: "Methodology", type: "select", options: ["waterfall", "agile", "hybrid", "kanban"] },
      { key: "default_duration_days", label: "Duration days", type: "number" },
      { key: "budget_template", label: "Budget template", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", methodology: "waterfall", default_duration_days: 90 },
  }),

  requests: cfg({
    title: "Project Requests",
    description: "Intake: create → submit → approve → convert",
    table: "ppm_project_requests",
    numberField: "request_number",
    numberPrefix: "PREQ",
    statusField: "status",
    statusOptions: ["draft", "submitted", "under_review", "approved", "rejected", "converted", "withdrawn", "archived"],
    columns: [
      { key: "request_number", label: "Number" },
      { key: "title", label: "Title" },
      { key: "requestor_name", label: "Requestor" },
      { key: "priority", label: "Priority" },
      { key: "estimated_budget", label: "Budget" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "request_number", label: "Request number", autoNumber: "PREQ", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "requestor_name", label: "Requestor" },
      { key: "department_name", label: "Department" },
      { key: "business_need", label: "Business need", type: "textarea" },
      { key: "estimated_budget", label: "Estimated budget", type: "number" },
      { key: "expected_benefits", label: "Expected benefits", type: "textarea" },
      { key: "priority", label: "Priority", type: "select", options: ["low", "normal", "high", "critical"] },
      { key: "sponsor_name", label: "Sponsor" },
      { key: "project_type", label: "Project type" },
      { key: "status", label: "Status", type: "select", options: ["draft", "submitted", "under_review", "approved", "rejected", "converted", "withdrawn", "archived"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "draft", priority: "normal", project_type: "internal" },
  }),

  "business-cases": cfg({
    title: "Business Cases",
    description: "ROI, NPV, IRR and executive approval",
    table: "ppm_business_cases",
    numberField: "case_number",
    numberPrefix: "BC",
    statusField: "status",
    statusOptions: ["draft", "submitted", "approved", "rejected", "archived"],
    columns: [
      { key: "case_number", label: "Case #" },
      { key: "title", label: "Title" },
      { key: "roi_pct", label: "ROI %" },
      { key: "npv", label: "NPV" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "case_number", label: "Case number", autoNumber: "BC", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "strategic_objectives", label: "Strategic objectives", type: "textarea" },
      { key: "financial_analysis", label: "Financial analysis", type: "textarea" },
      { key: "roi_pct", label: "ROI %", type: "number" },
      { key: "npv", label: "NPV", type: "number" },
      { key: "irr_pct", label: "IRR %", type: "number" },
      { key: "cost_benefit", label: "Cost-benefit", type: "textarea" },
      { key: "risk_assessment", label: "Risk assessment", type: "textarea" },
      { key: "swot_analysis", label: "SWOT", type: "textarea" },
      { key: "funding_source", label: "Funding source" },
      { key: "total_investment", label: "Total investment", type: "number" },
      { key: "expected_return", label: "Expected return", type: "number" },
      { key: "file_url", label: "Attachment URL" },
      { key: "status", label: "Status", type: "select", options: ["draft", "submitted", "approved", "rejected", "archived"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "draft" },
  }),

  categories: cfg({
    title: "Project Categories",
    description: "Strategic, ops, customer, CAPEX categories",
    table: "ppm_categories",
    numberField: "code",
    numberPrefix: "CAT",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "description", label: "Description" },
    ],
    fields: [
      { key: "code", label: "Code", required: true, autoNumber: "CAT", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "description", label: "Description", type: "textarea" },
    ],
  }),

  types: cfg({
    title: "Project Types",
    description: "Manufacturing, ICT, construction, secure print…",
    table: "ppm_project_types",
    numberField: "code",
    numberPrefix: "TYP",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "default_methodology", label: "Methodology" },
    ],
    fields: [
      { key: "code", label: "Code", required: true, autoNumber: "TYP", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "default_methodology", label: "Default methodology", type: "select", options: ["waterfall", "agile", "hybrid", "kanban"] },
      { key: "description", label: "Description", type: "textarea" },
    ],
    defaults: { default_methodology: "hybrid" },
  }),

  wbs: cfg({
    title: "Work Breakdown Structure",
    description: "Phases, deliverables, work packages",
    table: "ppm_wbs",
    numberField: "wbs_code",
    numberPrefix: "WBS",
    statusField: "status",
    statusOptions: ["open", "in_progress", "done", "cancelled"],
    columns: [
      { key: "wbs_code", label: "WBS" },
      { key: "name", label: "Name" },
      { key: "project_code", label: "Project" },
      { key: "node_type", label: "Type" },
      { key: "percent_complete", label: "%" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "wbs_code", label: "WBS code", required: true },
      { key: "name", label: "Name", required: true },
      { key: "project_code", label: "Project code" },
      { key: "node_type", label: "Type", type: "select", options: ["phase", "deliverable", "work_package", "task", "milestone", "closure"] },
      { key: "sort_order", label: "Sort order", type: "number" },
      { key: "percent_complete", label: "% Complete", type: "number" },
      { key: "planned_start", label: "Start", type: "date" },
      { key: "planned_end", label: "End", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["open", "in_progress", "done", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "open", node_type: "phase" },
  }),

  milestones: cfg({
    title: "Milestones",
    description: "Key dates and billing milestones",
    table: "ppm_milestones",
    numberField: "milestone_code",
    numberPrefix: "MS",
    statusField: "status",
    statusOptions: ["pending", "achieved", "missed", "cancelled"],
    columns: [
      { key: "milestone_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "project_code", label: "Project" },
      { key: "due_date", label: "Due" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "milestone_code", label: "Code", required: true, autoNumber: "MS", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "project_code", label: "Project code" },
      { key: "due_date", label: "Due date", type: "date" },
      { key: "completed_date", label: "Completed", type: "date" },
      { key: "percent_complete", label: "%", type: "number" },
      { key: "owner_name", label: "Owner" },
      { key: "status", label: "Status", type: "select", options: ["pending", "achieved", "missed", "cancelled"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "pending" },
  }),

  deliverables: cfg({
    title: "Deliverables",
    description: "Acceptance-tracked project outputs",
    table: "ppm_deliverables",
    numberField: "deliverable_code",
    numberPrefix: "DEL",
    statusField: "status",
    statusOptions: ["pending", "in_progress", "delivered", "accepted", "rejected"],
    columns: [
      { key: "deliverable_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "project_code", label: "Project" },
      { key: "due_date", label: "Due" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "deliverable_code", label: "Code", required: true, autoNumber: "DEL", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "project_code", label: "Project code" },
      { key: "due_date", label: "Due", type: "date" },
      { key: "acceptance_criteria", label: "Acceptance criteria", type: "textarea" },
      { key: "owner_name", label: "Owner" },
      { key: "file_url", label: "File URL" },
      { key: "status", label: "Status", type: "select", options: ["pending", "in_progress", "delivered", "accepted", "rejected"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "pending" },
  }),

  tasks: cfg({
    title: "Tasks",
    description: "Assignments, estimates, dependencies, progress",
    table: "ppm_tasks",
    numberField: "task_code",
    numberPrefix: "TSK",
    statusField: "status",
    statusOptions: ["todo", "in_progress", "blocked", "in_review", "done", "cancelled"],
    searchCols: ["task_code", "name", "assignee_name", "project_code", "status", "sprint_name"],
    columns: [
      { key: "task_code", label: "Code" },
      { key: "name", label: "Task" },
      { key: "project_code", label: "Project" },
      { key: "assignee_name", label: "Assignee" },
      { key: "priority", label: "Priority" },
      { key: "due_date", label: "Due" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "task_code", label: "Task code", required: true, autoNumber: "TSK", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "project_code", label: "Project code" },
      { key: "assignee_name", label: "Assignee" },
      { key: "reviewer_name", label: "Reviewer" },
      { key: "approver_name", label: "Approver" },
      { key: "priority", label: "Priority", type: "select", options: ["low", "normal", "high", "critical"] },
      { key: "status", label: "Status", type: "select", options: ["todo", "in_progress", "blocked", "in_review", "done", "cancelled"] },
      { key: "board_column", label: "Board column", type: "select", options: ["todo", "in_progress", "in_review", "done", "blocked"] },
      { key: "estimated_hours", label: "Est. hours", type: "number" },
      { key: "actual_hours", label: "Actual hours", type: "number" },
      { key: "cost", label: "Cost", type: "number" },
      { key: "start_date", label: "Start", type: "date" },
      { key: "due_date", label: "Due", type: "date" },
      { key: "finish_date", label: "Finish", type: "date" },
      { key: "percent_complete", label: "% Complete", type: "number" },
      { key: "sprint_name", label: "Sprint" },
      { key: "dependency_codes", label: "Dependencies" },
      { key: "qr_payload", label: "QR payload" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "todo", priority: "normal", board_column: "todo" },
  }),

  checklists: cfg({
    title: "Checklists",
    description: "Task checklist items",
    table: "ppm_checklists",
    columns: [
      { key: "item_text", label: "Item" },
      { key: "is_done", label: "Done" },
      { key: "sort_order", label: "Order" },
    ],
    fields: [
      { key: "item_text", label: "Item text", required: true },
      { key: "sort_order", label: "Sort order", type: "number" },
    ],
  }),

  dependencies: cfg({
    title: "Dependencies",
    description: "FS / SS / FF / SF task links",
    table: "ppm_dependencies",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "predecessor_task_code", label: "Predecessor" },
      { key: "successor_task_code", label: "Successor" },
      { key: "dependency_type", label: "Type" },
      { key: "lag_days", label: "Lag" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "predecessor_task_code", label: "Predecessor task", required: true },
      { key: "successor_task_code", label: "Successor task", required: true },
      { key: "dependency_type", label: "Type", type: "select", options: ["FS", "SS", "FF", "SF"] },
      { key: "lag_days", label: "Lag days", type: "number" },
      { key: "project_id", label: "Project ID (optional)" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", dependency_type: "FS", lag_days: 0 },
  }),

  sprints: cfg({
    title: "Sprint Management",
    description: "Agile sprint planning and capacity",
    table: "ppm_sprints",
    numberField: "sprint_code",
    numberPrefix: "SPR",
    statusField: "status",
    statusOptions: ["planned", "active", "completed", "cancelled"],
    columns: [
      { key: "sprint_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "project_code", label: "Project" },
      { key: "start_date", label: "Start" },
      { key: "end_date", label: "End" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "sprint_code", label: "Code", required: true, autoNumber: "SPR", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "project_code", label: "Project code" },
      { key: "goal", label: "Goal", type: "textarea" },
      { key: "start_date", label: "Start", type: "date" },
      { key: "end_date", label: "End", type: "date" },
      { key: "capacity_hours", label: "Capacity hours", type: "number" },
      { key: "committed_points", label: "Committed points", type: "number" },
      { key: "completed_points", label: "Completed points", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["planned", "active", "completed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "planned" },
  }),

  backlog: cfg({
    title: "Product Backlog",
    description: "Epics, stories, bugs and spikes",
    table: "ppm_backlog",
    numberField: "item_code",
    numberPrefix: "BLG",
    statusField: "status",
    statusOptions: ["backlog", "ready", "sprint", "done", "cancelled"],
    columns: [
      { key: "item_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "item_type", label: "Type" },
      { key: "story_points", label: "Points" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "item_code", label: "Code", required: true, autoNumber: "BLG", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "project_code", label: "Project code" },
      { key: "item_type", label: "Type", type: "select", options: ["epic", "story", "bug", "spike", "task"] },
      { key: "priority", label: "Priority", type: "select", options: ["low", "normal", "high", "critical"] },
      { key: "story_points", label: "Story points", type: "number" },
      { key: "sprint_name", label: "Sprint" },
      { key: "assignee_name", label: "Assignee" },
      { key: "status", label: "Status", type: "select", options: ["backlog", "ready", "sprint", "done", "cancelled"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "backlog", item_type: "story", priority: "normal" },
  }),

  roadmap: cfg({
    title: "Roadmap",
    description: "Quarterly themes and targets",
    table: "ppm_roadmap",
    numberField: "item_code",
    numberPrefix: "RM",
    statusField: "status",
    statusOptions: ["planned", "in_progress", "done", "deferred"],
    columns: [
      { key: "item_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "quarter", label: "Quarter" },
      { key: "target_date", label: "Target" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "item_code", label: "Code", required: true, autoNumber: "RM", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "project_code", label: "Project code" },
      { key: "quarter", label: "Quarter" },
      { key: "target_date", label: "Target date", type: "date" },
      { key: "theme", label: "Theme" },
      { key: "status", label: "Status", type: "select", options: ["planned", "in_progress", "done", "deferred"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "planned" },
  }),

  resources: cfg({
    title: "Resource Management",
    description: "People, machines, rooms and rates",
    table: "ppm_resources",
    numberField: "resource_code",
    numberPrefix: "RES",
    statusField: "status",
    statusOptions: ["available", "allocated", "unavailable", "leave"],
    columns: [
      { key: "resource_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "resource_type", label: "Type" },
      { key: "capacity_hours_week", label: "Capacity" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "resource_code", label: "Code", required: true, autoNumber: "RES", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "resource_type", label: "Type", type: "select", options: ["employee", "contractor", "consultant", "machine", "vehicle", "room", "equipment"] },
      { key: "skills", label: "Skills" },
      { key: "certifications", label: "Certifications" },
      { key: "capacity_hours_week", label: "Hours/week", type: "number" },
      { key: "cost_rate", label: "Cost rate", type: "number" },
      { key: "bill_rate", label: "Bill rate", type: "number" },
      { key: "availability_pct", label: "Availability %", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["available", "allocated", "unavailable", "leave"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "available", resource_type: "employee", capacity_hours_week: 40, availability_pct: 100 },
  }),

  allocations: cfg({
    title: "Resource Allocation",
    description: "Assign resources to projects",
    table: "ppm_resource_allocations",
    numberField: "allocation_code",
    numberPrefix: "RAL",
    statusField: "status",
    statusOptions: ["active", "planned", "completed", "cancelled"],
    columns: [
      { key: "allocation_code", label: "Code" },
      { key: "resource_name", label: "Resource" },
      { key: "project_code", label: "Project" },
      { key: "allocation_pct", label: "%" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "allocation_code", label: "Code", autoNumber: "RAL", createOnly: true },
      { key: "resource_name", label: "Resource name", required: true },
      { key: "project_code", label: "Project code" },
      { key: "role_name", label: "Role" },
      { key: "allocation_pct", label: "Allocation %", type: "number" },
      { key: "hours_planned", label: "Hours planned", type: "number" },
      { key: "hours_actual", label: "Hours actual", type: "number" },
      { key: "start_date", label: "Start", type: "date" },
      { key: "end_date", label: "End", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["active", "planned", "completed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", allocation_pct: 100 },
  }),

  timesheets: cfg({
    title: "Timesheets",
    description: "Time entry, approval and billing",
    table: "ppm_timesheets",
    numberField: "timesheet_number",
    numberPrefix: "TS",
    statusField: "status",
    statusOptions: ["draft", "submitted", "approved", "rejected", "posted"],
    columns: [
      { key: "timesheet_number", label: "Number" },
      { key: "project_code", label: "Project" },
      { key: "resource_name", label: "Resource" },
      { key: "work_date", label: "Date" },
      { key: "hours", label: "Hours" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "timesheet_number", label: "Number", autoNumber: "TS", createOnly: true },
      { key: "project_code", label: "Project code" },
      { key: "task_code", label: "Task code" },
      { key: "resource_name", label: "Resource", required: true },
      { key: "work_date", label: "Work date", type: "date" },
      { key: "hours", label: "Hours", type: "number", required: true },
      { key: "cost_amount", label: "Cost", type: "number" },
      { key: "bill_amount", label: "Bill amount", type: "number" },
      { key: "entry_method", label: "Method", type: "select", options: ["manual", "timer", "mobile", "qr", "gps", "biometric"] },
      { key: "status", label: "Status", type: "select", options: ["draft", "submitted", "approved", "rejected", "posted"] },
      { key: "description", label: "Description", type: "textarea" },
    ],
    defaults: { status: "draft", entry_method: "manual" },
  }),

  "time-logs": cfg({
    title: "Time Tracking Logs",
    description: "Timer sessions and duration logs",
    table: "ppm_time_logs",
    columns: [
      { key: "project_code", label: "Project" },
      { key: "task_code", label: "Task" },
      { key: "resource_name", label: "Resource" },
      { key: "duration_minutes", label: "Minutes" },
      { key: "created_at", label: "Created" },
    ],
    fields: [
      { key: "project_code", label: "Project code" },
      { key: "task_code", label: "Task code" },
      { key: "resource_name", label: "Resource" },
      { key: "duration_minutes", label: "Duration minutes", type: "number" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  }),

  budgets: cfg({
    title: "Budget Management",
    description: "Planned, committed, actual, forecast",
    table: "ppm_budgets",
    numberField: "budget_code",
    numberPrefix: "BDG",
    statusField: "status",
    statusOptions: ["active", "closed", "frozen"],
    columns: [
      { key: "budget_code", label: "Code" },
      { key: "project_code", label: "Project" },
      { key: "category", label: "Category" },
      { key: "planned_amount", label: "Planned" },
      { key: "actual_amount", label: "Actual" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "budget_code", label: "Code", required: true, autoNumber: "BDG", createOnly: true },
      { key: "project_code", label: "Project code" },
      { key: "cost_center", label: "Cost center" },
      { key: "category", label: "Category", type: "select", options: ["labor", "materials", "equipment", "services", "overhead", "contingency", "other"] },
      { key: "planned_amount", label: "Planned", type: "number" },
      { key: "committed_amount", label: "Committed", type: "number" },
      { key: "actual_amount", label: "Actual", type: "number" },
      { key: "forecast_amount", label: "Forecast", type: "number" },
      { key: "currency_code", label: "Currency" },
      { key: "status", label: "Status", type: "select", options: ["active", "closed", "frozen"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", category: "labor", currency_code: "UGX" },
  }),

  expenses: cfg({
    title: "Expense Claims",
    description: "Project expense submission and reimbursement",
    table: "ppm_expenses",
    numberField: "expense_number",
    numberPrefix: "EXP",
    statusField: "status",
    statusOptions: ["draft", "submitted", "approved", "rejected", "reimbursed", "posted"],
    columns: [
      { key: "expense_number", label: "Number" },
      { key: "project_code", label: "Project" },
      { key: "claimant_name", label: "Claimant" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "expense_number", label: "Number", autoNumber: "EXP", createOnly: true },
      { key: "project_code", label: "Project code" },
      { key: "claimant_name", label: "Claimant", required: true },
      { key: "expense_date", label: "Date", type: "date" },
      { key: "category", label: "Category", type: "select", options: ["travel", "meals", "materials", "software", "other"] },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "currency_code", label: "Currency" },
      { key: "receipt_url", label: "Receipt URL" },
      { key: "status", label: "Status", type: "select", options: ["draft", "submitted", "approved", "rejected", "reimbursed", "posted"] },
      { key: "description", label: "Description", type: "textarea" },
    ],
    defaults: { status: "submitted", category: "travel", currency_code: "UGX" },
  }),

  "purchase-requests": cfg({
    title: "Purchase Requests",
    description: "Project → PR → PO → receipt → cost",
    table: "ppm_purchase_requests",
    numberField: "pr_number",
    numberPrefix: "PPR",
    statusField: "status",
    statusOptions: ["draft", "submitted", "approved", "ordered", "received", "cancelled"],
    columns: [
      { key: "pr_number", label: "PR #" },
      { key: "title", label: "Title" },
      { key: "project_code", label: "Project" },
      { key: "estimated_cost", label: "Est. cost" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "pr_number", label: "PR number", autoNumber: "PPR", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "project_code", label: "Project code" },
      { key: "item_description", label: "Item description", type: "textarea" },
      { key: "quantity", label: "Quantity", type: "number" },
      { key: "estimated_cost", label: "Estimated cost", type: "number" },
      { key: "needed_by", label: "Needed by", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["draft", "submitted", "approved", "ordered", "received", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "draft", quantity: 1 },
  }),

  documents: cfg({
    title: "Document Management",
    description: "Contracts, drawings, BOQs, certificates",
    table: "ppm_documents",
    numberField: "doc_code",
    numberPrefix: "DOC",
    statusField: "status",
    statusOptions: ["active", "superseded", "archived"],
    columns: [
      { key: "doc_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "doc_type", label: "Type" },
      { key: "project_code", label: "Project" },
      { key: "version_label", label: "Ver" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "doc_code", label: "Code", required: true, autoNumber: "DOC", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "project_code", label: "Project code" },
      { key: "doc_type", label: "Type", type: "select", options: ["contract", "drawing", "boq", "specification", "photo", "video", "inspection", "change_order", "minutes", "certificate", "other"] },
      { key: "version_label", label: "Version" },
      { key: "file_url", label: "File URL" },
      { key: "qr_payload", label: "QR payload" },
      { key: "status", label: "Status", type: "select", options: ["active", "superseded", "archived"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", doc_type: "other", version_label: "1.0" },
  }),

  changes: cfg({
    title: "Change Requests",
    description: "Scope, budget, schedule change control",
    table: "ppm_change_requests",
    numberField: "change_number",
    numberPrefix: "CR",
    statusField: "status",
    statusOptions: ["submitted", "impact_analysis", "approved", "rejected", "implemented", "closed"],
    columns: [
      { key: "change_number", label: "CR #" },
      { key: "title", label: "Title" },
      { key: "change_type", label: "Type" },
      { key: "cost_impact", label: "Cost impact" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "change_number", label: "Number", autoNumber: "CR", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "project_code", label: "Project code" },
      { key: "change_type", label: "Type", type: "select", options: ["scope", "budget", "schedule", "resource"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "impact_analysis", label: "Impact analysis", type: "textarea" },
      { key: "cost_impact", label: "Cost impact", type: "number" },
      { key: "schedule_impact_days", label: "Schedule days", type: "number" },
      { key: "requester_name", label: "Requester" },
      { key: "status", label: "Status", type: "select", options: ["submitted", "impact_analysis", "approved", "rejected", "implemented", "closed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "submitted", change_type: "scope" },
  }),

  risks: cfg({
    title: "Risk Register",
    description: "Probability, impact, mitigation, owners",
    table: "ppm_risks",
    numberField: "risk_code",
    numberPrefix: "RSK",
    statusField: "status",
    statusOptions: ["open", "mitigating", "closed", "accepted"],
    columns: [
      { key: "risk_code", label: "Code" },
      { key: "title", label: "Risk" },
      { key: "probability", label: "Prob." },
      { key: "impact", label: "Impact" },
      { key: "risk_score", label: "Score" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "risk_code", label: "Code", required: true, autoNumber: "RSK", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "project_code", label: "Project code" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "probability", label: "Probability", type: "select", options: ["low", "medium", "high", "critical"] },
      { key: "impact", label: "Impact", type: "select", options: ["low", "medium", "high", "critical"] },
      { key: "risk_score", label: "Score", type: "number" },
      { key: "mitigation", label: "Mitigation", type: "textarea" },
      { key: "owner_name", label: "Owner" },
      { key: "status", label: "Status", type: "select", options: ["open", "mitigating", "closed", "accepted"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "open", probability: "medium", impact: "medium", risk_score: 9 },
  }),

  issues: cfg({
    title: "Issue Register",
    description: "Severity, root cause, resolution, escalation",
    table: "ppm_issues",
    numberField: "issue_code",
    numberPrefix: "ISS",
    statusField: "status",
    statusOptions: ["open", "in_progress", "escalated", "resolved", "closed"],
    columns: [
      { key: "issue_code", label: "Code" },
      { key: "title", label: "Issue" },
      { key: "severity", label: "Severity" },
      { key: "owner_name", label: "Owner" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "issue_code", label: "Code", required: true, autoNumber: "ISS", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "project_code", label: "Project code" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "severity", label: "Severity", type: "select", options: ["low", "medium", "high", "critical"] },
      { key: "root_cause", label: "Root cause", type: "textarea" },
      { key: "resolution", label: "Resolution", type: "textarea" },
      { key: "escalation_level", label: "Escalation", type: "select", options: ["project", "program", "portfolio", "executive"] },
      { key: "owner_name", label: "Owner" },
      { key: "raised_date", label: "Raised", type: "date" },
      { key: "closed_date", label: "Closed", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["open", "in_progress", "escalated", "resolved", "closed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "open", severity: "medium", escalation_level: "project" },
  }),

  decisions: cfg({
    title: "Decision Log",
    description: "Recorded project decisions",
    table: "ppm_decisions",
    numberField: "decision_code",
    numberPrefix: "DEC",
    statusField: "status",
    statusOptions: ["recorded", "superseded", "void"],
    columns: [
      { key: "decision_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "decision_date", label: "Date" },
      { key: "decided_by", label: "By" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "decision_code", label: "Code", autoNumber: "DEC", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "project_code", label: "Project code" },
      { key: "decision_text", label: "Decision", type: "textarea" },
      { key: "decision_date", label: "Date", type: "date" },
      { key: "decided_by", label: "Decided by" },
      { key: "status", label: "Status", type: "select", options: ["recorded", "superseded", "void"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "recorded" },
  }),

  lessons: cfg({
    title: "Lessons Learned",
    description: "What went well and improvements",
    table: "ppm_lessons",
    numberField: "lesson_code",
    numberPrefix: "LL",
    statusField: "status",
    statusOptions: ["draft", "published", "archived"],
    columns: [
      { key: "lesson_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "category", label: "Category" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "lesson_code", label: "Code", autoNumber: "LL", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "project_code", label: "Project code" },
      { key: "category", label: "Category" },
      { key: "what_went_well", label: "What went well", type: "textarea" },
      { key: "what_to_improve", label: "What to improve", type: "textarea" },
      { key: "recommendation", label: "Recommendation", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["draft", "published", "archived"] },
    ],
    defaults: { status: "draft", category: "general" },
  }),

  meetings: cfg({
    title: "Meeting Minutes",
    description: "Agenda, attendees, actions",
    table: "ppm_meetings",
    numberField: "meeting_code",
    numberPrefix: "MTG",
    statusField: "status",
    statusOptions: ["scheduled", "completed", "cancelled"],
    columns: [
      { key: "meeting_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "project_code", label: "Project" },
      { key: "meeting_date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "meeting_code", label: "Code", autoNumber: "MTG", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "project_code", label: "Project code" },
      { key: "attendees", label: "Attendees", type: "textarea" },
      { key: "agenda", label: "Agenda", type: "textarea" },
      { key: "minutes", label: "Minutes", type: "textarea" },
      { key: "action_items", label: "Action items", type: "textarea" },
      { key: "file_url", label: "File URL" },
      { key: "status", label: "Status", type: "select", options: ["scheduled", "completed", "cancelled"] },
    ],
    defaults: { status: "scheduled" },
  }),

  inspections: cfg({
    title: "Project Inspections",
    description: "QA/QC inspection results",
    table: "ppm_inspections",
    numberField: "inspection_code",
    numberPrefix: "INSP",
    statusField: "status",
    statusOptions: ["scheduled", "completed", "failed", "cancelled"],
    columns: [
      { key: "inspection_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "result", label: "Result" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "inspection_code", label: "Code", autoNumber: "INSP", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "project_code", label: "Project code" },
      { key: "inspection_type", label: "Type", type: "select", options: ["qa", "qc", "safety", "handover"] },
      { key: "inspection_date", label: "Date", type: "date" },
      { key: "result", label: "Result", type: "select", options: ["pass", "conditional", "fail"] },
      { key: "inspector_name", label: "Inspector" },
      { key: "findings", label: "Findings", type: "textarea" },
      { key: "file_url", label: "File URL" },
      { key: "status", label: "Status", type: "select", options: ["scheduled", "completed", "failed", "cancelled"] },
    ],
    defaults: { status: "completed", result: "pass", inspection_type: "qa" },
  }),

  ncr: cfg({
    title: "NCR / CAPA",
    description: "Non-conformances and corrective actions",
    table: "ppm_ncr",
    numberField: "ncr_code",
    numberPrefix: "NCR",
    statusField: "status",
    statusOptions: ["open", "in_progress", "closed"],
    columns: [
      { key: "ncr_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "severity", label: "Severity" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "ncr_code", label: "Code", autoNumber: "NCR", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "project_code", label: "Project code" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "severity", label: "Severity", type: "select", options: ["low", "medium", "high", "critical"] },
      { key: "capa", label: "CAPA", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["open", "in_progress", "closed"] },
      { key: "closed_date", label: "Closed", type: "date" },
    ],
    defaults: { status: "open", severity: "medium" },
  }),

  invoices: cfg({
    title: "Project Invoices",
    description: "Customer billing from projects",
    table: "ppm_invoices",
    numberField: "invoice_number",
    numberPrefix: "PINV",
    statusField: "status",
    statusOptions: ["draft", "issued", "paid", "partial", "overdue", "cancelled"],
    columns: [
      { key: "invoice_number", label: "Invoice #" },
      { key: "project_code", label: "Project" },
      { key: "customer_name", label: "Customer" },
      { key: "net_amount", label: "Net" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "invoice_number", label: "Number", autoNumber: "PINV", createOnly: true },
      { key: "project_code", label: "Project code" },
      { key: "customer_name", label: "Customer" },
      { key: "invoice_date", label: "Invoice date", type: "date" },
      { key: "due_date", label: "Due date", type: "date" },
      { key: "billing_method", label: "Method", type: "select", options: ["fixed_price", "t_and_m", "milestone", "progress", "retention", "recurring"] },
      { key: "amount", label: "Amount", type: "number" },
      { key: "tax_amount", label: "Tax", type: "number" },
      { key: "retention_amount", label: "Retention", type: "number" },
      { key: "net_amount", label: "Net amount", type: "number" },
      { key: "currency_code", label: "Currency" },
      { key: "milestone_name", label: "Milestone" },
      { key: "status", label: "Status", type: "select", options: ["draft", "issued", "paid", "partial", "overdue", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "draft", billing_method: "milestone", currency_code: "UGX" },
  }),

  claims: cfg({
    title: "Progress Claims",
    description: "Period claims and certification",
    table: "ppm_progress_claims",
    numberField: "claim_number",
    numberPrefix: "CLM",
    statusField: "status",
    statusOptions: ["draft", "submitted", "certified", "paid", "disputed"],
    columns: [
      { key: "claim_number", label: "Claim #" },
      { key: "project_code", label: "Project" },
      { key: "period_label", label: "Period" },
      { key: "claimed_amount", label: "Claimed" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "claim_number", label: "Number", autoNumber: "CLM", createOnly: true },
      { key: "project_code", label: "Project code" },
      { key: "period_label", label: "Period" },
      { key: "claim_date", label: "Date", type: "date" },
      { key: "percent_complete", label: "% Complete", type: "number" },
      { key: "claimed_amount", label: "Claimed amount", type: "number" },
      { key: "certified_amount", label: "Certified amount", type: "number" },
      { key: "retention_pct", label: "Retention %", type: "number" },
      { key: "retention_amount", label: "Retention amount", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["draft", "submitted", "certified", "paid", "disputed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "draft", retention_pct: 10 },
  }),

  retentions: cfg({
    title: "Retention Management",
    description: "Held and released retention amounts",
    table: "ppm_retentions",
    numberField: "retention_code",
    numberPrefix: "RET",
    statusField: "status",
    statusOptions: ["held", "released", "partial"],
    columns: [
      { key: "retention_code", label: "Code" },
      { key: "project_code", label: "Project" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "retention_code", label: "Code", autoNumber: "RET", createOnly: true },
      { key: "project_code", label: "Project code" },
      { key: "claim_number", label: "Claim number" },
      { key: "amount", label: "Amount", type: "number" },
      { key: "release_date", label: "Release date", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["held", "released", "partial"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "held" },
  }),

  revenue: cfg({
    title: "Revenue Recognition",
    description: "Percent-complete and milestone revenue",
    table: "ppm_revenue",
    numberField: "revenue_code",
    numberPrefix: "REV",
    statusField: "status",
    statusOptions: ["draft", "recognized", "reversed"],
    columns: [
      { key: "revenue_code", label: "Code" },
      { key: "project_code", label: "Project" },
      { key: "amount", label: "Amount" },
      { key: "recognition_date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "revenue_code", label: "Code", autoNumber: "REV", createOnly: true },
      { key: "project_code", label: "Project code" },
      { key: "recognition_date", label: "Date", type: "date" },
      { key: "method", label: "Method", type: "select", options: ["percent_complete", "milestone", "completed_contract"] },
      { key: "amount", label: "Amount", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["draft", "recognized", "reversed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "recognized", method: "percent_complete" },
  }),

  assets: cfg({
    title: "Asset Allocation",
    description: "Equipment and assets on projects",
    table: "ppm_asset_allocations",
    numberField: "allocation_code",
    numberPrefix: "AST",
    statusField: "status",
    statusOptions: ["allocated", "returned", "damaged"],
    columns: [
      { key: "allocation_code", label: "Code" },
      { key: "asset_name", label: "Asset" },
      { key: "project_code", label: "Project" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "allocation_code", label: "Code", autoNumber: "AST", createOnly: true },
      { key: "asset_name", label: "Asset name", required: true },
      { key: "project_code", label: "Project code" },
      { key: "asset_type", label: "Type" },
      { key: "quantity", label: "Qty", type: "number" },
      { key: "start_date", label: "Start", type: "date" },
      { key: "end_date", label: "End", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["allocated", "returned", "damaged"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "allocated", quantity: 1 },
  }),

  inventory: cfg({
    title: "Inventory Allocation",
    description: "Materials reserved for projects",
    table: "ppm_inventory_allocations",
    numberField: "allocation_code",
    numberPrefix: "INV",
    statusField: "status",
    statusOptions: ["reserved", "issued", "returned", "consumed"],
    columns: [
      { key: "allocation_code", label: "Code" },
      { key: "item_name", label: "Item" },
      { key: "project_code", label: "Project" },
      { key: "quantity", label: "Qty" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "allocation_code", label: "Code", autoNumber: "INV", createOnly: true },
      { key: "item_name", label: "Item name", required: true },
      { key: "project_code", label: "Project code" },
      { key: "sku", label: "SKU" },
      { key: "quantity", label: "Quantity", type: "number" },
      { key: "uom", label: "UOM" },
      { key: "status", label: "Status", type: "select", options: ["reserved", "issued", "returned", "consumed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "reserved", uom: "EA" },
  }),

  approvals: cfg({
    title: "Project Approvals",
    description: "Electronic approval workflow",
    table: "ppm_approvals",
    numberField: "approval_number",
    numberPrefix: "PAP",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected"],
    columns: [
      { key: "approval_number", label: "Number" },
      { key: "title", label: "Title" },
      { key: "entity_table", label: "Entity" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "approval_number", label: "Number", autoNumber: "PAP", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "entity_table", label: "Entity table", required: true },
      { key: "entity_code", label: "Entity code" },
      { key: "workflow_step", label: "Workflow step" },
      { key: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected"] },
      { key: "decision_notes", label: "Decision notes", type: "textarea" },
    ],
    defaults: { status: "pending", workflow_step: "review" },
  }),

  notifications: cfg({
    title: "Project Notifications",
    description: "In-app project alerts",
    table: "ppm_notifications",
    columns: [
      { key: "title", label: "Title" },
      { key: "severity", label: "Severity" },
      { key: "project_code", label: "Project" },
      { key: "is_read", label: "Read" },
      { key: "created_at", label: "Created" },
    ],
    fields: [
      { key: "title", label: "Title", required: true },
      { key: "body", label: "Body", type: "textarea" },
      { key: "severity", label: "Severity", type: "select", options: ["info", "warning", "critical"] },
      { key: "category", label: "Category" },
      { key: "project_code", label: "Project code" },
    ],
    defaults: { severity: "info", category: "general" },
  }),

  settings: cfg({
    title: "Project Settings",
    description: "Company PPM configuration",
    table: "ppm_settings",
    columns: [
      { key: "setting_key", label: "Key" },
      { key: "setting_value", label: "Value" },
      { key: "description", label: "Description" },
    ],
    fields: [
      { key: "setting_key", label: "Key", required: true, createOnly: true },
      { key: "setting_value", label: "Value (JSON)", required: true },
      { key: "description", label: "Description" },
    ],
  }),

  audit: cfg({
    title: "Project Audit Logs",
    description: "Immutable action history",
    table: "ppm_audit_log",
    columns: [
      { key: "action", label: "Action" },
      { key: "entity_table", label: "Entity" },
      { key: "entity_code", label: "Code" },
      { key: "details", label: "Details" },
      { key: "created_at", label: "When" },
    ],
    fields: [
      { key: "action", label: "Action", required: true },
      { key: "entity_table", label: "Entity table" },
      { key: "entity_code", label: "Entity code" },
      { key: "details", label: "Details", type: "textarea" },
    ],
  }),

  baselines: cfg({
    title: "Project Baselines",
    description: "Schedule and budget baselines",
    table: "ppm_baselines",
    statusField: "status",
    statusOptions: ["active", "superseded", "archived"],
    columns: [
      { key: "baseline_name", label: "Name" },
      { key: "project_code", label: "Project" },
      { key: "baseline_date", label: "Date" },
      { key: "budget", label: "Budget" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "baseline_name", label: "Name", required: true },
      { key: "project_code", label: "Project code" },
      { key: "baseline_date", label: "Date", type: "date" },
      { key: "start_date", label: "Start", type: "date" },
      { key: "end_date", label: "End", type: "date" },
      { key: "budget", label: "Budget", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "superseded", "archived"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active" },
  }),

  calendar: cfg({
    title: "Project Calendar",
    description: "Milestones, meetings and key events",
    table: "ppm_calendar_events",
    statusField: "status",
    statusOptions: ["scheduled", "completed", "cancelled"],
    columns: [
      { key: "title", label: "Title" },
      { key: "project_code", label: "Project" },
      { key: "event_type", label: "Type" },
      { key: "start_at", label: "Start" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "title", label: "Title", required: true },
      { key: "project_code", label: "Project code" },
      { key: "event_type", label: "Type", type: "select", options: ["milestone", "meeting", "deadline", "review", "other"] },
      { key: "start_at", label: "Start", type: "datetime" },
      { key: "end_at", label: "End", type: "datetime" },
      { key: "status", label: "Status", type: "select", options: ["scheduled", "completed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "scheduled", event_type: "milestone" },
  }),
};

export const PPM_ENTITY_ALIASES: Record<string, string> = {
  lifecycle: "list",
  timeline: "tasks",
  subtasks: "tasks",
  "critical-path": "dependencies",
  "agile-boards": "tasks",
  capacity: "resources",
  costing: "budgets",
  drawings: "documents",
  contracts: "documents",
  quality: "inspections",
  billing: "invoices",
  "customer-portal": "list",
  "supplier-portal": "purchase-requests",
};

export function resolvePpmEntityConfig(
  slug: string
): (typeof PPM_ENTITIES)[string] | null {
  const key = PPM_ENTITY_ALIASES[slug] || slug;
  return PPM_ENTITIES[key] ?? null;
}

export function listPpmEntityTables(): string[] {
  return [...new Set(Object.values(PPM_ENTITIES).map((c) => c.table))];
}
