/** Complete Project Portfolio Management navigation */

export const PPM_MENU = [
  { title: "Project Dashboard", href: "/dashboard/projects", group: "Overview" },
  { title: "Project Portfolio", href: "/dashboard/projects/portfolio", group: "Portfolio" },
  { title: "Programs", href: "/dashboard/projects/programs", group: "Portfolio" },
  { title: "Projects", href: "/dashboard/projects/list", group: "Portfolio" },
  { title: "Project Templates", href: "/dashboard/projects/templates", group: "Portfolio" },
  { title: "Project Requests", href: "/dashboard/projects/requests", group: "Intake" },
  { title: "Business Cases", href: "/dashboard/projects/business-cases", group: "Intake" },
  { title: "Approval Workflow", href: "/dashboard/projects/approvals", group: "Intake" },
  { title: "Project Categories", href: "/dashboard/projects/categories", group: "Setup" },
  { title: "Project Types", href: "/dashboard/projects/types", group: "Setup" },
  { title: "Project Lifecycle", href: "/dashboard/projects/lifecycle", group: "Setup" },
  { title: "Project Calendar", href: "/dashboard/projects/calendar", group: "Planning" },
  { title: "Project Timeline", href: "/dashboard/projects/timeline", group: "Planning" },
  { title: "Gantt Chart", href: "/dashboard/projects/gantt", group: "Planning" },
  { title: "Kanban Board", href: "/dashboard/projects/kanban", group: "Planning" },
  { title: "Work Breakdown Structure", href: "/dashboard/projects/wbs", group: "Planning" },
  { title: "Milestones", href: "/dashboard/projects/milestones", group: "Planning" },
  { title: "Deliverables", href: "/dashboard/projects/deliverables", group: "Planning" },
  { title: "Tasks", href: "/dashboard/projects/tasks", group: "Execution" },
  { title: "Subtasks", href: "/dashboard/projects/subtasks", group: "Execution" },
  { title: "Checklists", href: "/dashboard/projects/checklists", group: "Execution" },
  { title: "Dependencies", href: "/dashboard/projects/dependencies", group: "Execution" },
  { title: "Critical Path", href: "/dashboard/projects/critical-path", group: "Execution" },
  { title: "Sprint Management", href: "/dashboard/projects/sprints", group: "Agile" },
  { title: "Agile Boards", href: "/dashboard/projects/agile-boards", group: "Agile" },
  { title: "Backlog", href: "/dashboard/projects/backlog", group: "Agile" },
  { title: "Roadmap", href: "/dashboard/projects/roadmap", group: "Agile" },
  { title: "Resource Management", href: "/dashboard/projects/resources", group: "Resources" },
  { title: "Resource Allocation", href: "/dashboard/projects/allocations", group: "Resources" },
  { title: "Capacity Planning", href: "/dashboard/projects/capacity", group: "Resources" },
  { title: "Time Tracking", href: "/dashboard/projects/time-logs", group: "Resources" },
  { title: "Timesheets", href: "/dashboard/projects/timesheets", group: "Resources" },
  { title: "Budget Management", href: "/dashboard/projects/budgets", group: "Finance" },
  { title: "Project Costing", href: "/dashboard/projects/costing", group: "Finance" },
  { title: "Expense Claims", href: "/dashboard/projects/expenses", group: "Finance" },
  { title: "Purchase Requests", href: "/dashboard/projects/purchase-requests", group: "Procurement" },
  { title: "Inventory Allocation", href: "/dashboard/projects/inventory", group: "Procurement" },
  { title: "Asset Allocation", href: "/dashboard/projects/assets", group: "Procurement" },
  { title: "Document Management", href: "/dashboard/projects/documents", group: "Documents" },
  { title: "Drawings", href: "/dashboard/projects/drawings", group: "Documents" },
  { title: "Contracts", href: "/dashboard/projects/contracts", group: "Documents" },
  { title: "Change Requests", href: "/dashboard/projects/changes", group: "Control" },
  { title: "Risk Register", href: "/dashboard/projects/risks", group: "Control" },
  { title: "Issue Register", href: "/dashboard/projects/issues", group: "Control" },
  { title: "Decision Log", href: "/dashboard/projects/decisions", group: "Control" },
  { title: "Lessons Learned", href: "/dashboard/projects/lessons", group: "Control" },
  { title: "Meeting Minutes", href: "/dashboard/projects/meetings", group: "Control" },
  { title: "Quality Management", href: "/dashboard/projects/quality", group: "Quality" },
  { title: "Inspections", href: "/dashboard/projects/inspections", group: "Quality" },
  { title: "QA / NCR", href: "/dashboard/projects/ncr", group: "Quality" },
  { title: "Billing", href: "/dashboard/projects/billing", group: "Billing" },
  { title: "Invoices", href: "/dashboard/projects/invoices", group: "Billing" },
  { title: "Progress Claims", href: "/dashboard/projects/claims", group: "Billing" },
  { title: "Retention Management", href: "/dashboard/projects/retentions", group: "Billing" },
  { title: "Revenue Recognition", href: "/dashboard/projects/revenue", group: "Billing" },
  { title: "Customer Portal", href: "/dashboard/projects/customer-portal", group: "Portals" },
  { title: "Supplier Portal", href: "/dashboard/projects/supplier-portal", group: "Portals" },
  { title: "Project Reports", href: "/dashboard/projects/reports", group: "Analytics" },
  { title: "Analytics", href: "/dashboard/projects/analytics", group: "Analytics" },
  { title: "AI Project Assistant", href: "/dashboard/projects/ai", group: "Analytics" },
  { title: "Baselines", href: "/dashboard/projects/baselines", group: "System" },
  { title: "Notifications", href: "/dashboard/projects/notifications", group: "System" },
  { title: "Audit Logs", href: "/dashboard/projects/audit", group: "System" },
  { title: "Project Settings", href: "/dashboard/projects/settings", group: "System" },
] as const;
