export type FinEntityConfig = {
  title: string;
  description: string;
  table: string;
  numberField?: string;
  numberPrefix?: string;
  searchCols?: string[];
  columns: Array<{ key: string; label: string }>;
  fields: Array<{
    key: string;
    label: string;
    type?: "text" | "number" | "date" | "datetime" | "select" | "textarea";
    options?: string[];
    required?: boolean;
    createOnly?: boolean;
    autoNumber?: string;
  }>;
  statusField?: string;
  statusOptions?: string[];
  defaults?: Record<string, unknown>;
};

function cfg(p: FinEntityConfig): FinEntityConfig {
  return {
    searchCols: p.searchCols || ["code", "name", "title", "status", "account_code", "journal_number"],
    ...p,
  };
}

export const FIN_ENTITIES: Record<string, FinEntityConfig> = {
  "account-groups": cfg({
    title: "Account Groups",
    description: "COA grouping for reporting",
    table: "fin_account_groups",
    numberField: "code",
    numberPrefix: "AG",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "account_type", label: "Type" },
    ],
    fields: [
      { key: "code", label: "Code", required: true, autoNumber: "AG", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "account_type", label: "Account type", type: "select", options: ["asset", "liability", "equity", "revenue", "cost_of_sales", "operating_expense"] },
      { key: "description", label: "Description", type: "textarea" },
    ],
    defaults: { account_type: "asset" },
  }),

  dimensions: cfg({
    title: "Financial Dimensions",
    description: "Branch, department, project, product dimensions",
    table: "fin_dimensions",
    numberField: "code",
    numberPrefix: "DIM",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "dimension_type", label: "Type" },
    ],
    fields: [
      { key: "code", label: "Code", required: true, autoNumber: "DIM", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "dimension_type", label: "Type", type: "select", options: ["branch", "department", "project", "product", "customer", "supplier", "custom"] },
    ],
    defaults: { dimension_type: "custom" },
  }),

  "profit-centers": cfg({
    title: "Profit Centers",
    description: "Profit center master",
    table: "fin_profit_centers",
    numberField: "code",
    numberPrefix: "PC",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "manager_name", label: "Manager" },
      { key: "branch_name", label: "Branch" },
    ],
    fields: [
      { key: "code", label: "Code", required: true, autoNumber: "PC", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "manager_name", label: "Manager" },
      { key: "branch_name", label: "Branch" },
    ],
  }),

  "business-units": cfg({
    title: "Business Units",
    description: "Branches, BUs and divisions",
    table: "fin_business_units",
    numberField: "code",
    numberPrefix: "BU",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "unit_type", label: "Type" },
    ],
    fields: [
      { key: "code", label: "Code", required: true, autoNumber: "BU", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "unit_type", label: "Type", type: "select", options: ["branch", "bu", "division"] },
    ],
    defaults: { unit_type: "branch" },
  }),

  "fiscal-years": cfg({
    title: "Fiscal Years",
    description: "Company fiscal year definitions",
    table: "fiscal_years",
    columns: [
      { key: "name", label: "Name" },
      { key: "start_date", label: "Start" },
      { key: "end_date", label: "End" },
      { key: "status", label: "Status" },
    ],
    statusField: "status",
    statusOptions: ["open", "soft_close", "closed", "locked"],
    fields: [
      { key: "name", label: "Name", required: true },
      { key: "start_date", label: "Start date", type: "date", required: true },
      { key: "end_date", label: "End date", type: "date", required: true },
      { key: "status", label: "Status", type: "select", options: ["open", "soft_close", "closed", "locked"] },
    ],
    defaults: { status: "open" },
  }),

  "journal-templates": cfg({
    title: "Journal Templates",
    description: "Reusable JE templates",
    table: "fin_journal_templates",
    numberField: "template_code",
    numberPrefix: "JT",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "template_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "journal_type", label: "Type" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "template_code", label: "Code", required: true, autoNumber: "JT", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "journal_type", label: "Type", type: "select", options: ["general", "sales", "purchase", "cash", "bank", "payroll", "depreciation", "adjustment", "closing"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
    defaults: { status: "active", journal_type: "general" },
  }),

  "recurring-journals": cfg({
    title: "Recurring Journals",
    description: "Scheduled automatic journals",
    table: "fin_recurring_journals",
    numberField: "schedule_code",
    numberPrefix: "RJ",
    statusField: "status",
    statusOptions: ["active", "paused", "completed"],
    columns: [
      { key: "schedule_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "frequency", label: "Frequency" },
      { key: "next_run_date", label: "Next run" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "schedule_code", label: "Code", autoNumber: "RJ", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "template_code", label: "Template code" },
      { key: "frequency", label: "Frequency", type: "select", options: ["daily", "weekly", "monthly", "quarterly", "yearly"] },
      { key: "next_run_date", label: "Next run", type: "date" },
      { key: "amount", label: "Amount", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "paused", "completed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", frequency: "monthly" },
  }),

  "posting-batches": cfg({
    title: "Posting Batches",
    description: "Batch journal posting control",
    table: "fin_posting_batches",
    numberField: "batch_number",
    numberPrefix: "PB",
    statusField: "status",
    statusOptions: ["open", "posted", "cancelled"],
    columns: [
      { key: "batch_number", label: "Batch #" },
      { key: "batch_date", label: "Date" },
      { key: "journal_count", label: "Journals" },
      { key: "total_debit", label: "Debit" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "batch_number", label: "Batch number", autoNumber: "PB", createOnly: true },
      { key: "batch_date", label: "Date", type: "date" },
      { key: "journal_count", label: "Journal count", type: "number" },
      { key: "total_debit", label: "Total debit", type: "number" },
      { key: "total_credit", label: "Total credit", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["open", "posted", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "open" },
  }),

  "trial-balance": cfg({
    title: "Trial Balance Snapshots",
    description: "Period trial balance lines",
    table: "fin_trial_balance",
    columns: [
      { key: "snapshot_code", label: "Snapshot" },
      { key: "account_code", label: "Account" },
      { key: "account_name", label: "Name" },
      { key: "debit", label: "Debit" },
      { key: "credit", label: "Credit" },
    ],
    fields: [
      { key: "snapshot_code", label: "Snapshot code", required: true },
      { key: "period_label", label: "Period" },
      { key: "account_code", label: "Account code", required: true },
      { key: "account_name", label: "Account name" },
      { key: "debit", label: "Debit", type: "number" },
      { key: "credit", label: "Credit", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["draft", "final"] },
    ],
    defaults: { status: "draft" },
  }),

  "period-locks": cfg({
    title: "Period Locks",
    description: "Module and period lock controls",
    table: "fin_period_locks",
    numberField: "lock_code",
    numberPrefix: "LK",
    statusField: "status",
    statusOptions: ["locked", "unlocked"],
    columns: [
      { key: "lock_code", label: "Code" },
      { key: "period_name", label: "Period" },
      { key: "module_scope", label: "Scope" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "lock_code", label: "Lock code", autoNumber: "LK", createOnly: true },
      { key: "period_name", label: "Period name", required: true },
      { key: "module_scope", label: "Scope", type: "select", options: ["all", "gl", "ar", "ap", "bank", "assets"] },
      { key: "status", label: "Status", type: "select", options: ["locked", "unlocked"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "locked", module_scope: "all" },
  }),

  "ar-credit-notes": cfg({
    title: "AR Credit Notes",
    description: "Customer credit notes",
    table: "ar_credit_notes",
    numberField: "credit_note_number",
    numberPrefix: "CN",
    statusField: "status",
    statusOptions: ["draft", "issued", "applied", "void"],
    columns: [
      { key: "credit_note_number", label: "Number" },
      { key: "amount", label: "Amount" },
      { key: "credit_date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "credit_note_number", label: "Number", autoNumber: "CN", createOnly: true },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "credit_date", label: "Date", type: "date" },
      { key: "currency", label: "Currency" },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["draft", "issued", "applied", "void"] },
    ],
    defaults: { status: "issued", currency: "UGX" },
  }),

  "ar-debit-notes": cfg({
    title: "AR Debit Notes",
    description: "Customer debit notes",
    table: "fin_ar_debit_notes",
    numberField: "debit_note_number",
    numberPrefix: "DN",
    statusField: "status",
    statusOptions: ["draft", "issued", "void"],
    columns: [
      { key: "debit_note_number", label: "Number" },
      { key: "customer_name", label: "Customer" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "debit_note_number", label: "Number", autoNumber: "DN", createOnly: true },
      { key: "customer_name", label: "Customer", required: true },
      { key: "invoice_ref", label: "Invoice ref" },
      { key: "debit_date", label: "Date", type: "date" },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "currency", label: "Currency" },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["draft", "issued", "void"] },
    ],
    defaults: { status: "issued", currency: "UGX" },
  }),

  receipts: cfg({
    title: "AR Receipts",
    description: "Customer receipts and allocations",
    table: "ar_receipts",
    numberField: "receipt_number",
    numberPrefix: "RCT",
    columns: [
      { key: "receipt_number", label: "Number" },
      { key: "amount", label: "Amount" },
      { key: "receipt_date", label: "Date" },
      { key: "payment_method", label: "Method" },
    ],
    fields: [
      { key: "receipt_number", label: "Number", autoNumber: "RCT", createOnly: true },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "receipt_date", label: "Date", type: "date" },
      { key: "currency", label: "Currency" },
      { key: "payment_method", label: "Method", type: "select", options: ["bank_transfer", "cash", "cheque", "mobile_money", "card"] },
      { key: "reference", label: "Reference" },
    ],
    defaults: { currency: "UGX", payment_method: "bank_transfer" },
  }),

  collections: cfg({
    title: "Collections",
    description: "Collection activities and recoveries",
    table: "fin_collections",
    numberField: "collection_number",
    numberPrefix: "COL",
    statusField: "status",
    statusOptions: ["open", "partial", "collected", "written_off"],
    columns: [
      { key: "collection_number", label: "Number" },
      { key: "customer_name", label: "Customer" },
      { key: "amount_due", label: "Due" },
      { key: "amount_collected", label: "Collected" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "collection_number", label: "Number", autoNumber: "COL", createOnly: true },
      { key: "customer_name", label: "Customer", required: true },
      { key: "amount_due", label: "Amount due", type: "number" },
      { key: "amount_collected", label: "Collected", type: "number" },
      { key: "collector_name", label: "Collector" },
      { key: "collection_date", label: "Date", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["open", "partial", "collected", "written_off"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "open" },
  }),

  "payment-plans": cfg({
    title: "Payment Plans",
    description: "Customer installment plans",
    table: "fin_payment_plans",
    numberField: "plan_number",
    numberPrefix: "PP",
    statusField: "status",
    statusOptions: ["active", "completed", "defaulted", "cancelled"],
    columns: [
      { key: "plan_number", label: "Plan #" },
      { key: "customer_name", label: "Customer" },
      { key: "total_amount", label: "Total" },
      { key: "installments", label: "Installments" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "plan_number", label: "Plan number", autoNumber: "PP", createOnly: true },
      { key: "customer_name", label: "Customer", required: true },
      { key: "invoice_ref", label: "Invoice ref" },
      { key: "total_amount", label: "Total", type: "number" },
      { key: "installments", label: "Installments", type: "number" },
      { key: "start_date", label: "Start", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["active", "completed", "defaulted", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", installments: 3 },
  }),

  "customer-statements": cfg({
    title: "Customer Statements",
    description: "Issued AR statements",
    table: "fin_customer_statements",
    numberField: "statement_number",
    numberPrefix: "CST",
    statusField: "status",
    statusOptions: ["draft", "issued", "sent"],
    columns: [
      { key: "statement_number", label: "Number" },
      { key: "customer_name", label: "Customer" },
      { key: "closing_balance", label: "Closing" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "statement_number", label: "Number", autoNumber: "CST", createOnly: true },
      { key: "customer_name", label: "Customer", required: true },
      { key: "period_from", label: "From", type: "date" },
      { key: "period_to", label: "To", type: "date" },
      { key: "opening_balance", label: "Opening", type: "number" },
      { key: "closing_balance", label: "Closing", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["draft", "issued", "sent"] },
      { key: "file_url", label: "File URL" },
    ],
    defaults: { status: "issued" },
  }),

  "recurring-invoices": cfg({
    title: "Recurring Invoices",
    description: "Scheduled customer invoices",
    table: "fin_recurring_invoices",
    numberField: "schedule_code",
    numberPrefix: "RI",
    statusField: "status",
    statusOptions: ["active", "paused", "ended"],
    columns: [
      { key: "schedule_code", label: "Code" },
      { key: "customer_name", label: "Customer" },
      { key: "amount", label: "Amount" },
      { key: "frequency", label: "Frequency" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "schedule_code", label: "Code", autoNumber: "RI", createOnly: true },
      { key: "customer_name", label: "Customer", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "amount", label: "Amount", type: "number" },
      { key: "frequency", label: "Frequency", type: "select", options: ["weekly", "monthly", "quarterly", "yearly"] },
      { key: "next_invoice_date", label: "Next invoice", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["active", "paused", "ended"] },
    ],
    defaults: { status: "active", frequency: "monthly" },
  }),

  "ap-invoices": cfg({
    title: "Supplier Invoices",
    description: "AP invoices (supplier required via UI later)",
    table: "ap_invoices",
    numberField: "invoice_number",
    numberPrefix: "API",
    statusField: "status",
    statusOptions: ["draft", "pending_approval", "approved", "partially_paid", "paid", "void", "disputed"],
    columns: [
      { key: "invoice_number", label: "Number" },
      { key: "invoice_date", label: "Date" },
      { key: "total_amount", label: "Total" },
      { key: "amount_paid", label: "Paid" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "invoice_number", label: "Invoice number", autoNumber: "API", createOnly: true },
      { key: "supplier_invoice_ref", label: "Supplier ref" },
      { key: "invoice_date", label: "Date", type: "date" },
      { key: "due_date", label: "Due", type: "date" },
      { key: "subtotal", label: "Subtotal", type: "number" },
      { key: "tax_amount", label: "Tax", type: "number" },
      { key: "total_amount", label: "Total", type: "number" },
      { key: "currency", label: "Currency" },
      { key: "status", label: "Status", type: "select", options: ["draft", "pending_approval", "approved", "partially_paid", "paid", "void", "disputed"] },
      { key: "description", label: "Description", type: "textarea" },
    ],
    defaults: { status: "draft", currency: "UGX" },
  }),

  "ap-credit-notes": cfg({
    title: "AP Credit Notes",
    description: "Supplier credit notes",
    table: "fin_ap_credit_notes",
    numberField: "credit_note_number",
    numberPrefix: "APC",
    statusField: "status",
    statusOptions: ["draft", "issued", "applied", "void"],
    columns: [
      { key: "credit_note_number", label: "Number" },
      { key: "supplier_name", label: "Supplier" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "credit_note_number", label: "Number", autoNumber: "APC", createOnly: true },
      { key: "supplier_name", label: "Supplier", required: true },
      { key: "invoice_ref", label: "Invoice ref" },
      { key: "credit_date", label: "Date", type: "date" },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "currency", label: "Currency" },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["draft", "issued", "applied", "void"] },
    ],
    defaults: { status: "issued", currency: "UGX" },
  }),

  "ap-debit-notes": cfg({
    title: "AP Debit Notes",
    description: "Supplier debit notes",
    table: "fin_ap_debit_notes",
    numberField: "debit_note_number",
    numberPrefix: "APD",
    statusField: "status",
    statusOptions: ["draft", "issued", "void"],
    columns: [
      { key: "debit_note_number", label: "Number" },
      { key: "supplier_name", label: "Supplier" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "debit_note_number", label: "Number", autoNumber: "APD", createOnly: true },
      { key: "supplier_name", label: "Supplier", required: true },
      { key: "invoice_ref", label: "Invoice ref" },
      { key: "debit_date", label: "Date", type: "date" },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "status", label: "Status", type: "select", options: ["draft", "issued", "void"] },
      { key: "reason", label: "Reason", type: "textarea" },
    ],
    defaults: { status: "issued", currency: "UGX" },
  }),

  "payment-runs": cfg({
    title: "Payment Runs",
    description: "Batch supplier payment processing",
    table: "fin_payment_runs",
    numberField: "run_number",
    numberPrefix: "PRUN",
    statusField: "status",
    statusOptions: ["draft", "approved", "processed", "cancelled"],
    columns: [
      { key: "run_number", label: "Run #" },
      { key: "run_date", label: "Date" },
      { key: "total_amount", label: "Total" },
      { key: "payment_method", label: "Method" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "run_number", label: "Run number", autoNumber: "PRUN", createOnly: true },
      { key: "run_date", label: "Date", type: "date" },
      { key: "payment_method", label: "Method", type: "select", options: ["eft", "rtgs", "cheque", "mobile_money", "swift"] },
      { key: "total_amount", label: "Total", type: "number" },
      { key: "invoice_count", label: "Invoice count", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["draft", "approved", "processed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "draft", payment_method: "eft" },
  }),

  "supplier-statements": cfg({
    title: "Vendor Statements",
    description: "Supplier statement register",
    table: "fin_supplier_statements",
    numberField: "statement_number",
    numberPrefix: "SST",
    statusField: "status",
    statusOptions: ["received", "reconciled", "disputed"],
    columns: [
      { key: "statement_number", label: "Number" },
      { key: "supplier_name", label: "Supplier" },
      { key: "closing_balance", label: "Closing" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "statement_number", label: "Number", autoNumber: "SST", createOnly: true },
      { key: "supplier_name", label: "Supplier", required: true },
      { key: "period_from", label: "From", type: "date" },
      { key: "period_to", label: "To", type: "date" },
      { key: "opening_balance", label: "Opening", type: "number" },
      { key: "closing_balance", label: "Closing", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["received", "reconciled", "disputed"] },
    ],
    defaults: { status: "received" },
  }),

  "supplier-recon": cfg({
    title: "Supplier Reconciliation",
    description: "Book vs statement reconciliation",
    table: "fin_supplier_recon",
    numberField: "recon_number",
    numberPrefix: "SREC",
    statusField: "status",
    statusOptions: ["in_progress", "matched", "difference"],
    columns: [
      { key: "recon_number", label: "Number" },
      { key: "supplier_name", label: "Supplier" },
      { key: "difference", label: "Difference" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "recon_number", label: "Number", autoNumber: "SREC", createOnly: true },
      { key: "supplier_name", label: "Supplier", required: true },
      { key: "recon_date", label: "Date", type: "date" },
      { key: "book_balance", label: "Book balance", type: "number" },
      { key: "statement_balance", label: "Statement balance", type: "number" },
      { key: "difference", label: "Difference", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["in_progress", "matched", "difference"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "in_progress" },
  }),

  banks: cfg({
    title: "Banks",
    description: "Bank master with SWIFT codes",
    table: "fin_banks",
    numberField: "bank_code",
    numberPrefix: "BNK",
    columns: [
      { key: "bank_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "swift_code", label: "SWIFT" },
      { key: "country", label: "Country" },
    ],
    fields: [
      { key: "bank_code", label: "Code", required: true, autoNumber: "BNK", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "swift_code", label: "SWIFT" },
      { key: "country", label: "Country" },
      { key: "contact_phone", label: "Phone" },
    ],
    defaults: { country: "Uganda" },
  }),

  "bank-statements": cfg({
    title: "Bank Statements",
    description: "Imported bank statements",
    table: "fin_bank_statements",
    numberField: "statement_number",
    numberPrefix: "BST",
    statusField: "status",
    statusOptions: ["imported", "reconciled", "error"],
    columns: [
      { key: "statement_number", label: "Number" },
      { key: "bank_account_code", label: "Account" },
      { key: "statement_date", label: "Date" },
      { key: "closing_balance", label: "Closing" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "statement_number", label: "Number", autoNumber: "BST", createOnly: true },
      { key: "bank_account_code", label: "Bank account code" },
      { key: "statement_date", label: "Date", type: "date" },
      { key: "opening_balance", label: "Opening", type: "number" },
      { key: "closing_balance", label: "Closing", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["imported", "reconciled", "error"] },
      { key: "file_url", label: "File URL" },
    ],
    defaults: { status: "imported" },
  }),

  "bank-recon": cfg({
    title: "Bank Reconciliation",
    description: "Statement vs book balances",
    table: "bank_reconciliations",
    statusField: "status",
    statusOptions: ["in_progress", "completed", "cancelled"],
    columns: [
      { key: "statement_date", label: "Statement date" },
      { key: "statement_balance", label: "Statement" },
      { key: "book_balance", label: "Book" },
      { key: "difference", label: "Diff" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "statement_date", label: "Statement date", type: "date", required: true },
      { key: "statement_balance", label: "Statement balance", type: "number", required: true },
      { key: "book_balance", label: "Book balance", type: "number", required: true },
      { key: "difference", label: "Difference", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["in_progress", "completed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "in_progress" },
  }),

  "electronic-payments": cfg({
    title: "Electronic Banking",
    description: "SWIFT, RTGS, ACH, EFT payments",
    table: "fin_electronic_payments",
    numberField: "payment_number",
    numberPrefix: "EP",
    statusField: "status",
    statusOptions: ["pending", "sent", "completed", "failed", "cancelled"],
    columns: [
      { key: "payment_number", label: "Number" },
      { key: "channel", label: "Channel" },
      { key: "beneficiary", label: "Beneficiary" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "payment_number", label: "Number", autoNumber: "EP", createOnly: true },
      { key: "channel", label: "Channel", type: "select", options: ["swift", "rtgs", "ach", "eft", "mobile_money", "cheque"] },
      { key: "beneficiary", label: "Beneficiary", required: true },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "currency", label: "Currency" },
      { key: "payment_date", label: "Date", type: "date" },
      { key: "reference", label: "Reference" },
      { key: "status", label: "Status", type: "select", options: ["pending", "sent", "completed", "failed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "pending", channel: "eft", currency: "UGX" },
  }),

  "petty-cash": cfg({
    title: "Petty Cash",
    description: "Petty cash vouchers",
    table: "fin_petty_cash",
    numberField: "voucher_number",
    numberPrefix: "PCV",
    statusField: "status",
    statusOptions: ["draft", "posted", "void"],
    columns: [
      { key: "voucher_number", label: "Voucher" },
      { key: "payee", label: "Payee" },
      { key: "amount", label: "Amount" },
      { key: "txn_date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "voucher_number", label: "Voucher", autoNumber: "PCV", createOnly: true },
      { key: "txn_date", label: "Date", type: "date" },
      { key: "payee", label: "Payee", required: true },
      { key: "purpose", label: "Purpose", type: "textarea" },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "currency", label: "Currency" },
      { key: "status", label: "Status", type: "select", options: ["draft", "posted", "void"] },
    ],
    defaults: { status: "posted", currency: "UGX" },
  }),

  "cash-forecast": cfg({
    title: "Cash Forecasting",
    description: "Daily cash inflow/outflow forecast",
    table: "fin_cash_forecasts",
    columns: [
      { key: "forecast_date", label: "Date" },
      { key: "inflow", label: "Inflow" },
      { key: "outflow", label: "Outflow" },
      { key: "projected_balance", label: "Projected" },
      { key: "source", label: "Source" },
    ],
    fields: [
      { key: "forecast_date", label: "Date", type: "date", required: true },
      { key: "inflow", label: "Inflow", type: "number" },
      { key: "outflow", label: "Outflow", type: "number" },
      { key: "projected_balance", label: "Projected balance", type: "number" },
      { key: "source", label: "Source", type: "select", options: ["ai", "manual", "system"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { source: "manual" },
  }),

  liquidity: cfg({
    title: "Liquidity Management",
    description: "Cash available and facilities",
    table: "fin_liquidity",
    columns: [
      { key: "snapshot_date", label: "Date" },
      { key: "cash_available", label: "Cash" },
      { key: "undrawn_facilities", label: "Facilities" },
      { key: "short_term_debt", label: "ST Debt" },
      { key: "liquidity_ratio", label: "Ratio" },
    ],
    fields: [
      { key: "snapshot_date", label: "Date", type: "date" },
      { key: "cash_available", label: "Cash available", type: "number" },
      { key: "undrawn_facilities", label: "Undrawn facilities", type: "number" },
      { key: "short_term_debt", label: "Short-term debt", type: "number" },
      { key: "liquidity_ratio", label: "Liquidity ratio", type: "number" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  }),

  investments: cfg({
    title: "Investments",
    description: "Fixed deposits and instruments",
    table: "fin_investments",
    numberField: "investment_code",
    numberPrefix: "INV",
    statusField: "status",
    statusOptions: ["active", "matured", "redeemed"],
    columns: [
      { key: "investment_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "principal", label: "Principal" },
      { key: "interest_rate", label: "Rate" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "investment_code", label: "Code", autoNumber: "INV", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "investment_type", label: "Type", type: "select", options: ["fixed_deposit", "treasury_bill", "bond", "equity", "other"] },
      { key: "principal", label: "Principal", type: "number" },
      { key: "interest_rate", label: "Interest rate", type: "number" },
      { key: "start_date", label: "Start", type: "date" },
      { key: "maturity_date", label: "Maturity", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["active", "matured", "redeemed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", investment_type: "fixed_deposit" },
  }),

  loans: cfg({
    title: "Loans",
    description: "Borrowings and facilities",
    table: "fin_loans",
    numberField: "loan_code",
    numberPrefix: "LN",
    statusField: "status",
    statusOptions: ["active", "closed", "defaulted"],
    columns: [
      { key: "loan_code", label: "Code" },
      { key: "lender_name", label: "Lender" },
      { key: "principal", label: "Principal" },
      { key: "outstanding", label: "Outstanding" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "loan_code", label: "Code", autoNumber: "LN", createOnly: true },
      { key: "lender_name", label: "Lender", required: true },
      { key: "principal", label: "Principal", type: "number" },
      { key: "outstanding", label: "Outstanding", type: "number" },
      { key: "interest_rate", label: "Rate", type: "number" },
      { key: "start_date", label: "Start", type: "date" },
      { key: "end_date", label: "End", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["active", "closed", "defaulted"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active" },
  }),

  "letters-of-credit": cfg({
    title: "Letters of Credit",
    description: "Trade finance LCs",
    table: "fin_letters_of_credit",
    numberField: "lc_number",
    numberPrefix: "LC",
    statusField: "status",
    statusOptions: ["open", "utilized", "expired", "cancelled"],
    columns: [
      { key: "lc_number", label: "LC #" },
      { key: "beneficiary", label: "Beneficiary" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "lc_number", label: "LC number", autoNumber: "LC", createOnly: true },
      { key: "beneficiary", label: "Beneficiary", required: true },
      { key: "amount", label: "Amount", type: "number" },
      { key: "currency", label: "Currency" },
      { key: "issue_date", label: "Issue", type: "date" },
      { key: "expiry_date", label: "Expiry", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["open", "utilized", "expired", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "open", currency: "USD" },
  }),

  guarantees: cfg({
    title: "Guarantees",
    description: "Performance and financial guarantees",
    table: "fin_guarantees",
    numberField: "guarantee_number",
    numberPrefix: "GRN",
    statusField: "status",
    statusOptions: ["active", "released", "claimed", "expired"],
    columns: [
      { key: "guarantee_number", label: "Number" },
      { key: "beneficiary", label: "Beneficiary" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "guarantee_number", label: "Number", autoNumber: "GRN", createOnly: true },
      { key: "beneficiary", label: "Beneficiary", required: true },
      { key: "amount", label: "Amount", type: "number" },
      { key: "guarantee_type", label: "Type", type: "select", options: ["performance", "bid", "advance", "financial"] },
      { key: "issue_date", label: "Issue", type: "date" },
      { key: "expiry_date", label: "Expiry", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["active", "released", "claimed", "expired"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", guarantee_type: "performance" },
  }),

  "budget-templates": cfg({
    title: "Budget Templates",
    description: "OPEX, CAPEX, production templates",
    table: "fin_budget_templates",
    numberField: "template_code",
    numberPrefix: "BT",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "template_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "budget_type", label: "Type" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "template_code", label: "Code", autoNumber: "BT", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "budget_type", label: "Type", type: "select", options: ["operational", "capital", "production", "sales", "procurement", "payroll"] },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
    defaults: { status: "active", budget_type: "operational" },
  }),

  "budget-revisions": cfg({
    title: "Budget Revisions",
    description: "Controlled budget changes",
    table: "fin_budget_revisions",
    numberField: "revision_number",
    numberPrefix: "BR",
    statusField: "status",
    statusOptions: ["draft", "submitted", "approved", "rejected"],
    columns: [
      { key: "revision_number", label: "Number" },
      { key: "budget_code", label: "Budget" },
      { key: "previous_amount", label: "Previous" },
      { key: "new_amount", label: "New" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "revision_number", label: "Number", autoNumber: "BR", createOnly: true },
      { key: "budget_code", label: "Budget code" },
      { key: "revision_date", label: "Date", type: "date" },
      { key: "previous_amount", label: "Previous amount", type: "number" },
      { key: "new_amount", label: "New amount", type: "number" },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["draft", "submitted", "approved", "rejected"] },
    ],
    defaults: { status: "draft" },
  }),

  "budget-variance": cfg({
    title: "Budget Variance",
    description: "Budget vs actual analysis",
    table: "fin_budget_variance",
    numberField: "variance_code",
    numberPrefix: "BV",
    statusField: "status",
    statusOptions: ["open", "explained", "closed"],
    columns: [
      { key: "variance_code", label: "Code" },
      { key: "budget_code", label: "Budget" },
      { key: "budget_amount", label: "Budget" },
      { key: "actual_amount", label: "Actual" },
      { key: "variance_pct", label: "Var %" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "variance_code", label: "Code", autoNumber: "BV", createOnly: true },
      { key: "budget_code", label: "Budget code" },
      { key: "period_label", label: "Period" },
      { key: "budget_amount", label: "Budget amount", type: "number" },
      { key: "actual_amount", label: "Actual amount", type: "number" },
      { key: "variance_amount", label: "Variance amount", type: "number" },
      { key: "variance_pct", label: "Variance %", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["open", "explained", "closed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "open" },
  }),

  forecasts: cfg({
    title: "Forecasts Register",
    description: "Revenue, expense, cash and AI forecasts",
    table: "fin_forecasts",
    numberField: "forecast_code",
    numberPrefix: "FC",
    statusField: "status",
    statusOptions: ["draft", "published", "archived"],
    columns: [
      { key: "forecast_code", label: "Code" },
      { key: "forecast_type", label: "Type" },
      { key: "period_label", label: "Period" },
      { key: "amount", label: "Amount" },
      { key: "source", label: "Source" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "forecast_code", label: "Code", autoNumber: "FC", createOnly: true },
      { key: "forecast_type", label: "Type", type: "select", options: ["revenue", "expense", "cash", "production", "payroll", "inventory", "tax"] },
      { key: "period_label", label: "Period" },
      { key: "amount", label: "Amount", type: "number" },
      { key: "currency", label: "Currency" },
      { key: "source", label: "Source", type: "select", options: ["manual", "ai", "system"] },
      { key: "confidence_pct", label: "Confidence %", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["draft", "published", "archived"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "draft", source: "manual", currency: "UGX", forecast_type: "revenue", confidence_pct: 70 },
  }),

  "costing-methods": cfg({
    title: "Costing Methods",
    description: "Standard, actual, batch, job, ABC, process",
    table: "fin_costing_methods",
    numberField: "method_code",
    numberPrefix: "CM",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "method_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "is_default", label: "Default" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "method_code", label: "Code", required: true, autoNumber: "CM", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
    defaults: { status: "active" },
  }),

  "standard-costs": cfg({
    title: "Standard Costing",
    description: "Standard material, labor, overhead",
    table: "fin_standard_costs",
    numberField: "cost_code",
    numberPrefix: "STD",
    statusField: "status",
    statusOptions: ["active", "superseded"],
    columns: [
      { key: "cost_code", label: "Code" },
      { key: "product_name", label: "Product" },
      { key: "total_standard", label: "Total std" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "cost_code", label: "Code", autoNumber: "STD", createOnly: true },
      { key: "product_name", label: "Product", required: true },
      { key: "material_cost", label: "Material", type: "number" },
      { key: "labor_cost", label: "Labor", type: "number" },
      { key: "overhead_cost", label: "Overhead", type: "number" },
      { key: "total_standard", label: "Total standard", type: "number" },
      { key: "effective_from", label: "Effective from", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["active", "superseded"] },
    ],
    defaults: { status: "active" },
  }),

  "cost-rolls": cfg({
    title: "Cost Rollups",
    description: "Batch/job actual cost rollups",
    table: "fin_cost_rolls",
    numberField: "roll_number",
    numberPrefix: "CRL",
    columns: [
      { key: "roll_number", label: "Roll #" },
      { key: "product_name", label: "Product" },
      { key: "direct_materials", label: "Materials" },
      { key: "direct_labor", label: "Labor" },
      { key: "costing_method", label: "Method" },
    ],
    fields: [
      { key: "roll_number", label: "Roll number", autoNumber: "CRL", createOnly: true },
      { key: "product_name", label: "Product", required: true },
      { key: "production_order_ref", label: "Prod order ref" },
      { key: "product_line", label: "Product line" },
      { key: "batch_qty", label: "Batch qty", type: "number" },
      { key: "direct_materials", label: "Direct materials", type: "number" },
      { key: "direct_labor", label: "Direct labor", type: "number" },
      { key: "factory_overhead", label: "Factory OH", type: "number" },
      { key: "machine_cost", label: "Machine", type: "number" },
      { key: "standard_cost", label: "Standard cost", type: "number" },
      { key: "variance_amount", label: "Variance", type: "number" },
      { key: "costing_method", label: "Method", type: "select", options: ["standard", "actual", "batch", "job", "abc", "process"] },
    ],
    defaults: { costing_method: "actual", currency: "UGX" },
  }),

  "cost-variances": cfg({
    title: "Cost Variance Analysis",
    description: "Material, labor, overhead variances",
    table: "fin_cost_variances",
    numberField: "variance_code",
    numberPrefix: "CV",
    statusField: "status",
    statusOptions: ["open", "analyzed", "closed"],
    columns: [
      { key: "variance_code", label: "Code" },
      { key: "product_name", label: "Product" },
      { key: "variance_type", label: "Type" },
      { key: "variance_amount", label: "Variance" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "variance_code", label: "Code", autoNumber: "CV", createOnly: true },
      { key: "product_name", label: "Product" },
      { key: "variance_type", label: "Type", type: "select", options: ["material", "labor", "overhead", "volume", "price"] },
      { key: "standard_amount", label: "Standard", type: "number" },
      { key: "actual_amount", label: "Actual", type: "number" },
      { key: "variance_amount", label: "Variance", type: "number" },
      { key: "period_label", label: "Period" },
      { key: "status", label: "Status", type: "select", options: ["open", "analyzed", "closed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "open", variance_type: "material" },
  }),

  wip: cfg({
    title: "WIP Accounting",
    description: "Work-in-progress balances",
    table: "fin_wip",
    statusField: "status",
    statusOptions: ["open", "closed"],
    columns: [
      { key: "production_order_ref", label: "Order" },
      { key: "product_name", label: "Product" },
      { key: "closing_wip", label: "Closing WIP" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "production_order_ref", label: "Production order", required: true },
      { key: "product_name", label: "Product" },
      { key: "opening_wip", label: "Opening WIP", type: "number" },
      { key: "materials_added", label: "Materials", type: "number" },
      { key: "labor_added", label: "Labor", type: "number" },
      { key: "overhead_added", label: "Overhead", type: "number" },
      { key: "transferred_to_fg", label: "To FG", type: "number" },
      { key: "closing_wip", label: "Closing WIP", type: "number" },
      { key: "period_year", label: "Year", type: "number" },
      { key: "period_month", label: "Month", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["open", "closed"] },
    ],
    defaults: { status: "open" },
  }),

  "tax-returns": cfg({
    title: "Tax Returns",
    description: "VAT, WHT, PAYE, corporate filings",
    table: "fin_tax_returns",
    statusField: "status",
    statusOptions: ["draft", "filed", "paid"],
    columns: [
      { key: "return_type", label: "Type" },
      { key: "period_year", label: "Year" },
      { key: "period_month", label: "Month" },
      { key: "tax_amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "return_type", label: "Type", type: "select", options: ["vat", "wht", "paye", "corporate", "nssf"], required: true },
      { key: "period_year", label: "Year", type: "number", required: true },
      { key: "period_month", label: "Month", type: "number" },
      { key: "tax_amount", label: "Tax amount", type: "number" },
      { key: "currency", label: "Currency" },
      { key: "due_date", label: "Due date", type: "date" },
      { key: "reference", label: "Reference" },
      { key: "status", label: "Status", type: "select", options: ["draft", "filed", "paid"] },
    ],
    defaults: { status: "draft", currency: "UGX", return_type: "vat" },
  }),

  wht: cfg({
    title: "Withholding Tax",
    description: "WHT on supplier payments",
    table: "fin_withholding_tax",
    numberField: "wht_number",
    numberPrefix: "WHT",
    statusField: "status",
    statusOptions: ["posted", "filed", "void"],
    columns: [
      { key: "wht_number", label: "Number" },
      { key: "supplier_name", label: "Supplier" },
      { key: "gross_amount", label: "Gross" },
      { key: "wht_amount", label: "WHT" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "wht_number", label: "Number", autoNumber: "WHT", createOnly: true },
      { key: "supplier_name", label: "Supplier", required: true },
      { key: "invoice_ref", label: "Invoice ref" },
      { key: "gross_amount", label: "Gross", type: "number" },
      { key: "rate_pct", label: "Rate %", type: "number" },
      { key: "wht_amount", label: "WHT amount", type: "number" },
      { key: "txn_date", label: "Date", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["posted", "filed", "void"] },
    ],
    defaults: { status: "posted", rate_pct: 6 },
  }),

  "tax-jurisdictions": cfg({
    title: "Tax Jurisdictions",
    description: "Multi-jurisdiction tax masters",
    table: "fin_tax_jurisdictions",
    numberField: "code",
    numberPrefix: "TJ",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "country", label: "Country" },
    ],
    fields: [
      { key: "code", label: "Code", required: true, autoNumber: "TJ", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "country", label: "Country" },
    ],
    defaults: { country: "Uganda" },
  }),

  intercompany: cfg({
    title: "Intercompany Transactions",
    description: "IC postings between entities",
    table: "fin_intercompany_txns",
    numberField: "txn_number",
    numberPrefix: "IC",
    statusField: "status",
    statusOptions: ["draft", "posted", "eliminated", "void"],
    columns: [
      { key: "txn_number", label: "Number" },
      { key: "from_entity", label: "From" },
      { key: "to_entity", label: "To" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "txn_number", label: "Number", autoNumber: "IC", createOnly: true },
      { key: "from_entity", label: "From entity", required: true },
      { key: "to_entity", label: "To entity", required: true },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "currency", label: "Currency" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["draft", "posted", "eliminated", "void"] },
    ],
    defaults: { status: "draft", currency: "UGX" },
  }),

  eliminations: cfg({
    title: "Elimination Entries",
    description: "Consolidation eliminations",
    table: "fin_elimination_entries",
    statusField: "status",
    statusOptions: ["draft", "posted"],
    columns: [
      { key: "period_year", label: "Year" },
      { key: "description", label: "Description" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "period_year", label: "Year", type: "number", required: true },
      { key: "period_month", label: "Month", type: "number" },
      { key: "description", label: "Description", required: true },
      { key: "debit_account", label: "Debit account" },
      { key: "credit_account", label: "Credit account" },
      { key: "amount", label: "Amount", type: "number" },
      { key: "currency", label: "Currency" },
      { key: "status", label: "Status", type: "select", options: ["draft", "posted"] },
    ],
    defaults: { status: "draft", currency: "UGX" },
  }),

  notifications: cfg({
    title: "Finance Notifications",
    description: "Finance alerts and reminders",
    table: "fin_notifications",
    columns: [
      { key: "title", label: "Title" },
      { key: "severity", label: "Severity" },
      { key: "category", label: "Category" },
      { key: "is_read", label: "Read" },
      { key: "created_at", label: "Created" },
    ],
    fields: [
      { key: "title", label: "Title", required: true },
      { key: "body", label: "Body", type: "textarea" },
      { key: "severity", label: "Severity", type: "select", options: ["info", "warning", "critical"] },
      { key: "category", label: "Category" },
    ],
    defaults: { severity: "info", category: "general" },
  }),

  settings: cfg({
    title: "Finance Settings",
    description: "Company finance configuration",
    table: "fin_settings",
    columns: [
      { key: "setting_key", label: "Key" },
      { key: "setting_value", label: "Value" },
      { key: "description", label: "Description" },
    ],
    fields: [
      { key: "setting_key", label: "Key", required: true, createOnly: true },
      { key: "setting_value", label: "Value (JSON)", required: true },
      { key: "description", label: "Description" },
    ],
  }),

  audit: cfg({
    title: "Finance Audit Logs",
    description: "Immutable finance actions",
    table: "fin_audit_log",
    columns: [
      { key: "action", label: "Action" },
      { key: "entity_type", label: "Entity" },
      { key: "details", label: "Details" },
      { key: "created_at", label: "When" },
    ],
    fields: [
      { key: "action", label: "Action", required: true },
      { key: "entity_type", label: "Entity type" },
      { key: "details", label: "Details", type: "textarea" },
    ],
  }),

  "mobile-money": cfg({
    title: "Mobile Money",
    description: "MTN MoMo / Airtel Money transactions",
    table: "fin_mobile_money_txns",
    columns: [
      { key: "provider", label: "Provider" },
      { key: "direction", label: "Dir" },
      { key: "phone", label: "Phone" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "provider", label: "Provider", type: "select", options: ["mtn_momo", "airtel_money", "other"], required: true },
      { key: "direction", label: "Direction", type: "select", options: ["in", "out"] },
      { key: "phone", label: "Phone" },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "currency", label: "Currency" },
      { key: "reference", label: "Reference" },
      { key: "status", label: "Status", type: "select", options: ["pending", "completed", "failed"] },
    ],
    defaults: { direction: "in", currency: "UGX", status: "completed", provider: "mtn_momo" },
  }),

  "inventory-valuation": cfg({"title":"Inventory Valuation","description":"FIFO · weighted average · standard · specific","table":"fin_inventory_valuation","numberField":"valuation_code","numberPrefix":"IV","statusField":"status","statusOptions":["draft","posted","reversed"],"columns":[{"key":"valuation_code","label":"Code"},{"key":"method","label":"Method"},{"key":"item_name","label":"Item"},{"key":"total_value","label":"Value"},{"key":"status","label":"Status"}],"fields":[{"key":"valuation_code","label":"Code","autoNumber":"IV","createOnly":true},{"key":"method","label":"Method","type":"select","options":["fifo","weighted_average","standard","specific"]},{"key":"period_label","label":"Period"},{"key":"item_code","label":"Item code"},{"key":"item_name","label":"Item name","required":true},{"key":"quantity","label":"Qty","type":"number"},{"key":"unit_cost","label":"Unit cost","type":"number"},{"key":"total_value","label":"Total value","type":"number"},{"key":"currency","label":"Currency"},{"key":"status","label":"Status","type":"select","options":["draft","posted","reversed"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"draft","method":"weighted_average","currency":"UGX"}}),
  "stock-revaluation": cfg({"title":"Stock Revaluation","description":"Inventory cost revaluations","table":"fin_stock_revaluations","numberField":"reval_number","numberPrefix":"SRV","statusField":"status","statusOptions":["draft","posted","void"],"columns":[{"key":"reval_number","label":"Number"},{"key":"item_name","label":"Item"},{"key":"reval_amount","label":"Amount"},{"key":"status","label":"Status"}],"fields":[{"key":"reval_number","label":"Number","autoNumber":"SRV","createOnly":true},{"key":"item_name","label":"Item","required":true},{"key":"old_unit_cost","label":"Old unit cost","type":"number"},{"key":"new_unit_cost","label":"New unit cost","type":"number"},{"key":"quantity","label":"Qty","type":"number"},{"key":"reval_amount","label":"Reval amount","type":"number"},{"key":"reval_date","label":"Date","type":"date"},{"key":"status","label":"Status","type":"select","options":["draft","posted","void"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"draft"}}),
  "inventory-adjustments": cfg({"title":"Inventory Adjustments","description":"Count, write-off, damage adjustments","table":"fin_inventory_adjustments","numberField":"adjustment_number","numberPrefix":"IADJ","statusField":"status","statusOptions":["draft","posted","void"],"columns":[{"key":"adjustment_number","label":"Number"},{"key":"item_name","label":"Item"},{"key":"adjustment_type","label":"Type"},{"key":"amount","label":"Amount"},{"key":"status","label":"Status"}],"fields":[{"key":"adjustment_number","label":"Number","autoNumber":"IADJ","createOnly":true},{"key":"item_name","label":"Item","required":true},{"key":"adjustment_type","label":"Type","type":"select","options":["count","write_off","write_on","damage","theft"]},{"key":"quantity","label":"Qty","type":"number"},{"key":"unit_cost","label":"Unit cost","type":"number"},{"key":"amount","label":"Amount","type":"number"},{"key":"adjustment_date","label":"Date","type":"date"},{"key":"status","label":"Status","type":"select","options":["draft","posted","void"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"draft","adjustment_type":"count"}}),
  "production-profit": cfg({"title":"Production Profitability","description":"Machine · labor · material · packaging · OH · margin","table":"fin_production_profitability","numberField":"analysis_code","numberPrefix":"PPF","statusField":"status","statusOptions":["open","closed"],"columns":[{"key":"analysis_code","label":"Code"},{"key":"product_name","label":"Product"},{"key":"revenue","label":"Revenue"},{"key":"total_cost","label":"Cost"},{"key":"margin_pct","label":"Margin %"}],"fields":[{"key":"analysis_code","label":"Code","autoNumber":"PPF","createOnly":true},{"key":"product_name","label":"Product","required":true},{"key":"production_order_ref","label":"Prod order"},{"key":"revenue","label":"Revenue","type":"number"},{"key":"material_cost","label":"Material","type":"number"},{"key":"labor_cost","label":"Labor","type":"number"},{"key":"machine_cost","label":"Machine","type":"number"},{"key":"packaging_cost","label":"Packaging","type":"number"},{"key":"factory_overhead","label":"Factory OH","type":"number"},{"key":"scrap_cost","label":"Scrap","type":"number"},{"key":"total_cost","label":"Total cost","type":"number"},{"key":"gross_profit","label":"Gross profit","type":"number"},{"key":"margin_pct","label":"Margin %","type":"number"},{"key":"cost_per_ream","label":"Cost/ream","type":"number"},{"key":"cost_per_box","label":"Cost/box","type":"number"},{"key":"cost_per_ton","label":"Cost/ton","type":"number"},{"key":"period_label","label":"Period"},{"key":"status","label":"Status","type":"select","options":["open","closed"]}],"defaults":{"status":"open"}}),
  "asset-capitalization": cfg({"title":"Asset Capitalization","description":"CIP and acquisition capitalization","table":"fin_asset_capitalizations","numberField":"cap_number","numberPrefix":"CAP","statusField":"status","statusOptions":["draft","posted","void"],"columns":[{"key":"cap_number","label":"Number"},{"key":"asset_name","label":"Asset"},{"key":"amount","label":"Amount"},{"key":"status","label":"Status"}],"fields":[{"key":"cap_number","label":"Number","autoNumber":"CAP","createOnly":true},{"key":"asset_code","label":"Asset code"},{"key":"asset_name","label":"Asset name","required":true},{"key":"amount","label":"Amount","type":"number"},{"key":"cap_date","label":"Date","type":"date"},{"key":"source_ref","label":"Source ref"},{"key":"status","label":"Status","type":"select","options":["draft","posted","void"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"draft"}}),
  "asset-revaluation": cfg({"title":"Asset Revaluation","description":"Fair value revaluations","table":"fin_asset_revaluations","numberField":"reval_number","numberPrefix":"ARV","statusField":"status","statusOptions":["draft","posted"],"columns":[{"key":"reval_number","label":"Number"},{"key":"asset_code","label":"Asset"},{"key":"new_value","label":"New value"},{"key":"status","label":"Status"}],"fields":[{"key":"reval_number","label":"Number","autoNumber":"ARV","createOnly":true},{"key":"asset_code","label":"Asset code"},{"key":"old_value","label":"Old value","type":"number"},{"key":"new_value","label":"New value","type":"number"},{"key":"reval_date","label":"Date","type":"date"},{"key":"status","label":"Status","type":"select","options":["draft","posted"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"draft"}}),
  "asset-transfers": cfg({"title":"Asset Transfers","description":"Location and cost center transfers","table":"fin_asset_transfers","numberField":"transfer_number","numberPrefix":"ATR","statusField":"status","statusOptions":["completed","cancelled"],"columns":[{"key":"transfer_number","label":"Number"},{"key":"asset_code","label":"Asset"},{"key":"from_location","label":"From"},{"key":"to_location","label":"To"},{"key":"status","label":"Status"}],"fields":[{"key":"transfer_number","label":"Number","autoNumber":"ATR","createOnly":true},{"key":"asset_code","label":"Asset code"},{"key":"from_location","label":"From location"},{"key":"to_location","label":"To location"},{"key":"from_cost_center","label":"From CC"},{"key":"to_cost_center","label":"To CC"},{"key":"transfer_date","label":"Date","type":"date"},{"key":"status","label":"Status","type":"select","options":["completed","cancelled"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"completed"}}),
  "asset-disposals": cfg({"title":"Asset Disposals","description":"Sale, scrap, write-off","table":"fin_asset_disposals","numberField":"disposal_number","numberPrefix":"ADS","statusField":"status","statusOptions":["draft","posted","void"],"columns":[{"key":"disposal_number","label":"Number"},{"key":"asset_code","label":"Asset"},{"key":"proceeds","label":"Proceeds"},{"key":"gain_loss","label":"Gain/Loss"},{"key":"status","label":"Status"}],"fields":[{"key":"disposal_number","label":"Number","autoNumber":"ADS","createOnly":true},{"key":"asset_code","label":"Asset code"},{"key":"disposal_date","label":"Date","type":"date"},{"key":"disposal_type","label":"Type","type":"select","options":["sale","scrap","donation","write_off"]},{"key":"proceeds","label":"Proceeds","type":"number"},{"key":"book_value","label":"Book value","type":"number"},{"key":"gain_loss","label":"Gain/loss","type":"number"},{"key":"status","label":"Status","type":"select","options":["draft","posted","void"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"draft","disposal_type":"sale"}}),
  "asset-impairment": cfg({"title":"Asset Impairment","description":"IAS 36 impairment losses","table":"fin_asset_impairments","numberField":"impairment_number","numberPrefix":"IMP","statusField":"status","statusOptions":["draft","posted"],"columns":[{"key":"impairment_number","label":"Number"},{"key":"asset_code","label":"Asset"},{"key":"impairment_loss","label":"Loss"},{"key":"status","label":"Status"}],"fields":[{"key":"impairment_number","label":"Number","autoNumber":"IMP","createOnly":true},{"key":"asset_code","label":"Asset code"},{"key":"impairment_date","label":"Date","type":"date"},{"key":"carrying_amount","label":"Carrying amount","type":"number"},{"key":"recoverable_amount","label":"Recoverable","type":"number"},{"key":"impairment_loss","label":"Impairment loss","type":"number"},{"key":"status","label":"Status","type":"select","options":["draft","posted"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"draft"}}),
  "cip": cfg({"title":"Construction in Progress","description":"CIP projects and capitalization","table":"fin_cip","numberField":"cip_number","numberPrefix":"CIP","statusField":"status","statusOptions":["open","capitalized","cancelled"],"columns":[{"key":"cip_number","label":"Number"},{"key":"project_name","label":"Project"},{"key":"cumulative_cost","label":"Cost"},{"key":"status","label":"Status"}],"fields":[{"key":"cip_number","label":"Number","autoNumber":"CIP","createOnly":true},{"key":"project_name","label":"Project","required":true},{"key":"cumulative_cost","label":"Cumulative cost","type":"number"},{"key":"expected_completion","label":"Expected completion","type":"date"},{"key":"status","label":"Status","type":"select","options":["open","capitalized","cancelled"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"open"}}),
  "leases": cfg({"title":"Lease Accounting","description":"IFRS 16 / operating / finance leases","table":"fin_leases","numberField":"lease_number","numberPrefix":"LSE","statusField":"status","statusOptions":["active","ended","terminated"],"columns":[{"key":"lease_number","label":"Number"},{"key":"lessor_name","label":"Lessor"},{"key":"lease_type","label":"Type"},{"key":"monthly_payment","label":"Payment"},{"key":"status","label":"Status"}],"fields":[{"key":"lease_number","label":"Number","autoNumber":"LSE","createOnly":true},{"key":"lessor_name","label":"Lessor"},{"key":"asset_description","label":"Asset"},{"key":"lease_type","label":"Type","type":"select","options":["operating","finance","ifrs16"]},{"key":"commencement_date","label":"Start","type":"date"},{"key":"end_date","label":"End","type":"date"},{"key":"monthly_payment","label":"Monthly payment","type":"number"},{"key":"liability_balance","label":"Liability","type":"number"},{"key":"rou_asset_value","label":"ROU asset","type":"number"},{"key":"status","label":"Status","type":"select","options":["active","ended","terminated"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"active","lease_type":"ifrs16"}}),
  "payroll-journals": cfg({"title":"Payroll Accounting Journals","description":"Salary, PAYE, NSSF, pension, leave liability","table":"fin_payroll_journals","numberField":"journal_number","numberPrefix":"PAYJ","statusField":"status","statusOptions":["draft","posted","reversed"],"columns":[{"key":"journal_number","label":"Number"},{"key":"period_label","label":"Period"},{"key":"gross_pay","label":"Gross"},{"key":"net_pay","label":"Net"},{"key":"status","label":"Status"}],"fields":[{"key":"journal_number","label":"Number","autoNumber":"PAYJ","createOnly":true},{"key":"period_label","label":"Period","required":true},{"key":"gross_pay","label":"Gross pay","type":"number"},{"key":"paye","label":"PAYE","type":"number"},{"key":"nssf_employee","label":"NSSF employee","type":"number"},{"key":"nssf_employer","label":"NSSF employer","type":"number"},{"key":"pension","label":"Pension","type":"number"},{"key":"loans_deducted","label":"Loans","type":"number"},{"key":"overtime","label":"Overtime","type":"number"},{"key":"benefits","label":"Benefits","type":"number"},{"key":"leave_liability","label":"Leave liability","type":"number"},{"key":"net_pay","label":"Net pay","type":"number"},{"key":"status","label":"Status","type":"select","options":["draft","posted","reversed"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"draft"}}),
  "tax-calendar": cfg({"title":"Tax Calendar","description":"Filing due dates and status","table":"fin_tax_calendar","numberField":"event_code","numberPrefix":"TAXE","statusField":"status","statusOptions":["upcoming","filed","overdue","paid"],"columns":[{"key":"event_code","label":"Code"},{"key":"tax_type","label":"Type"},{"key":"title","label":"Title"},{"key":"due_date","label":"Due"},{"key":"status","label":"Status"}],"fields":[{"key":"event_code","label":"Code","autoNumber":"TAXE","createOnly":true},{"key":"tax_type","label":"Tax type","type":"select","options":["vat","wht","paye","corporate","excise","import","nssf"]},{"key":"title","label":"Title","required":true},{"key":"due_date","label":"Due date","type":"date","required":true},{"key":"status","label":"Status","type":"select","options":["upcoming","filed","overdue","paid"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"upcoming","tax_type":"vat"}}),
  "excise-duty": cfg({"title":"Excise Duty","description":"Excise assessments","table":"fin_excise_duty","numberField":"duty_number","numberPrefix":"EXC","statusField":"status","statusOptions":["draft","posted","paid"],"columns":[{"key":"duty_number","label":"Number"},{"key":"product_name","label":"Product"},{"key":"duty_amount","label":"Duty"},{"key":"status","label":"Status"}],"fields":[{"key":"duty_number","label":"Number","autoNumber":"EXC","createOnly":true},{"key":"product_name","label":"Product"},{"key":"taxable_amount","label":"Taxable","type":"number"},{"key":"rate_pct","label":"Rate %","type":"number"},{"key":"duty_amount","label":"Duty amount","type":"number"},{"key":"period_label","label":"Period"},{"key":"status","label":"Status","type":"select","options":["draft","posted","paid"]}],"defaults":{"status":"draft"}}),
  "import-duty": cfg({"title":"Import Duty","description":"Customs entries and import VAT","table":"fin_import_duty","numberField":"entry_number","numberPrefix":"IMP","statusField":"status","statusOptions":["posted","paid","void"],"columns":[{"key":"entry_number","label":"Entry"},{"key":"supplier_name","label":"Supplier"},{"key":"duty_amount","label":"Duty"},{"key":"vat_amount","label":"VAT"},{"key":"status","label":"Status"}],"fields":[{"key":"entry_number","label":"Entry number","autoNumber":"IMP","createOnly":true},{"key":"supplier_name","label":"Supplier"},{"key":"hs_code","label":"HS code"},{"key":"cif_value","label":"CIF value","type":"number"},{"key":"duty_amount","label":"Duty","type":"number"},{"key":"vat_amount","label":"VAT","type":"number"},{"key":"entry_date","label":"Date","type":"date"},{"key":"status","label":"Status","type":"select","options":["posted","paid","void"]}],"defaults":{"status":"posted"}}),
  "corporate-tax": cfg({"title":"Corporate Tax","description":"Annual corporate income tax","table":"fin_corporate_tax","numberField":"assessment_code","numberPrefix":"CIT","statusField":"status","statusOptions":["draft","filed","paid"],"columns":[{"key":"assessment_code","label":"Code"},{"key":"tax_year","label":"Year"},{"key":"taxable_profit","label":"Profit"},{"key":"tax_amount","label":"Tax"},{"key":"status","label":"Status"}],"fields":[{"key":"assessment_code","label":"Code","autoNumber":"CIT","createOnly":true},{"key":"tax_year","label":"Tax year","type":"number","required":true},{"key":"taxable_profit","label":"Taxable profit","type":"number"},{"key":"tax_rate_pct","label":"Rate %","type":"number"},{"key":"tax_amount","label":"Tax amount","type":"number"},{"key":"due_date","label":"Due","type":"date"},{"key":"status","label":"Status","type":"select","options":["draft","filed","paid"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"draft","tax_rate_pct":30}}),
  "deferred-revenue": cfg({"title":"Deferred Revenue","description":"Contract liabilities and recognition","table":"fin_deferred_revenue","numberField":"deferral_code","numberPrefix":"DR","statusField":"status","statusOptions":["open","partial","closed"],"columns":[{"key":"deferral_code","label":"Code"},{"key":"customer_name","label":"Customer"},{"key":"total_amount","label":"Total"},{"key":"remaining_amount","label":"Remaining"},{"key":"status","label":"Status"}],"fields":[{"key":"deferral_code","label":"Code","autoNumber":"DR","createOnly":true},{"key":"customer_name","label":"Customer"},{"key":"description","label":"Description","type":"textarea"},{"key":"total_amount","label":"Total","type":"number"},{"key":"recognized_amount","label":"Recognized","type":"number"},{"key":"remaining_amount","label":"Remaining","type":"number"},{"key":"start_date","label":"Start","type":"date"},{"key":"end_date","label":"End","type":"date"},{"key":"status","label":"Status","type":"select","options":["open","partial","closed"]}],"defaults":{"status":"open"}}),
  "subscription-revenue": cfg({"title":"Subscription Revenue","description":"MRR and recurring subscriptions","table":"fin_subscription_revenue","numberField":"subscription_code","numberPrefix":"SUB","statusField":"status","statusOptions":["active","paused","cancelled"],"columns":[{"key":"subscription_code","label":"Code"},{"key":"customer_name","label":"Customer"},{"key":"mrr","label":"MRR"},{"key":"billing_cycle","label":"Cycle"},{"key":"status","label":"Status"}],"fields":[{"key":"subscription_code","label":"Code","autoNumber":"SUB","createOnly":true},{"key":"customer_name","label":"Customer","required":true},{"key":"product_name","label":"Product"},{"key":"mrr","label":"MRR","type":"number"},{"key":"billing_cycle","label":"Cycle","type":"select","options":["monthly","quarterly","yearly"]},{"key":"start_date","label":"Start","type":"date"},{"key":"status","label":"Status","type":"select","options":["active","paused","cancelled"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"active","billing_cycle":"monthly"}}),
  "revenue-recognition": cfg({"title":"Revenue Recognition","description":"IFRS 15 recognition events","table":"fin_revenue_recognition","numberField":"recognition_code","numberPrefix":"RR","statusField":"status","statusOptions":["recognized","reversed","draft"],"columns":[{"key":"recognition_code","label":"Code"},{"key":"source_type","label":"Source"},{"key":"amount","label":"Amount"},{"key":"recognition_date","label":"Date"},{"key":"status","label":"Status"}],"fields":[{"key":"recognition_code","label":"Code","autoNumber":"RR","createOnly":true},{"key":"source_type","label":"Source","type":"select","options":["invoice","subscription","milestone","contract","export","government"]},{"key":"source_ref","label":"Source ref"},{"key":"amount","label":"Amount","type":"number"},{"key":"recognition_date","label":"Date","type":"date"},{"key":"method","label":"Method","type":"select","options":["point_in_time","over_time","percent_complete"]},{"key":"status","label":"Status","type":"select","options":["recognized","reversed","draft"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"recognized","method":"point_in_time","source_type":"invoice"}}),
  "gov-contracts": cfg({"title":"Government Contracts","description":"Public sector contract revenue","table":"fin_government_contracts","numberField":"contract_number","numberPrefix":"GOV","statusField":"status","statusOptions":["active","completed","cancelled"],"columns":[{"key":"contract_number","label":"Number"},{"key":"agency_name","label":"Agency"},{"key":"contract_value","label":"Value"},{"key":"billed_to_date","label":"Billed"},{"key":"status","label":"Status"}],"fields":[{"key":"contract_number","label":"Number","autoNumber":"GOV","createOnly":true},{"key":"agency_name","label":"Agency","required":true},{"key":"contract_value","label":"Value","type":"number"},{"key":"billed_to_date","label":"Billed to date","type":"number"},{"key":"start_date","label":"Start","type":"date"},{"key":"end_date","label":"End","type":"date"},{"key":"status","label":"Status","type":"select","options":["active","completed","cancelled"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"active"}}),
  "export-revenue": cfg({"title":"Export Revenue","description":"Export sales register","table":"fin_export_revenue","numberField":"export_number","numberPrefix":"EXP","statusField":"status","statusOptions":["invoiced","shipped","collected"],"columns":[{"key":"export_number","label":"Number"},{"key":"customer_name","label":"Customer"},{"key":"country","label":"Country"},{"key":"amount","label":"Amount"},{"key":"status","label":"Status"}],"fields":[{"key":"export_number","label":"Number","autoNumber":"EXP","createOnly":true},{"key":"customer_name","label":"Customer"},{"key":"country","label":"Country"},{"key":"amount","label":"Amount","type":"number"},{"key":"currency","label":"Currency"},{"key":"export_date","label":"Date","type":"date"},{"key":"status","label":"Status","type":"select","options":["invoiced","shipped","collected"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"invoiced","currency":"USD"}}),
  "project-costs": cfg({"title":"Project Costing","description":"Project cost accumulation","table":"fin_project_costs","numberField":"cost_number","numberPrefix":"PCST","statusField":"status","statusOptions":["posted","reversed"],"columns":[{"key":"cost_number","label":"Number"},{"key":"project_code","label":"Project"},{"key":"cost_type","label":"Type"},{"key":"amount","label":"Amount"},{"key":"status","label":"Status"}],"fields":[{"key":"cost_number","label":"Number","autoNumber":"PCST","createOnly":true},{"key":"project_code","label":"Project code","required":true},{"key":"cost_type","label":"Type","type":"select","options":["labor","materials","expenses","overhead","subcontractor"]},{"key":"amount","label":"Amount","type":"number"},{"key":"cost_date","label":"Date","type":"date"},{"key":"description","label":"Description","type":"textarea"},{"key":"status","label":"Status","type":"select","options":["posted","reversed"]}],"defaults":{"status":"posted","cost_type":"labor"}}),
  "project-billing": cfg({"title":"Project Billing","description":"Time, expense, milestone billing","table":"fin_project_billing","numberField":"billing_number","numberPrefix":"PBIL","statusField":"status","statusOptions":["draft","invoiced","paid"],"columns":[{"key":"billing_number","label":"Number"},{"key":"project_code","label":"Project"},{"key":"billing_type","label":"Type"},{"key":"amount","label":"Amount"},{"key":"status","label":"Status"}],"fields":[{"key":"billing_number","label":"Number","autoNumber":"PBIL","createOnly":true},{"key":"project_code","label":"Project code","required":true},{"key":"billing_type","label":"Type","type":"select","options":["time","expense","milestone","fixed"]},{"key":"amount","label":"Amount","type":"number"},{"key":"billing_date","label":"Date","type":"date"},{"key":"customer_name","label":"Customer"},{"key":"status","label":"Status","type":"select","options":["draft","invoiced","paid"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"draft","billing_type":"milestone"}}),
  "project-profit": cfg({"title":"Project Profitability","description":"Revenue vs cost by project","table":"fin_project_profitability","numberField":"analysis_code","numberPrefix":"PPR","statusField":"status","statusOptions":["open","closed"],"columns":[{"key":"analysis_code","label":"Code"},{"key":"project_code","label":"Project"},{"key":"revenue","label":"Revenue"},{"key":"cost","label":"Cost"},{"key":"margin_pct","label":"Margin %"}],"fields":[{"key":"analysis_code","label":"Code","autoNumber":"PPR","createOnly":true},{"key":"project_code","label":"Project code","required":true},{"key":"project_name","label":"Project name"},{"key":"revenue","label":"Revenue","type":"number"},{"key":"cost","label":"Cost","type":"number"},{"key":"profit","label":"Profit","type":"number"},{"key":"margin_pct","label":"Margin %","type":"number"},{"key":"period_label","label":"Period"},{"key":"status","label":"Status","type":"select","options":["open","closed"]}],"defaults":{"status":"open"}}),
  "expense-claims": cfg({"title":"Expense Claims","description":"Travel, fuel, meals, mileage, entertainment","table":"fin_expense_claims","numberField":"claim_number","numberPrefix":"ECL","statusField":"status","statusOptions":["draft","submitted","approved","rejected","paid","posted"],"columns":[{"key":"claim_number","label":"Number"},{"key":"claimant_name","label":"Claimant"},{"key":"category","label":"Category"},{"key":"amount","label":"Amount"},{"key":"status","label":"Status"}],"fields":[{"key":"claim_number","label":"Number","autoNumber":"ECL","createOnly":true},{"key":"claimant_name","label":"Claimant","required":true},{"key":"claim_date","label":"Date","type":"date"},{"key":"category","label":"Category","type":"select","options":["travel","fuel","accommodation","meals","mileage","entertainment","other"]},{"key":"amount","label":"Amount","type":"number","required":true},{"key":"currency","label":"Currency"},{"key":"description","label":"Description","type":"textarea"},{"key":"receipt_url","label":"Receipt URL"},{"key":"project_code","label":"Project"},{"key":"cost_center","label":"Cost center"},{"key":"status","label":"Status","type":"select","options":["draft","submitted","approved","rejected","paid","posted"]}],"defaults":{"status":"submitted","category":"travel","currency":"UGX"}}),
  "close-checklist": cfg({"title":"Close Checklist","description":"Month-end and year-end tasks","table":"fin_close_checklists","numberField":"checklist_code","numberPrefix":"CL","statusField":"status","statusOptions":["open","done","skipped"],"columns":[{"key":"checklist_code","label":"Code"},{"key":"close_type","label":"Type"},{"key":"period_label","label":"Period"},{"key":"task_name","label":"Task"},{"key":"status","label":"Status"}],"fields":[{"key":"checklist_code","label":"Code","autoNumber":"CL","createOnly":true},{"key":"close_type","label":"Close type","type":"select","options":["month_end","year_end","quarter"]},{"key":"period_label","label":"Period","required":true},{"key":"task_name","label":"Task","required":true},{"key":"owner_name","label":"Owner"},{"key":"due_date","label":"Due","type":"date"},{"key":"status","label":"Status","type":"select","options":["open","done","skipped"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"open","close_type":"month_end"}}),
  "close-adjustments": cfg({"title":"Close Adjustments","description":"Period-end adjusting entries","table":"fin_close_adjustments","numberField":"adjustment_number","numberPrefix":"CADJ","statusField":"status","statusOptions":["draft","posted"],"columns":[{"key":"adjustment_number","label":"Number"},{"key":"period_label","label":"Period"},{"key":"amount","label":"Amount"},{"key":"status","label":"Status"}],"fields":[{"key":"adjustment_number","label":"Number","autoNumber":"CADJ","createOnly":true},{"key":"period_label","label":"Period"},{"key":"description","label":"Description","required":true,"type":"textarea"},{"key":"amount","label":"Amount","type":"number"},{"key":"status","label":"Status","type":"select","options":["draft","posted"]}],"defaults":{"status":"draft"}}),
  "reconciliations": cfg({"title":"Financial Reconciliations","description":"GL, bank, AR, AP, inventory recon","table":"fin_reconciliations","numberField":"recon_number","numberPrefix":"FREC","statusField":"status","statusOptions":["in_progress","matched","difference"],"columns":[{"key":"recon_number","label":"Number"},{"key":"recon_type","label":"Type"},{"key":"difference","label":"Diff"},{"key":"status","label":"Status"}],"fields":[{"key":"recon_number","label":"Number","autoNumber":"FREC","createOnly":true},{"key":"recon_type","label":"Type","type":"select","options":["gl","bank","ar","ap","intercompany","inventory"]},{"key":"period_label","label":"Period"},{"key":"balance_system","label":"System balance","type":"number"},{"key":"balance_external","label":"External balance","type":"number"},{"key":"difference","label":"Difference","type":"number"},{"key":"status","label":"Status","type":"select","options":["in_progress","matched","difference"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"in_progress","recon_type":"gl"}}),
  "currency-translation": cfg({"title":"Currency Translation","description":"Group FX translation","table":"fin_currency_translation","numberField":"translation_code","numberPrefix":"FX","statusField":"status","statusOptions":["posted","draft"],"columns":[{"key":"translation_code","label":"Code"},{"key":"entity_name","label":"Entity"},{"key":"rate","label":"Rate"},{"key":"translation_gain_loss","label":"Gain/Loss"}],"fields":[{"key":"translation_code","label":"Code","autoNumber":"FX","createOnly":true},{"key":"entity_name","label":"Entity"},{"key":"from_currency","label":"From"},{"key":"to_currency","label":"To"},{"key":"rate","label":"Rate","type":"number"},{"key":"period_label","label":"Period"},{"key":"translation_gain_loss","label":"Gain/loss","type":"number"},{"key":"status","label":"Status","type":"select","options":["posted","draft"]}],"defaults":{"status":"posted","from_currency":"USD","to_currency":"UGX","rate":1}}),
  "group-consolidation": cfg({"title":"Group Consolidation","description":"Group financials and eliminations total","table":"fin_group_consolidation","numberField":"consolidation_code","numberPrefix":"GC","statusField":"status","statusOptions":["draft","final"],"columns":[{"key":"consolidation_code","label":"Code"},{"key":"period_label","label":"Period"},{"key":"group_revenue","label":"Revenue"},{"key":"group_net_profit","label":"Net profit"},{"key":"status","label":"Status"}],"fields":[{"key":"consolidation_code","label":"Code","autoNumber":"GC","createOnly":true},{"key":"period_label","label":"Period","required":true},{"key":"group_revenue","label":"Group revenue","type":"number"},{"key":"group_expenses","label":"Group expenses","type":"number"},{"key":"group_net_profit","label":"Net profit","type":"number"},{"key":"eliminations_total","label":"Eliminations","type":"number"},{"key":"status","label":"Status","type":"select","options":["draft","final"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"draft"}}),
  "internal-controls": cfg({"title":"Internal Controls","description":"Preventive and detective controls","table":"fin_internal_controls","numberField":"control_code","numberPrefix":"IC","statusField":"status","statusOptions":["active","inactive","remediation"],"columns":[{"key":"control_code","label":"Code"},{"key":"title","label":"Title"},{"key":"control_type","label":"Type"},{"key":"process_area","label":"Area"},{"key":"status","label":"Status"}],"fields":[{"key":"control_code","label":"Code","autoNumber":"IC","createOnly":true},{"key":"title","label":"Title","required":true},{"key":"control_type","label":"Type","type":"select","options":["preventive","detective","corrective"]},{"key":"process_area","label":"Process area"},{"key":"owner_name","label":"Owner"},{"key":"last_tested","label":"Last tested","type":"date"},{"key":"status","label":"Status","type":"select","options":["active","inactive","remediation"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"active","control_type":"preventive"}}),
  "sod-rules": cfg({"title":"Segregation of Duties","description":"SoD conflict rules","table":"fin_sod_rules","numberField":"rule_code","numberPrefix":"SOD","statusField":"status","statusOptions":["active","inactive"],"columns":[{"key":"rule_code","label":"Code"},{"key":"title","label":"Title"},{"key":"conflict_a","label":"Conflict A"},{"key":"conflict_b","label":"Conflict B"},{"key":"severity","label":"Severity"}],"fields":[{"key":"rule_code","label":"Code","autoNumber":"SOD","createOnly":true},{"key":"title","label":"Title","required":true},{"key":"conflict_a","label":"Conflict A","required":true},{"key":"conflict_b","label":"Conflict B","required":true},{"key":"severity","label":"Severity","type":"select","options":["low","medium","high","critical"]},{"key":"status","label":"Status","type":"select","options":["active","inactive"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"active","severity":"high"}}),
  "policies": cfg({"title":"Policy Management","description":"Finance and accounting policies","table":"fin_policies","numberField":"policy_code","numberPrefix":"POL","statusField":"status","statusOptions":["active","draft","archived"],"columns":[{"key":"policy_code","label":"Code"},{"key":"title","label":"Title"},{"key":"category","label":"Category"},{"key":"version_label","label":"Ver"},{"key":"status","label":"Status"}],"fields":[{"key":"policy_code","label":"Code","autoNumber":"POL","createOnly":true},{"key":"title","label":"Title","required":true},{"key":"category","label":"Category"},{"key":"version_label","label":"Version"},{"key":"effective_date","label":"Effective","type":"date"},{"key":"file_url","label":"File URL"},{"key":"status","label":"Status","type":"select","options":["active","draft","archived"]},{"key":"notes","label":"Notes","type":"textarea"}],"defaults":{"status":"active","category":"accounting","version_label":"1.0"}}),
  "risk-register": cfg({"title":"Financial Risk Register","description":"Finance risk management","table":"fin_risk_register","numberField":"risk_code","numberPrefix":"FRK","statusField":"status","statusOptions":["open","mitigating","closed"],"columns":[{"key":"risk_code","label":"Code"},{"key":"title","label":"Title"},{"key":"probability","label":"Prob"},{"key":"impact","label":"Impact"},{"key":"status","label":"Status"}],"fields":[{"key":"risk_code","label":"Code","autoNumber":"FRK","createOnly":true},{"key":"title","label":"Title","required":true},{"key":"category","label":"Category"},{"key":"probability","label":"Probability","type":"select","options":["low","medium","high"]},{"key":"impact","label":"Impact","type":"select","options":["low","medium","high"]},{"key":"mitigation","label":"Mitigation","type":"textarea"},{"key":"owner_name","label":"Owner"},{"key":"status","label":"Status","type":"select","options":["open","mitigating","closed"]}],"defaults":{"status":"open","probability":"medium","impact":"medium","category":"financial"}}),
  "posting-rules": cfg({"title":"Posting Rules","description":"Event-driven accounting engine rules","table":"fin_posting_rules","numberField":"rule_code","numberPrefix":"PR","columns":[{"key":"rule_code","label":"Code"},{"key":"name","label":"Name"},{"key":"event_type","label":"Event"},{"key":"debit_account_code","label":"Debit"},{"key":"credit_account_code","label":"Credit"}],"fields":[{"key":"rule_code","label":"Code","required":true,"autoNumber":"PR","createOnly":true},{"key":"name","label":"Name","required":true},{"key":"event_type","label":"Event type","required":true},{"key":"debit_account_code","label":"Debit account"},{"key":"credit_account_code","label":"Credit account"},{"key":"tax_account_code","label":"Tax account"},{"key":"ledger_book","label":"Ledger","type":"select","options":["primary","ifrs","tax","management"]},{"key":"accounting_basis","label":"Basis","type":"select","options":["accrual","cash"]},{"key":"description","label":"Description","type":"textarea"}],"defaults":{"ledger_book":"primary","accounting_basis":"accrual"}}),
  "auto-journals": cfg({"title":"Auto Journals","description":"System-generated journal trail","table":"fin_auto_journals","numberField":"auto_number","numberPrefix":"AJ","statusField":"status","statusOptions":["draft","posted","reversed","failed"],"columns":[{"key":"auto_number","label":"Number"},{"key":"event_type","label":"Event"},{"key":"source_module","label":"Module"},{"key":"amount","label":"Amount"},{"key":"status","label":"Status"}],"fields":[{"key":"auto_number","label":"Number","autoNumber":"AJ","createOnly":true},{"key":"event_type","label":"Event type","required":true},{"key":"source_module","label":"Source module"},{"key":"source_ref","label":"Source ref"},{"key":"rule_code","label":"Rule code"},{"key":"amount","label":"Amount","type":"number"},{"key":"currency","label":"Currency"},{"key":"status","label":"Status","type":"select","options":["draft","posted","reversed","failed"]}],"defaults":{"status":"posted","currency":"UGX"}}),
};

export const FIN_ENTITY_ALIASES: Record<string, string> = {
  "valuation-methods": "inventory-valuation",
  "month-end-close": "close-checklist",
  "year-end-close": "close-checklist",
  "depreciation": "asset-capitalization",

  "journal-entries": "journal-templates",
  "closing-periods": "period-locks",
  "ar-invoices": "customer-statements",
  "customer-aging": "customer-statements",
  "supplier-aging": "supplier-statements",
  "swift-eft": "electronic-payments",
  debt: "loans",
  "dept-budgets": "budget-templates",
  "project-budgets": "budget-templates",
  "production-budgets": "budget-templates",
  "forecast-revenue": "forecasts",
  "forecast-expense": "forecasts",
  "forecast-cash": "forecasts",
  "forecast-ai": "forecasts",
  "my-finance": "notifications",
  "cost-centres": "profit-centers",
};

/** Resolve a URL slug (or alias) to a FinEntityPage config. */
export function resolveFinEntityConfig(
  slug: string
): FinEntityConfig | null {
  const key = FIN_ENTITY_ALIASES[slug] || slug;
  return FIN_ENTITIES[key] ?? null;
}

/** All distinct DB tables used by finance EntityPages (for registry registration). */
export function listFinEntityTables(): string[] {
  return [
    ...new Set(Object.values(FIN_ENTITIES).map((c) => c.table)),
  ];
}
