/** Complete Enterprise Finance navigation */

export const FINANCE_MENU = [
  { title: "Executive Dashboard", href: "/dashboard/finance", group: "Overview" },
  { title: "Financial Cockpit", href: "/dashboard/finance/cfo", group: "Overview" },
  { title: "My Finance", href: "/dashboard/finance/my-finance", group: "Overview" },
  { title: "Approvals", href: "/dashboard/finance/approvals", group: "Overview" },
  { title: "Notifications", href: "/dashboard/finance/notifications", group: "Overview" },
  { title: "General Ledger", href: "/dashboard/finance/journals", group: "General Ledger" },
  { title: "Journal Entries", href: "/dashboard/finance/journal-entries", group: "General Ledger" },
  { title: "Recurring Journals", href: "/dashboard/finance/recurring-journals", group: "General Ledger" },
  { title: "Journal Templates", href: "/dashboard/finance/journal-templates", group: "General Ledger" },
  { title: "Posting Batches", href: "/dashboard/finance/posting-batches", group: "General Ledger" },
  { title: "Trial Balance", href: "/dashboard/finance/trial-balance", group: "General Ledger" },
  { title: "Chart of Accounts", href: "/dashboard/finance/coa", group: "Structure" },
  { title: "Account Groups", href: "/dashboard/finance/account-groups", group: "Structure" },
  { title: "Financial Dimensions", href: "/dashboard/finance/dimensions", group: "Structure" },
  { title: "Cost Centers", href: "/dashboard/finance/cost-centres", group: "Structure" },
  { title: "Profit Centers", href: "/dashboard/finance/profit-centers", group: "Structure" },
  { title: "Business Units", href: "/dashboard/finance/business-units", group: "Structure" },
  { title: "Fiscal Years", href: "/dashboard/finance/fiscal-years", group: "Periods" },
  { title: "Accounting Periods", href: "/dashboard/finance/periods", group: "Periods" },
  { title: "Closing Periods", href: "/dashboard/finance/closing-periods", group: "Periods" },
  { title: "Period Locks", href: "/dashboard/finance/period-locks", group: "Periods" },
  { title: "Customers Ledger", href: "/dashboard/finance/ar", group: "Accounts Receivable" },
  { title: "Invoices", href: "/dashboard/finance/ar-invoices", group: "Accounts Receivable" },
  { title: "Recurring Invoices", href: "/dashboard/finance/recurring-invoices", group: "Accounts Receivable" },
  { title: "Credit Notes", href: "/dashboard/finance/ar-credit-notes", group: "Accounts Receivable" },
  { title: "Debit Notes", href: "/dashboard/finance/ar-debit-notes", group: "Accounts Receivable" },
  { title: "Receipts", href: "/dashboard/finance/receipts", group: "Accounts Receivable" },
  { title: "Collections", href: "/dashboard/finance/collections", group: "Accounts Receivable" },
  { title: "Payment Plans", href: "/dashboard/finance/payment-plans", group: "Accounts Receivable" },
  { title: "Customer Statements", href: "/dashboard/finance/customer-statements", group: "Accounts Receivable" },
  { title: "Customer Aging", href: "/dashboard/finance/customer-aging", group: "Accounts Receivable" },
  { title: "Suppliers Ledger", href: "/dashboard/finance/ap", group: "Accounts Payable" },
  { title: "Supplier Invoices", href: "/dashboard/finance/ap-invoices", group: "Accounts Payable" },
  { title: "Vendor Statements", href: "/dashboard/finance/supplier-statements", group: "Accounts Payable" },
  { title: "AP Credit Notes", href: "/dashboard/finance/ap-credit-notes", group: "Accounts Payable" },
  { title: "AP Debit Notes", href: "/dashboard/finance/ap-debit-notes", group: "Accounts Payable" },
  { title: "Payment Runs", href: "/dashboard/finance/payment-runs", group: "Accounts Payable" },
  { title: "Supplier Aging", href: "/dashboard/finance/supplier-aging", group: "Accounts Payable" },
  { title: "Supplier Reconciliation", href: "/dashboard/finance/supplier-recon", group: "Accounts Payable" },
  { title: "Cash Management", href: "/dashboard/finance/cash", group: "Treasury" },
  { title: "Banks", href: "/dashboard/finance/banks", group: "Treasury" },
  { title: "Bank Accounts", href: "/dashboard/finance/bank", group: "Treasury" },
  { title: "Bank Statements", href: "/dashboard/finance/bank-statements", group: "Treasury" },
  { title: "Bank Reconciliation", href: "/dashboard/finance/bank-recon", group: "Treasury" },
  { title: "Electronic Banking", href: "/dashboard/finance/electronic-payments", group: "Treasury" },
  { title: "SWIFT / RTGS / EFT", href: "/dashboard/finance/swift-eft", group: "Treasury" },
  { title: "Mobile Money", href: "/dashboard/finance/mobile-money", group: "Treasury" },
  { title: "Petty Cash", href: "/dashboard/finance/petty-cash", group: "Treasury" },
  { title: "Cash Forecasting", href: "/dashboard/finance/cash-forecast", group: "Treasury" },
  { title: "Liquidity Management", href: "/dashboard/finance/liquidity", group: "Treasury" },
  { title: "Investments", href: "/dashboard/finance/investments", group: "Treasury" },
  { title: "Loans", href: "/dashboard/finance/loans", group: "Treasury" },
  { title: "Debt Management", href: "/dashboard/finance/debt", group: "Treasury" },
  { title: "Letters of Credit", href: "/dashboard/finance/letters-of-credit", group: "Treasury" },
  { title: "Guarantees", href: "/dashboard/finance/guarantees", group: "Treasury" },
  { title: "Budget Templates", href: "/dashboard/finance/budget-templates", group: "Budgeting" },
  { title: "Budgets", href: "/dashboard/finance/budgets", group: "Budgeting" },
  { title: "Department Budgets", href: "/dashboard/finance/dept-budgets", group: "Budgeting" },
  { title: "Project Budgets", href: "/dashboard/finance/project-budgets", group: "Budgeting" },
  { title: "Production Budgets", href: "/dashboard/finance/production-budgets", group: "Budgeting" },
  { title: "Budget Revisions", href: "/dashboard/finance/budget-revisions", group: "Budgeting" },
  { title: "Budget Variance", href: "/dashboard/finance/budget-variance", group: "Budgeting" },
  { title: "Revenue Forecast", href: "/dashboard/finance/forecast-revenue", group: "Forecasting" },
  { title: "Expense Forecast", href: "/dashboard/finance/forecast-expense", group: "Forecasting" },
  { title: "Cash Forecast", href: "/dashboard/finance/forecast-cash", group: "Forecasting" },
  { title: "AI Forecasting", href: "/dashboard/finance/forecast-ai", group: "Forecasting" },
  { title: "Forecasts Register", href: "/dashboard/finance/forecasts", group: "Forecasting" },
  { title: "Manufacturing Costing", href: "/dashboard/finance/costing", group: "Cost Accounting" },
  { title: "Standard Costing", href: "/dashboard/finance/standard-costs", group: "Cost Accounting" },
  { title: "Actual / Batch Costing", href: "/dashboard/finance/cost-rolls", group: "Cost Accounting" },
  { title: "Costing Methods", href: "/dashboard/finance/costing-methods", group: "Cost Accounting" },
  { title: "Variance Analysis", href: "/dashboard/finance/cost-variances", group: "Cost Accounting" },
  { title: "WIP Accounting", href: "/dashboard/finance/wip", group: "Cost Accounting" },
  { title: "Production Profitability", href: "/dashboard/finance/production-profit", group: "Cost Accounting" },
  { title: "Inventory Valuation", href: "/dashboard/finance/inventory-valuation", group: "Inventory" },
  { title: "FIFO / Weighted Avg / Standard", href: "/dashboard/finance/valuation-methods", group: "Inventory" },
  { title: "Stock Revaluation", href: "/dashboard/finance/stock-revaluation", group: "Inventory" },
  { title: "Inventory Adjustments", href: "/dashboard/finance/inventory-adjustments", group: "Inventory" },
  { title: "Asset Register", href: "/dashboard/finance/assets", group: "Fixed Assets" },
  { title: "Capitalization", href: "/dashboard/finance/asset-capitalization", group: "Fixed Assets" },
  { title: "Depreciation", href: "/dashboard/finance/depreciation", group: "Fixed Assets" },
  { title: "Asset Revaluation", href: "/dashboard/finance/asset-revaluation", group: "Fixed Assets" },
  { title: "Asset Transfers", href: "/dashboard/finance/asset-transfers", group: "Fixed Assets" },
  { title: "Disposals", href: "/dashboard/finance/asset-disposals", group: "Fixed Assets" },
  { title: "Impairment", href: "/dashboard/finance/asset-impairment", group: "Fixed Assets" },
  { title: "Construction in Progress", href: "/dashboard/finance/cip", group: "Fixed Assets" },
  { title: "Lease Accounting", href: "/dashboard/finance/leases", group: "Fixed Assets" },
  { title: "Payroll Journals", href: "/dashboard/finance/payroll-journals", group: "Payroll Accounting" },
  { title: "Tax Codes", href: "/dashboard/finance/tax", group: "Tax Management" },
  { title: "Tax Returns", href: "/dashboard/finance/tax-returns", group: "Tax Management" },
  { title: "Withholding Tax", href: "/dashboard/finance/wht", group: "Tax Management" },
  { title: "Corporate Tax", href: "/dashboard/finance/corporate-tax", group: "Tax Management" },
  { title: "Excise Duty", href: "/dashboard/finance/excise-duty", group: "Tax Management" },
  { title: "Import Duty", href: "/dashboard/finance/import-duty", group: "Tax Management" },
  { title: "Tax Calendar", href: "/dashboard/finance/tax-calendar", group: "Tax Management" },
  { title: "Tax Jurisdictions", href: "/dashboard/finance/tax-jurisdictions", group: "Tax Management" },
  { title: "Deferred Revenue", href: "/dashboard/finance/deferred-revenue", group: "Revenue" },
  { title: "Subscription Revenue", href: "/dashboard/finance/subscription-revenue", group: "Revenue" },
  { title: "Revenue Recognition", href: "/dashboard/finance/revenue-recognition", group: "Revenue" },
  { title: "Government Contracts", href: "/dashboard/finance/gov-contracts", group: "Revenue" },
  { title: "Export Revenue", href: "/dashboard/finance/export-revenue", group: "Revenue" },
  { title: "Project Costing", href: "/dashboard/finance/project-costs", group: "Project Accounting" },
  { title: "Project Billing", href: "/dashboard/finance/project-billing", group: "Project Accounting" },
  { title: "Project Profitability", href: "/dashboard/finance/project-profit", group: "Project Accounting" },
  { title: "Expense Claims", href: "/dashboard/finance/expense-claims", group: "Expenses" },
  { title: "Month-End Close", href: "/dashboard/finance/month-end-close", group: "Financial Close" },
  { title: "Year-End Close", href: "/dashboard/finance/year-end-close", group: "Financial Close" },
  { title: "Close Checklist", href: "/dashboard/finance/close-checklist", group: "Financial Close" },
  { title: "Close Adjustments", href: "/dashboard/finance/close-adjustments", group: "Financial Close" },
  { title: "Reconciliations", href: "/dashboard/finance/reconciliations", group: "Financial Close" },
  { title: "Intercompany", href: "/dashboard/finance/intercompany", group: "Consolidation" },
  { title: "Elimination Entries", href: "/dashboard/finance/eliminations", group: "Consolidation" },
  { title: "Currency Translation", href: "/dashboard/finance/currency-translation", group: "Consolidation" },
  { title: "Group Consolidation", href: "/dashboard/finance/group-consolidation", group: "Consolidation" },
  { title: "Internal Controls", href: "/dashboard/finance/internal-controls", group: "Compliance" },
  { title: "SoD Rules", href: "/dashboard/finance/sod-rules", group: "Compliance" },
  { title: "Policy Management", href: "/dashboard/finance/policies", group: "Compliance" },
  { title: "Risk Register", href: "/dashboard/finance/risk-register", group: "Compliance" },
  { title: "Posting Rules", href: "/dashboard/finance/posting-rules", group: "Accounting Engine" },
  { title: "Auto Journals", href: "/dashboard/finance/auto-journals", group: "Accounting Engine" },
  { title: "Accounting Engine", href: "/dashboard/finance/engine", group: "Accounting Engine" },
  { title: "AI Finance", href: "/dashboard/finance/ai", group: "Analytics" },
  { title: "Reports", href: "/dashboard/finance/reports", group: "Analytics" },
  { title: "KPI Dashboard", href: "/dashboard/finance/cfo", group: "Analytics" },
  { title: "Mobile Finance", href: "/dashboard/finance/mobile", group: "System" },
  { title: "Audit Logs", href: "/dashboard/finance/audit", group: "System" },
  { title: "Finance Settings", href: "/dashboard/finance/settings", group: "System" },
] as const;
