import type { LucideIcon } from "lucide-react";
import {
  Activity, Banknote, BarChart3, BedDouble, Bell, Bot, Box, Boxes, Briefcase,
  Building2, Calculator, CalendarClock, ClipboardCheck, Clock, CloudOff, Code2,
  Cpu, DatabaseBackup, Factory, FilePlus2, FileSearch, FileText, Fingerprint,
  FlaskConical, FolderKanban, Fuel, Gauge, Globe2, GraduationCap, Hammer,
  Handshake, HeartPulse, Home, KeyRound, Laptop, Landmark, Layers, Lightbulb, LineChart,
  Lock, Megaphone, Medal, MessagesSquare, Mic, Microscope, Package, PieChart, PencilRuler,
  Pickaxe, PlayCircle, Puzzle, QrCode, Radio, RefreshCcw, Rocket, Scale,
  ScanFace, ScanText, Search, SearchCheck, Server, Settings2, Share2, Shield,
  ShieldAlert, ShieldCheck, ShoppingCart, Smartphone, Sparkles, Sprout, Store,
  TabletSmartphone, Ticket, Timer, TrendingUp, Truck, UserCheck, Users,
  Warehouse, Webhook, Workflow, Wrench, Zap,
} from "lucide-react";

export const COMPANY = {
  name: "SecureTrack ERP",
  legalName: "SecureTrack ERP Limited",
  url: "https://hope-securetrack.vercel.app",
  tagline: "Run your entire enterprise on one intelligent platform.",
  description:
    "SecureTrack ERP is an AI-powered, cloud-native enterprise resource planning platform that unifies finance, HR, manufacturing, procurement, supply chain, CRM, projects, payroll, asset management, service desk, analytics, and AI into a single secure, scalable platform.",
  email: "sales@securetrackerp.com",
  phone: "+256 700 000 000",
  address: "Kampala, Uganda",
};

export const NAV_LINKS = [
  { label: "Solutions", href: "/solutions" },
  { label: "Industries", href: "/industries" },
  { label: "Modules", href: "/modules" },
  { label: "AI Platform", href: "/ai-platform" },
  { label: "Security", href: "/security" },
  { label: "Pricing", href: "/pricing" },
  { label: "Customers", href: "/customers" },
  { label: "Resources", href: "/resources" },
] as const;

export const TRUST_TECH = [
  "Microsoft", "Google Cloud", "Supabase", "PostgreSQL", "Docker", "Kubernetes",
  "Vercel", "Cloudflare", "AWS", "Azure",
] as const;

export const TRUST_BADGES = [
  "ISO 27001 Ready", "GDPR Ready", "SOC 2 Ready", "PCI DSS Ready",
  "Zero Trust", "Multi-Tenant", "99.99% Availability",
] as const;

export const STATS: Array<{ value: number; prefix?: string; suffix?: string; label: string; decimals?: number }> = [
  { value: 4800, suffix: "+", label: "Organizations" },
  { value: 1.2, suffix: "M+", label: "Users", decimals: 1 },
  { value: 40, suffix: "+", label: "Countries" },
  { value: 31, suffix: "", label: "ERP Modules" },
  { value: 42, suffix: "M+", label: "Transactions" },
  { value: 8.4, suffix: "M+", label: "Invoices", decimals: 1 },
  { value: 2.1, suffix: "M+", label: "Assets", decimals: 1 },
  { value: 680, suffix: "K+", label: "Employees" },
  { value: 95, suffix: "M+", label: "API Calls" },
  { value: 12, suffix: "M+", label: "AI Requests" },
  { value: 3.6, suffix: "M+", label: "Reports", decimals: 1 },
  { value: 28, suffix: "M+", label: "Documents" },
  { value: 4.2, suffix: "PB", label: "Storage Managed", decimals: 1 },
  { value: 1.4, suffix: "M", label: "Hours Saved / yr", decimals: 1 },
  { value: 3.2, suffix: "B+", label: "Revenue Managed", decimals: 1 },
];
export type Industry = {
  slug: string;
  name: string;
  icon: LucideIcon;
  blurb: string;
  challenges: string[];
  modules: string[];
  kpis: string[];
  compliance: string[];
};

export const INDUSTRIES: Industry[] = [
  { slug: "manufacturing", name: "Manufacturing", icon: Factory,
    blurb: "Plan, produce, inspect, and deliver with full traceability from shop floor to customer.",
    challenges: ["Production visibility", "Quality control", "Machine downtime", "BOM & costing accuracy"],
    modules: ["Manufacturing MES", "Quality", "Inventory", "Procurement", "Maintenance", "Fleet"],
    kpis: ["OEE +18%", "Scrap -22%", "On-time delivery 97%"],
    compliance: ["ISO 9001", "ISO 14001", "GS1 Traceability"] },
  { slug: "healthcare", name: "Healthcare", icon: HeartPulse,
    blurb: "Manage hospitals, clinics, labs, and pharmacies with patient-centric operations and strict compliance.",
    challenges: ["Patient records", "Pharmacy stockouts", "Equipment uptime", "Regulatory audits"],
    modules: ["Hospital ERP", "Inventory", "Asset Management", "HR & Payroll", "Procurement", "Help Desk"],
    kpis: ["Stockouts -35%", "Equipment uptime 99%", "Faster audits"],
    compliance: ["HIPAA Ready", "GDPR", "National Health Standards"] },
  { slug: "education", name: "Education", icon: GraduationCap,
    blurb: "Run schools, universities, and campuses — admissions, fees, academics, HR, and facilities in one place.",
    challenges: ["Fee collection", "Student records", "Campus assets", "Exam & grading workflows"],
    modules: ["School ERP", "Finance", "HR & Payroll", "Asset Management", "Projects", "Help Desk"],
    kpis: ["Fee recovery +24%", "Admin effort -40%", "1 platform, all campuses"],
    compliance: ["Education Ministry Reporting", "Data Protection Acts", "Accreditation Records"] },
  { slug: "government", name: "Government", icon: Landmark,
    blurb: "Modernize public services with auditable, transparent, and secure operations across departments.",
    challenges: ["Public accountability", "Budget control", "Audit readiness", "Service delivery"],
    modules: ["Finance", "Procurement", "Payroll", "Projects", "Document Management", "Compliance"],
    kpis: ["Audit pass 100%", "Procurement cycle -30%", "Full transparency"],
    compliance: ["IPSAS", "PFM Standards", "Data Protection & Privacy Act"] },
  { slug: "construction", name: "Construction", icon: Hammer,
    blurb: "Control projects, contracts, subcontractors, equipment, and costs from bid to handover.",
    challenges: ["Project overruns", "Equipment tracking", "Subcontractor payments", "Site-to-office visibility"],
    modules: ["Projects", "Procurement", "Equipment & Assets", "Fleet", "Payroll", "Finance"],
    kpis: ["Cost overrun -18%", "Equipment use +22%", "Real-time site data"],
    compliance: ["OSHA Ready", "Contract Law", "Tax Withholding"] },
  { slug: "retail", name: "Retail", icon: Store,
    blurb: "Unify POS, e-commerce, inventory, loyalty, and multi-store operations with real-time visibility.",
    challenges: ["Stockouts & overstock", "Multi-store control", "Shrinkage", "Omnichannel orders"],
    modules: ["POS", "CRM", "Inventory", "Sales", "Finance", "AI Forecasting"],
    kpis: ["Forecast accuracy 92%", "Shrinkage -15%", "Stock turns +28%"],
    compliance: ["PCI DSS Ready", "Consumer Protection", "VAT / GST"] },
  { slug: "wholesale", name: "Wholesale", icon: Boxes,
    blurb: "Manage distribution, pricing tiers, credit, and large-volume order flows with precision.",
    challenges: ["Thin margins", "Credit risk", "Order accuracy", "Distribution costs"],
    modules: ["Sales", "Inventory", "Procurement", "Credit & Collections", "Logistics", "BI"],
    kpis: ["Margin +6 pts", "DSO -12 days", "Order accuracy 99.5%"],
    compliance: ["Tax Compliance", "Trade Regulations", "Data Protection"] },
  { slug: "logistics", name: "Logistics", icon: Truck,
    blurb: "Coordinate fleets, dispatch, warehousing, and proof-of-delivery across regions and borders.",
    challenges: ["Route efficiency", "Fleet utilization", "Proof of delivery", "Fuel costs"],
    modules: ["Fleet", "Warehouse", "Dispatch", "GPS Tracking", "Mobile", "Billing"],
    kpis: ["Fuel -14%", "Deliveries +19%", "POD turnaround 100%"],
    compliance: ["Transport Licensing", "EAC Customs", "HSE"] },
  { slug: "hospitality", name: "Hospitality", icon: BedDouble,
    blurb: "Run hotels, restaurants, and resorts — reservations, POS, housekeeping, and finance as one.",
    challenges: ["Occupancy optimization", "Guest experience", "Inventory & F&B cost", "Seasonal staffing"],
    modules: ["Hotel ERP", "POS", "CRM", "HR & Payroll", "Procurement", "BI"],
    kpis: ["RevPAR +12%", "F&B cost -9%", "Guest satisfaction 4.7/5"],
    compliance: ["Tourism Licensing", "Food Safety", "Data Protection"] },
  { slug: "agriculture", name: "Agriculture", icon: Sprout,
    blurb: "Digitize farms, estates, and agribusiness — from planting and inputs to processing and sales.",
    challenges: ["Input tracking", "Yield variability", "Outgrower payments", "Post-harvest losses"],
    modules: ["Agri ERP", "Inventory", "Procurement", "Finance", "Fleet", "AI Insights"],
    kpis: ["Yield +15%", "Post-harvest loss -20%", "Traceable supply"],
    compliance: ["GlobalG.A.P. Ready", "Export Standards", "Fair Trade"] },
  { slug: "banking", name: "Banking & Microfinance", icon: Landmark,
    blurb: "Support banks, microfinance, and SACCOs with secure, auditable operations and lending.",
    challenges: ["Loan portfolios", "Regulatory reporting", "Fraud risk", "Branch networks"],
    modules: ["Core Ledger", "Loans", "Customer Management", "Compliance", "BI", "Security"],
    kpis: ["Portfolio at risk -25%", "Reporting faster", "Audit-ready 100%"],
    compliance: ["Central Bank Supervision", "Basel Principles", "AML / KYC Ready"] },
  { slug: "insurance", name: "Insurance", icon: ShieldCheck,
    blurb: "Manage policies, premiums, claims, agents, and reinsurance with actuarial-grade control.",
    challenges: ["Claims leakage", "Policy administration", "Agent commissions", "Solvency reporting"],
    modules: ["Policy Management", "Claims", "Finance", "CRM", "Compliance", "BI"],
    kpis: ["Claims cycle -30%", "Policy accuracy 99%", "Solvency reporting on time"],
    compliance: ["Insurance Regulator", "IFRS 17 Ready", "Data Protection"] },
  { slug: "ngos", name: "NGOs & Nonprofits", icon: Handshake,
    blurb: "Run programs, grants, donors, and field operations with transparent, compliant stewardship.",
    challenges: ["Donor reporting", "Grant compliance", "Field data capture", "Budget utilization"],
    modules: ["Projects", "Finance", "Procurement", "Mobile Forms", "Document Management", "Reports"],
    kpis: ["Donor reports on time", "Overhead -12%", "Field data live"],
    compliance: ["Donor Requirements", "Charity Law", "GDPR"] },
  { slug: "mining", name: "Mining", icon: Pickaxe,
    blurb: "Manage sites, equipment, minerals, contracts, and safety across remote operations.",
    challenges: ["Asset utilization", "Safety compliance", "Remote connectivity", "Mineral tracking"],
    modules: ["Equipment & Assets", "Maintenance", "Projects", "HR & Payroll", "Compliance", "IoT"],
    kpis: ["Asset availability +14%", "Safety incidents -30%", "Traceable production"],
    compliance: ["Mining Licenses", "HSE", "ESG Reporting"] },
  { slug: "utilities", name: "Utilities", icon: Zap,
    blurb: "Operate water, power, and energy networks with metering, maintenance, and billing at scale.",
    challenges: ["Meter-to-cash", "Network maintenance", "Revenue assurance", "Peak demand"],
    modules: ["Metering", "Billing", "Maintenance", "Fleet", "Finance", "IoT"],
    kpis: ["Collection +18%", "NRW / losses -12%", "Response time -40%"],
    compliance: ["Regulator Reporting", "Grid Codes", "Consumer Protection"] },
  { slug: "telecommunications", name: "Telecommunications", icon: Radio,
    blurb: "Manage networks, towers, dealers, airtime, devices, and subscribers at national scale.",
    challenges: ["Dealer networks", "Tower Opex", "Device inventory", "Subscriber churn"],
    modules: ["Distribution", "Inventory", "Fleet & Towers", "CRM", "Finance", "BI"],
    kpis: ["Dealer reconciliation 100%", "Tower Opex -11%", "Churn -8%"],
    compliance: ["Telecom Licensing", "Data Protection", "Interconnect Rules"] },
  { slug: "professional-services", name: "Professional Services", icon: Briefcase,
    blurb: "Run consultancies, law firms, and agencies with projects, timesheets, billing, and clients.",
    challenges: ["Billable utilization", "Time capture", "Project profitability", "Client billing"],
    modules: ["Projects", "Timesheets", "CRM", "Finance", "Expenses", "BI"],
    kpis: ["Utilization +16%", "Billing cycle -6 days", "Margin visibility live"],
    compliance: ["Client Confidentiality", "GDPR", "Professional Standards"] },
  { slug: "real-estate", name: "Real Estate", icon: Home,
    blurb: "Manage properties, tenants, leases, maintenance, and rental income across portfolios.",
    challenges: ["Tenant management", "Lease renewals", "Property maintenance", "Rent collection"],
    modules: ["Property Management", "Tenant CRM", "Maintenance", "Finance", "Contracts", "BI"],
    kpis: ["Occupancy +9%", "Rent collection +15%", "Maintenance SLA 95%"],
    compliance: ["Landlord-Tenant Law", "Property Tax", "Data Protection"] },
  { slug: "energy", name: "Energy", icon: Fuel,
    blurb: "Manage fuel, solar, power plants, and energy assets with procurement, logistics, and safety.",
    challenges: ["Fuel stock control", "Asset health", "Safety compliance", "Supply volatility"],
    modules: ["Inventory", "Assets", "Maintenance", "Procurement", "Compliance", "AI"],
    kpis: ["Stock accuracy 99%", "Asset health +20%", "Procurement savings 8%"],
    compliance: ["Energy Regulator", "HSE", "ISO 50001 Ready"] },
];

export type ModuleInfo = {
  slug: string;
  name: string;
  icon: LucideIcon;
  group: string;
  overview: string;
  features: string[];
  ai: string[];
};
export const MODULES: ModuleInfo[] = [
  { slug: "finance", name: "Finance", icon: Landmark, group: "Finance",
    overview: "General ledger, multi-company close, treasury, budgeting, and full audit trails.",
    features: ["GL & Chart of Accounts", "AR / AP", "Treasury & Cash", "Multi-currency", "Budgets & Forecasts"],
    ai: ["Anomaly detection", "Cash flow forecasting", "Narrative close commentary"] },
  { slug: "accounting", name: "Accounting", icon: Calculator, group: "Finance",
    overview: "Automated journals, reconciliations, fixed assets, and regulatory-ready ledgers.",
    features: ["Journal automation", "Bank reconciliation", "Fixed assets", "Tax & VAT", "Financial statements"],
    ai: ["Auto-reconciliation", "Classification suggestions", "Variance explanations"] },
  { slug: "procurement", name: "Procurement", icon: ShoppingCart, group: "Supply",
    overview: "Source-to-pay with RFQs, purchase orders, approvals, and supplier management.",
    features: ["RFQ / RFP", "Purchase Orders", "Approval workflows", "Supplier portals", "3-way matching"],
    ai: ["Spend analytics", "Supplier risk scores", "Purchase recommendations"] },
  { slug: "inventory", name: "Inventory", icon: Package, group: "Supply",
    overview: "Real-time multi-warehouse inventory with lot, serial, and batch traceability.",
    features: ["Multi-warehouse", "Serial & batch", "Stock transfers", "Cycle counts", "ABC analysis"],
    ai: ["Demand forecasting", "Re-order suggestions", "Dead-stock alerts"] },
  { slug: "warehouse", name: "Warehouse", icon: Warehouse, group: "Supply",
    overview: "WMS with bin locations, picking, packing, and mobile scanning workflows.",
    features: ["Bin locations", "Pick / pack / ship", "Mobile scanning", "Put-away", "Wave planning"],
    ai: ["Slotting optimization", "Labour forecasting", "Error detection"] },
  { slug: "manufacturing", name: "Manufacturing", icon: Factory, group: "Ops",
    overview: "MES-grade production with BOMs, routing, batches, quality gates, and OEE.",
    features: ["BOM & Routing", "Production orders", "Quality gates", "OEE tracking", "Batch genealogy"],
    ai: ["Predictive maintenance", "Yield optimization", "Defect classification"] },
  { slug: "crm", name: "CRM", icon: Users, group: "Revenue",
    overview: "Pipeline, accounts, contacts, opportunities, and customer 360 across channels.",
    features: ["Contact & account 360", "Opportunities", "Quotations", "Activities", "Customer portal"],
    ai: ["Lead scoring", "Next-best-action", "Churn prediction"] },
  { slug: "sales", name: "Sales", icon: LineChart, group: "Revenue",
    overview: "Quote-to-cash with pricing, contracts, credit, commissions, and forecasts.",
    features: ["Quotations & orders", "Price lists", "Credit control", "Commissions", "Forecasts"],
    ai: ["Revenue forecasting", "Won/lost insights", "Upsell recommendations"] },
  { slug: "pos", name: "Point of Sale", icon: Store, group: "Revenue",
    overview: "Omnichannel POS with offline mode, payments, receipts, and inventory sync.",
    features: ["Offline POS", "Payments", "Digital receipts", "Loyalty", "Multi-store"],
    ai: ["Demand-based promotions", "Shrink detection", "Basket analysis"] },
  { slug: "hr", name: "HR", icon: Users, group: "People",
    overview: "Core HRIS covering employees, org structure, documents, and the full lifecycle.",
    features: ["Employee records", "Org charts", "Onboarding", "Documents", "Self-service"],
    ai: ["Attrition risk", "Skills inference", "HR policy answers"] },
  { slug: "payroll", name: "Payroll", icon: Banknote, group: "People",
    overview: "Compliant payroll with statutory deductions, payslips, and approvals.",
    features: ["Salary structures", "Statutory deductions", "Payslips", "Payroll approvals", "Bank files"],
    ai: ["Payroll anomaly checks", "Cost allocation", "Compliance reminders"] },
  { slug: "recruitment", name: "Recruitment", icon: ClipboardCheck, group: "People",
    overview: "From requisition to hire — candidates, interviews, offers, and onboarding.",
    features: ["Job requisitions", "Candidate pipeline", "Interviews", "Offers", "Onboarding"],
    ai: ["Resume ranking", "Interview scheduling", "Bias checks"] },
  { slug: "learning", name: "Learning", icon: GraduationCap, group: "People",
    overview: "LMS with courses, certifications, assignments, and skill development tracking.",
    features: ["Courses", "Certifications", "Assessments", "Skills matrix", "Training plans"],
    ai: ["Personalized learning paths", "Skill gap analysis", "Content recommendations"] },
  { slug: "performance", name: "Performance", icon: Gauge, group: "People",
    overview: "Goals, reviews, check-ins, and 360 feedback linked to development.",
    features: ["OKRs & goals", "Reviews", "360 feedback", "Check-ins", "Development plans"],
    ai: ["Review summaries", "Goal alignment", "Feedback insights"] },
  { slug: "fleet", name: "Fleet", icon: Truck, group: "Ops",
    overview: "Vehicles, drivers, fuel, GPS, dispatch, and maintenance in one fleet platform.",
    features: ["Vehicle register", "GPS tracking", "Fuel management", "Dispatch", "Inspections"],
    ai: ["Route optimization", "Fuel anomaly alerts", "Predictive maintenance"] },
  { slug: "projects", name: "Projects", icon: FolderKanban, group: "Delivery",
    overview: "Projects, tasks, budgets, timesheets, resources, and profitability.",
    features: ["Portfolios", "Tasks & Gantt", "Budgets", "Timesheets", "Resource planning"],
    ai: ["Delay prediction", "Budget risk alerts", "Resource suggestions"] },
  { slug: "asset-management", name: "Asset Management", icon: Box, group: "Ops",
    overview: "Full asset lifecycle with digital twins, depreciation, and IoT telemetry.",
    features: ["Asset register", "Depreciation", "Warranty", "QR / RFID tags", "IoT telemetry"],
    ai: ["Health scores", "Remaining useful life", "Lifecycle cost insights"] },
  { slug: "maintenance", name: "Maintenance", icon: Wrench, group: "Ops",
    overview: "Preventive and corrective maintenance with work orders and spare parts.",
    features: ["Work orders", "Preventive schedules", "Spare parts", "Technicians", "SLA timers"],
    ai: ["Failure prediction", "Priority ranking", "Spare-part forecasting"] },
  { slug: "quality", name: "Quality", icon: Microscope, group: "Ops",
    overview: "Quality management with inspections, non-conformances, CAPA, and audits.",
    features: ["Inspections", "Non-conformance", "CAPA", "Supplier quality", "Audits"],
    ai: ["Defect pattern analysis", "Risk-based inspection", "CAPA recommendations"] },
  { slug: "help-desk", name: "Service Desk", icon: Ticket, group: "Service",
    overview: "Ticketing, SLAs, escalations, knowledge base, and customer satisfaction.",
    features: ["Tickets", "SLAs & escalations", "Knowledge base", "Self-service portal", "CSAT"],
    ai: ["Auto-triage", "Suggested resolutions", "SLA risk alerts"] },
  { slug: "customer-portal", name: "Customer Portal", icon: Globe2, group: "Service",
    overview: "Self-service portal for tickets, orders, invoices, and account health.",
    features: ["Self-service", "Order tracking", "Invoice download", "Knowledge base", "Chat"],
    ai: ["Instant answers", "Order status predictions", "Proactive alerts"] },
  { slug: "supplier-portal", name: "Supplier Portal", icon: Handshake, group: "Service",
    overview: "Collaborative portal for RFQs, POs, invoices, and supplier performance.",
    features: ["RFQ responses", "PO confirmations", "Supplier invoices", "Scorecards", "Documents"],
    ai: ["Performance analytics", "Risk flags", "Negotiation insights"] },
  { slug: "executive-bi", name: "Executive BI", icon: PieChart, group: "Intelligence",
    overview: "Executive dashboards, KPI cards, drill-down analytics, and scheduled reports.",
    features: ["Dashboards", "KPI cards", "Drill-down", "Scheduled reports", "Pivot analysis"],
    ai: ["Narrative reports", "Anomaly highlights", "Forecast overlays"] },
  { slug: "ai-platform", name: "AI Platform", icon: Sparkles, group: "Intelligence",
    overview: "Tenant-isolated AI with agents, workflows, OCR, and natural-language analytics.",
    features: ["AI agents", "Natural-language queries", "Document OCR", "Workflow builder", "AI memory"],
    ai: ["Explainable insights", "Permission-aware", "Tenant-isolated context"] },
  { slug: "document-management", name: "Document Management", icon: FileText, group: "Platform",
    overview: "Secure document storage, versioning, retention, and full-text search.",
    features: ["Versioning", "Retention policies", "OCR search", "Digital signatures", "Watermarks"],
    ai: ["Auto-classification", "Entity extraction", "Summary generation"] },
  { slug: "workflow", name: "Workflow", icon: Workflow, group: "Platform",
    overview: "No-code workflow designer for approvals, automation, SLAs, and routing.",
    features: ["Visual designer", "Conditional routing", "Approvals", "Escalations", "Business calendars"],
    ai: ["Workflow suggestions", "Bottleneck detection", "SLA predictions"] },
  { slug: "notifications", name: "Notifications", icon: Megaphone, group: "Platform",
    overview: "Omnichannel notifications — email, SMS, WhatsApp, push, Slack, Teams.",
    features: ["Templates", "Schedules", "Channels", "Opt-out rules", "Delivery analytics"],
    ai: ["Optimal send times", "Channel selection", "Engagement insights"] },
  { slug: "identity", name: "Identity", icon: Fingerprint, group: "Security",
    overview: "Tenant-managed IAM with employee-ID login, MFA, SSO, and lifecycle automation.",
    features: ["User provisioning", "Employee ID login", "MFA & passkeys", "SSO / SAML", "Session control"],
    ai: ["Risk-based authentication", "Anomalous sign-in alerts", "Access reviews"] },
  { slug: "compliance", name: "Compliance", icon: Scale, group: "Security",
    overview: "Policy-driven compliance with retention, consent, and audit automation.",
    features: ["Policy library", "Retention schedules", "Consent management", "Audit reports", "Frameworks"],
    ai: ["Control evidence mapping", "Gap detection", "Risk scoring"] },
  { slug: "security", name: "Security", icon: Shield, group: "Security",
    overview: "Zero-trust security with RBAC/ABAC, encryption, monitoring, and DLP.",
    features: ["RBAC / ABAC", "Encryption", "Security monitoring", "Threat detection", "Immutable audit"],
    ai: ["Threat correlation", "Anomaly detection", "Incident summaries"] },
  { slug: "administration", name: "Administration", icon: Settings2, group: "Platform",
    overview: "Platform administration for tenants, companies, users, and configurations.",
    features: ["Tenant management", "Company hierarchy", "Numbering rules", "Feature flags", "Audit console"],
    ai: ["Configuration health", "Adoption insights", "Optimization tips"] },
];
export const AI_CAPABILITIES: Array<{ icon: LucideIcon; title: string; desc: string }> = [
  { icon: MessagesSquare, title: "Natural Language Queries", desc: "Ask in plain language — “show revenue by region” — and get charts, tables, and answers instantly." },
  { icon: FileText, title: "Executive Reports", desc: "AI writes narrative summaries of your numbers, highlighting what changed and why." },
  { icon: LineChart, title: "AI Forecasting", desc: "Revenue, cash, demand, and workload forecasts trained on your tenant data — never anyone else's." },
  { icon: SearchCheck, title: "Financial Analysis", desc: "Variance explanations, margin drivers, and close commentary generated in seconds." },
  { icon: ShieldAlert, title: "Risk Detection", desc: "Continuous anomaly detection across finance, inventory, fleet, and HR." },
  { icon: Fingerprint, title: "Fraud Detection", desc: "Pattern analysis flags duplicate payments, ghost vendors, and unusual approvals." },
  { icon: Wrench, title: "Predictive Maintenance", desc: "AI predicts equipment failures before they stop production — with explainable signals." },
  { icon: Bot, title: "AI Chat", desc: "A permission-aware assistant that answers from your tenant's own context." },
  { icon: Workflow, title: "AI Workflow Builder", desc: "Describe a process and AI drafts the approval workflow — you review and publish." },
  { icon: FilePlus2, title: "AI Document Generator", desc: "Contracts, invoices, and reports generated from templates and your data." },
  { icon: ScanText, title: "AI OCR", desc: "Invoices, IDs, and documents scanned and entered automatically with high accuracy." },
  { icon: PieChart, title: "AI Analytics", desc: "Auto-generated dashboards, anomaly callouts, and plain-English insights." },
  { icon: Lightbulb, title: "AI Recommendations", desc: "Contextual suggestions embedded across every module." },
  { icon: CalendarClock, title: "AI Scheduling", desc: "Optimal shift, delivery, and maintenance schedules from constraint-aware AI." },
  { icon: ShoppingCart, title: "AI Procurement", desc: "Spend analysis, supplier risk, and purchase recommendations." },
  { icon: Factory, title: "AI Manufacturing", desc: "Yield, quality, and maintenance optimization across the shop floor." },
  { icon: Users, title: "AI HR", desc: "Attrition risk, skills inference, and policy answers from your HR data." },
  { icon: Banknote, title: "AI Payroll", desc: "Anomaly checks, cost allocation, and compliance reminders before run." },
  { icon: UserCheck, title: "AI CRM", desc: "Lead scoring, next-best-action, and churn prediction for your pipeline." },
  { icon: Ticket, title: "AI Service Desk", desc: "Auto-triage, suggested resolutions, and SLA risk alerts." },
];

export const PLATFORM_CAPABILITIES: Array<{ icon: LucideIcon; title: string; desc: string }> = [
  { icon: Building2, title: "Multi-company", desc: "Holding structures, subsidiaries, and consolidated reporting." },
  { icon: Layers, title: "Multi-tenant", desc: "Strict tenant isolation with RLS on every business table." },
  { icon: Share2, title: "Multi-branch", desc: "Branches, regions, departments, business units, and cost centers." },
  { icon: Banknote, title: "Multi-currency", desc: "Currencies, exchange rates, revaluation, and settlement." },
  { icon: Globe2, title: "Multi-language", desc: "Localized interfaces and regional number, date, and tax rules." },
  { icon: Clock, title: "Multi-timezone", desc: "Schedules, SLAs, and timestamps that respect local time." },
  { icon: Smartphone, title: "Offline-first", desc: "Capture data offline, sync securely, and resolve conflicts." },
  { icon: Cpu, title: "API-first", desc: "REST + GraphQL, webhooks, SDKs, and an API explorer." },
  { icon: Store, title: "Marketplace", desc: "Modules, connectors, themes, and industry packs — one-click install." },
  { icon: Workflow, title: "Workflow engine", desc: "No-code approvals, automation, SLAs, and business calendars." },
  { icon: Zap, title: "Automation", desc: "Event-driven rules that trigger actions across modules." },
  { icon: Fingerprint, title: "RBAC + ABAC", desc: "Role and attribute-based access with inheritance and delegation." },
  { icon: ClipboardCheck, title: "Audit", desc: "Immutable audit trails on every record and action." },
  { icon: Megaphone, title: "Notifications", desc: "Email, SMS, WhatsApp, push, Slack, and Teams." },
  { icon: TabletSmartphone, title: "Mobile apps", desc: "iOS, Android, PWA, QR/barcode/RFID, and push." },
  { icon: Code2, title: "Developer SDK", desc: "SDKs, CLI, sandbox, webhooks, and OAuth for builders." },
];

export const SECURITY_FEATURES: Array<{ icon: LucideIcon; title: string; desc: string }> = [
  { icon: Fingerprint, title: "MFA & Passkeys", desc: "Multi-factor authentication with passkey-ready support." },
  { icon: Lock, title: "SSO & Federation", desc: "OAuth 2.0, OpenID Connect, and SAML 2.0 federation." },
  { icon: ShieldCheck, title: "RBAC + ABAC", desc: "Fine-grained role and attribute-based authorization." },
  { icon: Layers, title: "Tenant isolation", desc: "Row-Level Security, isolated storage, search, cache, and AI context." },
  { icon: KeyRound, title: "Encryption", desc: "Encryption at rest and in transit with managed keys." },
  { icon: FileSearch, title: "Audit logs", desc: "Immutable, tamper-evident audit trails for every action." },
  { icon: Activity, title: "Security monitoring", desc: "Real-time threat detection and security incident dashboards." },
  { icon: ShieldAlert, title: "DLP", desc: "Data-loss prevention across exports, downloads, and transfers." },
  { icon: DatabaseBackup, title: "Backups & DR", desc: "Automated backups, point-in-time recovery, and disaster recovery." },
  { icon: Server, title: "Data residency", desc: "Regional deployment options for sovereignty requirements." },
  { icon: ScanFace, title: "Zero trust", desc: "Verify every session, device, and request — never trust implicitly." },
  { icon: Scale, title: "Compliance", desc: "ISO 27001, SOC 2, GDPR, PCI DSS, and HIPAA-ready controls." },
];
export const MARKETPLACE_ITEMS: Array<{ icon: LucideIcon; title: string; category: string; desc: string }> = [
  { icon: Factory, title: "Manufacturing MES", category: "Modules", desc: "Shop-floor execution with OEE and quality gates." },
  { icon: Banknote, title: "Payroll Premium", category: "Finance", desc: "Advanced statutory and multi-country payroll." },
  { icon: QrCode, title: "QR & RFID Suite", category: "Ops", desc: "Asset tagging, scanning, and traceability." },
  { icon: Fuel, title: "Fleet AI", category: "AI", desc: "Route, fuel, and maintenance intelligence." },
  { icon: BarChart3, title: "BI Suite", category: "Analytics", desc: "Pivot, matrix, and executive reporting." },
  { icon: FileText, title: "e-Signature", category: "Docs", desc: "Legally binding digital signatures." },
  { icon: MessagesSquare, title: "WhatsApp Gateway", category: "Connectors", desc: "Transactional messaging on WhatsApp." },
  { icon: Laptop, title: "Customer Portal", category: "Service", desc: "Self-service portals for customers and vendors." },
];

export const INTEGRATION_GROUPS: Array<{ title: string; items: string[] }> = [
  { title: "Productivity", items: ["Microsoft 365", "Google Workspace", "Microsoft Entra ID", "Slack", "Microsoft Teams", "Zoom", "Google Meet"] },
  { title: "Payments", items: ["Stripe", "Flutterwave", "MTN MoMo", "Airtel Money", "PayPal", "Pesapal", "Paystack"] },
  { title: "Accounting & BI", items: ["QuickBooks", "Xero", "Sage", "Tally", "Power BI", "Tableau"] },
  { title: "Enterprise", items: ["SAP", "Oracle", "Salesforce", "HubSpot", "Mailchimp", "GitHub", "Jira"] },
  { title: "Platform", items: ["REST API", "GraphQL", "Webhooks", "OAuth 2.0", "SAML 2.0", "OpenID Connect"] },
];

export const ANALYTICS_VIEWS: Array<{ id: string; label: string; icon: LucideIcon; points: number[]; caption: string }> = [
  { id: "revenue", label: "Revenue", icon: Banknote, points: [42, 48, 45, 52, 58, 63, 61, 70, 74, 81, 79, 88], caption: "Monthly revenue in $M — AI forecast overlay included." },
  { id: "sales", label: "Sales", icon: ShoppingCart, points: [30, 38, 36, 44, 49, 55, 60, 58, 66, 71, 78, 84], caption: "Pipeline and won/lost velocity across regions." },
  { id: "inventory", label: "Inventory", icon: Package, points: [70, 66, 72, 64, 58, 60, 52, 48, 44, 46, 40, 38], caption: "Stock levels trending to optimal turns." },
  { id: "finance", label: "Finance", icon: Landmark, points: [55, 58, 54, 62, 60, 68, 72, 70, 76, 80, 82, 90], caption: "Cash position and DSO improving monthly." },
  { id: "manufacturing", label: "Manufacturing", icon: Factory, points: [62, 65, 70, 68, 74, 78, 76, 82, 85, 88, 90, 93], caption: "OEE climbing with predictive maintenance." },
  { id: "payroll", label: "Payroll", icon: Banknote, points: [20, 24, 22, 28, 30, 33, 36, 38, 41, 44, 47, 50], caption: "Payroll runs processed — 100% on-time compliance." },
  { id: "assets", label: "Assets", icon: Box, points: [50, 52, 55, 58, 60, 63, 65, 68, 70, 72, 75, 78], caption: "Asset availability trending above 97%." },
  { id: "crm", label: "CRM", icon: Users, points: [35, 40, 44, 48, 52, 57, 61, 65, 70, 74, 79, 85], caption: "Pipeline value and win rate by quarter." },
  { id: "service-desk", label: "Service Desk", icon: Ticket, points: [80, 76, 72, 70, 65, 62, 58, 55, 52, 48, 45, 42], caption: "Open tickets falling as resolution SLA improves." },
  { id: "projects", label: "Projects", icon: FolderKanban, points: [40, 44, 48, 52, 55, 58, 62, 65, 69, 72, 76, 80], caption: "Portfolio health and on-time delivery rate." },
];

export const MOBILE_FEATURES: Array<{ icon: LucideIcon; title: string; desc: string }> = [
  { icon: Smartphone, title: "Android & iOS", desc: "Native-feel mobile apps for field and shop-floor teams." },
  { icon: TabletSmartphone, title: "Tablet & PWA", desc: "Installable PWA with offline-first behavior." },
  { icon: CloudOff, title: "Offline mode", desc: "Capture data without connectivity; sync when back online." },
  { icon: QrCode, title: "QR, Barcode & RFID", desc: "Scan assets, inventory, and documents from any device." },
  { icon: Bell, title: "Push notifications", desc: "Approvals, alerts, and deadlines delivered instantly." },
  { icon: Mic, title: "Voice commands", desc: "Future-ready voice actions for the AI assistant." },
];
export const TESTIMONIALS: Array<{ quote: string; name: string; role: string; company: string }> = [
  { quote: "We replaced four legacy systems with SecureTrack. Finance, production, and fleet now close the month in two days instead of two weeks.", name: "Daniel K.", role: "Group CFO", company: "Manufacturing Group, Uganda" },
  { quote: "The AI assistant writes our executive pack every Monday. It caught a supplier duplicate-payment risk we had missed for quarters.", name: "Amina W.", role: "Finance Director", company: "Distribution Company, Kenya" },
  { quote: "Onboarding took under an hour. Our branches, users, taxes, and workflows were configured automatically from our industry profile.", name: "Peter O.", role: "COO", company: "Retail Chain, Tanzania" },
  { quote: "Tenant isolation and audit trails gave our board total confidence. Every record is traceable to a person, device, and timestamp.", name: "Grace N.", role: "Head of IT", company: "NGO Federation" },
];

export const CASE_STUDIES: Array<{ title: string; industry: string; summary: string; results: string[] }> = [
  { title: "Mid-size manufacturer modernizes end-to-end", industry: "Manufacturing", summary: "MES, quality, inventory, and payroll unified on one platform across three plants.", results: ["OEE +18%", "Scrap -22%", "Month-end close 2 days"] },
  { title: "National retailer unifies 40 stores", industry: "Retail", summary: "POS, inventory, CRM, and finance live across 40 stores with offline resilience.", results: ["Stockouts -35%", "Shrinkage -15%", "Real-time margin"] },
  { title: "Logistics fleet cuts fuel spend", industry: "Logistics", summary: "GPS, dispatch, fuel, and maintenance intelligence across 120 vehicles.", results: ["Fuel -14%", "Deliveries +19%", "POD 100%"] },
];

export const PRICING_PLANS: Array<{
  name: string; monthly: number; annual: number; tagline: string; cta: string;
  users: string; storage: string; ai: string; modules: string; features: string[]; featured?: boolean;
}> = [
  { name: "Starter", monthly: 49, annual: 39, tagline: "For small teams getting started.", cta: "Start Free Trial", users: "Up to 10 users", storage: "50 GB", ai: "1,000 AI credits / mo", modules: "Core: Finance, Inventory, CRM, HR", features: ["1 company / 3 branches", "Core modules", "Email support", "Daily backups", "Mobile app"] },
  { name: "Professional", monthly: 199, annual: 159, tagline: "For growing businesses.", cta: "Start Free Trial", users: "Up to 100 users", storage: "500 GB", ai: "25,000 AI credits / mo", modules: "All core + Procurement, Payroll, Projects", features: ["Multi-company (3)", "All core modules", "AI assistant", "Workflow engine", "API access", "Priority support"], featured: true },
  { name: "Business", monthly: 499, annual: 399, tagline: "For scaling organizations.", cta: "Talk to Sales", users: "Up to 500 users", storage: "2 TB", ai: "100,000 AI credits / mo", modules: "All modules incl. Manufacturing, Fleet, BI", features: ["Multi-company (10)", "All modules", "Advanced AI agents", "Marketplace apps", "SSO / SAML", "Dedicated support"] },
  { name: "Enterprise", monthly: 0, annual: 0, tagline: "For multinationals and governments.", cta: "Contact Sales", users: "Unlimited", storage: "Custom", ai: "Custom", modules: "Everything + private cloud options", features: ["Unlimited everything", "Private / dedicated cloud", "On-premise option", "Custom SLA 99.99%", "Data residency", "Solution architecture"] },
];

export const FAQS: Array<{ q: string; a: string }> = [
  { q: "How fast can we go live?", a: "Most organizations complete the guided onboarding in under an hour for core modules. Industry packs pre-configure workflows, reports, and compliance templates so you start with best practices, not a blank system." },
  { q: "Is our data isolated from other tenants?", a: "Yes. Every business table carries tenant identifiers and is protected by PostgreSQL Row-Level Security. Storage, search, caching, AI context, notifications, and reports are all tenant-scoped. No tenant can ever access another tenant's data." },
  { q: "Can we run SecureTrack on our own infrastructure?", a: "Enterprise plans support private cloud, dedicated cloud, and on-premise deployment. The platform is Docker/Kubernetes-ready and runs on PostgreSQL, so you keep full control of data residency." },
  { q: "Does AI use our data to train models for other customers?", a: "Never. AI context is tenant-isolated, permission-aware, and never used to train shared models. Your data stays yours." },
  { q: "Can we customize without writing code?", a: "Yes. Modules, forms, fields, workflows, approval rules, numbering, dashboards, reports, and automation are all metadata-driven and configurable by administrators without code." },
  { q: "What happens if we exceed plan limits?", a: "You can upgrade instantly or purchase add-ons for users, storage, and AI credits. Usage metering gives you visibility before you hit limits." },
];

export const JOURNEY_STEPS: Array<{ title: string; desc: string; icon: LucideIcon }> = [
  { title: "Discovery", desc: "We map your processes, scale, and compliance needs.", icon: Search },
  { title: "Solution design", desc: "Industry pack, modules, and configuration blueprint.", icon: PencilRuler },
  { title: "Configuration", desc: "Tenant provisioned, modules installed, data mapped.", icon: Settings2 },
  { title: "Migration", desc: "Import customers, inventory, accounts, and balances.", icon: DatabaseBackup },
  { title: "Training", desc: "Admin, manager, and end-user enablement.", icon: GraduationCap },
  { title: "Testing", desc: "UAT, security review, and readiness assessment.", icon: FlaskConical },
  { title: "Go live", desc: "Cutover with monitoring, support, and rollback plan.", icon: Rocket },
  { title: "Optimization", desc: "AI insights, adoption coaching, and continuous improvement.", icon: TrendingUp },
];

export const DEVELOPER_FEATURES: Array<{ icon: LucideIcon; title: string; desc: string }> = [
  { icon: Cpu, title: "REST API", desc: "Versioned, documented REST endpoints with API keys and OAuth." },
  { icon: Share2, title: "GraphQL", desc: "Query exactly the fields you need with tenant-scoped resolvers." },
  { icon: Code2, title: "SDKs & CLI", desc: "TypeScript and Python SDKs plus a CLI for automation." },
  { icon: Puzzle, title: "Extensions", desc: "Build modules and marketplace apps on the metadata platform." },
  { icon: Store, title: "Marketplace SDK", desc: "Package, version, license, and distribute your apps." },
  { icon: Globe2, title: "API explorer", desc: "Interactive, sandboxed explorer with live examples." },
  { icon: FileText, title: "Documentation", desc: "Guides, references, and sample code for every endpoint." },
  { icon: Webhook, title: "Webhooks", desc: "Event-driven callbacks with retries and dead-letter queues." },
  { icon: KeyRound, title: "OAuth 2.0", desc: "Secure delegated access for third-party integrations." },
  { icon: FlaskConical, title: "Sandbox", desc: "Isolated environments for build, test, and staging." },
];

export const LEARNING_ITEMS: Array<{ icon: LucideIcon; title: string; desc: string; href: string }> = [
  { icon: FileText, title: "Documentation", desc: "Guides and references for every module.", href: "/resources" },
  { icon: MessagesSquare, title: "Knowledge base", desc: "Answers and how-tos from real deployments.", href: "/resources" },
  { icon: PlayCircle, title: "Videos", desc: "Product tours and feature walkthroughs.", href: "/resources" },
  { icon: GraduationCap, title: "Academy", desc: "Role-based learning paths and certification.", href: "/resources" },
  { icon: Medal, title: "Certification", desc: "Prove expertise as an admin or partner.", href: "/resources" },
  { icon: Users, title: "Community", desc: "Forums, events, and partner ecosystem.", href: "/partners" },
];

export const FOOTER_LINKS: Array<{ title: string; links: Array<{ label: string; href: string }> }> = [
  { title: "Platform", links: [
    { label: "Solutions", href: "/solutions" },
    { label: "Modules", href: "/modules" },
    { label: "AI Platform", href: "/ai-platform" },
    { label: "Security", href: "/security" },
    { label: "Marketplace", href: "/#marketplace" },
    { label: "Integrations", href: "/#integrations" } ] },
  { title: "Company", links: [
    { label: "About", href: "/company" },
    { label: "Customers", href: "/customers" },
    { label: "Partners", href: "/partners" },
    { label: "Careers", href: "/careers" },
    { label: "Contact", href: "/contact" } ] },
  { title: "Resources", links: [
    { label: "Pricing", href: "/pricing" },
    { label: "Learning center", href: "/resources" },
    { label: "Developers", href: "/developers" },
    { label: "Status", href: "/api/health" },
    { label: "Roadmap", href: "/resources" } ] },
  { title: "Legal", links: [
    { label: "Privacy", href: "/legal/privacy" },
    { label: "Terms", href: "/legal/terms" },
    { label: "Cookies", href: "/legal/cookies" },
    { label: "Compliance", href: "/security" },
    { label: "Security", href: "/security" } ] },
];