import type { LblEntityConfig } from "./types";

function cfg(p: LblEntityConfig): LblEntityConfig {
  return {
    searchCols: p.searchCols || ["code", "name", "title", "status", "template_code", "label_number", "batch_code"],
    ...p,
  };
}

export const LBL_ENTITIES: Record<string, LblEntityConfig> = {
  formats: cfg({
    title: "Label Formats & Sizes",
    description: "Physical label dimensions, DPI and multi-up layouts",
    table: "lbl_formats",
    numberField: "format_code",
    numberPrefix: "FMT",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "format_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "width_mm", label: "W mm" },
      { key: "height_mm", label: "H mm" },
      { key: "dpi", label: "DPI" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "format_code", label: "Code", required: true, autoNumber: "FMT", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "width_mm", label: "Width mm", type: "number", required: true },
      { key: "height_mm", label: "Height mm", type: "number", required: true },
      { key: "orientation", label: "Orientation", type: "select", options: ["portrait", "landscape"] },
      { key: "dpi", label: "DPI", type: "number" },
      { key: "columns", label: "Columns", type: "number" },
      { key: "rows", label: "Rows", type: "number" },
      { key: "gap_mm", label: "Gap mm", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { width_mm: 50, height_mm: 30, dpi: 203, orientation: "portrait", columns: 1, rows: 1, gap_mm: 2, status: "active" },
  }),

  categories: cfg({
    title: "Label Categories",
    description: "Product, shipping, inventory, security families",
    table: "lbl_categories",
    numberField: "category_code",
    numberPrefix: "CAT",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "category_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "label_family", label: "Family" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "category_code", label: "Code", required: true, autoNumber: "CAT", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "label_family", label: "Family", type: "select", options: ["product", "carton", "pallet", "shipping", "shelf", "asset", "security", "id", "compliance", "custom"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
    defaults: { label_family: "product", status: "active" },
  }),

  templates: cfg({
    title: "Label Templates",
    description: "Design templates for product, auth, shipping and inventory labels",
    table: "lbl_templates",
    numberField: "template_code",
    numberPrefix: "TPL",
    statusField: "status",
    statusOptions: ["draft", "active", "retired"],
    columns: [
      { key: "template_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "label_type", label: "Type" },
      { key: "format_code", label: "Format" },
      { key: "barcode_symbology", label: "Barcode" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "template_code", label: "Code", required: true, autoNumber: "TPL", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "category_code", label: "Category" },
      { key: "format_code", label: "Format" },
      { key: "label_type", label: "Type", type: "select", options: ["product", "ream", "carton", "pallet", "shipping", "shelf", "bin", "asset", "security", "auth_qr", "gs1", "custom"] },
      { key: "version", label: "Version", type: "number" },
      { key: "barcode_symbology", label: "Symbology", type: "select", options: ["qr", "code128", "code39", "ean13", "upc", "gs1_128", "pdf417", "datamatrix"] },
      { key: "default_printer_model", label: "Default printer model" },
      { key: "language", label: "Language" },
      { key: "status", label: "Status", type: "select", options: ["draft", "active", "retired"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { label_type: "product", barcode_symbology: "qr", version: 1, language: "en", status: "draft" },
  }),

  fields: cfg({
    title: "Label Field Layout",
    description: "Field positions and data sources on templates",
    table: "lbl_fields",
    numberField: "field_code",
    numberPrefix: "FLD",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "field_code", label: "Code" },
      { key: "template_code", label: "Template" },
      { key: "field_key", label: "Key" },
      { key: "field_type", label: "Type" },
      { key: "x_mm", label: "X" },
      { key: "y_mm", label: "Y" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "field_code", label: "Code", required: true, autoNumber: "FLD", createOnly: true },
      { key: "template_code", label: "Template code" },
      { key: "field_key", label: "Field key", required: true },
      { key: "label_text", label: "Label text" },
      { key: "field_type", label: "Type", type: "select", options: ["text", "number", "date", "barcode", "qr", "image", "logo", "variable"] },
      { key: "data_source", label: "Data source" },
      { key: "x_mm", label: "X mm", type: "number" },
      { key: "y_mm", label: "Y mm", type: "number" },
      { key: "width_mm", label: "Width mm", type: "number" },
      { key: "height_mm", label: "Height mm", type: "number" },
      { key: "font_size", label: "Font size", type: "number" },
      { key: "align", label: "Align", type: "select", options: ["left", "center", "right"] },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { field_type: "text", x_mm: 0, y_mm: 0, width_mm: 20, height_mm: 5, font_size: 10, align: "left", status: "active" },
  }),

  variables: cfg({
    title: "Merge Variables",
    description: "Tokens like {{product_name}} and {{serial}}",
    table: "lbl_variables",
    numberField: "variable_code",
    numberPrefix: "VAR",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "variable_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "token", label: "Token" },
      { key: "sample_value", label: "Sample" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "variable_code", label: "Code", required: true, autoNumber: "VAR", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "token", label: "Token", required: true },
      { key: "default_value", label: "Default" },
      { key: "sample_value", label: "Sample" },
      { key: "data_type", label: "Data type", type: "select", options: ["string", "number", "date", "boolean"] },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { data_type: "string", status: "active" },
  }),

  materials: cfg({
    title: "Label Materials",
    description: "Thermal rolls, vinyl, paper media catalog",
    table: "lbl_materials",
    numberField: "material_code",
    numberPrefix: "MAT",
    statusField: "status",
    statusOptions: ["active", "inactive", "discontinued"],
    columns: [
      { key: "material_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "material_type", label: "Type" },
      { key: "format_code", label: "Format" },
      { key: "roll_qty", label: "Roll qty" },
      { key: "reorder_level", label: "Reorder" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "material_code", label: "Code", required: true, autoNumber: "MAT", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "material_type", label: "Type", type: "select", options: ["thermal", "direct_thermal", "transfer", "paper", "polyester", "vinyl", "fabric"] },
      { key: "format_code", label: "Format" },
      { key: "width_mm", label: "Width mm", type: "number" },
      { key: "height_mm", label: "Height mm", type: "number" },
      { key: "color", label: "Color" },
      { key: "adhesive", label: "Adhesive", type: "select", options: ["permanent", "removable", "freezer", "high_tack"] },
      { key: "roll_qty", label: "Roll qty", type: "number" },
      { key: "reorder_level", label: "Reorder level", type: "number" },
      { key: "unit_cost", label: "Unit cost", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD", "KES"] },
      { key: "supplier_name", label: "Supplier" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive", "discontinued"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { material_type: "direct_thermal", color: "white", adhesive: "permanent", roll_qty: 0, reorder_level: 50, unit_cost: 0, currency: "UGX", status: "active" },
  }),

  stock: cfg({
    title: "Media Stock",
    description: "On-hand label stock by location",
    table: "lbl_stock",
    numberField: "stock_code",
    numberPrefix: "STK",
    statusField: "status",
    statusOptions: ["available", "low", "expired", "quarantine"],
    columns: [
      { key: "stock_code", label: "Code" },
      { key: "material_code", label: "Material" },
      { key: "location_name", label: "Location" },
      { key: "qty_on_hand", label: "Qty" },
      { key: "lot_number", label: "Lot" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "stock_code", label: "Code", required: true, autoNumber: "STK", createOnly: true },
      { key: "material_code", label: "Material code", required: true },
      { key: "location_name", label: "Location" },
      { key: "branch_name", label: "Branch" },
      { key: "qty_on_hand", label: "Qty on hand", type: "number" },
      { key: "qty_reserved", label: "Reserved", type: "number" },
      { key: "lot_number", label: "Lot number" },
      { key: "received_at", label: "Received", type: "date" },
      { key: "expiry_date", label: "Expiry", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["available", "low", "expired", "quarantine"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { qty_on_hand: 0, qty_reserved: 0, status: "available" },
  }),

  barcodes: cfg({
    title: "Barcode Library",
    description: "Symbologies and sample encodings",
    table: "lbl_barcodes",
    numberField: "barcode_code",
    numberPrefix: "BC",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "barcode_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "symbology", label: "Symbology" },
      { key: "sample_value", label: "Sample" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "barcode_code", label: "Code", required: true, autoNumber: "BC", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "symbology", label: "Symbology", type: "select", options: ["qr", "code128", "code39", "ean13", "upc", "gs1_128", "pdf417", "datamatrix", "aztec"] },
      { key: "sample_value", label: "Sample value" },
      { key: "error_correction", label: "ECC", type: "select", options: ["L", "M", "Q", "H"] },
      { key: "module_size", label: "Module size", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { symbology: "qr", error_correction: "M", module_size: 3, status: "active" },
  }),

  gs1: cfg({
    title: "GS1 Configuration",
    description: "GTIN, company prefix and application identifiers",
    table: "lbl_gs1",
    numberField: "gs1_code",
    numberPrefix: "GS1",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "gs1_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "company_prefix", label: "Prefix" },
      { key: "gtin", label: "GTIN" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "gs1_code", label: "Code", required: true, autoNumber: "GS1", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "company_prefix", label: "Company prefix" },
      { key: "gtin", label: "GTIN" },
      { key: "ai_list", label: "AI list" },
      { key: "application_identifier", label: "Primary AI" },
      { key: "serial_ai", label: "Serial AI" },
      { key: "lot_ai", label: "Lot AI" },
      { key: "expiry_ai", label: "Expiry AI" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { serial_ai: "21", lot_ai: "10", expiry_ai: "17", status: "active" },
  }),

  security: cfg({
    title: "Security Features",
    description: "Watermark, microtext, hologram, signed QR",
    table: "lbl_security",
    numberField: "security_code",
    numberPrefix: "SEC",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "security_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "feature_type", label: "Feature" },
      { key: "intensity", label: "Intensity" },
      { key: "template_code", label: "Template" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "security_code", label: "Code", required: true, autoNumber: "SEC", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "feature_type", label: "Feature", type: "select", options: ["watermark", "microtext", "hologram", "void_panel", "uv", "serial_crypto", "checksum", "qr_signed"] },
      { key: "intensity", label: "Intensity", type: "select", options: ["low", "medium", "high"] },
      { key: "template_code", label: "Template" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { feature_type: "watermark", intensity: "medium", status: "active" },
  }),

  rules: cfg({
    title: "Automation Rules",
    description: "Auto-generate and print labels from ERP events",
    table: "lbl_rules",
    numberField: "rule_code",
    numberPrefix: "RULE",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "rule_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "trigger_event", label: "Trigger" },
      { key: "template_code", label: "Template" },
      { key: "copies", label: "Copies" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "rule_code", label: "Code", required: true, autoNumber: "RULE", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "trigger_event", label: "Trigger", type: "select", options: ["batch_complete", "order_confirm", "grn", "shipment", "asset_create", "manual"] },
      { key: "template_code", label: "Template" },
      { key: "label_type", label: "Label type", type: "select", options: ["product", "carton", "pallet", "shipping", "shelf", "auth_qr"] },
      { key: "printer_name", label: "Printer" },
      { key: "copies", label: "Copies", type: "number" },
      { key: "priority", label: "Priority", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { trigger_event: "batch_complete", label_type: "product", copies: 1, priority: 100, status: "active" },
  }),

  batches: cfg({
    title: "Label Batches",
    description: "High-volume label generation runs",
    table: "lbl_batches",
    numberField: "batch_code",
    numberPrefix: "LB",
    statusField: "status",
    statusOptions: ["draft", "ready", "printing", "paused", "completed", "failed", "cancelled"],
    columns: [
      { key: "batch_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "label_type", label: "Type" },
      { key: "quantity", label: "Qty" },
      { key: "printed_count", label: "Printed" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "batch_code", label: "Code", required: true, autoNumber: "LB", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "template_code", label: "Template" },
      { key: "format_code", label: "Format" },
      { key: "material_code", label: "Material" },
      { key: "label_type", label: "Type", type: "select", options: ["product", "ream", "carton", "pallet", "shipping", "auth_qr", "shelf"] },
      { key: "product_code", label: "Product code" },
      { key: "product_name", label: "Product name" },
      { key: "production_batch", label: "Production batch" },
      { key: "quantity", label: "Quantity", type: "number" },
      { key: "start_serial", label: "Start serial" },
      { key: "end_serial", label: "End serial" },
      { key: "printer_name", label: "Printer" },
      { key: "requested_by_name", label: "Requested by" },
      { key: "status", label: "Status", type: "select", options: ["draft", "ready", "printing", "paused", "completed", "failed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { label_type: "product", quantity: 0, printed_count: 0, failed_count: 0, status: "draft" },
  }),

  instances: cfg({
    title: "Label Instances",
    description: "Individual printed/ready labels with serials",
    table: "lbl_instances",
    numberField: "label_number",
    numberPrefix: "LBL",
    statusField: "status",
    statusOptions: ["ready", "printed", "void", "recalled", "archived"],
    columns: [
      { key: "label_number", label: "Label #" },
      { key: "serial_number", label: "Serial" },
      { key: "product_code", label: "SKU" },
      { key: "label_type", label: "Type" },
      { key: "print_count", label: "Prints" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "label_number", label: "Label number", required: true, autoNumber: "LBL", createOnly: true },
      { key: "batch_code", label: "Batch" },
      { key: "template_code", label: "Template" },
      { key: "label_type", label: "Type", type: "select", options: ["product", "ream", "carton", "pallet", "shipping", "shelf", "auth_qr"] },
      { key: "serial_number", label: "Serial" },
      { key: "barcode_value", label: "Barcode value" },
      { key: "qr_payload", label: "QR payload", type: "textarea" },
      { key: "product_code", label: "Product code" },
      { key: "product_name", label: "Product name" },
      { key: "lot_number", label: "Lot" },
      { key: "mfg_date", label: "Mfg date", type: "date" },
      { key: "expiry_date", label: "Expiry", type: "date" },
      { key: "verification_status", label: "Verification", type: "select", options: ["unverified", "valid", "invalid", "recalled"] },
      { key: "status", label: "Status", type: "select", options: ["ready", "printed", "void", "recalled", "archived"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { label_type: "product", print_count: 0, verification_status: "unverified", status: "ready" },
  }),

  jobs: cfg({
    title: "Label Print Jobs",
    description: "Queue of label print jobs",
    table: "lbl_jobs",
    numberField: "job_code",
    numberPrefix: "JOB",
    statusField: "status",
    statusOptions: ["queued", "sending", "printing", "completed", "failed", "cancelled"],
    columns: [
      { key: "job_code", label: "Job #" },
      { key: "batch_code", label: "Batch" },
      { key: "printer_name", label: "Printer" },
      { key: "label_count", label: "Labels" },
      { key: "priority", label: "Pri" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "job_code", label: "Job code", required: true, autoNumber: "JOB", createOnly: true },
      { key: "batch_code", label: "Batch" },
      { key: "template_code", label: "Template" },
      { key: "printer_name", label: "Printer" },
      { key: "copies", label: "Copies", type: "number" },
      { key: "label_count", label: "Label count", type: "number" },
      { key: "priority", label: "Priority", type: "number" },
      { key: "requested_by_name", label: "Requested by" },
      { key: "error_message", label: "Error", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["queued", "sending", "printing", "completed", "failed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { copies: 1, label_count: 0, priority: 5, status: "queued" },
  }),

  reprints: cfg({
    title: "Reprint Requests",
    description: "Controlled reprint workflow with approval",
    table: "lbl_reprints",
    numberField: "reprint_code",
    numberPrefix: "RP",
    statusField: "status",
    statusOptions: ["pending", "approved", "printed", "rejected"],
    columns: [
      { key: "reprint_code", label: "Code" },
      { key: "label_number", label: "Label" },
      { key: "reason", label: "Reason" },
      { key: "copies", label: "Copies" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "reprint_code", label: "Code", required: true, autoNumber: "RP", createOnly: true },
      { key: "label_number", label: "Label number" },
      { key: "batch_code", label: "Batch" },
      { key: "reason", label: "Reason" },
      { key: "requested_by_name", label: "Requested by" },
      { key: "approved_by_name", label: "Approved by" },
      { key: "copies", label: "Copies", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["pending", "approved", "printed", "rejected"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { copies: 1, status: "pending" },
  }),

  approvals: cfg({
    title: "Label Approvals",
    description: "Template, reprint and void approvals",
    table: "lbl_approvals",
    numberField: "approval_code",
    numberPrefix: "AP",
    statusField: "status",
    statusOptions: ["open", "closed"],
    columns: [
      { key: "approval_code", label: "Code" },
      { key: "approval_type", label: "Type" },
      { key: "related_code", label: "Related" },
      { key: "decision", label: "Decision" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "approval_code", label: "Code", required: true, autoNumber: "AP", createOnly: true },
      { key: "approval_type", label: "Type", type: "select", options: ["template", "reprint", "batch", "security", "void"] },
      { key: "related_code", label: "Related code" },
      { key: "requested_by_name", label: "Requested by" },
      { key: "approver_name", label: "Approver" },
      { key: "decision", label: "Decision", type: "select", options: ["pending", "approved", "rejected"] },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["open", "closed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { approval_type: "reprint", decision: "pending", status: "open" },
  }),

  shipping: cfg({
    title: "Shipping Labels",
    description: "Carrier and consignment shipping labels",
    table: "lbl_shipping",
    numberField: "shipping_code",
    numberPrefix: "SHP",
    statusField: "status",
    statusOptions: ["ready", "printed", "shipped", "void"],
    columns: [
      { key: "shipping_code", label: "Code" },
      { key: "order_number", label: "Order" },
      { key: "customer_name", label: "Customer" },
      { key: "carrier_name", label: "Carrier" },
      { key: "tracking_number", label: "Tracking" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "shipping_code", label: "Code", required: true, autoNumber: "SHP", createOnly: true },
      { key: "order_number", label: "Order number" },
      { key: "consignment_number", label: "Consignment" },
      { key: "customer_name", label: "Customer" },
      { key: "ship_to_address", label: "Ship-to", type: "textarea" },
      { key: "carrier_name", label: "Carrier" },
      { key: "tracking_number", label: "Tracking" },
      { key: "weight_kg", label: "Weight kg", type: "number" },
      { key: "packages", label: "Packages", type: "number" },
      { key: "barcode_value", label: "Barcode" },
      { key: "status", label: "Status", type: "select", options: ["ready", "printed", "shipped", "void"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { weight_kg: 0, packages: 1, status: "ready" },
  }),

  pallet: cfg({
    title: "Pallet Labels",
    description: "SSCC and pallet identity labels",
    table: "lbl_pallet",
    numberField: "pallet_code",
    numberPrefix: "PLT",
    statusField: "status",
    statusOptions: ["ready", "printed", "shipped", "void"],
    columns: [
      { key: "pallet_code", label: "Code" },
      { key: "sscc", label: "SSCC" },
      { key: "product_code", label: "SKU" },
      { key: "carton_count", label: "Cartons" },
      { key: "warehouse_code", label: "WH" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "pallet_code", label: "Code", required: true, autoNumber: "PLT", createOnly: true },
      { key: "sscc", label: "SSCC" },
      { key: "product_code", label: "Product code" },
      { key: "product_name", label: "Product name" },
      { key: "carton_count", label: "Carton count", type: "number" },
      { key: "unit_count", label: "Unit count", type: "number" },
      { key: "weight_kg", label: "Weight kg", type: "number" },
      { key: "warehouse_code", label: "Warehouse" },
      { key: "location_code", label: "Location" },
      { key: "barcode_value", label: "Barcode" },
      { key: "status", label: "Status", type: "select", options: ["ready", "printed", "shipped", "void"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { carton_count: 0, unit_count: 0, weight_kg: 0, status: "ready" },
  }),

  shelf: cfg({
    title: "Shelf / Bin Labels",
    description: "Warehouse aisle-rack-bin location labels",
    table: "lbl_shelf",
    numberField: "shelf_code",
    numberPrefix: "SHF",
    statusField: "status",
    statusOptions: ["active", "inactive", "printed"],
    columns: [
      { key: "shelf_code", label: "Code" },
      { key: "warehouse_code", label: "WH" },
      { key: "aisle", label: "Aisle" },
      { key: "rack", label: "Rack" },
      { key: "bin", label: "Bin" },
      { key: "product_code", label: "SKU" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "shelf_code", label: "Code", required: true, autoNumber: "SHF", createOnly: true },
      { key: "warehouse_code", label: "Warehouse" },
      { key: "aisle", label: "Aisle" },
      { key: "rack", label: "Rack" },
      { key: "bin", label: "Bin" },
      { key: "product_code", label: "Product code" },
      { key: "product_name", label: "Product name" },
      { key: "barcode_value", label: "Barcode" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive", "printed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active" },
  }),

  compliance: cfg({
    title: "Compliance Labels",
    description: "Regulatory required fields and templates",
    table: "lbl_compliance",
    numberField: "compliance_code",
    numberPrefix: "CMP",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "compliance_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "regulation", label: "Regulation" },
      { key: "template_code", label: "Template" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "compliance_code", label: "Code", required: true, autoNumber: "CMP", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "regulation", label: "Regulation", type: "select", options: ["UNBS", "KEBS", "SON", "FDA", "ISO", "CE", "custom"] },
      { key: "required_fields", label: "Required fields" },
      { key: "template_code", label: "Template" },
      { key: "product_category", label: "Product category" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { regulation: "UNBS", status: "active" },
  }),

  "printer-profiles": cfg({
    title: "Printer Profiles",
    description: "Darkness, speed, DPI profiles per device",
    table: "lbl_printer_profiles",
    numberField: "profile_code",
    numberPrefix: "PP",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "profile_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "brand", label: "Brand" },
      { key: "model", label: "Model" },
      { key: "dpi", label: "DPI" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "profile_code", label: "Code", required: true, autoNumber: "PP", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "printer_name", label: "Printer name" },
      { key: "brand", label: "Brand", type: "select", options: ["Niimbot", "Zebra", "TSC", "Honeywell", "Brother", "Godex", "SATO", "Other"] },
      { key: "model", label: "Model" },
      { key: "connection_type", label: "Connection", type: "select", options: ["bluetooth", "usb", "network", "system"] },
      { key: "default_format_code", label: "Default format" },
      { key: "darkness", label: "Darkness", type: "number" },
      { key: "speed", label: "Speed", type: "number" },
      { key: "dpi", label: "DPI", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { connection_type: "bluetooth", darkness: 8, speed: 4, dpi: 203, status: "active" },
  }),

  product: cfg({
    title: "Product Labels",
    description: "Product / ream auth labels (instances filtered view)",
    table: "lbl_instances",
    numberField: "label_number",
    numberPrefix: "LBL",
    statusField: "status",
    statusOptions: ["ready", "printed", "void", "recalled", "archived"],
    columns: [
      { key: "label_number", label: "Label #" },
      { key: "serial_number", label: "Serial" },
      { key: "product_name", label: "Product" },
      { key: "lot_number", label: "Lot" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "label_number", label: "Label number", required: true, autoNumber: "LBL", createOnly: true },
      { key: "label_type", label: "Type", type: "select", options: ["product", "ream", "auth_qr"] },
      { key: "serial_number", label: "Serial" },
      { key: "product_code", label: "Product code" },
      { key: "product_name", label: "Product name" },
      { key: "lot_number", label: "Lot" },
      { key: "qr_payload", label: "QR payload", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["ready", "printed", "void", "recalled", "archived"] },
    ],
    defaults: { label_type: "product", status: "ready" },
  }),

  carton: cfg({
    title: "Carton Labels",
    description: "Outer carton identification labels",
    table: "lbl_instances",
    numberField: "label_number",
    numberPrefix: "CTN",
    statusField: "status",
    statusOptions: ["ready", "printed", "void", "recalled", "archived"],
    columns: [
      { key: "label_number", label: "Label #" },
      { key: "serial_number", label: "Serial" },
      { key: "product_code", label: "SKU" },
      { key: "barcode_value", label: "Barcode" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "label_number", label: "Label number", required: true, autoNumber: "CTN", createOnly: true },
      { key: "label_type", label: "Type", type: "select", options: ["carton"] },
      { key: "serial_number", label: "Serial" },
      { key: "product_code", label: "Product code" },
      { key: "product_name", label: "Product name" },
      { key: "barcode_value", label: "Barcode" },
      { key: "status", label: "Status", type: "select", options: ["ready", "printed", "void"] },
    ],
    defaults: { label_type: "carton", status: "ready" },
  }),

  documents: cfg({
    title: "Label Documents",
    description: "Artwork, specs and SOPs",
    table: "lbl_documents",
    numberField: "doc_code",
    numberPrefix: "DOC",
    statusField: "status",
    statusOptions: ["active", "archived", "draft"],
    columns: [
      { key: "doc_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "doc_type", label: "Type" },
      { key: "version", label: "Ver" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "doc_code", label: "Code", required: true, autoNumber: "DOC", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "doc_type", label: "Type", type: "select", options: ["spec", "artwork", "approval", "sop", "other"] },
      { key: "related_code", label: "Related code" },
      { key: "file_url", label: "File URL" },
      { key: "version", label: "Version", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "archived", "draft"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { doc_type: "spec", version: 1, status: "active" },
  }),

  notifications: cfg({
    title: "Label Notifications",
    description: "Stock and print alerts",
    table: "lbl_notifications",
    numberField: "notif_code",
    numberPrefix: "NT",
    statusField: "status",
    statusOptions: ["unread", "read", "archived"],
    columns: [
      { key: "notif_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "severity", label: "Severity" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "notif_code", label: "Code", required: true, autoNumber: "NT", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "body", label: "Body", type: "textarea" },
      { key: "severity", label: "Severity", type: "select", options: ["info", "warning", "critical"] },
      { key: "related_type", label: "Related type" },
      { key: "related_code", label: "Related code" },
      { key: "status", label: "Status", type: "select", options: ["unread", "read", "archived"] },
    ],
    defaults: { severity: "info", status: "unread" },
  }),

  settings: cfg({
    title: "Label Settings",
    description: "Company label configuration",
    table: "lbl_settings",
    numberField: "setting_key",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    searchCols: ["setting_key", "setting_value", "category", "description"],
    columns: [
      { key: "setting_key", label: "Key" },
      { key: "setting_value", label: "Value" },
      { key: "category", label: "Category" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "setting_key", label: "Key", required: true },
      { key: "setting_value", label: "Value", required: true },
      { key: "category", label: "Category", type: "select", options: ["general", "barcode", "security", "print", "stock"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
    defaults: { category: "general", status: "active" },
  }),

  audit: cfg({
    title: "Label Audit Log",
    description: "Create/update/print audit trail",
    table: "lbl_audit_log",
    columns: [
      { key: "action", label: "Action" },
      { key: "entity_table", label: "Table" },
      { key: "entity_code", label: "Code" },
      { key: "details", label: "Details" },
      { key: "created_at", label: "When" },
    ],
    fields: [
      { key: "action", label: "Action", required: true },
      { key: "entity_table", label: "Entity table" },
      { key: "entity_code", label: "Entity code" },
      { key: "details", label: "Details", type: "textarea" },
    ],
  }),

  insights: cfg({
    title: "Label Insights",
    description: "Stored operational insights",
    table: "lbl_ai_insights",
    numberField: "insight_code",
    numberPrefix: "AI",
    statusField: "status",
    statusOptions: ["open", "acknowledged", "closed"],
    columns: [
      { key: "insight_code", label: "Code" },
      { key: "insight_type", label: "Type" },
      { key: "title", label: "Title" },
      { key: "severity", label: "Severity" },
      { key: "score", label: "Score" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "insight_code", label: "Code", required: true, autoNumber: "AI", createOnly: true },
      { key: "insight_type", label: "Type", required: true },
      { key: "title", label: "Title", required: true },
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "severity", label: "Severity", type: "select", options: ["info", "low", "medium", "high", "critical"] },
      { key: "score", label: "Score", type: "number" },
      { key: "recommendations", label: "Recommendations", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["open", "acknowledged", "closed"] },
    ],
    defaults: { severity: "medium", status: "open", score: 50 },
  }),

  reports: cfg({
    title: "Label Reports Feed",
    description: "Insight store used for operational reports",
    table: "lbl_ai_insights",
    numberField: "insight_code",
    numberPrefix: "RPT",
    statusField: "status",
    statusOptions: ["open", "acknowledged", "closed"],
    columns: [
      { key: "insight_type", label: "Type" },
      { key: "title", label: "Title" },
      { key: "severity", label: "Severity" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "insight_code", label: "Code", required: true, autoNumber: "RPT", createOnly: true },
      { key: "insight_type", label: "Type", required: true },
      { key: "title", label: "Title", required: true },
      { key: "summary", label: "Body", type: "textarea" },
      { key: "severity", label: "Severity", type: "select", options: ["info", "low", "medium", "high"] },
      { key: "status", label: "Status", type: "select", options: ["open", "acknowledged", "closed"] },
    ],
    defaults: { severity: "medium", status: "open" },
  }),

  analytics: cfg({
    title: "Label Analytics",
    description: "AI insight feed for analytics",
    table: "lbl_ai_insights",
    numberField: "insight_code",
    numberPrefix: "AN",
    statusField: "status",
    statusOptions: ["open", "acknowledged", "closed"],
    columns: [
      { key: "insight_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "score", label: "Score" },
      { key: "severity", label: "Severity" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "insight_code", label: "Code", required: true, autoNumber: "AN", createOnly: true },
      { key: "insight_type", label: "Type", required: true },
      { key: "title", label: "Title", required: true },
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "score", label: "Score", type: "number" },
      { key: "severity", label: "Severity", type: "select", options: ["info", "low", "medium", "high"] },
      { key: "status", label: "Status", type: "select", options: ["open", "acknowledged", "closed"] },
    ],
    defaults: { severity: "medium", status: "open", score: 50 },
  }),
};

export const LBL_ENTITY_ALIASES: Record<string, string> = {};

export function resolveLblEntityConfig(
  slug: string
): (typeof LBL_ENTITIES)[string] | null {
  const key = LBL_ENTITY_ALIASES[slug] || slug;
  return LBL_ENTITIES[key] ?? null;
}

export function listLblEntityTables(): string[] {
  return [...new Set(Object.values(LBL_ENTITIES).map((c) => c.table))];
}
