import type { TaEntityConfig } from "./types";

function cfg(p: TaEntityConfig): TaEntityConfig {
  return {
    searchCols: p.searchCols || [
      "code", "name", "title", "status", "candidate_name", "vacancy_code",
      "application_number", "requisition_number", "email",
    ],
    ...p,
  };
}

export const TA_ENTITIES: Record<string, TaEntityConfig> = {
  headcount: cfg({
    title: "Headcount plans",
    description: "Strategic workforce and headcount planning by department",
    table: "ta_headcount_plans",
    numberField: "plan_code",
    numberPrefix: "HC",
    statusField: "status",
    statusOptions: ["draft", "approved", "closed"],
    columns: [
      { key: "plan_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "department", label: "Dept" },
      { key: "approved_headcount", label: "Approved" },
      { key: "open_positions", label: "Open" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "plan_code", label: "Code", required: true, autoNumber: "HC", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "fiscal_year", label: "Fiscal year", type: "number" },
      { key: "department", label: "Department" },
      { key: "branch_name", label: "Branch" },
      { key: "country", label: "Country" },
      { key: "approved_headcount", label: "Approved HC", type: "number" },
      { key: "current_headcount", label: "Current HC", type: "number" },
      { key: "open_positions", label: "Open positions", type: "number" },
      { key: "budget_amount", label: "Budget", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD", "KES"] },
      { key: "owner_name", label: "Owner" },
      { key: "status", label: "Status", type: "select", options: ["draft", "approved", "closed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "draft", currency: "UGX", country: "Uganda", fiscal_year: new Date().getFullYear() },
  }),

  requisitions: cfg({
    title: "Recruitment requests",
    description: "Requisitions with multi-level approval",
    table: "ta_requisitions",
    numberField: "requisition_number",
    numberPrefix: "REQ",
    statusField: "status",
    statusOptions: ["open", "filled", "cancelled", "on_hold"],
    columns: [
      { key: "requisition_number", label: "Number" },
      { key: "title", label: "Title" },
      { key: "department", label: "Dept" },
      { key: "headcount", label: "HC" },
      { key: "approval_status", label: "Approval" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "requisition_number", label: "Number", required: true, autoNumber: "REQ", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "department", label: "Department" },
      { key: "branch_name", label: "Branch" },
      { key: "job_family", label: "Job family" },
      { key: "employment_type", label: "Type", type: "select", options: ["permanent", "contract", "temporary", "intern", "consultant"] },
      { key: "headcount", label: "Headcount", type: "number" },
      { key: "priority", label: "Priority", type: "select", options: ["low", "normal", "high", "critical"] },
      { key: "justification", label: "Justification", type: "textarea" },
      { key: "budget_amount", label: "Budget", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "requested_by_name", label: "Requested by" },
      { key: "hiring_manager_name", label: "Hiring manager" },
      { key: "approval_status", label: "Approval", type: "select", options: ["pending", "approved", "rejected", "cancelled"] },
      { key: "target_start_date", label: "Target start", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["open", "filled", "cancelled", "on_hold"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { employment_type: "permanent", headcount: 1, priority: "normal", approval_status: "pending", status: "open", currency: "UGX" },
  }),

  positions: cfg({
    title: "Position management",
    description: "Organization positions and salary bands",
    table: "ta_positions",
    numberField: "position_code",
    numberPrefix: "POS",
    statusField: "status",
    statusOptions: ["open", "filled", "frozen", "closed"],
    columns: [
      { key: "position_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "department", label: "Dept" },
      { key: "grade", label: "Grade" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "position_code", label: "Code", required: true, autoNumber: "POS", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "department", label: "Department" },
      { key: "grade", label: "Grade" },
      { key: "reports_to", label: "Reports to" },
      { key: "employment_type", label: "Type", type: "select", options: ["permanent", "contract", "temporary", "intern"] },
      { key: "min_salary", label: "Min salary", type: "number" },
      { key: "max_salary", label: "Max salary", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "location_name", label: "Location" },
      { key: "fte", label: "FTE", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["open", "filled", "frozen", "closed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "open", currency: "UGX", fte: 1, employment_type: "permanent" },
  }),

  "job-library": cfg({
    title: "Job library",
    description: "Reusable job descriptions and competency profiles",
    table: "ta_job_library",
    numberField: "job_code",
    numberPrefix: "JOB",
    statusField: "status",
    statusOptions: ["active", "inactive", "archived"],
    columns: [
      { key: "job_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "family", label: "Family" },
      { key: "level", label: "Level" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "job_code", label: "Code", required: true, autoNumber: "JOB", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "family", label: "Family" },
      { key: "level", label: "Level" },
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "responsibilities", label: "Responsibilities", type: "textarea" },
      { key: "requirements", label: "Requirements", type: "textarea" },
      { key: "skills", label: "Skills", type: "textarea" },
      { key: "education", label: "Education" },
      { key: "experience_years", label: "Experience years", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive", "archived"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", experience_years: 0 },
  }),

  vacancies: cfg({
    title: "Vacancies",
    description: "Published and draft job openings",
    table: "ta_vacancies",
    numberField: "vacancy_code",
    numberPrefix: "VAC",
    statusField: "status",
    statusOptions: ["draft", "open", "on_hold", "closed", "cancelled", "filled"],
    columns: [
      { key: "vacancy_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "department", label: "Dept" },
      { key: "location_name", label: "Location" },
      { key: "positions", label: "Slots" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "vacancy_code", label: "Code", required: true, autoNumber: "VAC", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "department", label: "Department" },
      { key: "branch_name", label: "Branch" },
      { key: "location_name", label: "Location" },
      { key: "country", label: "Country" },
      { key: "employment_type", label: "Employment", type: "select", options: ["permanent", "contract", "temporary", "intern"] },
      { key: "work_mode", label: "Work mode", type: "select", options: ["onsite", "hybrid", "remote"] },
      { key: "positions", label: "Positions", type: "number" },
      { key: "salary_min", label: "Salary min", type: "number" },
      { key: "salary_max", label: "Salary max", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "requirements", label: "Requirements", type: "textarea" },
      { key: "benefits", label: "Benefits", type: "textarea" },
      { key: "application_deadline", label: "Deadline", type: "date" },
      { key: "hiring_manager_name", label: "Hiring manager" },
      { key: "recruiter_name", label: "Recruiter" },
      { key: "status", label: "Status", type: "select", options: ["draft", "open", "on_hold", "closed", "cancelled", "filled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: {
      status: "draft",
      employment_type: "permanent",
      work_mode: "onsite",
      positions: 1,
      currency: "UGX",
      country: "Uganda",
    },
  }),

  stages: cfg({
    title: "Pipeline stages",
    description: "Configurable ATS stages",
    table: "ta_pipeline_stages",
    numberField: "stage_code",
    numberPrefix: "STG",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "stage_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "sort_order", label: "Order" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "stage_code", label: "Code", required: true },
      { key: "name", label: "Name", required: true },
      { key: "sort_order", label: "Sort order", type: "number" },
      { key: "color", label: "Color" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { sort_order: 100, status: "active", color: "slate" },
  }),

  candidates: cfg({
    title: "Candidate database",
    description: "Talent profiles and resume inventory",
    table: "ta_candidates",
    numberField: "candidate_number",
    numberPrefix: "CND",
    statusField: "status",
    statusOptions: ["active", "inactive", "blacklisted", "hired"],
    columns: [
      { key: "candidate_number", label: "Number" },
      { key: "first_name", label: "First" },
      { key: "last_name", label: "Last" },
      { key: "email", label: "Email" },
      { key: "source", label: "Source" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "candidate_number", label: "Number", required: true, autoNumber: "CND", createOnly: true },
      { key: "first_name", label: "First name", required: true },
      { key: "last_name", label: "Last name", required: true },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "country", label: "Country" },
      { key: "city", label: "City" },
      { key: "current_title", label: "Current title" },
      { key: "current_employer", label: "Employer" },
      { key: "years_experience", label: "Years exp", type: "number" },
      { key: "education_level", label: "Education" },
      { key: "skills", label: "Skills", type: "textarea" },
      { key: "source", label: "Source", type: "select", options: ["careers_portal", "referral", "agency", "campus", "linkedin", "internal", "walk_in"] },
      { key: "resume_url", label: "Resume URL" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive", "blacklisted", "hired"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", source: "careers_portal", country: "Uganda", years_experience: 0 },
  }),

  applications: cfg({
    title: "Applications (ATS)",
    description: "Application lifecycle records",
    table: "ta_applications",
    numberField: "application_number",
    numberPrefix: "APP",
    statusField: "status",
    statusOptions: ["open", "hired", "rejected", "withdrawn", "on_hold"],
    columns: [
      { key: "application_number", label: "Number" },
      { key: "candidate_name", label: "Candidate" },
      { key: "vacancy_title", label: "Vacancy" },
      { key: "stage_code", label: "Stage" },
      { key: "match_score", label: "Match" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "application_number", label: "Number", required: true, autoNumber: "APP", createOnly: true },
      { key: "vacancy_code", label: "Vacancy code" },
      { key: "vacancy_title", label: "Vacancy title" },
      { key: "candidate_number", label: "Candidate number" },
      { key: "candidate_name", label: "Candidate name", required: true },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "stage_code", label: "Stage", type: "select", options: ["applied", "screen", "shortlist", "assessment", "interview", "background", "offer", "hired", "rejected"] },
      { key: "stage_name", label: "Stage name" },
      { key: "match_score", label: "Match score", type: "number" },
      { key: "ai_summary", label: "AI summary", type: "textarea" },
      { key: "source", label: "Source", type: "select", options: ["careers_portal", "referral", "agency", "campus", "internal"] },
      { key: "recruiter_name", label: "Recruiter" },
      { key: "status", label: "Status", type: "select", options: ["open", "hired", "rejected", "withdrawn", "on_hold"] },
      { key: "reject_reason", label: "Reject reason", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { stage_code: "applied", stage_name: "Applied", status: "open", source: "careers_portal", match_score: 0 },
  }),

  "talent-pool": cfg({
    title: "Talent pool",
    description: "Passive and active talent community",
    table: "ta_talent_pool",
    numberField: "pool_code",
    numberPrefix: "POOL",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "pool_code", label: "Code" },
      { key: "candidate_name", label: "Candidate" },
      { key: "interest_area", label: "Interest" },
      { key: "availability", label: "Availability" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "pool_code", label: "Code", required: true, autoNumber: "POOL", createOnly: true },
      { key: "candidate_number", label: "Candidate number" },
      { key: "candidate_name", label: "Candidate name", required: true },
      { key: "skills", label: "Skills", type: "textarea" },
      { key: "interest_area", label: "Interest area" },
      { key: "availability", label: "Availability", type: "select", options: ["active", "passive", "not_looking"] },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { availability: "passive", status: "active" },
  }),

  referrals: cfg({
    title: "Employee referrals",
    description: "Referral program tracking and rewards",
    table: "ta_referrals",
    numberField: "referral_code",
    numberPrefix: "REF",
    statusField: "status",
    statusOptions: ["submitted", "interviewing", "hired", "paid", "rejected"],
    columns: [
      { key: "referral_code", label: "Code" },
      { key: "employee_name", label: "Employee" },
      { key: "candidate_name", label: "Candidate" },
      { key: "vacancy_title", label: "Vacancy" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "referral_code", label: "Code", required: true, autoNumber: "REF", createOnly: true },
      { key: "employee_name", label: "Employee", required: true },
      { key: "candidate_name", label: "Candidate", required: true },
      { key: "vacancy_title", label: "Vacancy" },
      { key: "reward_amount", label: "Reward", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "status", label: "Status", type: "select", options: ["submitted", "interviewing", "hired", "paid", "rejected"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "submitted", currency: "UGX", reward_amount: 0 },
  }),

  agencies: cfg({
    title: "Recruitment agencies",
    description: "External agency partners",
    table: "ta_agencies",
    numberField: "agency_code",
    numberPrefix: "AGY",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "agency_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "contact_name", label: "Contact" },
      { key: "fee_pct", label: "Fee %" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "agency_code", label: "Code", required: true, autoNumber: "AGY", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "contact_name", label: "Contact" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "fee_pct", label: "Fee %", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", fee_pct: 0 },
  }),

  campus: cfg({
    title: "Campus recruitment",
    description: "University and campus hiring events",
    table: "ta_campus_events",
    numberField: "event_code",
    numberPrefix: "CMP",
    statusField: "status",
    statusOptions: ["planned", "active", "completed", "cancelled"],
    columns: [
      { key: "event_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "institution", label: "Institution" },
      { key: "event_date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "event_code", label: "Code", required: true, autoNumber: "CMP", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "institution", label: "Institution" },
      { key: "event_date", label: "Date", type: "date" },
      { key: "location_name", label: "Location" },
      { key: "candidates_reached", label: "Reached", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["planned", "active", "completed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "planned", candidates_reached: 0 },
  }),

  assessments: cfg({
    title: "Assessments",
    description: "Tests and evaluation instruments",
    table: "ta_assessments",
    numberField: "assessment_code",
    numberPrefix: "ASM",
    statusField: "status",
    statusOptions: ["active", "inactive", "archived"],
    columns: [
      { key: "assessment_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "assessment_type", label: "Type" },
      { key: "duration_minutes", label: "Mins" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "assessment_code", label: "Code", required: true, autoNumber: "ASM", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "assessment_type", label: "Type", type: "select", options: ["technical", "coding", "manufacturing", "accounting", "hr", "psychometric", "aptitude", "personality", "language", "essay", "practical", "video"] },
      { key: "duration_minutes", label: "Duration (min)", type: "number" },
      { key: "pass_score", label: "Pass score", type: "number" },
      { key: "vacancy_code", label: "Vacancy code" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive", "archived"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { assessment_type: "aptitude", duration_minutes: 60, pass_score: 50, status: "active" },
  }),

  "assessment-attempts": cfg({
    title: "Assessment attempts",
    description: "Candidate assessment invitations and scores",
    table: "ta_assessment_attempts",
    numberField: "attempt_code",
    numberPrefix: "ATT",
    statusField: "status",
    statusOptions: ["invited", "in_progress", "completed", "expired", "cancelled"],
    columns: [
      { key: "attempt_code", label: "Code" },
      { key: "candidate_name", label: "Candidate" },
      { key: "assessment_code", label: "Assessment" },
      { key: "score", label: "Score" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "attempt_code", label: "Code", required: true, autoNumber: "ATT", createOnly: true },
      { key: "assessment_code", label: "Assessment code" },
      { key: "application_number", label: "Application #" },
      { key: "candidate_name", label: "Candidate" },
      { key: "score", label: "Score", type: "number" },
      { key: "max_score", label: "Max score", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["invited", "in_progress", "completed", "expired", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "invited", score: 0, max_score: 100 },
  }),

  interviews: cfg({
    title: "Interview management",
    description: "Scheduling, panels, and recommendations",
    table: "ta_interviews",
    numberField: "interview_code",
    numberPrefix: "INT",
    statusField: "status",
    statusOptions: ["scheduled", "completed", "cancelled", "no_show", "rescheduled"],
    columns: [
      { key: "interview_code", label: "Code" },
      { key: "candidate_name", label: "Candidate" },
      { key: "interview_type", label: "Type" },
      { key: "scheduled_at", label: "When" },
      { key: "recommendation", label: "Rec" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "interview_code", label: "Code", required: true, autoNumber: "INT", createOnly: true },
      { key: "application_number", label: "Application #" },
      { key: "vacancy_title", label: "Vacancy" },
      { key: "candidate_name", label: "Candidate", required: true },
      { key: "interview_type", label: "Type", type: "select", options: ["phone", "video", "onsite", "panel", "assessment_center"] },
      { key: "scheduled_at", label: "Scheduled at", type: "datetime" },
      { key: "duration_minutes", label: "Duration", type: "number" },
      { key: "location_name", label: "Location / room" },
      { key: "meeting_url", label: "Meeting URL" },
      { key: "panel_members", label: "Panel members", type: "textarea" },
      { key: "score", label: "Score", type: "number" },
      { key: "recommendation", label: "Recommendation", type: "select", options: ["pending", "hire", "hold", "reject"] },
      { key: "status", label: "Status", type: "select", options: ["scheduled", "completed", "cancelled", "no_show", "rescheduled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { interview_type: "panel", duration_minutes: 60, recommendation: "pending", status: "scheduled", score: 0 },
  }),

  background: cfg({
    title: "Background verification",
    description: "Employment, academic, identity and criminal checks",
    table: "ta_background_checks",
    numberField: "check_code",
    numberPrefix: "BGC",
    statusField: "status",
    statusOptions: ["open", "closed", "cancelled"],
    columns: [
      { key: "check_code", label: "Code" },
      { key: "candidate_name", label: "Candidate" },
      { key: "check_type", label: "Type" },
      { key: "result", label: "Result" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "check_code", label: "Code", required: true, autoNumber: "BGC", createOnly: true },
      { key: "application_number", label: "Application #" },
      { key: "candidate_name", label: "Candidate" },
      { key: "check_type", label: "Type", type: "select", options: ["employment", "academic", "license", "reference", "identity", "right_to_work", "criminal"] },
      { key: "provider_name", label: "Provider" },
      { key: "result", label: "Result", type: "select", options: ["pending", "clear", "flagged", "failed", "cancelled"] },
      { key: "status", label: "Status", type: "select", options: ["open", "closed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { check_type: "employment", result: "pending", status: "open" },
  }),

  references: cfg({
    title: "Reference checks",
    description: "Referee requests and feedback",
    table: "ta_references",
    numberField: "reference_code",
    numberPrefix: "REF",
    statusField: "status",
    statusOptions: ["requested", "received", "verified", "declined"],
    columns: [
      { key: "reference_code", label: "Code" },
      { key: "candidate_name", label: "Candidate" },
      { key: "referee_name", label: "Referee" },
      { key: "rating", label: "Rating" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "reference_code", label: "Code", required: true, autoNumber: "REF", createOnly: true },
      { key: "application_number", label: "Application #" },
      { key: "candidate_name", label: "Candidate" },
      { key: "referee_name", label: "Referee", required: true },
      { key: "referee_title", label: "Title" },
      { key: "referee_company", label: "Company" },
      { key: "referee_email", label: "Email" },
      { key: "referee_phone", label: "Phone" },
      { key: "relationship", label: "Relationship" },
      { key: "feedback", label: "Feedback", type: "textarea" },
      { key: "rating", label: "Rating", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["requested", "received", "verified", "declined"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "requested", rating: 0 },
  }),

  medical: cfg({
    title: "Medical examinations",
    description: "Pre-employment medical fitness tracking",
    table: "ta_medical_exams",
    numberField: "exam_code",
    numberPrefix: "MED",
    statusField: "status",
    statusOptions: ["scheduled", "completed", "cancelled", "no_show"],
    columns: [
      { key: "exam_code", label: "Code" },
      { key: "candidate_name", label: "Candidate" },
      { key: "clinic_name", label: "Clinic" },
      { key: "result", label: "Result" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "exam_code", label: "Code", required: true, autoNumber: "MED", createOnly: true },
      { key: "application_number", label: "Application #" },
      { key: "candidate_name", label: "Candidate" },
      { key: "clinic_name", label: "Clinic" },
      { key: "scheduled_at", label: "Scheduled", type: "datetime" },
      { key: "result", label: "Result", type: "select", options: ["pending", "fit", "fit_with_restrictions", "unfit"] },
      { key: "status", label: "Status", type: "select", options: ["scheduled", "completed", "cancelled", "no_show"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { result: "pending", status: "scheduled" },
  }),

  offers: cfg({
    title: "Offer management",
    description: "Offer letters, approvals and acceptances",
    table: "ta_offers",
    numberField: "offer_number",
    numberPrefix: "OFR",
    statusField: "status",
    statusOptions: ["draft", "issued", "accepted", "declined", "expired", "cancelled"],
    columns: [
      { key: "offer_number", label: "Number" },
      { key: "candidate_name", label: "Candidate" },
      { key: "vacancy_title", label: "Role" },
      { key: "salary_amount", label: "Salary" },
      { key: "candidate_response", label: "Response" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "offer_number", label: "Number", required: true, autoNumber: "OFR", createOnly: true },
      { key: "application_number", label: "Application #" },
      { key: "candidate_name", label: "Candidate", required: true },
      { key: "vacancy_title", label: "Vacancy" },
      { key: "department", label: "Department" },
      { key: "employment_type", label: "Type", type: "select", options: ["permanent", "contract", "temporary", "intern"] },
      { key: "salary_amount", label: "Salary", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "benefits_summary", label: "Benefits", type: "textarea" },
      { key: "probation_months", label: "Probation months", type: "number" },
      { key: "start_date", label: "Start date", type: "date" },
      { key: "expiry_date", label: "Offer expiry", type: "date" },
      { key: "approval_status", label: "Approval", type: "select", options: ["pending", "approved", "rejected"] },
      { key: "candidate_response", label: "Response", type: "select", options: ["pending", "accepted", "declined", "expired", "withdrawn"] },
      { key: "status", label: "Status", type: "select", options: ["draft", "issued", "accepted", "declined", "expired", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: {
      employment_type: "permanent",
      currency: "UGX",
      probation_months: 6,
      approval_status: "pending",
      candidate_response: "pending",
      status: "draft",
      salary_amount: 0,
    },
  }),

  onboarding: cfg({
    title: "Digital onboarding tasks",
    description: "Cross-department pre-boarding and day-one tasks",
    table: "ta_onboarding_tasks",
    numberField: "task_code",
    numberPrefix: "ONB",
    statusField: "status",
    statusOptions: ["pending", "in_progress", "done", "blocked", "cancelled"],
    columns: [
      { key: "task_code", label: "Code" },
      { key: "candidate_name", label: "Candidate" },
      { key: "task_name", label: "Task" },
      { key: "owner_department", label: "Owner" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "task_code", label: "Code", required: true, autoNumber: "ONB", createOnly: true },
      { key: "offer_number", label: "Offer #" },
      { key: "candidate_name", label: "Candidate" },
      { key: "task_name", label: "Task name", required: true },
      { key: "owner_department", label: "Owner dept", type: "select", options: ["hr", "it", "facilities", "security", "payroll", "training"] },
      { key: "due_date", label: "Due date", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["pending", "in_progress", "done", "blocked", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "pending", owner_department: "hr" },
  }),

  documents: cfg({
    title: "Recruitment documents",
    description: "Resumes, offers, contracts and certificates",
    table: "ta_documents",
    numberField: "doc_code",
    numberPrefix: "DOC",
    statusField: "status",
    statusOptions: ["active", "archived", "draft"],
    columns: [
      { key: "doc_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "doc_type", label: "Type" },
      { key: "related_number", label: "Related" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "doc_code", label: "Code", required: true, autoNumber: "DOC", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "doc_type", label: "Type", type: "select", options: ["resume", "cover_letter", "offer", "contract", "id", "certificate", "policy", "other"] },
      { key: "related_type", label: "Related type" },
      { key: "related_number", label: "Related #" },
      { key: "file_url", label: "File URL" },
      { key: "status", label: "Status", type: "select", options: ["active", "archived", "draft"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { doc_type: "resume", status: "active" },
  }),

  settings: cfg({
    title: "Talent settings",
    description: "Company recruitment configuration",
    table: "ta_settings",
    numberField: "setting_key",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    searchCols: ["setting_key", "setting_value", "category", "description"],
    columns: [
      { key: "setting_key", label: "Key" },
      { key: "setting_value", label: "Value" },
      { key: "category", label: "Category" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "setting_key", label: "Key", required: true },
      { key: "setting_value", label: "Value", required: true },
      { key: "category", label: "Category", type: "select", options: ["general", "portal", "offer", "ai", "compliance", "notifications"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
    defaults: { category: "general", status: "active" },
  }),

  audit: cfg({
    title: "Talent audit log",
    description: "Immutable recruitment actions",
    table: "ta_audit_log",
    columns: [
      { key: "action", label: "Action" },
      { key: "entity_table", label: "Table" },
      { key: "entity_code", label: "Code" },
      { key: "details", label: "Details" },
      { key: "created_at", label: "When" },
    ],
    fields: [
      { key: "action", label: "Action", required: true },
      { key: "entity_table", label: "Entity table" },
      { key: "entity_code", label: "Entity code" },
      { key: "details", label: "Details", type: "textarea" },
    ],
  }),

  reports: cfg({
    title: "Recruitment reports feed",
    description: "Stored insights for operational reporting",
    table: "ta_ai_insights",
    numberField: "insight_code",
    numberPrefix: "RPT",
    statusField: "status",
    statusOptions: ["open", "acknowledged", "closed"],
    columns: [
      { key: "insight_type", label: "Type" },
      { key: "title", label: "Title" },
      { key: "severity", label: "Severity" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "insight_code", label: "Code", required: true, autoNumber: "RPT", createOnly: true },
      { key: "insight_type", label: "Type", required: true },
      { key: "title", label: "Title", required: true },
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "severity", label: "Severity", type: "select", options: ["info", "low", "medium", "high"] },
      { key: "status", label: "Status", type: "select", options: ["open", "acknowledged", "closed"] },
    ],
    defaults: { severity: "medium", status: "open" },
  }),

  analytics: cfg({
    title: "Recruitment analytics feed",
    description: "AI insight store for analytics dashboards",
    table: "ta_ai_insights",
    numberField: "insight_code",
    numberPrefix: "AN",
    statusField: "status",
    statusOptions: ["open", "acknowledged", "closed"],
    columns: [
      { key: "insight_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "score", label: "Score" },
      { key: "severity", label: "Severity" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "insight_code", label: "Code", required: true, autoNumber: "AN", createOnly: true },
      { key: "insight_type", label: "Type", required: true },
      { key: "title", label: "Title", required: true },
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "score", label: "Score", type: "number" },
      { key: "severity", label: "Severity", type: "select", options: ["info", "low", "medium", "high"] },
      { key: "recommendations", label: "Recommendations", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["open", "acknowledged", "closed"] },
    ],
    defaults: { severity: "medium", status: "open", score: 50 },
  }),
};
