import type { PayEntityConfig } from "@/components/payroll/pay-entity-page";

function cfg(p: PayEntityConfig): PayEntityConfig {
  return {
    searchCols: p.searchCols || ["code", "name", "status", "employee_name", "period_label"],
    ...p,
  };
}

export const PAY_ENTITIES: Record<string, PayEntityConfig> = {
  calendars: cfg({
    title: "Payroll calendars",
    description: "Multi-company payroll calendars and pay frequencies",
    table: "pay_calendars",
    numberField: "calendar_code",
    numberPrefix: "CAL",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "calendar_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "frequency", label: "Frequency" },
      { key: "country_code", label: "Country" },
      { key: "currency", label: "Currency" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "calendar_code", label: "Code", required: true, autoNumber: "CAL", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "frequency", label: "Frequency", type: "select", options: ["monthly", "weekly", "biweekly", "daily"] },
      { key: "country_code", label: "Country", type: "select", options: ["UG", "KE", "TZ", "RW"] },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD", "KES", "TZS", "RWF"] },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { frequency: "monthly", country_code: "UG", currency: "UGX", status: "active" },
  }),

  periods: cfg({
    title: "Payroll periods",
    description: "Open, process, close, and lock pay periods",
    table: "pay_periods",
    numberField: "period_code",
    numberPrefix: "PER",
    statusField: "status",
    statusOptions: ["open", "processing", "closed", "locked"],
    columns: [
      { key: "period_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "calendar_code", label: "Calendar" },
      { key: "start_date", label: "Start" },
      { key: "end_date", label: "End" },
      { key: "pay_date", label: "Pay date" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "period_code", label: "Code", required: true, autoNumber: "PER", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "calendar_code", label: "Calendar code" },
      { key: "period_year", label: "Year", type: "number" },
      { key: "period_month", label: "Month", type: "number" },
      { key: "start_date", label: "Start date", type: "date", required: true },
      { key: "end_date", label: "End date", type: "date", required: true },
      { key: "pay_date", label: "Pay date", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["open", "processing", "closed", "locked"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: {
      status: "open",
      period_year: new Date().getFullYear(),
      period_month: new Date().getMonth() + 1,
    },
  }),

  grades: cfg({
    title: "Salary grades",
    description: "Grade min / mid / max salary ranges",
    table: "pay_salary_grades",
    numberField: "grade_code",
    numberPrefix: "G",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "grade_code", label: "Grade" },
      { key: "name", label: "Name" },
      { key: "min_salary", label: "Min" },
      { key: "mid_salary", label: "Mid" },
      { key: "max_salary", label: "Max" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "grade_code", label: "Grade code", required: true, createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "min_salary", label: "Min salary", type: "number" },
      { key: "mid_salary", label: "Mid salary", type: "number" },
      { key: "max_salary", label: "Max salary", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { currency: "UGX", status: "active", min_salary: 0, mid_salary: 0, max_salary: 0 },
  }),

  bands: cfg({
    title: "Salary bands",
    description: "Bands and steps within grades",
    table: "pay_salary_bands",
    numberField: "band_code",
    numberPrefix: "BND",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "band_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "grade_code", label: "Grade" },
      { key: "step_count", label: "Steps" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "band_code", label: "Code", required: true, autoNumber: "BND", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "grade_code", label: "Grade code" },
      { key: "step_count", label: "Step count", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { step_count: 5, status: "active" },
  }),

  scales: cfg({
    title: "Salary scales",
    description: "Step amounts by grade",
    table: "pay_salary_scales",
    numberField: "scale_code",
    numberPrefix: "SCL",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "scale_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "grade_code", label: "Grade" },
      { key: "step_no", label: "Step" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "scale_code", label: "Code", required: true, autoNumber: "SCL", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "grade_code", label: "Grade code" },
      { key: "step_no", label: "Step no", type: "number" },
      { key: "amount", label: "Amount", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { step_no: 1, amount: 0, currency: "UGX", status: "active" },
  }),

  groups: cfg({
    title: "Payroll groups",
    description: "Pay groups for batch processing",
    table: "pay_groups",
    numberField: "group_code",
    numberPrefix: "PG",
    searchCols: ["group_code", "name", "frequency", "country_code"],
    columns: [
      { key: "group_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "frequency", label: "Frequency" },
      { key: "country_code", label: "Country" },
      { key: "currency", label: "Currency" },
      { key: "pay_day", label: "Pay day" },
    ],
    fields: [
      { key: "group_code", label: "Code", required: true, autoNumber: "PG", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "frequency", label: "Frequency", type: "select", options: ["monthly", "weekly", "biweekly", "daily"] },
      { key: "country_code", label: "Country", type: "select", options: ["UG", "KE", "TZ", "RW"] },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD", "KES"] },
      { key: "pay_day", label: "Pay day", type: "number" },
      { key: "description", label: "Description", type: "textarea" },
    ],
    defaults: { frequency: "monthly", country_code: "UG", currency: "UGX", pay_day: 28 },
  }),

  commissions: cfg({
    title: "Commissions",
    description: "Sales and performance commissions",
    table: "pay_commissions",
    numberField: "commission_code",
    numberPrefix: "COM",
    statusField: "status",
    statusOptions: ["accrued", "approved", "paid", "cancelled"],
    searchCols: ["commission_code", "employee_name", "employee_number", "period_label", "status"],
    columns: [
      { key: "commission_code", label: "Code" },
      { key: "employee_name", label: "Employee" },
      { key: "period_label", label: "Period" },
      { key: "basis_amount", label: "Basis" },
      { key: "rate_pct", label: "Rate %" },
      { key: "commission_amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "commission_code", label: "Code", required: true, autoNumber: "COM", createOnly: true },
      { key: "employee_name", label: "Employee name", required: true },
      { key: "employee_number", label: "Employee no" },
      { key: "period_label", label: "Period" },
      { key: "basis_amount", label: "Basis amount", type: "number" },
      { key: "rate_pct", label: "Rate %", type: "number" },
      { key: "commission_amount", label: "Commission", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "source_module", label: "Source", type: "select", options: ["sales", "projects", "manual", "other"] },
      { key: "status", label: "Status", type: "select", options: ["accrued", "approved", "paid", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "accrued", currency: "UGX", source_module: "sales", rate_pct: 0, basis_amount: 0, commission_amount: 0 },
  }),

  incentives: cfg({
    title: "Production incentives",
    description: "Manufacturing and productivity incentives",
    table: "pay_incentives",
    numberField: "incentive_code",
    numberPrefix: "INC",
    statusField: "status",
    statusOptions: ["draft", "approved", "paid", "cancelled"],
    columns: [
      { key: "incentive_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "incentive_type", label: "Type" },
      { key: "employee_name", label: "Employee" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "incentive_code", label: "Code", required: true, autoNumber: "INC", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "incentive_type", label: "Type", type: "select", options: ["production", "attendance", "quality", "safety", "custom"] },
      { key: "employee_name", label: "Employee" },
      { key: "period_label", label: "Period" },
      { key: "amount", label: "Amount", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "production_batch", label: "Production batch" },
      { key: "status", label: "Status", type: "select", options: ["draft", "approved", "paid", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { incentive_type: "production", status: "draft", currency: "UGX", amount: 0 },
  }),

  "shift-premiums": cfg({
    title: "Shift premiums",
    description: "Night, weekend, and special shift rates",
    table: "pay_shift_premiums",
    numberField: "premium_code",
    numberPrefix: "SP",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "premium_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "shift_name", label: "Shift" },
      { key: "rate_pct", label: "Rate %" },
      { key: "fixed_amount", label: "Fixed" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "premium_code", label: "Code", required: true, autoNumber: "SP", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "shift_name", label: "Shift name" },
      { key: "rate_pct", label: "Rate %", type: "number" },
      { key: "fixed_amount", label: "Fixed amount", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { rate_pct: 0, fixed_amount: 0, status: "active" },
  }),

  formulas: cfg({
    title: "Payroll formulas",
    description: "No-code formula engine for earnings and deductions",
    table: "pay_formulas",
    numberField: "formula_code",
    numberPrefix: "F",
    statusField: "status",
    statusOptions: ["active", "draft", "retired"],
    searchCols: ["formula_code", "name", "component_code", "expression", "status"],
    columns: [
      { key: "formula_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "component_code", label: "Component" },
      { key: "version_no", label: "Ver" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "formula_code", label: "Code", required: true, autoNumber: "F", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "component_code", label: "Component code" },
      { key: "expression", label: "Expression", type: "textarea", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "version_no", label: "Version", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "draft", "retired"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { version_no: 1, status: "active" },
  }),

  simulations: cfg({
    title: "Payroll simulations",
    description: "What-if payroll runs before live processing",
    table: "pay_simulations",
    numberField: "simulation_code",
    numberPrefix: "SIM",
    statusField: "status",
    statusOptions: ["draft", "complete", "archived"],
    columns: [
      { key: "simulation_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "period_code", label: "Period" },
      { key: "employee_count", label: "Employees" },
      { key: "gross_total", label: "Gross" },
      { key: "net_total", label: "Net" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "simulation_code", label: "Code", required: true, autoNumber: "SIM", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "period_code", label: "Period code" },
      { key: "employee_count", label: "Employee count", type: "number" },
      { key: "gross_total", label: "Gross total", type: "number" },
      { key: "net_total", label: "Net total", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["draft", "complete", "archived"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "draft", employee_count: 0, gross_total: 0, net_total: 0 },
  }),

  corrections: cfg({
    title: "Corrections & retro",
    description: "Adjustments, reversals, retroactive and off-cycle payroll",
    table: "pay_corrections",
    numberField: "correction_code",
    numberPrefix: "COR",
    statusField: "status",
    statusOptions: ["pending", "approved", "posted", "cancelled"],
    searchCols: ["correction_code", "run_number", "employee_name", "correction_type", "status"],
    columns: [
      { key: "correction_code", label: "Code" },
      { key: "run_number", label: "Run" },
      { key: "employee_name", label: "Employee" },
      { key: "correction_type", label: "Type" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "correction_code", label: "Code", required: true, autoNumber: "COR", createOnly: true },
      { key: "run_number", label: "Run number" },
      { key: "employee_name", label: "Employee" },
      { key: "correction_type", label: "Type", type: "select", options: ["adjustment", "reversal", "retro", "off_cycle"] },
      { key: "amount", label: "Amount", type: "number" },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["pending", "approved", "posted", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { correction_type: "adjustment", status: "pending", amount: 0 },
  }),

  settlements: cfg({
    title: "Final settlements",
    description: "Exit pay, leave encashment, gratuity, loan recovery",
    table: "pay_final_settlements",
    numberField: "settlement_code",
    numberPrefix: "FS",
    statusField: "status",
    statusOptions: ["draft", "approved", "paid", "cancelled"],
    searchCols: ["settlement_code", "employee_name", "employee_number", "status"],
    columns: [
      { key: "settlement_code", label: "Code" },
      { key: "employee_name", label: "Employee" },
      { key: "last_working_date", label: "Last day" },
      { key: "net_settlement", label: "Net" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "settlement_code", label: "Code", required: true, autoNumber: "FS", createOnly: true },
      { key: "employee_name", label: "Employee name", required: true },
      { key: "employee_number", label: "Employee no" },
      { key: "last_working_date", label: "Last working date", type: "date" },
      { key: "leave_encashment", label: "Leave encashment", type: "number" },
      { key: "gratuity_amount", label: "Gratuity", type: "number" },
      { key: "loan_balance", label: "Loan balance", type: "number" },
      { key: "net_settlement", label: "Net settlement", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "status", label: "Status", type: "select", options: ["draft", "approved", "paid", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: {
      currency: "UGX",
      status: "draft",
      leave_encashment: 0,
      gratuity_amount: 0,
      loan_balance: 0,
      net_settlement: 0,
    },
  }),

  "cost-allocations": cfg({
    title: "Labour cost allocations",
    description: "Cost centre, project, and manufacturing labour costing",
    table: "pay_cost_allocations",
    numberField: "allocation_code",
    numberPrefix: "CA",
    statusField: "status",
    statusOptions: ["draft", "posted", "reversed"],
    searchCols: ["allocation_code", "run_number", "cost_center", "department", "project_code", "status"],
    columns: [
      { key: "allocation_code", label: "Code" },
      { key: "run_number", label: "Run" },
      { key: "cost_center", label: "Cost centre" },
      { key: "department", label: "Dept" },
      { key: "project_code", label: "Project" },
      { key: "labour_cost", label: "Labour cost" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "allocation_code", label: "Code", required: true, autoNumber: "CA", createOnly: true },
      { key: "run_number", label: "Run number" },
      { key: "cost_center", label: "Cost centre" },
      { key: "department", label: "Department" },
      { key: "project_code", label: "Project code" },
      { key: "production_line", label: "Production line" },
      { key: "batch_number", label: "Batch number" },
      { key: "labour_cost", label: "Labour cost", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "status", label: "Status", type: "select", options: ["draft", "posted", "reversed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "posted", currency: "UGX", labour_cost: 0 },
  }),

  "mobile-money": cfg({
    title: "Mobile money centre",
    description: "MTN, Airtel and other mobile salary disbursements",
    table: "pay_mobile_money",
    numberField: "txn_code",
    numberPrefix: "MM",
    statusField: "status",
    statusOptions: ["pending", "sent", "failed", "reconciled"],
    searchCols: ["txn_code", "employee_name", "phone", "provider", "status"],
    columns: [
      { key: "txn_code", label: "Txn" },
      { key: "provider", label: "Provider" },
      { key: "employee_name", label: "Employee" },
      { key: "phone", label: "Phone" },
      { key: "amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "txn_code", label: "Txn code", required: true, autoNumber: "MM", createOnly: true },
      { key: "provider", label: "Provider", type: "select", options: ["mtn", "airtel", "other"] },
      { key: "employee_name", label: "Employee", required: true },
      { key: "phone", label: "Phone", required: true },
      { key: "amount", label: "Amount", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "period_label", label: "Period" },
      { key: "external_ref", label: "External ref" },
      { key: "status", label: "Status", type: "select", options: ["pending", "sent", "failed", "reconciled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { provider: "mtn", status: "pending", currency: "UGX", amount: 0 },
  }),

  "bank-files": cfg({
    title: "Bank payment files",
    description: "Generated bank transfer files for salary runs",
    table: "pay_bank_files",
    numberField: "file_code",
    numberPrefix: "BF",
    statusField: "status",
    statusOptions: ["generated", "downloaded", "submitted", "failed"],
    columns: [
      { key: "file_code", label: "Code" },
      { key: "run_number", label: "Run" },
      { key: "bank_name", label: "Bank" },
      { key: "record_count", label: "Records" },
      { key: "total_amount", label: "Total" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "file_code", label: "Code", required: true, autoNumber: "BF", createOnly: true },
      { key: "run_number", label: "Run number" },
      { key: "bank_name", label: "Bank name" },
      { key: "format", label: "Format", type: "select", options: ["csv", "txt", "xml", "aba"] },
      { key: "record_count", label: "Record count", type: "number" },
      { key: "total_amount", label: "Total amount", type: "number" },
      { key: "file_url", label: "File URL" },
      { key: "status", label: "Status", type: "select", options: ["generated", "downloaded", "submitted", "failed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { format: "csv", status: "generated", record_count: 0, total_amount: 0 },
  }),

  pension: cfg({
    title: "Pension schemes",
    description: "NSSF and private pension contribution schemes",
    table: "pay_pension_schemes",
    numberField: "scheme_code",
    numberPrefix: "PEN",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "scheme_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "employee_pct", label: "EE %" },
      { key: "employer_pct", label: "ER %" },
      { key: "provider_name", label: "Provider" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "scheme_code", label: "Code", required: true, autoNumber: "PEN", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "employee_pct", label: "Employee %", type: "number" },
      { key: "employer_pct", label: "Employer %", type: "number" },
      { key: "provider_name", label: "Provider" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { employee_pct: 5, employer_pct: 10, status: "active" },
  }),

  gratuity: cfg({
    title: "Gratuity rules",
    description: "Service gratuity calculation rules",
    table: "pay_gratuity_rules",
    numberField: "rule_code",
    numberPrefix: "GRT",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "rule_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "years_of_service_min", label: "Min years" },
      { key: "months_per_year", label: "Months/yr" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "rule_code", label: "Code", required: true, autoNumber: "GRT", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "years_of_service_min", label: "Min years of service", type: "number" },
      { key: "months_per_year", label: "Months per year", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { years_of_service_min: 0, months_per_year: 1, status: "active" },
  }),

  advances: cfg({
    title: "Salary advances",
    description: "Advance requests and recovery tracking",
    table: "pay_advances",
    numberField: "advance_number",
    numberPrefix: "ADV",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected", "deducted", "cancelled"],
    searchCols: ["advance_number", "status", "reason"],
    columns: [
      { key: "advance_number", label: "Number" },
      { key: "amount", label: "Amount" },
      { key: "request_date", label: "Requested" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "advance_number", label: "Number", required: true, autoNumber: "ADV", createOnly: true },
      { key: "employee_id", label: "Employee ID (UUID)", required: true },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "request_date", label: "Request date", type: "date" },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected", "deducted", "cancelled"] },
    ],
    defaults: { status: "pending", amount: 0 },
  }),

  "gl-mappings": cfg({
    title: "Payroll GL mappings",
    description: "Map payroll posting keys to chart of accounts",
    table: "pay_gl_mappings",
    numberField: "mapping_key",
    numberPrefix: "GLM",
    searchCols: ["mapping_key", "account_code", "account_name"],
    columns: [
      { key: "mapping_key", label: "Key" },
      { key: "account_code", label: "Account" },
      { key: "account_name", label: "Name" },
    ],
    fields: [
      { key: "mapping_key", label: "Mapping key", required: true, createOnly: true },
      { key: "account_code", label: "Account code", required: true },
      { key: "account_name", label: "Account name" },
    ],
    defaults: {},
  }),

  documents: cfg({
    title: "Payroll documents",
    description: "Payslips, bank files, tax returns, policies",
    table: "pay_documents",
    numberField: "doc_code",
    numberPrefix: "DOC",
    statusField: "status",
    statusOptions: ["active", "archived"],
    columns: [
      { key: "doc_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "doc_type", label: "Type" },
      { key: "related_number", label: "Related" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "doc_code", label: "Code", required: true, autoNumber: "DOC", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "doc_type", label: "Type", type: "select", options: ["payslip", "bank_file", "tax_return", "nssf", "policy", "other"] },
      { key: "related_number", label: "Related number" },
      { key: "file_url", label: "File URL" },
      { key: "status", label: "Status", type: "select", options: ["active", "archived"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { doc_type: "payslip", status: "active" },
  }),

  settings: cfg({
    title: "Payroll settings",
    description: "Company payroll configuration keys",
    table: "pay_settings",
    numberField: "setting_key",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    searchCols: ["setting_key", "setting_value", "category", "description"],
    columns: [
      { key: "setting_key", label: "Key" },
      { key: "setting_value", label: "Value" },
      { key: "category", label: "Category" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "setting_key", label: "Key", required: true, createOnly: true },
      { key: "setting_value", label: "Value", required: true },
      { key: "category", label: "Category", type: "select", options: ["general", "tax", "calc", "accounting", "payslip", "bank"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
    defaults: { category: "general", status: "active" },
  }),

  audit: cfg({
    title: "Payroll audit log",
    description: "Immutable activity trail for payroll actions",
    table: "pay_audit",
    searchCols: ["action", "entity_type", "details"],
    columns: [
      { key: "action", label: "Action" },
      { key: "entity_type", label: "Entity" },
      { key: "details", label: "Details" },
      { key: "created_at", label: "When" },
    ],
    fields: [
      { key: "action", label: "Action", required: true },
      { key: "entity_type", label: "Entity type" },
      { key: "details", label: "Details", type: "textarea" },
    ],
    defaults: {},
  }),
};
