import type { SalesEntityConfig } from "./types";

function cfg(p: SalesEntityConfig): SalesEntityConfig {
  return {
    searchCols: p.searchCols || [
      "code",
      "name",
      "title",
      "status",
      "customer_name",
      "order_number",
      "quote_number",
      "lead_number",
      "opportunity_number",
    ],
    ...p,
  };
}

export const SALES_ENTITIES: Record<string, SalesEntityConfig> = {
  leads: cfg({
    title: "Sales Leads",
    description: "Inbound and outbound lead capture, qualification, conversion",
    table: "sales_leads",
    numberField: "lead_number",
    numberPrefix: "LD",
    statusField: "status",
    statusOptions: ["new", "contacted", "qualified", "unqualified", "converted", "lost"],
    searchCols: ["lead_number", "company_name", "contact_name", "email", "phone", "source", "status"],
    columns: [
      { key: "lead_number", label: "Lead #" },
      { key: "company_name", label: "Company" },
      { key: "contact_name", label: "Contact" },
      { key: "source", label: "Source" },
      { key: "estimated_value", label: "Value" },
      { key: "status", label: "Status" },
      { key: "owner_name", label: "Owner" },
    ],
    fields: [
      { key: "lead_number", label: "Lead number", required: true, autoNumber: "LD", createOnly: true },
      { key: "company_name", label: "Company name", required: true },
      { key: "contact_name", label: "Contact name" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "source", label: "Source", type: "select", options: ["web", "referral", "cold_call", "trade_show", "partner", "tender", "walk_in"] },
      { key: "industry", label: "Industry" },
      { key: "estimated_value", label: "Estimated value", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD", "KES", "TZS"] },
      { key: "rating", label: "Rating", type: "select", options: ["hot", "warm", "cold"] },
      { key: "territory_code", label: "Territory" },
      { key: "channel_code", label: "Channel" },
      { key: "owner_name", label: "Owner" },
      { key: "next_action_date", label: "Next action", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["new", "contacted", "qualified", "unqualified", "converted", "lost"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "new", currency: "UGX", rating: "warm", estimated_value: 0 },
  }),

  opportunities: cfg({
    title: "Opportunities",
    description: "Deal pipeline stages from prospecting to close",
    table: "sales_opportunities",
    numberField: "opportunity_number",
    numberPrefix: "OPP",
    statusField: "stage",
    statusOptions: ["prospecting", "qualification", "proposal", "negotiation", "won", "lost"],
    searchCols: ["opportunity_number", "name", "stage", "owner_name", "source"],
    columns: [
      { key: "opportunity_number", label: "Opp #" },
      { key: "name", label: "Name" },
      { key: "stage", label: "Stage" },
      { key: "expected_value", label: "Value" },
      { key: "probability", label: "Prob %" },
      { key: "expected_close_date", label: "Close" },
      { key: "owner_name", label: "Owner" },
    ],
    fields: [
      { key: "opportunity_number", label: "Number", required: true, autoNumber: "OPP", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "stage", label: "Stage", type: "select", options: ["prospecting", "qualification", "proposal", "negotiation", "won", "lost"] },
      { key: "probability", label: "Probability %", type: "number" },
      { key: "expected_value", label: "Expected value", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD", "KES", "TZS"] },
      { key: "expected_close_date", label: "Expected close", type: "date" },
      { key: "source", label: "Source" },
      { key: "competitor", label: "Competitor" },
      { key: "territory_code", label: "Territory" },
      { key: "channel_code", label: "Channel" },
      { key: "owner_name", label: "Owner" },
      { key: "next_step", label: "Next step", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { stage: "prospecting", probability: 20, currency: "UGX", expected_value: 0 },
  }),

  activities: cfg({
    title: "Sales Activities",
    description: "Calls, meetings, tasks and follow-ups",
    table: "sales_activities",
    numberField: "activity_code",
    numberPrefix: "ACT",
    statusField: "status",
    statusOptions: ["open", "done", "cancelled", "overdue"],
    columns: [
      { key: "activity_code", label: "Code" },
      { key: "activity_type", label: "Type" },
      { key: "subject", label: "Subject" },
      { key: "customer_name", label: "Customer" },
      { key: "owner_name", label: "Owner" },
      { key: "priority", label: "Priority" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "activity_code", label: "Code", required: true, autoNumber: "ACT", createOnly: true },
      { key: "activity_type", label: "Type", type: "select", options: ["call", "meeting", "email", "visit", "demo", "proposal", "follow_up", "task"] },
      { key: "subject", label: "Subject", required: true },
      { key: "related_type", label: "Related to", type: "select", options: ["lead", "opportunity", "customer", "order", "quote"] },
      { key: "related_number", label: "Related #" },
      { key: "customer_name", label: "Customer" },
      { key: "owner_name", label: "Owner" },
      { key: "due_at", label: "Due at", type: "datetime" },
      { key: "priority", label: "Priority", type: "select", options: ["low", "medium", "high", "urgent"] },
      { key: "status", label: "Status", type: "select", options: ["open", "done", "cancelled", "overdue"] },
      { key: "outcome", label: "Outcome", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { activity_type: "call", related_type: "lead", priority: "medium", status: "open" },
  }),

  "call-logs": cfg({
    title: "Call Logs",
    description: "Inbound/outbound call history and dispositions",
    table: "sales_call_logs",
    numberField: "call_code",
    numberPrefix: "CL",
    statusField: "status",
    statusOptions: ["logged", "follow_up", "closed"],
    columns: [
      { key: "call_code", label: "Code" },
      { key: "direction", label: "Dir" },
      { key: "customer_name", label: "Customer" },
      { key: "contact_name", label: "Contact" },
      { key: "rep_name", label: "Rep" },
      { key: "disposition", label: "Disposition" },
      { key: "duration_sec", label: "Sec" },
    ],
    fields: [
      { key: "call_code", label: "Code", required: true, autoNumber: "CL", createOnly: true },
      { key: "direction", label: "Direction", type: "select", options: ["outbound", "inbound"] },
      { key: "customer_name", label: "Customer" },
      { key: "contact_name", label: "Contact" },
      { key: "phone", label: "Phone" },
      { key: "rep_name", label: "Rep" },
      { key: "duration_sec", label: "Duration (sec)", type: "number" },
      { key: "disposition", label: "Disposition", type: "select", options: ["connected", "no_answer", "busy", "voicemail", "wrong_number"] },
      { key: "subject", label: "Subject" },
      { key: "status", label: "Status", type: "select", options: ["logged", "follow_up", "closed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { direction: "outbound", disposition: "connected", status: "logged", duration_sec: 0 },
  }),

  competitors: cfg({
    title: "Competitors",
    description: "Competitive intelligence registry",
    table: "sales_competitors",
    numberField: "competitor_code",
    numberPrefix: "CMP",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "competitor_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "threat_level", label: "Threat" },
      { key: "market_share_pct", label: "Share %" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "competitor_code", label: "Code", required: true, autoNumber: "CMP", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "strength", label: "Strengths", type: "textarea" },
      { key: "weakness", label: "Weaknesses", type: "textarea" },
      { key: "products", label: "Products" },
      { key: "market_share_pct", label: "Market share %", type: "number" },
      { key: "threat_level", label: "Threat", type: "select", options: ["low", "medium", "high"] },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { threat_level: "medium", status: "active", market_share_pct: 0 },
  }),

  "price-lists": cfg({
    title: "Price Lists",
    description: "Customer type and channel price books",
    table: "sales_price_lists",
    numberField: "price_list_code",
    numberPrefix: "PL",
    statusField: "status",
    statusOptions: ["active", "inactive", "draft"],
    columns: [
      { key: "price_list_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "currency", label: "CCY" },
      { key: "customer_type", label: "Customer type" },
      { key: "channel_code", label: "Channel" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "price_list_code", label: "Code", required: true, autoNumber: "PL", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD", "KES", "TZS"] },
      { key: "customer_type", label: "Customer type", type: "select", options: ["wholesale", "retail", "dealer", "export", "government"] },
      { key: "channel_code", label: "Channel" },
      { key: "valid_from", label: "Valid from", type: "date" },
      { key: "valid_to", label: "Valid to", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive", "draft"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { currency: "UGX", customer_type: "wholesale", status: "active" },
  }),

  "price-items": cfg({
    title: "Price Items",
    description: "SKU unit prices per price list",
    table: "sales_price_items",
    numberField: "item_code",
    numberPrefix: "PI",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "item_code", label: "Code" },
      { key: "price_list_code", label: "List" },
      { key: "product_code", label: "SKU" },
      { key: "product_name", label: "Product" },
      { key: "unit_price", label: "Price" },
      { key: "unit", label: "Unit" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "item_code", label: "Code", required: true, autoNumber: "PI", createOnly: true },
      { key: "price_list_code", label: "Price list", required: true },
      { key: "product_code", label: "Product code" },
      { key: "product_name", label: "Product name" },
      { key: "unit", label: "Unit" },
      { key: "unit_price", label: "Unit price", type: "number", required: true },
      { key: "min_qty", label: "Min qty", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD", "KES", "TZS"] },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { unit: "carton", currency: "UGX", status: "active", min_qty: 1, unit_price: 0 },
  }),

  "discount-rules": cfg({
    title: "Discount Rules",
    description: "Volume, channel and approval-gated discounts",
    table: "sales_discount_rules",
    numberField: "rule_code",
    numberPrefix: "DR",
    statusField: "status",
    statusOptions: ["active", "inactive", "draft"],
    columns: [
      { key: "rule_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "rule_type", label: "Type" },
      { key: "min_qty", label: "Min qty" },
      { key: "discount_pct", label: "Disc %" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "rule_code", label: "Code", required: true, autoNumber: "DR", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "rule_type", label: "Type", type: "select", options: ["volume", "customer", "channel", "promo", "manual", "contract"] },
      { key: "product_code", label: "Product code" },
      { key: "customer_type", label: "Customer type" },
      { key: "channel_code", label: "Channel" },
      { key: "min_qty", label: "Min qty", type: "number" },
      { key: "min_amount", label: "Min amount", type: "number" },
      { key: "discount_pct", label: "Discount %", type: "number" },
      { key: "max_discount_pct", label: "Max discount %", type: "number" },
      { key: "valid_from", label: "Valid from", type: "date" },
      { key: "valid_to", label: "Valid to", type: "date" },
      { key: "priority", label: "Priority", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive", "draft"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { rule_type: "volume", discount_pct: 0, max_discount_pct: 50, priority: 100, status: "active" },
  }),

  promotions: cfg({
    title: "Promotions",
    description: "Time-bound trade promotions and campaigns",
    table: "sales_promotions",
    numberField: "promo_code",
    numberPrefix: "PR",
    statusField: "status",
    statusOptions: ["draft", "active", "paused", "ended"],
    columns: [
      { key: "promo_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "promo_type", label: "Type" },
      { key: "discount_pct", label: "Disc %" },
      { key: "budget_amount", label: "Budget" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "promo_code", label: "Code", required: true, autoNumber: "PR", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "promo_type", label: "Type", type: "select", options: ["percentage", "fixed", "bogo", "bundle", "free_shipping"] },
      { key: "discount_pct", label: "Discount %", type: "number" },
      { key: "discount_amount", label: "Discount amount", type: "number" },
      { key: "product_codes", label: "Product codes" },
      { key: "channel_code", label: "Channel" },
      { key: "budget_amount", label: "Budget", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "valid_from", label: "Valid from", type: "date" },
      { key: "valid_to", label: "Valid to", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["draft", "active", "paused", "ended"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { promo_type: "percentage", status: "draft", currency: "UGX", discount_pct: 0 },
  }),

  "quote-lines": cfg({
    title: "Quotation Lines",
    description: "Line items across quotations",
    table: "quotation_lines",
    columns: [
      { key: "product_code", label: "SKU" },
      { key: "description", label: "Description" },
      { key: "quantity", label: "Qty" },
      { key: "unit_price", label: "Price" },
      { key: "discount_pct", label: "Disc %" },
      { key: "line_total", label: "Total" },
    ],
    fields: [
      { key: "product_code", label: "Product code" },
      { key: "product_name", label: "Product name" },
      { key: "description", label: "Description" },
      { key: "quantity", label: "Quantity", type: "number", required: true },
      { key: "unit", label: "Unit" },
      { key: "unit_price", label: "Unit price", type: "number" },
      { key: "discount_pct", label: "Discount %", type: "number" },
      { key: "tax_rate", label: "Tax rate %", type: "number" },
    ],
    defaults: { quantity: 1, unit: "carton", unit_price: 0, discount_pct: 0, tax_rate: 18 },
  }),

  "order-lines": cfg({
    title: "Order Lines",
    description: "Sales order line items",
    table: "sales_order_lines",
    columns: [
      { key: "product_code", label: "SKU" },
      { key: "product_name", label: "Product" },
      { key: "quantity", label: "Qty" },
      { key: "unit_price", label: "Price" },
      { key: "warehouse_code", label: "Warehouse" },
    ],
    fields: [
      { key: "product_code", label: "Product code" },
      { key: "product_name", label: "Product name" },
      { key: "description", label: "Description" },
      { key: "quantity", label: "Quantity", type: "number", required: true },
      { key: "unit", label: "Unit" },
      { key: "unit_price", label: "Unit price", type: "number" },
      { key: "warehouse_code", label: "Warehouse" },
    ],
    defaults: { quantity: 1, unit: "carton", unit_price: 0 },
  }),

  approvals: cfg({
    title: "Order Approvals",
    description: "Discount, credit and exception approvals",
    table: "sales_order_approvals",
    numberField: "approval_code",
    numberPrefix: "AP",
    statusField: "status",
    statusOptions: ["open", "closed"],
    columns: [
      { key: "approval_code", label: "Code" },
      { key: "approval_type", label: "Type" },
      { key: "order_number", label: "Order" },
      { key: "customer_name", label: "Customer" },
      { key: "discount_pct", label: "Disc %" },
      { key: "decision", label: "Decision" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "approval_code", label: "Code", required: true, autoNumber: "AP", createOnly: true },
      { key: "approval_type", label: "Type", type: "select", options: ["discount", "credit", "price", "cancel", "return", "contract"] },
      { key: "order_number", label: "Order number" },
      { key: "quote_number", label: "Quote number" },
      { key: "customer_name", label: "Customer" },
      { key: "requested_by_name", label: "Requested by" },
      { key: "approver_name", label: "Approver" },
      { key: "amount", label: "Amount", type: "number" },
      { key: "discount_pct", label: "Discount %", type: "number" },
      { key: "decision", label: "Decision", type: "select", options: ["pending", "approved", "rejected", "escalated"] },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["open", "closed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { approval_type: "discount", decision: "pending", status: "open", discount_pct: 0 },
  }),

  "blanket-orders": cfg({
    title: "Blanket / Contract Orders",
    description: "Long-running and framework sales orders",
    table: "sales_orders",
    numberField: "order_number",
    numberPrefix: "BO",
    statusField: "status",
    statusOptions: ["draft", "confirmed", "picking", "dispatched", "delivered", "cancelled", "closed"],
    searchCols: ["order_number", "order_type", "status", "po_number"],
    columns: [
      { key: "order_number", label: "Order #" },
      { key: "order_type", label: "Type" },
      { key: "status", label: "Status" },
      { key: "total_amount", label: "Total" },
      { key: "delivery_date", label: "Delivery" },
      { key: "po_number", label: "PO" },
    ],
    fields: [
      { key: "order_number", label: "Order number", required: true, autoNumber: "BO", createOnly: true },
      { key: "order_type", label: "Type", type: "select", options: ["blanket", "contract", "standard"] },
      { key: "status", label: "Status", type: "select", options: ["draft", "confirmed", "picking", "dispatched", "delivered", "cancelled", "closed"] },
      { key: "order_date", label: "Order date", type: "date" },
      { key: "delivery_date", label: "Delivery date", type: "date" },
      { key: "po_number", label: "Customer PO" },
      { key: "total_amount", label: "Total", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "channel_code", label: "Channel" },
      { key: "team_code", label: "Team" },
      { key: "priority", label: "Priority", type: "select", options: ["low", "normal", "high", "rush"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { order_type: "blanket", status: "draft", currency: "UGX", priority: "normal", total_amount: 0 },
  }),

  "credit-holds": cfg({
    title: "Credit Reviews & Holds",
    description: "Credit decisions against customers and orders",
    table: "credit_reviews",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected", "hold"],
    columns: [
      { key: "customer_name", label: "Customer" },
      { key: "order_number", label: "Order" },
      { key: "decision", label: "Decision" },
      { key: "credit_limit", label: "Limit" },
      { key: "outstanding", label: "Outstanding" },
      { key: "risk_score", label: "Risk" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "customer_name", label: "Customer name" },
      { key: "order_number", label: "Order number" },
      { key: "decision", label: "Decision", type: "select", options: ["pending", "approved", "rejected", "hold"] },
      { key: "credit_limit", label: "Credit limit", type: "number" },
      { key: "outstanding", label: "Outstanding", type: "number" },
      { key: "risk_score", label: "Risk score", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected", "hold"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { decision: "pending", status: "pending", risk_score: 0 },
  }),

  "payment-terms": cfg({
    title: "Payment Terms Catalog",
    description: "Standard commercial payment terms used on quotes and orders",
    table: "sales_settings",
    numberField: "setting_key",
    numberPrefix: "PT",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    searchCols: ["setting_key", "setting_value", "category", "description"],
    columns: [
      { key: "setting_key", label: "Key" },
      { key: "setting_value", label: "Value" },
      { key: "category", label: "Category" },
      { key: "description", label: "Description" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "setting_key", label: "Key", required: true },
      { key: "setting_value", label: "Value", required: true },
      { key: "category", label: "Category", type: "select", options: ["credit", "payment_terms", "general"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
    defaults: { category: "payment_terms", status: "active" },
  }),

  contracts: cfg({
    title: "Sales Contracts",
    description: "Framework, blanket and tender contracts",
    table: "sales_contracts",
    numberField: "contract_number",
    numberPrefix: "CT",
    statusField: "status",
    statusOptions: ["draft", "active", "expired", "terminated", "renewed"],
    columns: [
      { key: "contract_number", label: "Contract #" },
      { key: "name", label: "Name" },
      { key: "customer_name", label: "Customer" },
      { key: "contract_type", label: "Type" },
      { key: "contract_value", label: "Value" },
      { key: "end_date", label: "Ends" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "contract_number", label: "Number", required: true, autoNumber: "CT", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "customer_name", label: "Customer" },
      { key: "contract_type", label: "Type", type: "select", options: ["framework", "blanket", "service", "tender", "distributor"] },
      { key: "start_date", label: "Start", type: "date" },
      { key: "end_date", label: "End", type: "date" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "contract_value", label: "Contract value", type: "number" },
      { key: "consumed_value", label: "Consumed", type: "number" },
      { key: "payment_terms_days", label: "Payment terms (days)", type: "number" },
      { key: "price_list_code", label: "Price list" },
      { key: "owner_name", label: "Owner" },
      { key: "status", label: "Status", type: "select", options: ["draft", "active", "expired", "terminated", "renewed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { contract_type: "framework", currency: "UGX", status: "draft", payment_terms_days: 30 },
  }),

  "contract-lines": cfg({
    title: "Contract Lines",
    description: "Committed products and volumes on contracts",
    table: "sales_contract_lines",
    numberField: "line_code",
    numberPrefix: "CLN",
    statusField: "status",
    statusOptions: ["active", "fulfilled", "cancelled"],
    columns: [
      { key: "line_code", label: "Code" },
      { key: "contract_number", label: "Contract" },
      { key: "product_code", label: "SKU" },
      { key: "product_name", label: "Product" },
      { key: "quantity", label: "Qty" },
      { key: "unit_price", label: "Price" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "line_code", label: "Code", required: true, autoNumber: "CLN", createOnly: true },
      { key: "contract_number", label: "Contract number", required: true },
      { key: "product_code", label: "Product code" },
      { key: "product_name", label: "Product name" },
      { key: "quantity", label: "Quantity", type: "number" },
      { key: "unit", label: "Unit" },
      { key: "unit_price", label: "Unit price", type: "number" },
      { key: "committed_value", label: "Committed value", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "fulfilled", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { unit: "carton", status: "active", quantity: 0, unit_price: 0 },
  }),

  rebates: cfg({
    title: "Rebates",
    description: "Volume and growth rebate programs",
    table: "sales_rebates",
    numberField: "rebate_code",
    numberPrefix: "RB",
    statusField: "status",
    statusOptions: ["accruing", "approved", "paid", "cancelled"],
    columns: [
      { key: "rebate_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "customer_name", label: "Customer" },
      { key: "basis", label: "Basis" },
      { key: "rebate_pct", label: "Rebate %" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "rebate_code", label: "Code", required: true, autoNumber: "RB", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "customer_name", label: "Customer" },
      { key: "channel_code", label: "Channel" },
      { key: "basis", label: "Basis", type: "select", options: ["volume", "revenue", "growth"] },
      { key: "threshold_amount", label: "Threshold", type: "number" },
      { key: "rebate_pct", label: "Rebate %", type: "number" },
      { key: "rebate_amount", label: "Rebate amount", type: "number" },
      { key: "period_start", label: "Period start", type: "date" },
      { key: "period_end", label: "Period end", type: "date" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "status", label: "Status", type: "select", options: ["accruing", "approved", "paid", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { basis: "volume", status: "accruing", currency: "UGX", rebate_pct: 0 },
  }),

  territories: cfg({
    title: "Sales Territories",
    description: "Geographic and market territories",
    table: "sales_territories",
    numberField: "code",
    numberPrefix: "TR",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "country", label: "Country" },
      { key: "region", label: "Region" },
      { key: "zone", label: "Zone" },
      { key: "target_amount", label: "Target" },
    ],
    fields: [
      { key: "code", label: "Code", required: true, autoNumber: "TR", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "country", label: "Country" },
      { key: "region", label: "Region" },
      { key: "district", label: "District" },
      { key: "zone", label: "Zone" },
      { key: "target_amount", label: "Target amount", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { country: "Uganda", currency: "UGX", target_amount: 0 },
  }),

  teams: cfg({
    title: "Sales Teams",
    description: "Team structure, managers and targets",
    table: "sales_teams",
    numberField: "team_code",
    numberPrefix: "TM",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "team_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "manager_name", label: "Manager" },
      { key: "territory_code", label: "Territory" },
      { key: "target_amount", label: "Target" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "team_code", label: "Code", required: true, autoNumber: "TM", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "manager_name", label: "Manager" },
      { key: "territory_code", label: "Territory" },
      { key: "branch_name", label: "Branch" },
      { key: "region", label: "Region" },
      { key: "target_amount", label: "Target", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "member_count", label: "Members", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", currency: "UGX", target_amount: 0, member_count: 0 },
  }),

  channels: cfg({
    title: "Sales Channels",
    description: "Direct, dealer, export and e-commerce channels",
    table: "sales_channels",
    numberField: "channel_code",
    numberPrefix: "CH",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "channel_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "channel_type", label: "Type" },
      { key: "commission_pct", label: "Comm %" },
      { key: "margin_pct", label: "Margin %" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "channel_code", label: "Code", required: true, autoNumber: "CH", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "channel_type", label: "Type", type: "select", options: ["direct", "dealer", "distributor", "ecommerce", "export", "tender", "retail"] },
      { key: "margin_pct", label: "Margin %", type: "number" },
      { key: "commission_pct", label: "Commission %", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { channel_type: "direct", status: "active", commission_pct: 3, margin_pct: 0 },
  }),

  "visit-plans": cfg({
    title: "Visit Plans",
    description: "Field sales route and customer visit plans",
    table: "sales_visit_plans",
    numberField: "plan_code",
    numberPrefix: "VP",
    statusField: "status",
    statusOptions: ["planned", "in_progress", "completed", "missed", "cancelled"],
    columns: [
      { key: "plan_code", label: "Code" },
      { key: "rep_name", label: "Rep" },
      { key: "customer_name", label: "Customer" },
      { key: "planned_date", label: "Date" },
      { key: "purpose", label: "Purpose" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "plan_code", label: "Code", required: true, autoNumber: "VP", createOnly: true },
      { key: "rep_name", label: "Rep" },
      { key: "customer_name", label: "Customer" },
      { key: "territory_code", label: "Territory" },
      { key: "planned_date", label: "Planned date", type: "date" },
      { key: "purpose", label: "Purpose" },
      { key: "location_name", label: "Location" },
      { key: "lat", label: "Latitude", type: "number" },
      { key: "lng", label: "Longitude", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["planned", "in_progress", "completed", "missed", "cancelled"] },
      { key: "outcome", label: "Outcome", type: "textarea" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "planned" },
  }),

  samples: cfg({
    title: "Product Samples",
    description: "Sample issuance, return and conversion tracking",
    table: "sales_samples",
    numberField: "sample_code",
    numberPrefix: "SM",
    statusField: "status",
    statusOptions: ["issued", "returned", "converted", "written_off"],
    columns: [
      { key: "sample_code", label: "Code" },
      { key: "customer_name", label: "Customer" },
      { key: "product_code", label: "SKU" },
      { key: "quantity", label: "Qty" },
      { key: "issued_date", label: "Issued" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "sample_code", label: "Code", required: true, autoNumber: "SM", createOnly: true },
      { key: "customer_name", label: "Customer" },
      { key: "product_code", label: "Product code" },
      { key: "product_name", label: "Product name" },
      { key: "quantity", label: "Quantity", type: "number" },
      { key: "unit", label: "Unit" },
      { key: "issued_to", label: "Issued to" },
      { key: "issued_date", label: "Issued date", type: "date" },
      { key: "expected_return", label: "Expected return", type: "date" },
      { key: "cost_amount", label: "Cost", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "status", label: "Status", type: "select", options: ["issued", "returned", "converted", "written_off"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "issued", quantity: 1, unit: "unit", currency: "UGX", cost_amount: 0 },
  }),

  "field-map": cfg({
    title: "Field Visits (Map Data)",
    description: "Visit locations with GPS for field map views",
    table: "sales_visit_plans",
    numberField: "plan_code",
    numberPrefix: "VP",
    statusField: "status",
    statusOptions: ["planned", "in_progress", "completed", "missed", "cancelled"],
    columns: [
      { key: "plan_code", label: "Code" },
      { key: "customer_name", label: "Customer" },
      { key: "location_name", label: "Location" },
      { key: "lat", label: "Lat" },
      { key: "lng", label: "Lng" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "plan_code", label: "Code", required: true, autoNumber: "VP", createOnly: true },
      { key: "customer_name", label: "Customer" },
      { key: "location_name", label: "Location" },
      { key: "lat", label: "Latitude", type: "number" },
      { key: "lng", label: "Longitude", type: "number" },
      { key: "rep_name", label: "Rep" },
      { key: "planned_date", label: "Date", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["planned", "in_progress", "completed", "missed", "cancelled"] },
    ],
    defaults: { status: "planned" },
  }),

  forecasts: cfg({
    title: "Sales Forecasts",
    description: "Commit, best-case and worst-case forecasts",
    table: "sales_forecasts",
    numberField: "forecast_code",
    numberPrefix: "FC",
    statusField: "status",
    statusOptions: ["draft", "submitted", "approved", "locked"],
    columns: [
      { key: "forecast_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "period_year", label: "Year" },
      { key: "period_month", label: "Month" },
      { key: "forecast_amount", label: "Forecast" },
      { key: "committed_amount", label: "Commit" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "forecast_code", label: "Code", required: true, autoNumber: "FC", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "period_year", label: "Year", type: "number", required: true },
      { key: "period_month", label: "Month", type: "number" },
      { key: "period_quarter", label: "Quarter", type: "number" },
      { key: "territory_code", label: "Territory" },
      { key: "team_code", label: "Team" },
      { key: "channel_code", label: "Channel" },
      { key: "product_code", label: "Product" },
      { key: "forecast_amount", label: "Forecast amount", type: "number" },
      { key: "committed_amount", label: "Committed", type: "number" },
      { key: "best_case", label: "Best case", type: "number" },
      { key: "worst_case", label: "Worst case", type: "number" },
      { key: "actual_amount", label: "Actual", type: "number" },
      { key: "confidence_pct", label: "Confidence %", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "owner_name", label: "Owner" },
      { key: "status", label: "Status", type: "select", options: ["draft", "submitted", "approved", "locked"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: {
      status: "draft",
      currency: "UGX",
      confidence_pct: 50,
      period_year: new Date().getFullYear(),
      forecast_amount: 0,
    },
  }),

  targets: cfg({
    title: "Sales Targets",
    description: "Rep, team, territory and company targets",
    table: "sales_targets",
    numberField: "target_code",
    numberPrefix: "TG",
    statusField: "status",
    statusOptions: ["active", "closed", "cancelled"],
    columns: [
      { key: "target_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "scope_type", label: "Scope" },
      { key: "scope_name", label: "Scope name" },
      { key: "target_amount", label: "Target" },
      { key: "actual_amount", label: "Actual" },
      { key: "achievement_pct", label: "Ach %" },
    ],
    fields: [
      { key: "target_code", label: "Code", required: true, autoNumber: "TG", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "scope_type", label: "Scope", type: "select", options: ["rep", "team", "territory", "channel", "company", "product"] },
      { key: "scope_name", label: "Scope name" },
      { key: "period_year", label: "Year", type: "number" },
      { key: "period_month", label: "Month", type: "number" },
      { key: "period_quarter", label: "Quarter", type: "number" },
      { key: "target_amount", label: "Target amount", type: "number" },
      { key: "actual_amount", label: "Actual amount", type: "number" },
      { key: "achievement_pct", label: "Achievement %", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "status", label: "Status", type: "select", options: ["active", "closed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: {
      scope_type: "rep",
      status: "active",
      currency: "UGX",
      period_year: new Date().getFullYear(),
      target_amount: 0,
      actual_amount: 0,
    },
  }),

  "commission-accrual": cfg({
    title: "Commission Accruals",
    description: "Commission lines by rep and order",
    table: "sales_commissions",
    statusField: "status",
    statusOptions: ["accrued", "approved", "paid", "cancelled"],
    columns: [
      { key: "rep_name", label: "Rep" },
      { key: "order_number", label: "Order" },
      { key: "basis_amount", label: "Basis" },
      { key: "commission_pct", label: "Pct" },
      { key: "commission_amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "rep_name", label: "Rep name" },
      { key: "order_number", label: "Order number" },
      { key: "basis_amount", label: "Basis amount", type: "number" },
      { key: "commission_pct", label: "Commission %", type: "number" },
      { key: "commission_amount", label: "Commission amount", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "period_month", label: "Period month", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["accrued", "approved", "paid", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "accrued", currency: "UGX", commission_pct: 3, basis_amount: 0, commission_amount: 0 },
  }),

  "return-lines": cfg({
    title: "Return Lines",
    description: "RMA line items",
    table: "sales_return_lines",
    columns: [
      { key: "product_code", label: "SKU" },
      { key: "product_name", label: "Product" },
      { key: "quantity", label: "Qty" },
      { key: "unit_price", label: "Price" },
      { key: "reason", label: "Reason" },
    ],
    fields: [
      { key: "product_code", label: "Product code" },
      { key: "product_name", label: "Product name" },
      { key: "description", label: "Description" },
      { key: "quantity", label: "Quantity", type: "number" },
      { key: "unit_price", label: "Unit price", type: "number" },
      { key: "reason", label: "Reason" },
    ],
    defaults: { quantity: 1, unit_price: 0 },
  }),

  support: cfg({
    title: "After-Sales Support",
    description: "Customer support tickets linked to sales",
    table: "support_tickets",
    numberField: "ticket_number",
    numberPrefix: "TK",
    statusField: "status",
    statusOptions: ["open", "in_progress", "resolved", "closed"],
    columns: [
      { key: "ticket_number", label: "Ticket #" },
      { key: "subject", label: "Subject" },
      { key: "customer_name", label: "Customer" },
      { key: "category", label: "Category" },
      { key: "priority", label: "Priority" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "ticket_number", label: "Ticket number", required: true, autoNumber: "TK", createOnly: true },
      { key: "subject", label: "Subject", required: true },
      { key: "description", label: "Description", type: "textarea" },
      { key: "customer_name", label: "Customer" },
      { key: "category", label: "Category", type: "select", options: ["general", "product", "delivery", "billing", "quality", "warranty"] },
      { key: "priority", label: "Priority", type: "select", options: ["low", "medium", "high", "urgent"] },
      { key: "status", label: "Status", type: "select", options: ["open", "in_progress", "resolved", "closed"] },
      { key: "related_module", label: "Module" },
    ],
    defaults: { category: "general", priority: "medium", status: "open", related_module: "sales" },
  }),

  documents: cfg({
    title: "Sales Documents",
    description: "Proposals, contracts, PO scans and specs",
    table: "sales_documents",
    numberField: "doc_code",
    numberPrefix: "DOC",
    statusField: "status",
    statusOptions: ["active", "archived", "draft"],
    columns: [
      { key: "doc_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "doc_type", label: "Type" },
      { key: "customer_name", label: "Customer" },
      { key: "version", label: "Ver" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "doc_code", label: "Code", required: true, autoNumber: "DOC", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "doc_type", label: "Type", type: "select", options: ["proposal", "contract", "po", "spec", "brochure", "tender", "other"] },
      { key: "related_type", label: "Related type" },
      { key: "related_number", label: "Related #" },
      { key: "customer_name", label: "Customer" },
      { key: "file_url", label: "File URL" },
      { key: "version", label: "Version", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "archived", "draft"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { doc_type: "proposal", status: "active", version: 1 },
  }),

  proposals: cfg({
    title: "Sales Proposals",
    description: "Proposal documents subset",
    table: "sales_documents",
    numberField: "doc_code",
    numberPrefix: "PROP",
    statusField: "status",
    statusOptions: ["active", "archived", "draft"],
    columns: [
      { key: "doc_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "customer_name", label: "Customer" },
      { key: "version", label: "Ver" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "doc_code", label: "Code", required: true, autoNumber: "PROP", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "doc_type", label: "Type", type: "select", options: ["proposal"] },
      { key: "customer_name", label: "Customer" },
      { key: "related_number", label: "Opp / Quote #" },
      { key: "file_url", label: "File URL" },
      { key: "version", label: "Version", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "archived", "draft"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { doc_type: "proposal", status: "draft", version: 1 },
  }),

  insights: cfg({
    title: "Sales Insights",
    description: "Stored sales recommendations and alerts",
    table: "sales_insights",
    statusField: "status",
    statusOptions: ["open", "acknowledged", "closed"],
    columns: [
      { key: "insight_type", label: "Type" },
      { key: "severity", label: "Severity" },
      { key: "title", label: "Title" },
      { key: "recommendation", label: "Recommendation" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "insight_type", label: "Type", required: true },
      { key: "severity", label: "Severity", type: "select", options: ["low", "medium", "high", "critical"] },
      { key: "title", label: "Title", required: true },
      { key: "recommendation", label: "Recommendation", type: "textarea", required: true },
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "product_code", label: "Product code" },
      { key: "score", label: "Score", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["open", "acknowledged", "closed"] },
    ],
    defaults: { severity: "medium", status: "open", score: 50 },
  }),

  notifications: cfg({
    title: "Sales Notifications",
    description: "In-app sales alerts and reminders",
    table: "sales_notifications",
    numberField: "notif_code",
    numberPrefix: "SN",
    statusField: "status",
    statusOptions: ["unread", "read", "archived"],
    columns: [
      { key: "notif_code", label: "Code" },
      { key: "title", label: "Title" },
      { key: "severity", label: "Severity" },
      { key: "recipient_name", label: "To" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "notif_code", label: "Code", required: true, autoNumber: "SN", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "body", label: "Body", type: "textarea" },
      { key: "severity", label: "Severity", type: "select", options: ["info", "warning", "critical"] },
      { key: "channel", label: "Channel", type: "select", options: ["in_app", "email", "sms"] },
      { key: "recipient_name", label: "Recipient" },
      { key: "related_type", label: "Related type" },
      { key: "related_number", label: "Related #" },
      { key: "status", label: "Status", type: "select", options: ["unread", "read", "archived"] },
    ],
    defaults: { severity: "info", channel: "in_app", status: "unread" },
  }),

  settings: cfg({
    title: "Sales Settings",
    description: "Company sales configuration keys",
    table: "sales_settings",
    numberField: "setting_key",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    searchCols: ["setting_key", "setting_value", "category", "description"],
    columns: [
      { key: "setting_key", label: "Key" },
      { key: "setting_value", label: "Value" },
      { key: "category", label: "Category" },
      { key: "description", label: "Description" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "setting_key", label: "Key", required: true },
      { key: "setting_value", label: "Value", required: true },
      { key: "category", label: "Category", type: "select", options: ["general", "credit", "quoting", "pricing", "commissions", "orders"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
    defaults: { category: "general", status: "active" },
  }),

  audit: cfg({
    title: "Sales Audit Log",
    description: "Create/update/delete audit trail",
    table: "sales_audit_log",
    columns: [
      { key: "action", label: "Action" },
      { key: "entity_table", label: "Table" },
      { key: "entity_code", label: "Code" },
      { key: "details", label: "Details" },
      { key: "created_at", label: "When" },
    ],
    fields: [
      { key: "action", label: "Action", required: true },
      { key: "entity_table", label: "Entity table" },
      { key: "entity_code", label: "Entity code" },
      { key: "details", label: "Details", type: "textarea" },
    ],
  }),

  // Aliases that reuse tables with different framing
  live: cfg({
    title: "Live Pipeline Snapshot",
    description: "Open opportunities for live board filtering",
    table: "sales_opportunities",
    numberField: "opportunity_number",
    numberPrefix: "OPP",
    statusField: "stage",
    statusOptions: ["prospecting", "qualification", "proposal", "negotiation", "won", "lost"],
    columns: [
      { key: "opportunity_number", label: "Opp #" },
      { key: "name", label: "Name" },
      { key: "stage", label: "Stage" },
      { key: "expected_value", label: "Value" },
      { key: "probability", label: "Prob %" },
      { key: "owner_name", label: "Owner" },
    ],
    fields: [
      { key: "opportunity_number", label: "Number", required: true, autoNumber: "OPP", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "stage", label: "Stage", type: "select", options: ["prospecting", "qualification", "proposal", "negotiation", "won", "lost"] },
      { key: "expected_value", label: "Value", type: "number" },
      { key: "probability", label: "Probability", type: "number" },
      { key: "owner_name", label: "Owner" },
    ],
    defaults: { stage: "prospecting", probability: 20, expected_value: 0 },
  }),

  "quote-to-cash": cfg({
    title: "Quote-to-Cash Orders",
    description: "Orders driving the quote-to-cash lifecycle",
    table: "sales_orders",
    numberField: "order_number",
    numberPrefix: "SO",
    statusField: "status",
    statusOptions: ["draft", "confirmed", "picking", "dispatched", "delivered", "cancelled", "closed"],
    columns: [
      { key: "order_number", label: "Order #" },
      { key: "status", label: "Status" },
      { key: "total_amount", label: "Total" },
      { key: "payment_status", label: "Payment" },
      { key: "fulfilment_status", label: "Fulfilment" },
      { key: "order_date", label: "Date" },
    ],
    fields: [
      { key: "order_number", label: "Order number", required: true, autoNumber: "SO", createOnly: true },
      { key: "status", label: "Status", type: "select", options: ["draft", "confirmed", "picking", "dispatched", "delivered", "cancelled", "closed"] },
      { key: "order_date", label: "Order date", type: "date" },
      { key: "total_amount", label: "Total", type: "number" },
      { key: "currency", label: "Currency", type: "select", options: ["UGX", "USD"] },
      { key: "payment_status", label: "Payment status", type: "select", options: ["unpaid", "partial", "paid", "overdue"] },
      { key: "fulfilment_status", label: "Fulfilment", type: "select", options: ["unfulfilled", "partial", "fulfilled"] },
      { key: "po_number", label: "PO number" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "draft", currency: "UGX", payment_status: "unpaid", fulfilment_status: "unfulfilled" },
  }),

  reports: cfg({
    title: "Sales Reports Data",
    description: "Insight store used for operational reports",
    table: "sales_insights",
    statusField: "status",
    statusOptions: ["open", "acknowledged", "closed"],
    columns: [
      { key: "insight_type", label: "Type" },
      { key: "title", label: "Title" },
      { key: "severity", label: "Severity" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "insight_type", label: "Type", required: true },
      { key: "title", label: "Title", required: true },
      { key: "recommendation", label: "Body", type: "textarea", required: true },
      { key: "severity", label: "Severity", type: "select", options: ["low", "medium", "high"] },
      { key: "status", label: "Status", type: "select", options: ["open", "acknowledged", "closed"] },
    ],
    defaults: { severity: "medium", status: "open" },
  }),

  analytics: cfg({
    title: "Sales Analytics Feed",
    description: "AI insight feed for analytics dashboards",
    table: "sales_ai_insights",
    numberField: "insight_code",
    numberPrefix: "AI",
    statusField: "status",
    statusOptions: ["open", "acknowledged", "closed"],
    columns: [
      { key: "insight_code", label: "Code" },
      { key: "insight_type", label: "Type" },
      { key: "title", label: "Title" },
      { key: "severity", label: "Severity" },
      { key: "score", label: "Score" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "insight_code", label: "Code", required: true, autoNumber: "AI", createOnly: true },
      { key: "insight_type", label: "Type", required: true },
      { key: "title", label: "Title", required: true },
      { key: "summary", label: "Summary", type: "textarea" },
      { key: "severity", label: "Severity", type: "select", options: ["info", "low", "medium", "high", "critical"] },
      { key: "score", label: "Score", type: "number" },
      { key: "recommendations", label: "Recommendations", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["open", "acknowledged", "closed"] },
    ],
    defaults: { severity: "medium", status: "open", score: 50 },
  }),
};
