/** Complete Production / MES navigation */

export const MES_MENU = [
  { title: "Production Dashboard", href: "/dashboard/production", group: "Overview" },
  { title: "Production Planning", href: "/dashboard/production/planning", group: "Planning" },
  { title: "Master Production Schedule", href: "/dashboard/production/mps", group: "Planning" },
  { title: "MRP", href: "/dashboard/production/mrp", group: "Planning" },
  { title: "Production Calendar", href: "/dashboard/production/calendar", group: "Planning" },
  { title: "Production Orders", href: "/dashboard/production/orders", group: "Execution" },
  { title: "Production Batches", href: "/dashboard/production/batches", group: "Execution" },
  { title: "Batch Scheduling", href: "/dashboard/production/batch-scheduling", group: "Execution" },
  { title: "Job Cards", href: "/dashboard/production/job-cards", group: "Execution" },
  { title: "Shop Floor Control", href: "/dashboard/production/shop-floor", group: "Execution" },
  { title: "Work Instructions", href: "/dashboard/production/work-instructions", group: "Execution" },
  { title: "Bill of Materials", href: "/dashboard/production/bom", group: "Engineering" },
  { title: "BOM Versions", href: "/dashboard/production/bom-versions", group: "Engineering" },
  { title: "Recipes & Formulas", href: "/dashboard/production/recipes", group: "Engineering" },
  { title: "Production Routing", href: "/dashboard/production/routing", group: "Engineering" },
  { title: "Routing Steps", href: "/dashboard/production/routing-steps", group: "Engineering" },
  { title: "Operations", href: "/dashboard/production/operations", group: "Engineering" },
  { title: "Work Centers", href: "/dashboard/production/work-centers", group: "Resources" },
  { title: "Production Lines", href: "/dashboard/production/lines", group: "Resources" },
  { title: "Machines", href: "/dashboard/production/machines", group: "Resources" },
  { title: "Machine Groups", href: "/dashboard/production/machine-groups", group: "Resources" },
  { title: "Machine Capacity", href: "/dashboard/production/machine-capacity", group: "Resources" },
  { title: "Machine Scheduling", href: "/dashboard/production/machine-scheduling", group: "Resources" },
  { title: "Machine Maintenance", href: "/dashboard/production/maintenance", group: "Resources" },
  { title: "Workers / Operators", href: "/dashboard/production/operators", group: "Workforce" },
  { title: "Shift Management", href: "/dashboard/production/shifts", group: "Workforce" },
  { title: "Quality Control", href: "/dashboard/production/quality", group: "Quality" },
  { title: "Quality Inspections", href: "/dashboard/production/inspections", group: "Quality" },
  { title: "Laboratory", href: "/dashboard/production/laboratory", group: "Quality" },
  { title: "NCR / Rejects", href: "/dashboard/production/ncr", group: "Quality" },
  { title: "Rework", href: "/dashboard/production/rework", group: "Quality" },
  { title: "Waste Management", href: "/dashboard/production/waste", group: "Quality" },
  { title: "Downtime", href: "/dashboard/production/downtime", group: "Performance" },
  { title: "OEE Monitoring", href: "/dashboard/production/oee", group: "Performance" },
  { title: "Machine Monitoring", href: "/dashboard/production/monitoring", group: "Performance" },
  { title: "IoT Devices", href: "/dashboard/production/iot", group: "Performance" },
  { title: "Energy / Utilities", href: "/dashboard/production/energy", group: "Performance" },
  { title: "Material Requests", href: "/dashboard/production/materials", group: "Materials" },
  { title: "Material Consumption", href: "/dashboard/production/consumption", group: "Materials" },
  { title: "Consumables", href: "/dashboard/production/consumables", group: "Materials" },
  { title: "Traceability", href: "/dashboard/production/traceability", group: "Materials" },
  { title: "Packaging Orders", href: "/dashboard/production/packaging", group: "Packaging" },
  { title: "Labels & QR", href: "/dashboard/production/labels", group: "Packaging" },
  { title: "Serial Numbers", href: "/dashboard/production/serials", group: "Packaging" },
  { title: "Palletization", href: "/dashboard/production/pallets", group: "Packaging" },
  { title: "Production Costing", href: "/dashboard/production/costing", group: "Costing" },
  { title: "Cost Variance", href: "/dashboard/production/cost-variance", group: "Costing" },
  { title: "Production Reports", href: "/dashboard/production/reports", group: "Analytics" },
  { title: "Analytics", href: "/dashboard/production/analytics", group: "Analytics" },
  { title: "AI Assistant", href: "/dashboard/production/ai", group: "Analytics" },
  { title: "Documents", href: "/dashboard/production/documents", group: "System" },
  { title: "Approvals", href: "/dashboard/production/approvals", group: "System" },
  { title: "Audit Logs", href: "/dashboard/production/audit", group: "System" },
  { title: "Production Settings", href: "/dashboard/production/settings", group: "System" },
] as const;
