import type { FleetEntityConfig } from "./types";

function cfg(
  partial: FleetEntityConfig
): FleetEntityConfig {
  return {
    searchCols: partial.searchCols || [
      "code",
      "name",
      "title",
      "registration",
      "driver_name",
      "full_name",
      "status",
      "driver_code",
      "trip_number",
      "work_order_number",
      "request_number",
    ],
    ...partial,
  };
}

/** Shared entity configs for FleetEntityPage routes */
export const FLEET_ENTITIES: Record<string, FleetEntityConfig> = {
  vehicles: cfg({
    title: "Vehicle Registry",
    description: "Full vehicle identity, lifecycle, assignment and compliance",
    table: "fleet_vehicles",
    numberField: "vehicle_code",
    numberPrefix: "VEH",
    searchCols: ["registration", "vehicle_code", "asset_tag", "make", "model", "vin", "status"],
    statusField: "status",
    statusOptions: ["available", "assigned", "in_use", "maintenance", "out_of_service", "disposed"],
    columns: [
      { key: "registration", label: "Registration" },
      { key: "vehicle_code", label: "Code" },
      { key: "make", label: "Make" },
      { key: "model", label: "Model" },
      { key: "vehicle_type", label: "Type" },
      { key: "status", label: "Status" },
      { key: "current_odometer", label: "Odometer" },
      { key: "assigned_driver_name", label: "Driver" },
    ],
    fields: [
      { key: "registration", label: "Registration", required: true },
      { key: "vehicle_code", label: "Vehicle code", autoNumber: "VEH", createOnly: true },
      { key: "asset_tag", label: "Asset tag" },
      { key: "vin", label: "VIN" },
      { key: "chassis_number", label: "Chassis number" },
      { key: "engine_number", label: "Engine number" },
      { key: "make", label: "Make / Brand" },
      { key: "model", label: "Model" },
      { key: "year", label: "Year", type: "number" },
      { key: "color", label: "Color" },
      { key: "vehicle_type", label: "Type", type: "select", options: ["truck", "van", "pickup", "motorcycle", "trailer", "bus"] },
      { key: "category_name", label: "Category" },
      { key: "fuel_type", label: "Fuel type", type: "select", options: ["diesel", "petrol", "hybrid", "electric", "cng"] },
      { key: "transmission", label: "Transmission", type: "select", options: ["manual", "automatic"] },
      { key: "capacity_kg", label: "Capacity (kg)", type: "number" },
      { key: "current_odometer", label: "Odometer", type: "number" },
      { key: "ownership_type", label: "Ownership", type: "select", options: ["owned", "leased", "rented", "third_party"] },
      { key: "purchase_date", label: "Purchase date", type: "date" },
      { key: "purchase_cost", label: "Purchase cost", type: "number" },
      { key: "current_value", label: "Current value", type: "number" },
      { key: "branch_name", label: "Branch" },
      { key: "depot_name", label: "Depot" },
      { key: "department_name", label: "Department" },
      { key: "project_name", label: "Project" },
      { key: "assigned_driver_name", label: "Assigned driver" },
      { key: "gps_tracker_id", label: "GPS tracker ID" },
      { key: "status", label: "Status", type: "select", options: ["available", "assigned", "in_use", "maintenance", "out_of_service", "disposed"] },
      { key: "lifecycle_stage", label: "Lifecycle", type: "select", options: ["acquisition", "active", "maintenance", "transfer", "disposal"] },
      { key: "qr_payload", label: "QR payload" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "available", fuel_type: "diesel", ownership_type: "owned", lifecycle_stage: "active" },
  }),

  categories: cfg({
    title: "Vehicle Categories",
    description: "Light, heavy, special-purpose classifications",
    table: "fleet_vehicle_categories",
    numberField: "code",
    numberPrefix: "CAT",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "description", label: "Description" },
    ],
    fields: [
      { key: "code", label: "Code", required: true, autoNumber: "CAT", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "description", label: "Description", type: "textarea" },
    ],
  }),

  types: cfg({
    title: "Vehicle Types",
    description: "Truck, van, trailer and fuel defaults",
    table: "fleet_vehicle_types",
    numberField: "code",
    numberPrefix: "TYP",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "default_fuel_type", label: "Default fuel" },
    ],
    fields: [
      { key: "code", label: "Code", required: true, autoNumber: "TYP", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "default_fuel_type", label: "Default fuel", type: "select", options: ["diesel", "petrol", "hybrid", "electric"] },
      { key: "description", label: "Description", type: "textarea" },
    ],
    defaults: { default_fuel_type: "diesel" },
  }),

  brands: cfg({
    title: "Vehicle Brands",
    description: "OEM brands registry",
    table: "fleet_vehicle_brands",
    numberField: "code",
    numberPrefix: "BRD",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "country", label: "Country" },
    ],
    fields: [
      { key: "code", label: "Code", required: true, autoNumber: "BRD", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "country", label: "Country" },
    ],
  }),

  models: cfg({
    title: "Vehicle Models",
    description: "Brand models and year ranges",
    table: "fleet_vehicle_models",
    numberField: "code",
    numberPrefix: "MDL",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Model" },
      { key: "brand_name", label: "Brand" },
      { key: "fuel_type", label: "Fuel" },
    ],
    fields: [
      { key: "code", label: "Code", required: true, autoNumber: "MDL", createOnly: true },
      { key: "name", label: "Model name", required: true },
      { key: "brand_name", label: "Brand" },
      { key: "fuel_type", label: "Fuel", type: "select", options: ["diesel", "petrol", "hybrid", "electric"] },
      { key: "year_from", label: "Year from", type: "number" },
      { key: "year_to", label: "Year to", type: "number" },
    ],
  }),

  documents: cfg({
    title: "Vehicle Documents",
    description: "Insurance, licenses, warranties, contracts",
    table: "fleet_vehicle_documents",
    columns: [
      { key: "title", label: "Title" },
      { key: "doc_type", label: "Type" },
      { key: "registration", label: "Vehicle" },
      { key: "expiry_date", label: "Expiry" },
      { key: "status", label: "Status" },
    ],
    statusField: "status",
    statusOptions: ["valid", "expiring", "expired", "archived"],
    fields: [
      { key: "title", label: "Title", required: true },
      { key: "doc_type", label: "Type", type: "select", options: ["insurance", "road_license", "inspection", "warranty", "contract", "manual", "other"], required: true },
      { key: "registration", label: "Registration" },
      { key: "doc_number", label: "Document number" },
      { key: "file_url", label: "File URL" },
      { key: "issued_date", label: "Issued", type: "date" },
      { key: "expiry_date", label: "Expiry", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["valid", "expiring", "expired", "archived"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "valid", doc_type: "other" },
  }),

  photos: cfg({
    title: "Vehicle Photos",
    description: "Exterior, interior and damage photos",
    table: "fleet_vehicle_photos",
    columns: [
      { key: "title", label: "Title" },
      { key: "registration", label: "Vehicle" },
      { key: "photo_type", label: "Type" },
      { key: "photo_url", label: "URL" },
    ],
    fields: [
      { key: "title", label: "Title" },
      { key: "registration", label: "Registration" },
      { key: "photo_type", label: "Type", type: "select", options: ["exterior", "interior", "damage", "plate", "other"] },
      { key: "photo_url", label: "Photo URL", required: true },
    ],
    defaults: { photo_type: "exterior" },
  }),

  assignments: cfg({
    title: "Vehicle Assignments",
    description: "Employee, department, project and driver allocation",
    table: "fleet_vehicle_assignments",
    numberField: "assignment_number",
    numberPrefix: "ASN",
    statusField: "status",
    statusOptions: ["active", "ended", "pending", "cancelled"],
    columns: [
      { key: "assignment_number", label: "Number" },
      { key: "registration", label: "Vehicle" },
      { key: "assignment_type", label: "Type" },
      { key: "assignee_name", label: "Assignee" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "assignment_number", label: "Number", autoNumber: "ASN", createOnly: true },
      { key: "registration", label: "Registration", required: true },
      { key: "assignment_type", label: "Type", type: "select", options: ["employee", "department", "project", "driver", "branch", "production"] },
      { key: "assignee_name", label: "Assignee name", required: true },
      { key: "department_name", label: "Department" },
      { key: "project_name", label: "Project" },
      { key: "branch_name", label: "Branch" },
      { key: "start_date", label: "Start", type: "date" },
      { key: "end_date", label: "End", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["active", "ended", "pending", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", assignment_type: "employee" },
  }),

  drivers: cfg({
    title: "Driver Profiles",
    description: "HR-linked drivers, licenses, scores and status",
    table: "fleet_drivers",
    numberField: "driver_code",
    numberPrefix: "DRV",
    statusField: "status",
    statusOptions: ["available", "on_trip", "off_duty", "leave", "suspended", "terminated"],
    searchCols: ["driver_code", "full_name", "license_number", "phone", "status"],
    columns: [
      { key: "driver_code", label: "Code" },
      { key: "full_name", label: "Name" },
      { key: "license_number", label: "License" },
      { key: "license_expiry", label: "Lic. expiry" },
      { key: "performance_score", label: "Perf." },
      { key: "safety_score", label: "Safety" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "driver_code", label: "Driver code", required: true, autoNumber: "DRV", createOnly: true },
      { key: "full_name", label: "Full name", required: true },
      { key: "phone", label: "Phone" },
      { key: "email", label: "Email" },
      { key: "emergency_contact", label: "Emergency contact" },
      { key: "emergency_phone", label: "Emergency phone" },
      { key: "license_number", label: "License number" },
      { key: "license_class", label: "License class" },
      { key: "license_expiry", label: "License expiry", type: "date" },
      { key: "medical_status", label: "Medical", type: "select", options: ["fit", "restricted", "unfit"] },
      { key: "medical_expiry", label: "Medical expiry", type: "date" },
      { key: "performance_score", label: "Performance score", type: "number" },
      { key: "safety_score", label: "Safety score", type: "number" },
      { key: "assigned_registration", label: "Assigned vehicle" },
      { key: "branch_name", label: "Branch" },
      { key: "depot_name", label: "Depot" },
      { key: "status", label: "Status", type: "select", options: ["available", "on_trip", "off_duty", "leave", "suspended", "terminated"] },
      { key: "photo_url", label: "Photo URL" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "available", medical_status: "fit", performance_score: 80, safety_score: 100 },
  }),

  licenses: cfg({
    title: "Driver Licenses",
    description: "License classes, expiry and authority",
    table: "fleet_driver_licenses",
    statusField: "status",
    statusOptions: ["valid", "expiring", "expired", "suspended"],
    columns: [
      { key: "driver_name", label: "Driver" },
      { key: "license_number", label: "Number" },
      { key: "license_class", label: "Class" },
      { key: "expiry_date", label: "Expiry" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "driver_name", label: "Driver name", required: true },
      { key: "license_number", label: "License number", required: true },
      { key: "license_class", label: "Class" },
      { key: "issued_date", label: "Issued", type: "date" },
      { key: "expiry_date", label: "Expiry", type: "date" },
      { key: "issuing_authority", label: "Authority" },
      { key: "status", label: "Status", type: "select", options: ["valid", "expiring", "expired", "suspended"] },
      { key: "file_url", label: "File URL" },
    ],
    defaults: { status: "valid" },
  }),

  certifications: cfg({
    title: "Driver Certifications",
    description: "Hazmat, defensive driving and other certs",
    table: "fleet_driver_certifications",
    statusField: "status",
    statusOptions: ["valid", "expiring", "expired"],
    columns: [
      { key: "driver_name", label: "Driver" },
      { key: "cert_name", label: "Certification" },
      { key: "expiry_date", label: "Expiry" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "driver_name", label: "Driver name", required: true },
      { key: "cert_name", label: "Certification", required: true },
      { key: "cert_number", label: "Cert number" },
      { key: "issued_date", label: "Issued", type: "date" },
      { key: "expiry_date", label: "Expiry", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["valid", "expiring", "expired"] },
      { key: "file_url", label: "File URL" },
    ],
    defaults: { status: "valid" },
  }),

  training: cfg({
    title: "Driver Training",
    description: "Safety and skills training records",
    table: "fleet_driver_training",
    statusField: "status",
    statusOptions: ["scheduled", "completed", "failed", "expired"],
    columns: [
      { key: "driver_name", label: "Driver" },
      { key: "training_title", label: "Training" },
      { key: "completed_date", label: "Completed" },
      { key: "score", label: "Score" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "driver_name", label: "Driver name", required: true },
      { key: "training_title", label: "Title", required: true },
      { key: "training_type", label: "Type", type: "select", options: ["safety", "defensive", "hazmat", "induction", "refresher"] },
      { key: "completed_date", label: "Completed", type: "date" },
      { key: "expiry_date", label: "Expiry", type: "date" },
      { key: "score", label: "Score", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["scheduled", "completed", "failed", "expired"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "completed", training_type: "safety" },
  }),

  medicals: cfg({
    title: "Driver Medicals",
    description: "Fitness examinations and expiry",
    table: "fleet_driver_medicals",
    statusField: "status",
    statusOptions: ["valid", "expiring", "expired", "unfit"],
    columns: [
      { key: "driver_name", label: "Driver" },
      { key: "exam_date", label: "Exam date" },
      { key: "result", label: "Result" },
      { key: "expiry_date", label: "Expiry" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "driver_name", label: "Driver name", required: true },
      { key: "exam_date", label: "Exam date", type: "date" },
      { key: "expiry_date", label: "Expiry", type: "date" },
      { key: "result", label: "Result", type: "select", options: ["fit", "restricted", "unfit"] },
      { key: "clinic_name", label: "Clinic" },
      { key: "file_url", label: "File URL" },
      { key: "status", label: "Status", type: "select", options: ["valid", "expiring", "expired", "unfit"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "valid", result: "fit" },
  }),

  violations: cfg({
    title: "Driver Violations",
    description: "Speeding, fines and policy breaches",
    table: "fleet_driver_violations",
    statusField: "status",
    statusOptions: ["open", "acknowledged", "paid", "closed"],
    columns: [
      { key: "driver_name", label: "Driver" },
      { key: "violation_type", label: "Type" },
      { key: "violation_date", label: "Date" },
      { key: "severity", label: "Severity" },
      { key: "fine_amount", label: "Fine" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "driver_name", label: "Driver name", required: true },
      { key: "vehicle_registration", label: "Registration" },
      { key: "violation_date", label: "Date", type: "date" },
      { key: "violation_type", label: "Type", required: true },
      { key: "severity", label: "Severity", type: "select", options: ["low", "medium", "high", "critical"] },
      { key: "fine_amount", label: "Fine amount", type: "number" },
      { key: "description", label: "Description", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["open", "acknowledged", "paid", "closed"] },
    ],
    defaults: { status: "open", severity: "medium" },
  }),

  "driver-performance": cfg({
    title: "Driver Performance",
    description: "Period scores, on-time and fuel efficiency",
    table: "fleet_driver_performance",
    columns: [
      { key: "driver_name", label: "Driver" },
      { key: "period_label", label: "Period" },
      { key: "trips_completed", label: "Trips" },
      { key: "on_time_pct", label: "On-time %" },
      { key: "overall_score", label: "Score" },
    ],
    fields: [
      { key: "driver_name", label: "Driver name", required: true },
      { key: "period_label", label: "Period", required: true },
      { key: "trips_completed", label: "Trips", type: "number" },
      { key: "km_driven", label: "Km driven", type: "number" },
      { key: "on_time_pct", label: "On-time %", type: "number" },
      { key: "fuel_efficiency", label: "Fuel efficiency", type: "number" },
      { key: "safety_score", label: "Safety score", type: "number" },
      { key: "customer_rating", label: "Customer rating", type: "number" },
      { key: "overall_score", label: "Overall score", type: "number" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  }),

  attendance: cfg({
    title: "Driver Attendance",
    description: "Daily check-in / check-out and leave",
    table: "fleet_driver_attendance",
    statusField: "status",
    statusOptions: ["present", "absent", "late", "leave", "half_day"],
    columns: [
      { key: "driver_name", label: "Driver" },
      { key: "attendance_date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "driver_name", label: "Driver name", required: true },
      { key: "attendance_date", label: "Date", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["present", "absent", "late", "leave", "half_day"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "present" },
  }),

  "gps-devices": cfg({
    title: "GPS Devices",
    description: "Teltonika, Geotab, Queclink and generic trackers",
    table: "fleet_gps_devices",
    numberField: "device_code",
    numberPrefix: "GPS",
    statusField: "status",
    statusOptions: ["online", "offline", "faulty", "unassigned"],
    columns: [
      { key: "device_code", label: "Code" },
      { key: "provider", label: "Provider" },
      { key: "registration", label: "Vehicle" },
      { key: "imei", label: "IMEI" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "device_code", label: "Device code", required: true, autoNumber: "GPS", createOnly: true },
      { key: "imei", label: "IMEI" },
      { key: "provider", label: "Provider", type: "select", options: ["teltonika", "ruptela", "queclink", "jimi", "geotab", "generic"] },
      { key: "registration", label: "Registration" },
      { key: "protocol", label: "Protocol" },
      { key: "status", label: "Status", type: "select", options: ["online", "offline", "faulty", "unassigned"] },
      { key: "firmware", label: "Firmware" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "online", provider: "generic" },
  }),

  "gps-locations": cfg({
    title: "GPS Location History",
    description: "Historical pings, speed and ignition",
    table: "fleet_gps_locations",
    columns: [
      { key: "registration", label: "Vehicle" },
      { key: "lat", label: "Lat" },
      { key: "lng", label: "Lng" },
      { key: "speed_kmh", label: "Speed" },
      { key: "ignition", label: "Ignition" },
      { key: "recorded_at", label: "Time" },
    ],
    fields: [
      { key: "registration", label: "Registration", required: true },
      { key: "driver_name", label: "Driver" },
      { key: "lat", label: "Latitude", type: "number", required: true },
      { key: "lng", label: "Longitude", type: "number", required: true },
      { key: "speed_kmh", label: "Speed km/h", type: "number" },
      { key: "heading", label: "Heading", type: "number" },
      { key: "odometer_km", label: "Odometer", type: "number" },
    ],
  }),

  geofences: cfg({
    title: "Geo-fencing",
    description: "Depots, plants and route corridors",
    table: "fleet_geofences",
    numberField: "fence_code",
    numberPrefix: "GF",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "fence_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "fence_type", label: "Type" },
      { key: "radius_m", label: "Radius m" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "fence_code", label: "Code", required: true, autoNumber: "GF", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "fence_type", label: "Type", type: "select", options: ["circle", "polygon", "route_corridor"] },
      { key: "center_lat", label: "Center lat", type: "number" },
      { key: "center_lng", label: "Center lng", type: "number" },
      { key: "radius_m", label: "Radius (m)", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", fence_type: "circle", radius_m: 500 },
  }),

  trips: cfg({
    title: "Trip Management",
    description: "End-to-end trip lifecycle and closure",
    table: "fleet_trips",
    numberField: "trip_number",
    numberPrefix: "TRP",
    statusField: "status",
    statusOptions: ["planned", "dispatched", "in_progress", "completed", "delayed", "cancelled", "closed"],
    columns: [
      { key: "trip_number", label: "Trip #" },
      { key: "purpose", label: "Purpose" },
      { key: "registration", label: "Vehicle" },
      { key: "driver_name", label: "Driver" },
      { key: "status", label: "Status" },
      { key: "planned_distance_km", label: "Km" },
    ],
    fields: [
      { key: "trip_number", label: "Trip number", autoNumber: "TRP", createOnly: true },
      { key: "purpose", label: "Purpose", required: true },
      { key: "customer_name", label: "Customer" },
      { key: "project_name", label: "Project" },
      { key: "registration", label: "Vehicle registration" },
      { key: "driver_name", label: "Driver" },
      { key: "origin", label: "Origin" },
      { key: "destination", label: "Destination" },
      { key: "route_name", label: "Route" },
      { key: "planned_distance_km", label: "Planned km", type: "number" },
      { key: "actual_distance_km", label: "Actual km", type: "number" },
      { key: "fuel_used_l", label: "Fuel used (L)", type: "number" },
      { key: "expense_total", label: "Expenses", type: "number" },
      { key: "cargo_description", label: "Cargo" },
      { key: "status", label: "Status", type: "select", options: ["planned", "dispatched", "in_progress", "completed", "delayed", "cancelled", "closed"] },
      { key: "qr_payload", label: "QR payload" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "planned" },
  }),

  "trip-requests": cfg({
    title: "Trip Requests",
    description: "Request → approve → assign pipeline",
    table: "fleet_trip_requests",
    numberField: "request_number",
    numberPrefix: "TRQ",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected", "assigned", "cancelled"],
    columns: [
      { key: "request_number", label: "Request #" },
      { key: "purpose", label: "Purpose" },
      { key: "requestor_name", label: "Requestor" },
      { key: "priority", label: "Priority" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "request_number", label: "Request number", autoNumber: "TRQ", createOnly: true },
      { key: "purpose", label: "Purpose", required: true },
      { key: "requestor_name", label: "Requestor" },
      { key: "department_name", label: "Department" },
      { key: "project_name", label: "Project" },
      { key: "customer_name", label: "Customer" },
      { key: "origin", label: "Origin" },
      { key: "destination", label: "Destination" },
      { key: "requested_date", label: "Requested date", type: "date" },
      { key: "passengers", label: "Passengers", type: "number" },
      { key: "cargo_description", label: "Cargo" },
      { key: "priority", label: "Priority", type: "select", options: ["low", "normal", "high", "urgent"] },
      { key: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected", "assigned", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "pending", priority: "normal" },
  }),

  routes: cfg({
    title: "Delivery Routes",
    description: "Planned routes with distance and ETA",
    table: "fleet_trip_routes",
    numberField: "route_code",
    numberPrefix: "RT",
    statusField: "status",
    statusOptions: ["active", "inactive", "archived"],
    columns: [
      { key: "route_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "origin", label: "Origin" },
      { key: "destination", label: "Destination" },
      { key: "distance_km", label: "Km" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "route_code", label: "Route code", required: true, autoNumber: "RT", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "origin", label: "Origin" },
      { key: "destination", label: "Destination" },
      { key: "distance_km", label: "Distance km", type: "number" },
      { key: "estimated_hours", label: "Est. hours", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive", "archived"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active" },
  }),

  dispatch: cfg({
    title: "Dispatch Scheduling",
    description: "Dispatch orders linked to trips and drivers",
    table: "fleet_dispatch_orders",
    numberField: "dispatch_number",
    numberPrefix: "DSP",
    statusField: "status",
    statusOptions: ["scheduled", "loading", "dispatched", "in_transit", "delivered", "failed", "cancelled"],
    columns: [
      { key: "dispatch_number", label: "Dispatch #" },
      { key: "customer_name", label: "Customer" },
      { key: "registration", label: "Vehicle" },
      { key: "driver_name", label: "Driver" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "dispatch_number", label: "Number", autoNumber: "DSP", createOnly: true },
      { key: "customer_name", label: "Customer" },
      { key: "warehouse_name", label: "Warehouse" },
      { key: "delivery_address", label: "Delivery address", type: "textarea" },
      { key: "registration", label: "Vehicle" },
      { key: "driver_name", label: "Driver" },
      { key: "priority", label: "Priority", type: "select", options: ["low", "normal", "high", "urgent"] },
      { key: "status", label: "Status", type: "select", options: ["scheduled", "loading", "dispatched", "in_transit", "delivered", "failed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "scheduled", priority: "normal" },
  }),

  deliveries: cfg({
    title: "Delivery Management",
    description: "Customer deliveries and status tracking",
    table: "fleet_deliveries",
    numberField: "delivery_number",
    numberPrefix: "DEL",
    statusField: "status",
    statusOptions: ["pending", "out_for_delivery", "delivered", "failed", "returned", "partial"],
    columns: [
      { key: "delivery_number", label: "Delivery #" },
      { key: "customer_name", label: "Customer" },
      { key: "scheduled_date", label: "Scheduled" },
      { key: "status", label: "Status" },
      { key: "weight_kg", label: "Weight" },
    ],
    fields: [
      { key: "delivery_number", label: "Number", autoNumber: "DEL", createOnly: true },
      { key: "customer_name", label: "Customer", required: true },
      { key: "delivery_address", label: "Address", type: "textarea" },
      { key: "contact_phone", label: "Phone" },
      { key: "scheduled_date", label: "Scheduled date", type: "date" },
      { key: "items_summary", label: "Items summary" },
      { key: "weight_kg", label: "Weight kg", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["pending", "out_for_delivery", "delivered", "failed", "returned", "partial"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "pending" },
  }),

  pod: cfg({
    title: "Proof of Delivery",
    description: "Signatures, photos, GPS and QR verification",
    table: "fleet_proof_of_delivery",
    numberField: "pod_number",
    numberPrefix: "POD",
    statusField: "status",
    statusOptions: ["captured", "verified", "disputed", "archived"],
    columns: [
      { key: "pod_number", label: "POD #" },
      { key: "customer_name", label: "Customer" },
      { key: "recipient_name", label: "Recipient" },
      { key: "delivered_at", label: "Delivered" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "pod_number", label: "POD number", autoNumber: "POD", createOnly: true },
      { key: "customer_name", label: "Customer" },
      { key: "recipient_name", label: "Recipient", required: true },
      { key: "signature_url", label: "Signature URL" },
      { key: "photo_url", label: "Photo URL" },
      { key: "barcode_scanned", label: "Barcode" },
      { key: "lat", label: "Latitude", type: "number" },
      { key: "lng", label: "Longitude", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["captured", "verified", "disputed", "archived"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "captured" },
  }),

  containers: cfg({
    title: "Container Tracking",
    description: "Container numbers, seals and trips",
    table: "fleet_containers",
    numberField: "container_number",
    numberPrefix: "CTR",
    statusField: "status",
    statusOptions: ["empty", "loaded", "in_transit", "delivered", "returned"],
    columns: [
      { key: "container_number", label: "Container #" },
      { key: "container_type", label: "Type" },
      { key: "seal_number", label: "Seal" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "container_number", label: "Container number", required: true, autoNumber: "CTR", createOnly: true },
      { key: "container_type", label: "Type", type: "select", options: ["20ft", "40ft", "40hc", "reefer", "tank"] },
      { key: "seal_number", label: "Seal number" },
      { key: "origin", label: "Origin" },
      { key: "destination", label: "Destination" },
      { key: "status", label: "Status", type: "select", options: ["empty", "loaded", "in_transit", "delivered", "returned"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "empty", container_type: "20ft" },
  }),

  cargo: cfg({
    title: "Cargo Management",
    description: "Load descriptions, weights and hazmat flags",
    table: "fleet_cargo",
    numberField: "cargo_number",
    numberPrefix: "CRG",
    statusField: "status",
    statusOptions: ["staged", "loaded", "in_transit", "unloaded", "damaged"],
    columns: [
      { key: "cargo_number", label: "Cargo #" },
      { key: "description", label: "Description" },
      { key: "quantity", label: "Qty" },
      { key: "weight_kg", label: "Weight" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "cargo_number", label: "Cargo number", autoNumber: "CRG", createOnly: true },
      { key: "description", label: "Description", required: true },
      { key: "quantity", label: "Quantity", type: "number" },
      { key: "uom", label: "UOM" },
      { key: "weight_kg", label: "Weight kg", type: "number" },
      { key: "volume_m3", label: "Volume m³", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["staged", "loaded", "in_transit", "unloaded", "damaged"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "loaded", uom: "EA" },
  }),

  "fuel-stations": cfg({
    title: "Fuel Stations",
    description: "Preferred and partner fuel stations",
    table: "fleet_fuel_stations",
    numberField: "station_code",
    numberPrefix: "ST",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "station_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "provider", label: "Provider" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "station_code", label: "Code", required: true, autoNumber: "ST", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "provider", label: "Provider" },
      { key: "address", label: "Address", type: "textarea" },
      { key: "fuel_types", label: "Fuel types" },
      { key: "contact_phone", label: "Phone" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active" },
  }),

  "fuel-cards": cfg({
    title: "Fuel Cards",
    description: "Card limits, assignment and expiry",
    table: "fleet_fuel_cards",
    statusField: "status",
    statusOptions: ["active", "blocked", "expired", "lost"],
    columns: [
      { key: "card_number", label: "Card #" },
      { key: "provider", label: "Provider" },
      { key: "registration", label: "Vehicle" },
      { key: "driver_name", label: "Driver" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "card_number", label: "Card number", required: true },
      { key: "provider", label: "Provider" },
      { key: "registration", label: "Vehicle" },
      { key: "driver_name", label: "Driver" },
      { key: "daily_limit", label: "Daily limit", type: "number" },
      { key: "monthly_limit", label: "Monthly limit", type: "number" },
      { key: "expiry_date", label: "Expiry", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["active", "blocked", "expired", "lost"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active" },
  }),

  "fuel-requests": cfg({
    title: "Fuel Requests",
    description: "Request and approve fuel issuance",
    table: "fleet_fuel_requests",
    numberField: "request_number",
    numberPrefix: "FRQ",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected", "issued", "cancelled"],
    columns: [
      { key: "request_number", label: "Request #" },
      { key: "registration", label: "Vehicle" },
      { key: "driver_name", label: "Driver" },
      { key: "litres_requested", label: "Litres" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "request_number", label: "Number", autoNumber: "FRQ", createOnly: true },
      { key: "registration", label: "Registration", required: true },
      { key: "driver_name", label: "Driver" },
      { key: "litres_requested", label: "Litres", type: "number", required: true },
      { key: "fuel_type", label: "Fuel type", type: "select", options: ["diesel", "petrol", "adblue"] },
      { key: "station_name", label: "Station" },
      { key: "purpose", label: "Purpose" },
      { key: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected", "issued", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "pending", fuel_type: "diesel" },
  }),

  "fuel-issuance": cfg({
    title: "Fuel Issuance / Transactions",
    description: "Posted fuel purchases and consumption",
    table: "fleet_fuel_transactions",
    numberField: "txn_number",
    numberPrefix: "FTX",
    statusField: "status",
    statusOptions: ["draft", "posted", "void"],
    columns: [
      { key: "txn_number", label: "Txn #" },
      { key: "registration", label: "Vehicle" },
      { key: "litres", label: "Litres" },
      { key: "total_cost", label: "Cost" },
      { key: "txn_date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "txn_number", label: "Txn number", autoNumber: "FTX", createOnly: true },
      { key: "registration", label: "Registration", required: true },
      { key: "driver_name", label: "Driver" },
      { key: "station_name", label: "Station" },
      { key: "card_number", label: "Fuel card" },
      { key: "fuel_type", label: "Fuel type", type: "select", options: ["diesel", "petrol", "adblue"] },
      { key: "litres", label: "Litres", type: "number", required: true },
      { key: "unit_price", label: "Unit price", type: "number" },
      { key: "total_cost", label: "Total cost", type: "number" },
      { key: "odometer_km", label: "Odometer", type: "number" },
      { key: "txn_date", label: "Date", type: "date" },
      { key: "cost_center", label: "Cost center" },
      { key: "project_name", label: "Project" },
      { key: "status", label: "Status", type: "select", options: ["draft", "posted", "void"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "posted", fuel_type: "diesel", currency_code: "UGX" },
  }),

  "fuel-consumption": cfg({
    title: "Fuel Consumption Logs",
    description: "Legacy and detailed fuel logs by vehicle",
    table: "fleet_fuel_logs",
    columns: [
      { key: "log_date", label: "Date" },
      { key: "litres", label: "Litres" },
      { key: "cost", label: "Cost" },
      { key: "odometer", label: "Odometer" },
      { key: "station", label: "Station" },
    ],
    fields: [
      { key: "log_date", label: "Date", type: "date" },
      { key: "litres", label: "Litres", type: "number", required: true },
      { key: "cost", label: "Cost", type: "number" },
      { key: "odometer", label: "Odometer", type: "number" },
      { key: "station", label: "Station" },
      { key: "driver_name", label: "Driver" },
      { key: "fuel_card_number", label: "Card" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  }),

  pm: cfg({
    title: "Preventive Maintenance Plans",
    description: "Mileage, time and engine-hour intervals",
    table: "fleet_maintenance_plans",
    numberField: "plan_code",
    numberPrefix: "PM",
    statusField: "status",
    statusOptions: ["active", "paused", "completed", "cancelled"],
    columns: [
      { key: "plan_code", label: "Plan" },
      { key: "name", label: "Name" },
      { key: "registration", label: "Vehicle" },
      { key: "next_due_date", label: "Next due" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "plan_code", label: "Plan code", autoNumber: "PM", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "registration", label: "Registration" },
      { key: "plan_type", label: "Type", type: "select", options: ["preventive", "predictive", "manufacturer"] },
      { key: "interval_km", label: "Interval km", type: "number" },
      { key: "interval_days", label: "Interval days", type: "number" },
      { key: "interval_engine_hours", label: "Engine hours", type: "number" },
      { key: "last_service_date", label: "Last service", type: "date" },
      { key: "next_due_date", label: "Next due", type: "date" },
      { key: "next_due_odometer", label: "Next odometer", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "paused", "completed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", plan_type: "preventive" },
  }),

  "work-orders": cfg({
    title: "Maintenance Work Orders",
    description: "Preventive, corrective and emergency jobs",
    table: "fleet_work_orders",
    numberField: "work_order_number",
    numberPrefix: "WO",
    statusField: "status",
    statusOptions: ["open", "assigned", "in_progress", "waiting_parts", "completed", "cancelled"],
    columns: [
      { key: "work_order_number", label: "WO #" },
      { key: "title", label: "Title" },
      { key: "registration", label: "Vehicle" },
      { key: "work_type", label: "Type" },
      { key: "status", label: "Status" },
      { key: "total_cost", label: "Cost" },
    ],
    fields: [
      { key: "work_order_number", label: "WO number", autoNumber: "WO", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "registration", label: "Registration" },
      { key: "work_type", label: "Type", type: "select", options: ["preventive", "corrective", "emergency", "inspection", "calibration"] },
      { key: "description", label: "Description", type: "textarea" },
      { key: "workshop_name", label: "Workshop" },
      { key: "mechanic_name", label: "Mechanic" },
      { key: "priority", label: "Priority", type: "select", options: ["low", "normal", "high", "urgent"] },
      { key: "status", label: "Status", type: "select", options: ["open", "assigned", "in_progress", "waiting_parts", "completed", "cancelled"] },
      { key: "scheduled_date", label: "Scheduled", type: "date" },
      { key: "labor_cost", label: "Labor cost", type: "number" },
      { key: "parts_cost", label: "Parts cost", type: "number" },
      { key: "total_cost", label: "Total cost", type: "number" },
      { key: "odometer_km", label: "Odometer", type: "number" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "open", work_type: "preventive", priority: "normal" },
  }),

  repairs: cfg({
    title: "Repair Orders",
    description: "Fault diagnosis and repair actions",
    table: "fleet_repair_orders",
    numberField: "repair_number",
    numberPrefix: "RO",
    statusField: "status",
    statusOptions: ["open", "in_progress", "completed", "cancelled"],
    columns: [
      { key: "repair_number", label: "RO #" },
      { key: "registration", label: "Vehicle" },
      { key: "fault_description", label: "Fault" },
      { key: "status", label: "Status" },
      { key: "cost", label: "Cost" },
    ],
    fields: [
      { key: "repair_number", label: "Repair number", autoNumber: "RO", createOnly: true },
      { key: "registration", label: "Registration" },
      { key: "fault_description", label: "Fault", required: true, type: "textarea" },
      { key: "repair_action", label: "Repair action", type: "textarea" },
      { key: "mechanic_name", label: "Mechanic" },
      { key: "status", label: "Status", type: "select", options: ["open", "in_progress", "completed", "cancelled"] },
      { key: "cost", label: "Cost", type: "number" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "open" },
  }),

  workshops: cfg({
    title: "Workshop Management",
    description: "Internal and external workshops",
    table: "fleet_workshops",
    numberField: "workshop_code",
    numberPrefix: "WS",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "workshop_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "location", label: "Location" },
      { key: "manager_name", label: "Manager" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "workshop_code", label: "Code", required: true, autoNumber: "WS", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "location", label: "Location" },
      { key: "manager_name", label: "Manager" },
      { key: "phone", label: "Phone" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active" },
  }),

  mechanics: cfg({
    title: "Mechanics",
    description: "Workshop technicians and specialties",
    table: "fleet_mechanics",
    numberField: "mechanic_code",
    numberPrefix: "MEC",
    statusField: "status",
    statusOptions: ["available", "busy", "off_duty", "leave"],
    columns: [
      { key: "mechanic_code", label: "Code" },
      { key: "full_name", label: "Name" },
      { key: "workshop_name", label: "Workshop" },
      { key: "specialty", label: "Specialty" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "mechanic_code", label: "Code", required: true, autoNumber: "MEC", createOnly: true },
      { key: "full_name", label: "Full name", required: true },
      { key: "workshop_name", label: "Workshop" },
      { key: "specialty", label: "Specialty" },
      { key: "phone", label: "Phone" },
      { key: "status", label: "Status", type: "select", options: ["available", "busy", "off_duty", "leave"] },
    ],
    defaults: { status: "available" },
  }),

  "spare-parts": cfg({
    title: "Spare Parts",
    description: "Fleet parts inventory and reorder levels",
    table: "fleet_spare_parts",
    numberField: "part_code",
    numberPrefix: "SP",
    statusField: "status",
    statusOptions: ["active", "obsolete", "out_of_stock"],
    columns: [
      { key: "part_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "quantity_on_hand", label: "Qty" },
      { key: "unit_cost", label: "Unit cost" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "part_code", label: "Part code", required: true, autoNumber: "SP", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "category", label: "Category" },
      { key: "unit_cost", label: "Unit cost", type: "number" },
      { key: "quantity_on_hand", label: "Qty on hand", type: "number" },
      { key: "reorder_level", label: "Reorder level", type: "number" },
      { key: "supplier_name", label: "Supplier" },
      { key: "location", label: "Location" },
      { key: "status", label: "Status", type: "select", options: ["active", "obsolete", "out_of_stock"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active" },
  }),

  tyres: cfg({
    title: "Tyre Management",
    description: "Position, tread, pressure and cost/km",
    table: "fleet_tyres",
    numberField: "tyre_code",
    numberPrefix: "TYR",
    statusField: "status",
    statusOptions: ["in_service", "spare", "retread", "scrapped"],
    columns: [
      { key: "tyre_code", label: "Code" },
      { key: "registration", label: "Vehicle" },
      { key: "position", label: "Position" },
      { key: "tread_depth_mm", label: "Tread mm" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "tyre_code", label: "Tyre code", required: true, autoNumber: "TYR", createOnly: true },
      { key: "registration", label: "Registration" },
      { key: "position", label: "Position", type: "select", options: ["FL", "FR", "RL", "RR", "spare", "trailer"] },
      { key: "brand", label: "Brand" },
      { key: "size_label", label: "Size" },
      { key: "serial_number", label: "Serial" },
      { key: "install_date", label: "Install date", type: "date" },
      { key: "pressure_psi", label: "Pressure PSI", type: "number" },
      { key: "tread_depth_mm", label: "Tread depth mm", type: "number" },
      { key: "cost", label: "Cost", type: "number" },
      { key: "supplier_name", label: "Supplier" },
      { key: "status", label: "Status", type: "select", options: ["in_service", "spare", "retread", "scrapped"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "in_service", position: "FL" },
  }),

  batteries: cfg({
    title: "Battery Management",
    description: "Battery install, warranty and voltage",
    table: "fleet_batteries",
    numberField: "battery_code",
    numberPrefix: "BAT",
    statusField: "status",
    statusOptions: ["in_service", "spare", "failed", "scrapped"],
    columns: [
      { key: "battery_code", label: "Code" },
      { key: "registration", label: "Vehicle" },
      { key: "brand", label: "Brand" },
      { key: "capacity_ah", label: "Ah" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "battery_code", label: "Code", required: true, autoNumber: "BAT", createOnly: true },
      { key: "registration", label: "Registration" },
      { key: "brand", label: "Brand" },
      { key: "capacity_ah", label: "Capacity Ah", type: "number" },
      { key: "install_date", label: "Install date", type: "date" },
      { key: "warranty_end", label: "Warranty end", type: "date" },
      { key: "voltage", label: "Voltage", type: "number" },
      { key: "cost", label: "Cost", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["in_service", "spare", "failed", "scrapped"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "in_service" },
  }),

  insurance: cfg({
    title: "Insurance Management",
    description: "Policies, premiums and expiry tracking",
    table: "fleet_insurance_policies",
    numberField: "policy_number",
    numberPrefix: "INS",
    statusField: "status",
    statusOptions: ["active", "expiring", "expired", "cancelled"],
    columns: [
      { key: "policy_number", label: "Policy #" },
      { key: "registration", label: "Vehicle" },
      { key: "insurer_name", label: "Insurer" },
      { key: "expiry_date", label: "Expiry" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "policy_number", label: "Policy number", required: true, autoNumber: "INS", createOnly: true },
      { key: "registration", label: "Registration" },
      { key: "insurer_name", label: "Insurer", required: true },
      { key: "policy_type", label: "Type", type: "select", options: ["comprehensive", "third_party", "fire_theft"] },
      { key: "premium", label: "Premium", type: "number" },
      { key: "coverage_amount", label: "Coverage", type: "number" },
      { key: "start_date", label: "Start", type: "date" },
      { key: "expiry_date", label: "Expiry", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["active", "expiring", "expired", "cancelled"] },
      { key: "file_url", label: "File URL" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", policy_type: "comprehensive" },
  }),

  "road-licenses": cfg({
    title: "Road Licenses",
    description: "Road tax and operating licenses",
    table: "fleet_road_licenses",
    numberField: "license_number",
    numberPrefix: "RL",
    statusField: "status",
    statusOptions: ["valid", "expiring", "expired"],
    columns: [
      { key: "license_number", label: "Number" },
      { key: "registration", label: "Vehicle" },
      { key: "expiry_date", label: "Expiry" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "license_number", label: "License number", required: true, autoNumber: "RL", createOnly: true },
      { key: "registration", label: "Registration" },
      { key: "issued_date", label: "Issued", type: "date" },
      { key: "expiry_date", label: "Expiry", type: "date" },
      { key: "authority", label: "Authority" },
      { key: "fee_amount", label: "Fee", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["valid", "expiring", "expired"] },
      { key: "file_url", label: "File URL" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "valid" },
  }),

  inspections: cfg({
    title: "Vehicle Inspections",
    description: "Periodic, pre-trip and compliance inspections",
    table: "fleet_inspections",
    numberField: "inspection_number",
    numberPrefix: "INSP",
    statusField: "status",
    statusOptions: ["scheduled", "completed", "failed", "cancelled"],
    columns: [
      { key: "inspection_number", label: "Insp #" },
      { key: "registration", label: "Vehicle" },
      { key: "inspection_type", label: "Type" },
      { key: "result", label: "Result" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "inspection_number", label: "Number", autoNumber: "INSP", createOnly: true },
      { key: "registration", label: "Registration" },
      { key: "inspection_type", label: "Type", type: "select", options: ["periodic", "pre_trip", "post_trip", "compliance", "safety"] },
      { key: "inspection_date", label: "Date", type: "date" },
      { key: "next_due_date", label: "Next due", type: "date" },
      { key: "result", label: "Result", type: "select", options: ["pass", "conditional", "fail"] },
      { key: "inspector_name", label: "Inspector" },
      { key: "findings", label: "Findings", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["scheduled", "completed", "failed", "cancelled"] },
      { key: "file_url", label: "File URL" },
    ],
    defaults: { status: "completed", result: "pass", inspection_type: "periodic" },
  }),

  accidents: cfg({
    title: "Accident Management",
    description: "Incidents, severity and damage estimates",
    table: "fleet_accidents",
    numberField: "accident_number",
    numberPrefix: "ACC",
    statusField: "status",
    statusOptions: ["reported", "investigating", "claim_filed", "closed"],
    columns: [
      { key: "accident_number", label: "Acc #" },
      { key: "registration", label: "Vehicle" },
      { key: "driver_name", label: "Driver" },
      { key: "severity", label: "Severity" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "accident_number", label: "Number", autoNumber: "ACC", createOnly: true },
      { key: "registration", label: "Registration" },
      { key: "driver_name", label: "Driver" },
      { key: "location", label: "Location" },
      { key: "severity", label: "Severity", type: "select", options: ["minor", "moderate", "major", "fatal"] },
      { key: "description", label: "Description", type: "textarea", required: true },
      { key: "police_report", label: "Police report #" },
      { key: "estimated_damage", label: "Est. damage", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["reported", "investigating", "claim_filed", "closed"] },
      { key: "photo_url", label: "Photo URL" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "reported", severity: "minor" },
  }),

  claims: cfg({
    title: "Claims Management",
    description: "Insurance claims lifecycle",
    table: "fleet_claims",
    numberField: "claim_number",
    numberPrefix: "CLM",
    statusField: "status",
    statusOptions: ["submitted", "under_review", "approved", "rejected", "paid", "closed"],
    columns: [
      { key: "claim_number", label: "Claim #" },
      { key: "registration", label: "Vehicle" },
      { key: "claim_amount", label: "Amount" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "claim_number", label: "Claim number", autoNumber: "CLM", createOnly: true },
      { key: "registration", label: "Registration" },
      { key: "claim_amount", label: "Claim amount", type: "number" },
      { key: "approved_amount", label: "Approved amount", type: "number" },
      { key: "submitted_date", label: "Submitted", type: "date" },
      { key: "settled_date", label: "Settled", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["submitted", "under_review", "approved", "rejected", "paid", "closed"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "submitted" },
  }),

  odometer: cfg({
    title: "Odometer Logs",
    description: "Manual and GPS odometer readings",
    table: "fleet_odometer_logs",
    columns: [
      { key: "registration", label: "Vehicle" },
      { key: "reading_date", label: "Date" },
      { key: "odometer_km", label: "Odometer" },
      { key: "source", label: "Source" },
    ],
    fields: [
      { key: "registration", label: "Registration", required: true },
      { key: "reading_date", label: "Date", type: "date" },
      { key: "odometer_km", label: "Odometer km", type: "number", required: true },
      { key: "source", label: "Source", type: "select", options: ["manual", "gps", "trip", "maintenance"] },
      { key: "driver_name", label: "Driver" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { source: "manual" },
  }),

  costs: cfg({
    title: "Fleet Costs",
    description: "Fuel, repairs, insurance, tolls and posting to finance",
    table: "fleet_costs",
    numberField: "cost_number",
    numberPrefix: "FC",
    statusField: "status",
    statusOptions: ["draft", "posted", "void"],
    columns: [
      { key: "cost_number", label: "Cost #" },
      { key: "registration", label: "Vehicle" },
      { key: "cost_type", label: "Type" },
      { key: "amount", label: "Amount" },
      { key: "cost_date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "cost_number", label: "Cost number", autoNumber: "FC", createOnly: true },
      { key: "registration", label: "Registration" },
      { key: "cost_type", label: "Type", type: "select", options: ["fuel", "repair", "insurance", "road_tax", "salary", "depreciation", "toll", "parking", "licensing", "leasing", "fine", "other"], required: true },
      { key: "cost_date", label: "Date", type: "date" },
      { key: "amount", label: "Amount", type: "number", required: true },
      { key: "currency_code", label: "Currency" },
      { key: "cost_center", label: "Cost center" },
      { key: "project_name", label: "Project" },
      { key: "gl_account", label: "GL account" },
      { key: "description", label: "Description" },
      { key: "status", label: "Status", type: "select", options: ["draft", "posted", "void"] },
    ],
    defaults: { status: "posted", currency_code: "UGX", cost_type: "other" },
  }),

  iot: cfg({
    title: "IoT Devices",
    description: "Temperature, engine and camera sensors",
    table: "fleet_iot_devices",
    numberField: "device_code",
    numberPrefix: "IOT",
    statusField: "status",
    statusOptions: ["online", "offline", "faulty"],
    columns: [
      { key: "device_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "device_type", label: "Type" },
      { key: "registration", label: "Vehicle" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "device_code", label: "Code", required: true, autoNumber: "IOT", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "device_type", label: "Type", type: "select", options: ["sensor", "temp", "engine", "camera", "tachograph"] },
      { key: "registration", label: "Registration" },
      { key: "status", label: "Status", type: "select", options: ["online", "offline", "faulty"] },
    ],
    defaults: { status: "online", device_type: "sensor" },
  }),

  telematics: cfg({
    title: "Telematics Readings",
    description: "Engine, fuel level, harsh events",
    table: "fleet_telematics",
    columns: [
      { key: "registration", label: "Vehicle" },
      { key: "engine_rpm", label: "RPM" },
      { key: "fuel_level_pct", label: "Fuel %" },
      { key: "coolant_temp_c", label: "Coolant °C" },
      { key: "reading_at", label: "Time" },
    ],
    fields: [
      { key: "registration", label: "Registration", required: true },
      { key: "engine_rpm", label: "Engine RPM", type: "number" },
      { key: "coolant_temp_c", label: "Coolant °C", type: "number" },
      { key: "fuel_level_pct", label: "Fuel %", type: "number" },
      { key: "battery_v", label: "Battery V", type: "number" },
      { key: "cargo_temp_c", label: "Cargo °C", type: "number" },
      { key: "harsh_brake", label: "Harsh brake", type: "number" },
      { key: "harsh_accel", label: "Harsh accel", type: "number" },
      { key: "overspeed", label: "Overspeed", type: "number" },
      { key: "dtc_codes", label: "DTC codes" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
  }),

  approvals: cfg({
    title: "Fleet Approvals",
    description: "Electronic approvals for trips, fuel and maintenance",
    table: "fleet_approvals",
    numberField: "approval_number",
    numberPrefix: "FAP",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected"],
    columns: [
      { key: "approval_number", label: "Approval #" },
      { key: "title", label: "Title" },
      { key: "entity_table", label: "Entity" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "approval_number", label: "Number", autoNumber: "FAP", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "entity_table", label: "Entity table", required: true },
      { key: "entity_code", label: "Entity code" },
      { key: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected"] },
      { key: "decision_notes", label: "Decision notes", type: "textarea" },
    ],
    defaults: { status: "pending" },
  }),

  notifications: cfg({
    title: "Fleet Notifications",
    description: "Compliance reminders and operational alerts",
    table: "fleet_notifications",
    columns: [
      { key: "title", label: "Title" },
      { key: "severity", label: "Severity" },
      { key: "category", label: "Category" },
      { key: "is_read", label: "Read" },
      { key: "created_at", label: "Created" },
    ],
    fields: [
      { key: "title", label: "Title", required: true },
      { key: "body", label: "Body", type: "textarea" },
      { key: "severity", label: "Severity", type: "select", options: ["info", "warning", "critical"] },
      { key: "category", label: "Category" },
    ],
    defaults: { severity: "info", category: "general" },
  }),

  settings: cfg({
    title: "Fleet Settings",
    description: "Company fleet configuration keys",
    table: "fleet_settings",
    columns: [
      { key: "setting_key", label: "Key" },
      { key: "setting_value", label: "Value" },
      { key: "description", label: "Description" },
    ],
    fields: [
      { key: "setting_key", label: "Key", required: true, createOnly: true },
      { key: "setting_value", label: "Value (JSON)", required: true },
      { key: "description", label: "Description" },
    ],
  }),

  audit: cfg({
    title: "Fleet Audit Logs",
    description: "Immutable action history",
    table: "fleet_audit_log",
    columns: [
      { key: "action", label: "Action" },
      { key: "entity_table", label: "Entity" },
      { key: "entity_code", label: "Code" },
      { key: "details", label: "Details" },
      { key: "created_at", label: "When" },
    ],
    fields: [
      { key: "action", label: "Action", required: true },
      { key: "entity_table", label: "Entity table" },
      { key: "entity_code", label: "Entity code" },
      { key: "details", label: "Details", type: "textarea" },
    ],
  }),
};

/** Map menu slugs that re-use another entity config */
export const FLEET_ENTITY_ALIASES: Record<string, string> = {
  ownership: "vehicles",
  "qr-tags": "vehicles",
  "asset-tags": "vehicles",
  "route-tracking": "routes",
  "trip-planner": "trips",
  "customer-deliveries": "deliveries",
  "supplier-pickups": "deliveries",
  "production-transport": "dispatch",
  "warehouse-logistics": "dispatch",
  corrective: "work-orders",
  maintenance: "work-orders",
  "service-history": "work-orders",
  mileage: "odometer",
  inventory: "spare-parts",
  "employee-allocation": "assignments",
  "department-allocation": "assignments",
  "project-allocation": "assignments",
  incidents: "accidents",
  speed: "telematics",
  engine: "telematics",
  temperature: "telematics",
  "driver-behavior": "telematics",
  "fuel-analytics": "fuel-issuance",
};

export function resolveFleetEntityConfig(
  slug: string
): FleetEntityConfig | null {
  const key = FLEET_ENTITY_ALIASES[slug] || slug;
  return FLEET_ENTITIES[key] ?? null;
}

export function listFleetEntityTables(): string[] {
  return [...new Set(Object.values(FLEET_ENTITIES).map((c) => c.table))];
}
