/** Complete Fleet & Transport navigation */

export const FLEET_MENU = [
  { title: "Fleet Dashboard", href: "/dashboard/fleet", group: "Overview" },
  { title: "Vehicle Registry", href: "/dashboard/fleet/vehicles", group: "Vehicles" },
  { title: "Vehicle Categories", href: "/dashboard/fleet/categories", group: "Vehicles" },
  { title: "Vehicle Types", href: "/dashboard/fleet/types", group: "Vehicles" },
  { title: "Vehicle Brands", href: "/dashboard/fleet/brands", group: "Vehicles" },
  { title: "Vehicle Models", href: "/dashboard/fleet/models", group: "Vehicles" },
  { title: "Vehicle Ownership", href: "/dashboard/fleet/ownership", group: "Vehicles" },
  { title: "Vehicle Documents", href: "/dashboard/fleet/documents", group: "Vehicles" },
  { title: "Vehicle Photos", href: "/dashboard/fleet/photos", group: "Vehicles" },
  { title: "Vehicle QR Tags", href: "/dashboard/fleet/qr-tags", group: "Vehicles" },
  { title: "Vehicle Asset Tags", href: "/dashboard/fleet/asset-tags", group: "Vehicles" },
  { title: "GPS Devices", href: "/dashboard/fleet/gps-devices", group: "Tracking" },
  { title: "Live Vehicle Map", href: "/dashboard/fleet/map", group: "Tracking" },
  { title: "GPS Locations", href: "/dashboard/fleet/gps-locations", group: "Tracking" },
  { title: "Route Tracking", href: "/dashboard/fleet/route-tracking", group: "Tracking" },
  { title: "Geo-fencing", href: "/dashboard/fleet/geofences", group: "Tracking" },
  { title: "Telematics", href: "/dashboard/fleet/telematics", group: "Tracking" },
  { title: "IoT Devices", href: "/dashboard/fleet/iot", group: "Tracking" },
  { title: "Speed Monitoring", href: "/dashboard/fleet/speed", group: "Tracking" },
  { title: "Engine Monitoring", href: "/dashboard/fleet/engine", group: "Tracking" },
  { title: "Temperature Monitoring", href: "/dashboard/fleet/temperature", group: "Tracking" },
  { title: "Driver Behavior", href: "/dashboard/fleet/driver-behavior", group: "Tracking" },
  { title: "Trip Management", href: "/dashboard/fleet/trips", group: "Trips" },
  { title: "Trip Planner", href: "/dashboard/fleet/trip-planner", group: "Trips" },
  { title: "Trip Requests", href: "/dashboard/fleet/trip-requests", group: "Trips" },
  { title: "Delivery Routes", href: "/dashboard/fleet/routes", group: "Trips" },
  { title: "Dispatch Scheduling", href: "/dashboard/fleet/dispatch", group: "Transport" },
  { title: "Delivery Management", href: "/dashboard/fleet/deliveries", group: "Transport" },
  { title: "Customer Deliveries", href: "/dashboard/fleet/customer-deliveries", group: "Transport" },
  { title: "Supplier Pickups", href: "/dashboard/fleet/supplier-pickups", group: "Transport" },
  { title: "Container Tracking", href: "/dashboard/fleet/containers", group: "Transport" },
  { title: "Cargo Management", href: "/dashboard/fleet/cargo", group: "Transport" },
  { title: "Proof of Delivery", href: "/dashboard/fleet/pod", group: "Transport" },
  { title: "Production Transport", href: "/dashboard/fleet/production-transport", group: "Transport" },
  { title: "Warehouse Logistics", href: "/dashboard/fleet/warehouse-logistics", group: "Transport" },
  { title: "Driver Profiles", href: "/dashboard/fleet/drivers", group: "Drivers" },
  { title: "Driver Licenses", href: "/dashboard/fleet/licenses", group: "Drivers" },
  { title: "Driver Certifications", href: "/dashboard/fleet/certifications", group: "Drivers" },
  { title: "Driver Training", href: "/dashboard/fleet/training", group: "Drivers" },
  { title: "Driver Medicals", href: "/dashboard/fleet/medicals", group: "Drivers" },
  { title: "Driver Violations", href: "/dashboard/fleet/violations", group: "Drivers" },
  { title: "Driver Performance", href: "/dashboard/fleet/driver-performance", group: "Drivers" },
  { title: "Driver Attendance", href: "/dashboard/fleet/attendance", group: "Drivers" },
  { title: "Fuel Stations", href: "/dashboard/fleet/fuel-stations", group: "Fuel" },
  { title: "Fuel Cards", href: "/dashboard/fleet/fuel-cards", group: "Fuel" },
  { title: "Fuel Requests", href: "/dashboard/fleet/fuel-requests", group: "Fuel" },
  { title: "Fuel Issuance", href: "/dashboard/fleet/fuel-issuance", group: "Fuel" },
  { title: "Fuel Consumption", href: "/dashboard/fleet/fuel-consumption", group: "Fuel" },
  { title: "Fuel Analytics", href: "/dashboard/fleet/fuel-analytics", group: "Fuel" },
  { title: "Maintenance Dashboard", href: "/dashboard/fleet/maintenance", group: "Maintenance" },
  { title: "Preventive Maintenance", href: "/dashboard/fleet/pm", group: "Maintenance" },
  { title: "Corrective Maintenance", href: "/dashboard/fleet/corrective", group: "Maintenance" },
  { title: "Repair Orders", href: "/dashboard/fleet/repairs", group: "Maintenance" },
  { title: "Work Orders", href: "/dashboard/fleet/work-orders", group: "Maintenance" },
  { title: "Workshop Management", href: "/dashboard/fleet/workshops", group: "Maintenance" },
  { title: "Mechanics", href: "/dashboard/fleet/mechanics", group: "Maintenance" },
  { title: "Service History", href: "/dashboard/fleet/service-history", group: "Maintenance" },
  { title: "Spare Parts", href: "/dashboard/fleet/spare-parts", group: "Maintenance" },
  { title: "Tyre Management", href: "/dashboard/fleet/tyres", group: "Assets" },
  { title: "Battery Management", href: "/dashboard/fleet/batteries", group: "Assets" },
  { title: "Insurance Management", href: "/dashboard/fleet/insurance", group: "Compliance" },
  { title: "Road License", href: "/dashboard/fleet/road-licenses", group: "Compliance" },
  { title: "Vehicle Inspection", href: "/dashboard/fleet/inspections", group: "Compliance" },
  { title: "Accident Management", href: "/dashboard/fleet/accidents", group: "Compliance" },
  { title: "Incident Reports", href: "/dashboard/fleet/incidents", group: "Compliance" },
  { title: "Claims Management", href: "/dashboard/fleet/claims", group: "Compliance" },
  { title: "Fleet Inventory", href: "/dashboard/fleet/inventory", group: "Allocation" },
  { title: "Vehicle Assignments", href: "/dashboard/fleet/assignments", group: "Allocation" },
  { title: "Employee Allocation", href: "/dashboard/fleet/employee-allocation", group: "Allocation" },
  { title: "Department Allocation", href: "/dashboard/fleet/department-allocation", group: "Allocation" },
  { title: "Project Allocation", href: "/dashboard/fleet/project-allocation", group: "Allocation" },
  { title: "Mileage Tracking", href: "/dashboard/fleet/mileage", group: "Costs" },
  { title: "Odometer Logs", href: "/dashboard/fleet/odometer", group: "Costs" },
  { title: "Fleet Costs", href: "/dashboard/fleet/costs", group: "Costs" },
  { title: "AI Fleet Assistant", href: "/dashboard/fleet/ai", group: "Analytics" },
  { title: "Fleet Reports", href: "/dashboard/fleet/reports", group: "Analytics" },
  { title: "Fleet Analytics", href: "/dashboard/fleet/analytics", group: "Analytics" },
  { title: "Approvals", href: "/dashboard/fleet/approvals", group: "System" },
  { title: "Notifications", href: "/dashboard/fleet/notifications", group: "System" },
  { title: "Audit Logs", href: "/dashboard/fleet/audit", group: "System" },
  { title: "Fleet Settings", href: "/dashboard/fleet/settings", group: "System" },
] as const;
