-- ============================================================
-- RBAC catalog: permissions + 2120 roles + access (role_permissions)
-- Generated by scripts/gen-role-catalog-migration.mjs
-- Modules: 53 x levels: 8 x variants: 5 = 2120 roles
-- Permission slugs seeded: 313
-- Idempotent (safe to re-run)
-- ============================================================

-- 1) Ensure full permission catalog
INSERT INTO permissions (name, slug, module, description)
VALUES
  ('perm:ast.ai', 'ast.ai', 'ast', 'Catalog permission: ast.ai'),
  ('perm:ast.assign', 'ast.assign', 'ast', 'Catalog permission: ast.assign'),
  ('perm:ast.audit', 'ast.audit', 'ast', 'Catalog permission: ast.audit'),
  ('perm:ast.manage', 'ast.manage', 'ast', 'Catalog permission: ast.manage'),
  ('perm:ast.print', 'ast.print', 'ast', 'Catalog permission: ast.print'),
  ('perm:ast.view', 'ast.view', 'ast', 'Catalog permission: ast.view'),
  ('perm:att.admin', 'att.admin', 'att', 'Catalog permission: att.admin'),
  ('perm:att.ai', 'att.ai', 'att', 'Catalog permission: att.ai'),
  ('perm:att.approve', 'att.approve', 'att', 'Catalog permission: att.approve'),
  ('perm:att.clock', 'att.clock', 'att', 'Catalog permission: att.clock'),
  ('perm:att.devices', 'att.devices', 'att', 'Catalog permission: att.devices'),
  ('perm:att.field', 'att.field', 'att', 'Catalog permission: att.field'),
  ('perm:att.manage', 'att.manage', 'att', 'Catalog permission: att.manage'),
  ('perm:att.view', 'att.view', 'att', 'Catalog permission: att.view'),
  ('perm:audit.manage', 'audit.manage', 'audit', 'Catalog permission: audit.manage'),
  ('perm:audit.view', 'audit.view', 'audit', 'Catalog permission: audit.view'),
  ('perm:billing.manage', 'billing.manage', 'billing', 'Catalog permission: billing.manage'),
  ('perm:billing.view', 'billing.view', 'billing', 'Catalog permission: billing.view'),
  ('perm:brand.ai', 'brand.ai', 'brand', 'Catalog permission: brand.ai'),
  ('perm:brand.approve', 'brand.approve', 'brand', 'Catalog permission: brand.approve'),
  ('perm:brand.assets', 'brand.assets', 'brand', 'Catalog permission: brand.assets'),
  ('perm:brand.design', 'brand.design', 'brand', 'Catalog permission: brand.design'),
  ('perm:brand.manage', 'brand.manage', 'brand', 'Catalog permission: brand.manage'),
  ('perm:brand.publish', 'brand.publish', 'brand', 'Catalog permission: brand.publish'),
  ('perm:brand.view', 'brand.view', 'brand', 'Catalog permission: brand.view'),
  ('perm:comm.admin', 'comm.admin', 'comm', 'Catalog permission: comm.admin'),
  ('perm:comm.ai', 'comm.ai', 'comm', 'Catalog permission: comm.ai'),
  ('perm:comm.broadcast', 'comm.broadcast', 'comm', 'Catalog permission: comm.broadcast'),
  ('perm:comm.manage', 'comm.manage', 'comm', 'Catalog permission: comm.manage'),
  ('perm:comm.templates', 'comm.templates', 'comm', 'Catalog permission: comm.templates'),
  ('perm:comm.view', 'comm.view', 'comm', 'Catalog permission: comm.view'),
  ('perm:crm.admin', 'crm.admin', 'crm', 'Catalog permission: crm.admin'),
  ('perm:crm.ai', 'crm.ai', 'crm', 'Catalog permission: crm.ai'),
  ('perm:crm.credit', 'crm.credit', 'crm', 'Catalog permission: crm.credit'),
  ('perm:crm.export', 'crm.export', 'crm', 'Catalog permission: crm.export'),
  ('perm:crm.leads', 'crm.leads', 'crm', 'Catalog permission: crm.leads'),
  ('perm:crm.manage', 'crm.manage', 'crm', 'Catalog permission: crm.manage'),
  ('perm:crm.marketing', 'crm.marketing', 'crm', 'Catalog permission: crm.marketing'),
  ('perm:crm.opportunities', 'crm.opportunities', 'crm', 'Catalog permission: crm.opportunities'),
  ('perm:crm.portal', 'crm.portal', 'crm', 'Catalog permission: crm.portal'),
  ('perm:crm.service', 'crm.service', 'crm', 'Catalog permission: crm.service'),
  ('perm:crm.view', 'crm.view', 'crm', 'Catalog permission: crm.view'),
  ('perm:dashboard.view', 'dashboard.view', 'dashboard', 'Catalog permission: dashboard.view'),
  ('perm:di.admin', 'di.admin', 'di', 'Catalog permission: di.admin'),
  ('perm:di.ai', 'di.ai', 'di', 'Catalog permission: di.ai'),
  ('perm:di.biometrics', 'di.biometrics', 'di', 'Catalog permission: di.biometrics'),
  ('perm:di.cards', 'di.cards', 'di', 'Catalog permission: di.cards'),
  ('perm:di.clearance', 'di.clearance', 'di', 'Catalog permission: di.clearance'),
  ('perm:di.manage', 'di.manage', 'di', 'Catalog permission: di.manage'),
  ('perm:di.org', 'di.org', 'di', 'Catalog permission: di.org'),
  ('perm:di.provision', 'di.provision', 'di', 'Catalog permission: di.provision'),
  ('perm:di.view', 'di.view', 'di', 'Catalog permission: di.view'),
  ('perm:dispatch.manage', 'dispatch.manage', 'dispatch', 'Catalog permission: dispatch.manage'),
  ('perm:dispatch.view', 'dispatch.view', 'dispatch', 'Catalog permission: dispatch.view'),
  ('perm:distributors.view', 'distributors.view', 'distributors', 'Catalog permission: distributors.view'),
  ('perm:dsp.ai', 'dsp.ai', 'dsp', 'Catalog permission: dsp.ai'),
  ('perm:dsp.approve', 'dsp.approve', 'dsp', 'Catalog permission: dsp.approve'),
  ('perm:dsp.manage', 'dsp.manage', 'dsp', 'Catalog permission: dsp.manage'),
  ('perm:dsp.operate', 'dsp.operate', 'dsp', 'Catalog permission: dsp.operate'),
  ('perm:dsp.track', 'dsp.track', 'dsp', 'Catalog permission: dsp.track'),
  ('perm:dsp.view', 'dsp.view', 'dsp', 'Catalog permission: dsp.view'),
  ('perm:eal.ai', 'eal.ai', 'eal', 'Catalog permission: eal.ai'),
  ('perm:eal.archive', 'eal.archive', 'eal', 'Catalog permission: eal.archive'),
  ('perm:eal.compliance', 'eal.compliance', 'eal', 'Catalog permission: eal.compliance'),
  ('perm:eal.config', 'eal.config', 'eal', 'Catalog permission: eal.config'),
  ('perm:eal.executive', 'eal.executive', 'eal', 'Catalog permission: eal.executive'),
  ('perm:eal.export', 'eal.export', 'eal', 'Catalog permission: eal.export'),
  ('perm:eal.infra', 'eal.infra', 'eal', 'Catalog permission: eal.infra'),
  ('perm:eal.investigate', 'eal.investigate', 'eal', 'Catalog permission: eal.investigate'),
  ('perm:eal.manage', 'eal.manage', 'eal', 'Catalog permission: eal.manage'),
  ('perm:eal.security', 'eal.security', 'eal', 'Catalog permission: eal.security'),
  ('perm:eal.view', 'eal.view', 'eal', 'Catalog permission: eal.view'),
  ('perm:ec.admin', 'ec.admin', 'ec', 'Catalog permission: ec.admin'),
  ('perm:ec.ai', 'ec.ai', 'ec', 'Catalog permission: ec.ai'),
  ('perm:ec.documents', 'ec.documents', 'ec', 'Catalog permission: ec.documents'),
  ('perm:ec.governance', 'ec.governance', 'ec', 'Catalog permission: ec.governance'),
  ('perm:ec.manage', 'ec.manage', 'ec', 'Catalog permission: ec.manage'),
  ('perm:ec.risk', 'ec.risk', 'ec', 'Catalog permission: ec.risk'),
  ('perm:ec.structure', 'ec.structure', 'ec', 'Catalog permission: ec.structure'),
  ('perm:ec.view', 'ec.view', 'ec', 'Catalog permission: ec.view'),
  ('perm:finance.admin', 'finance.admin', 'finance', 'Catalog permission: finance.admin'),
  ('perm:finance.ai', 'finance.ai', 'finance', 'Catalog permission: finance.ai'),
  ('perm:finance.approve', 'finance.approve', 'finance', 'Catalog permission: finance.approve'),
  ('perm:finance.bank', 'finance.bank', 'finance', 'Catalog permission: finance.bank'),
  ('perm:finance.cfo', 'finance.cfo', 'finance', 'Catalog permission: finance.cfo'),
  ('perm:finance.close', 'finance.close', 'finance', 'Catalog permission: finance.close'),
  ('perm:finance.consolidate', 'finance.consolidate', 'finance', 'Catalog permission: finance.consolidate'),
  ('perm:finance.costing', 'finance.costing', 'finance', 'Catalog permission: finance.costing'),
  ('perm:finance.fpa', 'finance.fpa', 'finance', 'Catalog permission: finance.fpa'),
  ('perm:finance.manage', 'finance.manage', 'finance', 'Catalog permission: finance.manage'),
  ('perm:finance.multibook', 'finance.multibook', 'finance', 'Catalog permission: finance.multibook'),
  ('perm:finance.post', 'finance.post', 'finance', 'Catalog permission: finance.post'),
  ('perm:finance.tax', 'finance.tax', 'finance', 'Catalog permission: finance.tax'),
  ('perm:finance.tax.manage', 'finance.tax.manage', 'finance', 'Catalog permission: finance.tax.manage'),
  ('perm:finance.treasury', 'finance.treasury', 'finance', 'Catalog permission: finance.treasury'),
  ('perm:finance.view', 'finance.view', 'finance', 'Catalog permission: finance.view'),
  ('perm:fleet.admin', 'fleet.admin', 'fleet', 'Catalog permission: fleet.admin'),
  ('perm:fleet.ai', 'fleet.ai', 'fleet', 'Catalog permission: fleet.ai'),
  ('perm:fleet.approve', 'fleet.approve', 'fleet', 'Catalog permission: fleet.approve'),
  ('perm:fleet.dispatch', 'fleet.dispatch', 'fleet', 'Catalog permission: fleet.dispatch'),
  ('perm:fleet.drivers', 'fleet.drivers', 'fleet', 'Catalog permission: fleet.drivers'),
  ('perm:fleet.fuel', 'fleet.fuel', 'fleet', 'Catalog permission: fleet.fuel'),
  ('perm:fleet.maintenance', 'fleet.maintenance', 'fleet', 'Catalog permission: fleet.maintenance'),
  ('perm:fleet.manage', 'fleet.manage', 'fleet', 'Catalog permission: fleet.manage'),
  ('perm:fleet.track', 'fleet.track', 'fleet', 'Catalog permission: fleet.track'),
  ('perm:fleet.view', 'fleet.view', 'fleet', 'Catalog permission: fleet.view'),
  ('perm:fraud.manage', 'fraud.manage', 'fraud', 'Catalog permission: fraud.manage'),
  ('perm:hc.admin', 'hc.admin', 'hc', 'Catalog permission: hc.admin'),
  ('perm:hc.ai', 'hc.ai', 'hc', 'Catalog permission: hc.ai'),
  ('perm:hc.announce', 'hc.announce', 'hc', 'Catalog permission: hc.announce'),
  ('perm:hc.manage', 'hc.manage', 'hc', 'Catalog permission: hc.manage'),
  ('perm:hc.meetings', 'hc.meetings', 'hc', 'Catalog permission: hc.meetings'),
  ('perm:hc.view', 'hc.view', 'hc', 'Catalog permission: hc.view'),
  ('perm:hr.manage', 'hr.manage', 'hr', 'Catalog permission: hr.manage'),
  ('perm:hr.payroll', 'hr.payroll', 'hr', 'Catalog permission: hr.payroll'),
  ('perm:hr.performance', 'hr.performance', 'hr', 'Catalog permission: hr.performance'),
  ('perm:hr.recruit', 'hr.recruit', 'hr', 'Catalog permission: hr.recruit'),
  ('perm:hr.self', 'hr.self', 'hr', 'Catalog permission: hr.self'),
  ('perm:hr.training', 'hr.training', 'hr', 'Catalog permission: hr.training'),
  ('perm:hr.view', 'hr.view', 'hr', 'Catalog permission: hr.view'),
  ('perm:iam.abac', 'iam.abac', 'iam', 'Catalog permission: iam.abac'),
  ('perm:iam.approvals', 'iam.approvals', 'iam', 'Catalog permission: iam.approvals'),
  ('perm:iam.governance', 'iam.governance', 'iam', 'Catalog permission: iam.governance'),
  ('perm:iam.import', 'iam.import', 'iam', 'Catalog permission: iam.import'),
  ('perm:iam.manage', 'iam.manage', 'iam', 'Catalog permission: iam.manage'),
  ('perm:iam.mfa', 'iam.mfa', 'iam', 'Catalog permission: iam.mfa'),
  ('perm:iam.password', 'iam.password', 'iam', 'Catalog permission: iam.password'),
  ('perm:iam.provision', 'iam.provision', 'iam', 'Catalog permission: iam.provision'),
  ('perm:iam.roles', 'iam.roles', 'iam', 'Catalog permission: iam.roles'),
  ('perm:iam.security', 'iam.security', 'iam', 'Catalog permission: iam.security'),
  ('perm:iam.sessions', 'iam.sessions', 'iam', 'Catalog permission: iam.sessions'),
  ('perm:iam.view', 'iam.view', 'iam', 'Catalog permission: iam.view'),
  ('perm:intg.manage', 'intg.manage', 'intg', 'Catalog permission: intg.manage'),
  ('perm:intg.view', 'intg.view', 'intg', 'Catalog permission: intg.view'),
  ('perm:inventory.adjust', 'inventory.adjust', 'inventory', 'Catalog permission: inventory.adjust'),
  ('perm:inventory.grn', 'inventory.grn', 'inventory', 'Catalog permission: inventory.grn'),
  ('perm:inventory.qc', 'inventory.qc', 'inventory', 'Catalog permission: inventory.qc'),
  ('perm:inventory.transfer', 'inventory.transfer', 'inventory', 'Catalog permission: inventory.transfer'),
  ('perm:inventory.valuation', 'inventory.valuation', 'inventory', 'Catalog permission: inventory.valuation'),
  ('perm:inventory.view', 'inventory.view', 'inventory', 'Catalog permission: inventory.view'),
  ('perm:invoices.manage', 'invoices.manage', 'invoices', 'Catalog permission: invoices.manage'),
  ('perm:invoices.view', 'invoices.view', 'invoices', 'Catalog permission: invoices.view'),
  ('perm:lbl.admin', 'lbl.admin', 'lbl', 'Catalog permission: lbl.admin'),
  ('perm:lbl.ai', 'lbl.ai', 'lbl', 'Catalog permission: lbl.ai'),
  ('perm:lbl.approve', 'lbl.approve', 'lbl', 'Catalog permission: lbl.approve'),
  ('perm:lbl.design', 'lbl.design', 'lbl', 'Catalog permission: lbl.design'),
  ('perm:lbl.manage', 'lbl.manage', 'lbl', 'Catalog permission: lbl.manage'),
  ('perm:lbl.print', 'lbl.print', 'lbl', 'Catalog permission: lbl.print'),
  ('perm:lbl.security', 'lbl.security', 'lbl', 'Catalog permission: lbl.security'),
  ('perm:lbl.view', 'lbl.view', 'lbl', 'Catalog permission: lbl.view'),
  ('perm:logistics.manage', 'logistics.manage', 'logistics', 'Catalog permission: logistics.manage'),
  ('perm:logistics.view', 'logistics.view', 'logistics', 'Catalog permission: logistics.view'),
  ('perm:media.manage', 'media.manage', 'media', 'Catalog permission: media.manage'),
  ('perm:media.upload', 'media.upload', 'media', 'Catalog permission: media.upload'),
  ('perm:media.view', 'media.view', 'media', 'Catalog permission: media.view'),
  ('perm:mes.admin', 'mes.admin', 'mes', 'Catalog permission: mes.admin'),
  ('perm:mes.ai', 'mes.ai', 'mes', 'Catalog permission: mes.ai'),
  ('perm:mes.cost', 'mes.cost', 'mes', 'Catalog permission: mes.cost'),
  ('perm:mes.manage', 'mes.manage', 'mes', 'Catalog permission: mes.manage'),
  ('perm:mes.operate', 'mes.operate', 'mes', 'Catalog permission: mes.operate'),
  ('perm:mes.plan', 'mes.plan', 'mes', 'Catalog permission: mes.plan'),
  ('perm:mes.quality', 'mes.quality', 'mes', 'Catalog permission: mes.quality'),
  ('perm:mes.view', 'mes.view', 'mes', 'Catalog permission: mes.view'),
  ('perm:notifications.manage', 'notifications.manage', 'notifications', 'Catalog permission: notifications.manage'),
  ('perm:notifications.send', 'notifications.send', 'notifications', 'Catalog permission: notifications.send'),
  ('perm:notifications.view', 'notifications.view', 'notifications', 'Catalog permission: notifications.view'),
  ('perm:packing.approve', 'packing.approve', 'packing', 'Catalog permission: packing.approve'),
  ('perm:packing.create', 'packing.create', 'packing', 'Catalog permission: packing.create'),
  ('perm:packing.manage', 'packing.manage', 'packing', 'Catalog permission: packing.manage'),
  ('perm:packing.operate', 'packing.operate', 'packing', 'Catalog permission: packing.operate'),
  ('perm:payroll.admin', 'payroll.admin', 'payroll', 'Catalog permission: payroll.admin'),
  ('perm:payroll.ai', 'payroll.ai', 'payroll', 'Catalog permission: payroll.ai'),
  ('perm:payroll.approve', 'payroll.approve', 'payroll', 'Catalog permission: payroll.approve'),
  ('perm:payroll.bank', 'payroll.bank', 'payroll', 'Catalog permission: payroll.bank'),
  ('perm:payroll.costing', 'payroll.costing', 'payroll', 'Catalog permission: payroll.costing'),
  ('perm:payroll.manage', 'payroll.manage', 'payroll', 'Catalog permission: payroll.manage'),
  ('perm:payroll.pay', 'payroll.pay', 'payroll', 'Catalog permission: payroll.pay'),
  ('perm:payroll.process', 'payroll.process', 'payroll', 'Catalog permission: payroll.process'),
  ('perm:payroll.self', 'payroll.self', 'payroll', 'Catalog permission: payroll.self'),
  ('perm:payroll.tax', 'payroll.tax', 'payroll', 'Catalog permission: payroll.tax'),
  ('perm:payroll.view', 'payroll.view', 'payroll', 'Catalog permission: payroll.view'),
  ('perm:pkg.ai', 'pkg.ai', 'pkg', 'Catalog permission: pkg.ai'),
  ('perm:pkg.approve', 'pkg.approve', 'pkg', 'Catalog permission: pkg.approve'),
  ('perm:pkg.manage', 'pkg.manage', 'pkg', 'Catalog permission: pkg.manage'),
  ('perm:pkg.operate', 'pkg.operate', 'pkg', 'Catalog permission: pkg.operate'),
  ('perm:pkg.view', 'pkg.view', 'pkg', 'Catalog permission: pkg.view'),
  ('perm:platform.admin', 'platform.admin', 'platform', 'Catalog permission: platform.admin'),
  ('perm:platform.events', 'platform.events', 'platform', 'Catalog permission: platform.events'),
  ('perm:platform.flags', 'platform.flags', 'platform', 'Catalog permission: platform.flags'),
  ('perm:platform.provision', 'platform.provision', 'platform', 'Catalog permission: platform.provision'),
  ('perm:platform.view', 'platform.view', 'platform', 'Catalog permission: platform.view'),
  ('perm:ppm.admin', 'ppm.admin', 'ppm', 'Catalog permission: ppm.admin'),
  ('perm:ppm.ai', 'ppm.ai', 'ppm', 'Catalog permission: ppm.ai'),
  ('perm:ppm.approve', 'ppm.approve', 'ppm', 'Catalog permission: ppm.approve'),
  ('perm:ppm.execute', 'ppm.execute', 'ppm', 'Catalog permission: ppm.execute'),
  ('perm:ppm.finance', 'ppm.finance', 'ppm', 'Catalog permission: ppm.finance'),
  ('perm:ppm.manage', 'ppm.manage', 'ppm', 'Catalog permission: ppm.manage'),
  ('perm:ppm.plan', 'ppm.plan', 'ppm', 'Catalog permission: ppm.plan'),
  ('perm:ppm.portal', 'ppm.portal', 'ppm', 'Catalog permission: ppm.portal'),
  ('perm:ppm.view', 'ppm.view', 'ppm', 'Catalog permission: ppm.view'),
  ('perm:print.admin', 'print.admin', 'print', 'Catalog permission: print.admin'),
  ('perm:print.ai', 'print.ai', 'print', 'Catalog permission: print.ai'),
  ('perm:print.design', 'print.design', 'print', 'Catalog permission: print.design'),
  ('perm:print.manage', 'print.manage', 'print', 'Catalog permission: print.manage'),
  ('perm:print.operate', 'print.operate', 'print', 'Catalog permission: print.operate'),
  ('perm:print.security', 'print.security', 'print', 'Catalog permission: print.security'),
  ('perm:print.submit', 'print.submit', 'print', 'Catalog permission: print.submit'),
  ('perm:print.view', 'print.view', 'print', 'Catalog permission: print.view'),
  ('perm:printers.manage', 'printers.manage', 'printers', 'Catalog permission: printers.manage'),
  ('perm:printing.create', 'printing.create', 'printing', 'Catalog permission: printing.create'),
  ('perm:printing.manage', 'printing.manage', 'printing', 'Catalog permission: printing.manage'),
  ('perm:printing.reprint', 'printing.reprint', 'printing', 'Catalog permission: printing.reprint'),
  ('perm:procurement.approve', 'procurement.approve', 'procurement', 'Catalog permission: procurement.approve'),
  ('perm:procurement.manage', 'procurement.manage', 'procurement', 'Catalog permission: procurement.manage'),
  ('perm:procurement.suppliers', 'procurement.suppliers', 'procurement', 'Catalog permission: procurement.suppliers'),
  ('perm:procurement.view', 'procurement.view', 'procurement', 'Catalog permission: procurement.view'),
  ('perm:production.approve', 'production.approve', 'production', 'Catalog permission: production.approve'),
  ('perm:production.create', 'production.create', 'production', 'Catalog permission: production.create'),
  ('perm:production.manage', 'production.manage', 'production', 'Catalog permission: production.manage'),
  ('perm:production.view', 'production.view', 'production', 'Catalog permission: production.view'),
  ('perm:products.view', 'products.view', 'products', 'Catalog permission: products.view'),
  ('perm:profile.ai', 'profile.ai', 'profile', 'Catalog permission: profile.ai'),
  ('perm:profile.analytics', 'profile.analytics', 'profile', 'Catalog permission: profile.analytics'),
  ('perm:profile.documents', 'profile.documents', 'profile', 'Catalog permission: profile.documents'),
  ('perm:profile.manage', 'profile.manage', 'profile', 'Catalog permission: profile.manage'),
  ('perm:profile.manager', 'profile.manager', 'profile', 'Catalog permission: profile.manager'),
  ('perm:profile.payroll', 'profile.payroll', 'profile', 'Catalog permission: profile.payroll'),
  ('perm:profile.security', 'profile.security', 'profile', 'Catalog permission: profile.security'),
  ('perm:profile.self', 'profile.self', 'profile', 'Catalog permission: profile.self'),
  ('perm:profile.view', 'profile.view', 'profile', 'Catalog permission: profile.view'),
  ('perm:qr.view', 'qr.view', 'qr', 'Catalog permission: qr.view'),
  ('perm:reports.ai', 'reports.ai', 'reports', 'Catalog permission: reports.ai'),
  ('perm:reports.assistant', 'reports.assistant', 'reports', 'Catalog permission: reports.assistant'),
  ('perm:reports.classify', 'reports.classify', 'reports', 'Catalog permission: reports.classify'),
  ('perm:reports.dashboards', 'reports.dashboards', 'reports', 'Catalog permission: reports.dashboards'),
  ('perm:reports.documents', 'reports.documents', 'reports', 'Catalog permission: reports.documents'),
  ('perm:reports.dwh', 'reports.dwh', 'reports', 'Catalog permission: reports.dwh'),
  ('perm:reports.export', 'reports.export', 'reports', 'Catalog permission: reports.export'),
  ('perm:reports.intelligence', 'reports.intelligence', 'reports', 'Catalog permission: reports.intelligence'),
  ('perm:reports.kpis', 'reports.kpis', 'reports', 'Catalog permission: reports.kpis'),
  ('perm:reports.manage', 'reports.manage', 'reports', 'Catalog permission: reports.manage'),
  ('perm:reports.regulatory', 'reports.regulatory', 'reports', 'Catalog permission: reports.regulatory'),
  ('perm:reports.schedule', 'reports.schedule', 'reports', 'Catalog permission: reports.schedule'),
  ('perm:reports.search', 'reports.search', 'reports', 'Catalog permission: reports.search'),
  ('perm:reports.view', 'reports.view', 'reports', 'Catalog permission: reports.view'),
  ('perm:sales.admin', 'sales.admin', 'sales', 'Catalog permission: sales.admin'),
  ('perm:sales.ai', 'sales.ai', 'sales', 'Catalog permission: sales.ai'),
  ('perm:sales.commissions', 'sales.commissions', 'sales', 'Catalog permission: sales.commissions'),
  ('perm:sales.contracts', 'sales.contracts', 'sales', 'Catalog permission: sales.contracts'),
  ('perm:sales.credit', 'sales.credit', 'sales', 'Catalog permission: sales.credit'),
  ('perm:sales.forecast', 'sales.forecast', 'sales', 'Catalog permission: sales.forecast'),
  ('perm:sales.manage', 'sales.manage', 'sales', 'Catalog permission: sales.manage'),
  ('perm:sales.pipeline', 'sales.pipeline', 'sales', 'Catalog permission: sales.pipeline'),
  ('perm:sales.pricing', 'sales.pricing', 'sales', 'Catalog permission: sales.pricing'),
  ('perm:sales.quotes', 'sales.quotes', 'sales', 'Catalog permission: sales.quotes'),
  ('perm:sales.returns', 'sales.returns', 'sales', 'Catalog permission: sales.returns'),
  ('perm:sales.view', 'sales.view', 'sales', 'Catalog permission: sales.view'),
  ('perm:scm.manage', 'scm.manage', 'scm', 'Catalog permission: scm.manage'),
  ('perm:scm.risk', 'scm.risk', 'scm', 'Catalog permission: scm.risk'),
  ('perm:scm.sop', 'scm.sop', 'scm', 'Catalog permission: scm.sop'),
  ('perm:scm.view', 'scm.view', 'scm', 'Catalog permission: scm.view'),
  ('perm:sd.admin', 'sd.admin', 'sd', 'Catalog permission: sd.admin'),
  ('perm:sd.agent', 'sd.agent', 'sd', 'Catalog permission: sd.agent'),
  ('perm:sd.ai', 'sd.ai', 'sd', 'Catalog permission: sd.ai'),
  ('perm:sd.approve', 'sd.approve', 'sd', 'Catalog permission: sd.approve'),
  ('perm:sd.change', 'sd.change', 'sd', 'Catalog permission: sd.change'),
  ('perm:sd.field', 'sd.field', 'sd', 'Catalog permission: sd.field'),
  ('perm:sd.knowledge', 'sd.knowledge', 'sd', 'Catalog permission: sd.knowledge'),
  ('perm:sd.major', 'sd.major', 'sd', 'Catalog permission: sd.major'),
  ('perm:sd.manage', 'sd.manage', 'sd', 'Catalog permission: sd.manage'),
  ('perm:sd.portal', 'sd.portal', 'sd', 'Catalog permission: sd.portal'),
  ('perm:sd.view', 'sd.view', 'sd', 'Catalog permission: sd.view'),
  ('perm:security.admin', 'security.admin', 'security', 'Catalog permission: security.admin'),
  ('perm:security.dual_control', 'security.dual_control', 'security', 'Catalog permission: security.dual_control'),
  ('perm:settings.branding', 'settings.branding', 'settings', 'Catalog permission: settings.branding'),
  ('perm:settings.integrations', 'settings.integrations', 'settings', 'Catalog permission: settings.integrations'),
  ('perm:settings.manage', 'settings.manage', 'settings', 'Catalog permission: settings.manage'),
  ('perm:settings.sequences', 'settings.sequences', 'settings', 'Catalog permission: settings.sequences'),
  ('perm:settings.view', 'settings.view', 'settings', 'Catalog permission: settings.view'),
  ('perm:settings.workflows', 'settings.workflows', 'settings', 'Catalog permission: settings.workflows'),
  ('perm:srm.admin', 'srm.admin', 'srm', 'Catalog permission: srm.admin'),
  ('perm:srm.ai', 'srm.ai', 'srm', 'Catalog permission: srm.ai'),
  ('perm:srm.approve', 'srm.approve', 'srm', 'Catalog permission: srm.approve'),
  ('perm:srm.contracts', 'srm.contracts', 'srm', 'Catalog permission: srm.contracts'),
  ('perm:srm.manage', 'srm.manage', 'srm', 'Catalog permission: srm.manage'),
  ('perm:srm.portal', 'srm.portal', 'srm', 'Catalog permission: srm.portal'),
  ('perm:srm.quality', 'srm.quality', 'srm', 'Catalog permission: srm.quality'),
  ('perm:srm.view', 'srm.view', 'srm', 'Catalog permission: srm.view'),
  ('perm:ta.admin', 'ta.admin', 'ta', 'Catalog permission: ta.admin'),
  ('perm:ta.ai', 'ta.ai', 'ta', 'Catalog permission: ta.ai'),
  ('perm:ta.approve', 'ta.approve', 'ta', 'Catalog permission: ta.approve'),
  ('perm:ta.manage', 'ta.manage', 'ta', 'Catalog permission: ta.manage'),
  ('perm:ta.portal', 'ta.portal', 'ta', 'Catalog permission: ta.portal'),
  ('perm:ta.recruit', 'ta.recruit', 'ta', 'Catalog permission: ta.recruit'),
  ('perm:ta.view', 'ta.view', 'ta', 'Catalog permission: ta.view'),
  ('perm:tenant.admin', 'tenant.admin', 'tenant', 'Catalog permission: tenant.admin'),
  ('perm:tenant.manage', 'tenant.manage', 'tenant', 'Catalog permission: tenant.manage'),
  ('perm:tenant.switch', 'tenant.switch', 'tenant', 'Catalog permission: tenant.switch'),
  ('perm:tenant.view', 'tenant.view', 'tenant', 'Catalog permission: tenant.view'),
  ('perm:users.manage', 'users.manage', 'users', 'Catalog permission: users.manage'),
  ('perm:users.view', 'users.view', 'users', 'Catalog permission: users.view'),
  ('perm:uw.admin', 'uw.admin', 'uw', 'Catalog permission: uw.admin'),
  ('perm:uw.manage', 'uw.manage', 'uw', 'Catalog permission: uw.manage'),
  ('perm:uw.merge', 'uw.merge', 'uw', 'Catalog permission: uw.merge'),
  ('perm:uw.view', 'uw.view', 'uw', 'Catalog permission: uw.view'),
  ('perm:verification.view', 'verification.view', 'verification', 'Catalog permission: verification.view'),
  ('perm:wfm.approve', 'wfm.approve', 'wfm', 'Catalog permission: wfm.approve'),
  ('perm:wfm.field', 'wfm.field', 'wfm', 'Catalog permission: wfm.field'),
  ('perm:wfm.manage', 'wfm.manage', 'wfm', 'Catalog permission: wfm.manage'),
  ('perm:wfm.safety', 'wfm.safety', 'wfm', 'Catalog permission: wfm.safety'),
  ('perm:wfm.view', 'wfm.view', 'wfm', 'Catalog permission: wfm.view'),
  ('perm:wid.manage', 'wid.manage', 'wid', 'Catalog permission: wid.manage'),
  ('perm:wid.view', 'wid.view', 'wid', 'Catalog permission: wid.view')
ON CONFLICT (slug) DO NOTHING;

-- 2) Provision catalog roles and append module/level access
DO $$
DECLARE
  v_modules text[] := ARRAY['dashboard', 'production', 'mes', 'qr', 'lbl', 'printing', 'print', 'packing', 'pkg', 'ast', 'inventory', 'products', 'procurement', 'srm', 'scm', 'logistics', 'crm', 'sales', 'billing', 'invoices', 'dispatch', 'dsp', 'fleet', 'finance', 'payroll', 'hr', 'ta', 'wfm', 'att', 'profile', 'wid', 'di', 'uw', 'iam', 'users', 'sd', 'hc', 'comm', 'media', 'brand', 'reports', 'audit', 'eal', 'fraud', 'verification', 'notifications', 'settings', 'intg', 'ppm', 'ec', 'tenant', 'security', 'distributors'];
  v_levels  text[] := ARRAY['viewer', 'clerk', 'operator', 'specialist', 'supervisor', 'manager', 'director', 'admin'];
  v_variants text[] := ARRAY['core', 'east', 'west', 'central', 'remote'];
  v_company uuid;
  v_mod text;
  v_level text;
  v_variant text;
  v_slug text;
  v_name text;
  v_role_id uuid;
  v_created int := 0;
  v_links int := 0;
  v_prefix text;
BEGIN
  SELECT id INTO v_company
  FROM companies
  WHERE id = 'a0000000-0000-4000-8000-000000000001';

  FOREACH v_variant IN ARRAY v_variants LOOP
    FOREACH v_mod IN ARRAY v_modules LOOP
      FOREACH v_level IN ARRAY v_levels LOOP
        v_slug := 'catalog_' || v_mod || '_' || v_level || '_' || v_variant;
        v_name := initcap(replace(v_mod, '_', ' '))
          || ' '
          || initcap(v_level)
          || ' ('
          || initcap(v_variant)
          || ')';

        SELECT id INTO v_role_id
        FROM roles
        WHERE slug = v_slug
          AND deleted_at IS NULL
        LIMIT 1;

        IF v_role_id IS NULL THEN
          INSERT INTO roles (
            company_id, name, slug, description,
            is_system, is_active, role_category
          )
          VALUES (
            v_company,
            v_name,
            v_slug,
            'Catalog role — '
              || v_mod || ' ' || v_level || ' (' || v_variant
              || '). Seeded for RBAC least-privilege assignment.',
            true,
            true,
            'system'
          )
          RETURNING id INTO v_role_id;
          v_created := v_created + 1;
        END IF;

        -- Baseline access every catalog role gets
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT v_role_id, p.id
        FROM permissions p
        WHERE p.slug IN (
          'dashboard.view',
          'notifications.view',
          'profile.self',
          'profile.view'
        )
        ON CONFLICT DO NOTHING;

        -- Module prefix for permission matching
        v_prefix := v_mod;

        -- Module-scoped access by level
        IF v_level IN ('viewer', 'clerk') THEN
          INSERT INTO role_permissions (role_id, permission_id)
          SELECT v_role_id, p.id
          FROM permissions p
          WHERE p.slug NOT LIKE 'platform.%'
            AND (
              p.slug = v_prefix || '.view'
              OR p.slug LIKE v_prefix || '.%.view'
              OR (v_mod = 'reports' AND p.slug IN ('reports.view', 'reports.export'))
              OR (v_mod = 'audit' AND p.slug IN ('audit.view', 'eal.view'))
              OR (v_mod = 'printing' AND p.slug IN ('print.view', 'printing.create'))
              OR (v_mod = 'print' AND p.slug = 'print.view')
            )
          ON CONFLICT DO NOTHING;

        ELSIF v_level IN ('operator', 'specialist') THEN
          INSERT INTO role_permissions (role_id, permission_id)
          SELECT v_role_id, p.id
          FROM permissions p
          WHERE p.slug NOT LIKE 'platform.%'
            AND (
              p.slug LIKE v_prefix || '.%'
            )
            AND (
              p.slug LIKE '%.view'
              OR p.slug LIKE '%.create'
              OR p.slug LIKE '%.operate'
              OR p.slug LIKE '%.clock'
              OR p.slug LIKE '%.field'
              OR p.slug LIKE '%.submit'
              OR p.slug LIKE '%.print'
              OR p.slug LIKE '%.move'
              OR p.slug LIKE '%.track'
              OR p.slug LIKE '%.design'
              OR p.slug LIKE '%.agent'
              OR p.slug LIKE '%.recruit'
            )
          ON CONFLICT DO NOTHING;

        ELSIF v_level IN ('supervisor', 'manager') THEN
          INSERT INTO role_permissions (role_id, permission_id)
          SELECT v_role_id, p.id
          FROM permissions p
          WHERE p.slug NOT LIKE 'platform.%'
            AND p.slug LIKE v_prefix || '.%'
            AND (
              p.slug LIKE '%.view'
              OR p.slug LIKE '%.manage'
              OR p.slug LIKE '%.operate'
              OR p.slug LIKE '%.create'
              OR p.slug LIKE '%.approve'
              OR p.slug LIKE '%.export'
              OR p.slug LIKE '%.edit'
              OR p.slug LIKE '%.process'
              OR p.slug LIKE '%.post'
              OR p.slug LIKE '%.collect'
            )
          ON CONFLICT DO NOTHING;

        ELSIF v_level = 'director' THEN
          INSERT INTO role_permissions (role_id, permission_id)
          SELECT v_role_id, p.id
          FROM permissions p
          WHERE p.slug NOT LIKE 'platform.%'
            AND (
              p.slug LIKE v_prefix || '.%'
              OR p.slug IN ('reports.view', 'reports.dashboards', 'reports.kpis')
            )
          ON CONFLICT DO NOTHING;

        ELSIF v_level = 'admin' THEN
          INSERT INTO role_permissions (role_id, permission_id)
          SELECT v_role_id, p.id
          FROM permissions p
          WHERE p.slug NOT LIKE 'platform.%'
            AND (
              p.slug LIKE v_prefix || '.%'
              OR p.slug IN ('settings.view', 'reports.view')
            )
          ON CONFLICT DO NOTHING;
        END IF;

      END LOOP;
    END LOOP;
  END LOOP;

  -- 3) Super administrator gets every non-platform permission (append)
  INSERT INTO role_permissions (role_id, permission_id)
  SELECT r.id, p.id
  FROM roles r
  CROSS JOIN permissions p
  WHERE r.slug = 'super_administrator'
    AND p.slug NOT LIKE 'platform.%'
  ON CONFLICT DO NOTHING;

  -- 4) Every active role has dashboard.view (append baseline)
  INSERT INTO role_permissions (role_id, permission_id)
  SELECT r.id, p.id
  FROM roles r
  CROSS JOIN permissions p
  WHERE COALESCE(r.is_active, true) = true
    AND r.deleted_at IS NULL
    AND p.slug = 'dashboard.view'
  ON CONFLICT DO NOTHING;

  -- 5) Existing seed system roles: append module-aligned access where empty-ish
  --    (managing_director gets broad view/manage across business modules)
  INSERT INTO role_permissions (role_id, permission_id)
  SELECT r.id, p.id
  FROM roles r
  CROSS JOIN permissions p
  WHERE r.slug = 'managing_director'
    AND p.slug NOT LIKE 'platform.%'
    AND (
      p.slug LIKE '%.view'
      OR p.slug LIKE '%.manage'
      OR p.slug LIKE '%.approve'
      OR p.slug LIKE '%.export'
      OR p.slug IN ('dashboard.view', 'reports.dashboards', 'reports.kpis')
    )
  ON CONFLICT DO NOTHING;

  INSERT INTO role_permissions (role_id, permission_id)
  SELECT r.id, p.id
  FROM roles r
  CROSS JOIN permissions p
  WHERE r.slug IN ('auditor', 'read_only')
    AND (
      p.slug LIKE '%.view'
      OR p.slug IN (
        'dashboard.view',
        'reports.view',
        'reports.export',
        'audit.view',
        'eal.view'
      )
    )
    AND p.slug NOT LIKE 'platform.%'
  ON CONFLICT DO NOTHING;

  GET DIAGNOSTICS v_links = ROW_COUNT;
  RAISE NOTICE 'Catalog roles created this run: % (target total catalog slugs: %)',
    v_created, 2120;
END $$;

-- Optional verification (commented):
-- SELECT count(*) AS catalog_roles FROM roles WHERE slug LIKE 'catalog_%';
-- SELECT count(*) AS catalog_access
-- FROM role_permissions rp
-- JOIN roles r ON r.id = rp.role_id
-- WHERE r.slug LIKE 'catalog_%';
