-- ============================================================
-- RBAC catalog: permissions + 2120 roles + access (role_permissions)
-- Generated by scripts/gen-role-catalog-migration.mjs
-- Modules: 53 x levels: 8 x variants: 5 = 2120 roles
-- Permission slugs seeded: 313
-- Idempotent (safe to re-run)
-- ============================================================

-- 1) Ensure full permission catalog
INSERT INTO permissions (name, slug, module, description)
VALUES
  ('Ast Ai', 'ast.ai', 'ast', 'Catalog permission: ast.ai'),
  ('Ast Assign', 'ast.assign', 'ast', 'Catalog permission: ast.assign'),
  ('Ast Audit', 'ast.audit', 'ast', 'Catalog permission: ast.audit'),
  ('Ast Manage', 'ast.manage', 'ast', 'Catalog permission: ast.manage'),
  ('Ast Print', 'ast.print', 'ast', 'Catalog permission: ast.print'),
  ('Ast View', 'ast.view', 'ast', 'Catalog permission: ast.view'),
  ('Att Admin', 'att.admin', 'att', 'Catalog permission: att.admin'),
  ('Att Ai', 'att.ai', 'att', 'Catalog permission: att.ai'),
  ('Att Approve', 'att.approve', 'att', 'Catalog permission: att.approve'),
  ('Att Clock', 'att.clock', 'att', 'Catalog permission: att.clock'),
  ('Att Devices', 'att.devices', 'att', 'Catalog permission: att.devices'),
  ('Att Field', 'att.field', 'att', 'Catalog permission: att.field'),
  ('Att Manage', 'att.manage', 'att', 'Catalog permission: att.manage'),
  ('Att View', 'att.view', 'att', 'Catalog permission: att.view'),
  ('Audit Manage', 'audit.manage', 'audit', 'Catalog permission: audit.manage'),
  ('Audit View', 'audit.view', 'audit', 'Catalog permission: audit.view'),
  ('Billing Manage', 'billing.manage', 'billing', 'Catalog permission: billing.manage'),
  ('Billing View', 'billing.view', 'billing', 'Catalog permission: billing.view'),
  ('Brand Ai', 'brand.ai', 'brand', 'Catalog permission: brand.ai'),
  ('Brand Approve', 'brand.approve', 'brand', 'Catalog permission: brand.approve'),
  ('Brand Assets', 'brand.assets', 'brand', 'Catalog permission: brand.assets'),
  ('Brand Design', 'brand.design', 'brand', 'Catalog permission: brand.design'),
  ('Brand Manage', 'brand.manage', 'brand', 'Catalog permission: brand.manage'),
  ('Brand Publish', 'brand.publish', 'brand', 'Catalog permission: brand.publish'),
  ('Brand View', 'brand.view', 'brand', 'Catalog permission: brand.view'),
  ('Comm Admin', 'comm.admin', 'comm', 'Catalog permission: comm.admin'),
  ('Comm Ai', 'comm.ai', 'comm', 'Catalog permission: comm.ai'),
  ('Comm Broadcast', 'comm.broadcast', 'comm', 'Catalog permission: comm.broadcast'),
  ('Comm Manage', 'comm.manage', 'comm', 'Catalog permission: comm.manage'),
  ('Comm Templates', 'comm.templates', 'comm', 'Catalog permission: comm.templates'),
  ('Comm View', 'comm.view', 'comm', 'Catalog permission: comm.view'),
  ('Crm Admin', 'crm.admin', 'crm', 'Catalog permission: crm.admin'),
  ('Crm Ai', 'crm.ai', 'crm', 'Catalog permission: crm.ai'),
  ('Crm Credit', 'crm.credit', 'crm', 'Catalog permission: crm.credit'),
  ('Crm Export', 'crm.export', 'crm', 'Catalog permission: crm.export'),
  ('Crm Leads', 'crm.leads', 'crm', 'Catalog permission: crm.leads'),
  ('Crm Manage', 'crm.manage', 'crm', 'Catalog permission: crm.manage'),
  ('Crm Marketing', 'crm.marketing', 'crm', 'Catalog permission: crm.marketing'),
  ('Crm Opportunities', 'crm.opportunities', 'crm', 'Catalog permission: crm.opportunities'),
  ('Crm Portal', 'crm.portal', 'crm', 'Catalog permission: crm.portal'),
  ('Crm Service', 'crm.service', 'crm', 'Catalog permission: crm.service'),
  ('Crm View', 'crm.view', 'crm', 'Catalog permission: crm.view'),
  ('Dashboard View', 'dashboard.view', 'dashboard', 'Catalog permission: dashboard.view'),
  ('Di Admin', 'di.admin', 'di', 'Catalog permission: di.admin'),
  ('Di Ai', 'di.ai', 'di', 'Catalog permission: di.ai'),
  ('Di Biometrics', 'di.biometrics', 'di', 'Catalog permission: di.biometrics'),
  ('Di Cards', 'di.cards', 'di', 'Catalog permission: di.cards'),
  ('Di Clearance', 'di.clearance', 'di', 'Catalog permission: di.clearance'),
  ('Di Manage', 'di.manage', 'di', 'Catalog permission: di.manage'),
  ('Di Org', 'di.org', 'di', 'Catalog permission: di.org'),
  ('Di Provision', 'di.provision', 'di', 'Catalog permission: di.provision'),
  ('Di View', 'di.view', 'di', 'Catalog permission: di.view'),
  ('Dispatch Manage', 'dispatch.manage', 'dispatch', 'Catalog permission: dispatch.manage'),
  ('Dispatch View', 'dispatch.view', 'dispatch', 'Catalog permission: dispatch.view'),
  ('Distributors View', 'distributors.view', 'distributors', 'Catalog permission: distributors.view'),
  ('Dsp Ai', 'dsp.ai', 'dsp', 'Catalog permission: dsp.ai'),
  ('Dsp Approve', 'dsp.approve', 'dsp', 'Catalog permission: dsp.approve'),
  ('Dsp Manage', 'dsp.manage', 'dsp', 'Catalog permission: dsp.manage'),
  ('Dsp Operate', 'dsp.operate', 'dsp', 'Catalog permission: dsp.operate'),
  ('Dsp Track', 'dsp.track', 'dsp', 'Catalog permission: dsp.track'),
  ('Dsp View', 'dsp.view', 'dsp', 'Catalog permission: dsp.view'),
  ('Eal Ai', 'eal.ai', 'eal', 'Catalog permission: eal.ai'),
  ('Eal Archive', 'eal.archive', 'eal', 'Catalog permission: eal.archive'),
  ('Eal Compliance', 'eal.compliance', 'eal', 'Catalog permission: eal.compliance'),
  ('Eal Config', 'eal.config', 'eal', 'Catalog permission: eal.config'),
  ('Eal Executive', 'eal.executive', 'eal', 'Catalog permission: eal.executive'),
  ('Eal Export', 'eal.export', 'eal', 'Catalog permission: eal.export'),
  ('Eal Infra', 'eal.infra', 'eal', 'Catalog permission: eal.infra'),
  ('Eal Investigate', 'eal.investigate', 'eal', 'Catalog permission: eal.investigate'),
  ('Eal Manage', 'eal.manage', 'eal', 'Catalog permission: eal.manage'),
  ('Eal Security', 'eal.security', 'eal', 'Catalog permission: eal.security'),
  ('Eal View', 'eal.view', 'eal', 'Catalog permission: eal.view'),
  ('Ec Admin', 'ec.admin', 'ec', 'Catalog permission: ec.admin'),
  ('Ec Ai', 'ec.ai', 'ec', 'Catalog permission: ec.ai'),
  ('Ec Documents', 'ec.documents', 'ec', 'Catalog permission: ec.documents'),
  ('Ec Governance', 'ec.governance', 'ec', 'Catalog permission: ec.governance'),
  ('Ec Manage', 'ec.manage', 'ec', 'Catalog permission: ec.manage'),
  ('Ec Risk', 'ec.risk', 'ec', 'Catalog permission: ec.risk'),
  ('Ec Structure', 'ec.structure', 'ec', 'Catalog permission: ec.structure'),
  ('Ec View', 'ec.view', 'ec', 'Catalog permission: ec.view'),
  ('Finance Admin', 'finance.admin', 'finance', 'Catalog permission: finance.admin'),
  ('Finance Ai', 'finance.ai', 'finance', 'Catalog permission: finance.ai'),
  ('Finance Approve', 'finance.approve', 'finance', 'Catalog permission: finance.approve'),
  ('Finance Bank', 'finance.bank', 'finance', 'Catalog permission: finance.bank'),
  ('Finance Cfo', 'finance.cfo', 'finance', 'Catalog permission: finance.cfo'),
  ('Finance Close', 'finance.close', 'finance', 'Catalog permission: finance.close'),
  ('Finance Consolidate', 'finance.consolidate', 'finance', 'Catalog permission: finance.consolidate'),
  ('Finance Costing', 'finance.costing', 'finance', 'Catalog permission: finance.costing'),
  ('Finance Fpa', 'finance.fpa', 'finance', 'Catalog permission: finance.fpa'),
  ('Finance Manage', 'finance.manage', 'finance', 'Catalog permission: finance.manage'),
  ('Finance Multibook', 'finance.multibook', 'finance', 'Catalog permission: finance.multibook'),
  ('Finance Post', 'finance.post', 'finance', 'Catalog permission: finance.post'),
  ('Finance Tax', 'finance.tax', 'finance', 'Catalog permission: finance.tax'),
  ('Finance Tax Manage', 'finance.tax.manage', 'finance', 'Catalog permission: finance.tax.manage'),
  ('Finance Treasury', 'finance.treasury', 'finance', 'Catalog permission: finance.treasury'),
  ('Finance View', 'finance.view', 'finance', 'Catalog permission: finance.view'),
  ('Fleet Admin', 'fleet.admin', 'fleet', 'Catalog permission: fleet.admin'),
  ('Fleet Ai', 'fleet.ai', 'fleet', 'Catalog permission: fleet.ai'),
  ('Fleet Approve', 'fleet.approve', 'fleet', 'Catalog permission: fleet.approve'),
  ('Fleet Dispatch', 'fleet.dispatch', 'fleet', 'Catalog permission: fleet.dispatch'),
  ('Fleet Drivers', 'fleet.drivers', 'fleet', 'Catalog permission: fleet.drivers'),
  ('Fleet Fuel', 'fleet.fuel', 'fleet', 'Catalog permission: fleet.fuel'),
  ('Fleet Maintenance', 'fleet.maintenance', 'fleet', 'Catalog permission: fleet.maintenance'),
  ('Fleet Manage', 'fleet.manage', 'fleet', 'Catalog permission: fleet.manage'),
  ('Fleet Track', 'fleet.track', 'fleet', 'Catalog permission: fleet.track'),
  ('Fleet View', 'fleet.view', 'fleet', 'Catalog permission: fleet.view'),
  ('Fraud Manage', 'fraud.manage', 'fraud', 'Catalog permission: fraud.manage'),
  ('Hc Admin', 'hc.admin', 'hc', 'Catalog permission: hc.admin'),
  ('Hc Ai', 'hc.ai', 'hc', 'Catalog permission: hc.ai'),
  ('Hc Announce', 'hc.announce', 'hc', 'Catalog permission: hc.announce'),
  ('Hc Manage', 'hc.manage', 'hc', 'Catalog permission: hc.manage'),
  ('Hc Meetings', 'hc.meetings', 'hc', 'Catalog permission: hc.meetings'),
  ('Hc View', 'hc.view', 'hc', 'Catalog permission: hc.view'),
  ('Hr Manage', 'hr.manage', 'hr', 'Catalog permission: hr.manage'),
  ('Hr Payroll', 'hr.payroll', 'hr', 'Catalog permission: hr.payroll'),
  ('Hr Performance', 'hr.performance', 'hr', 'Catalog permission: hr.performance'),
  ('Hr Recruit', 'hr.recruit', 'hr', 'Catalog permission: hr.recruit'),
  ('Hr Self', 'hr.self', 'hr', 'Catalog permission: hr.self'),
  ('Hr Training', 'hr.training', 'hr', 'Catalog permission: hr.training'),
  ('Hr View', 'hr.view', 'hr', 'Catalog permission: hr.view'),
  ('Iam Abac', 'iam.abac', 'iam', 'Catalog permission: iam.abac'),
  ('Iam Approvals', 'iam.approvals', 'iam', 'Catalog permission: iam.approvals'),
  ('Iam Governance', 'iam.governance', 'iam', 'Catalog permission: iam.governance'),
  ('Iam Import', 'iam.import', 'iam', 'Catalog permission: iam.import'),
  ('Iam Manage', 'iam.manage', 'iam', 'Catalog permission: iam.manage'),
  ('Iam Mfa', 'iam.mfa', 'iam', 'Catalog permission: iam.mfa'),
  ('Iam Password', 'iam.password', 'iam', 'Catalog permission: iam.password'),
  ('Iam Provision', 'iam.provision', 'iam', 'Catalog permission: iam.provision'),
  ('Iam Roles', 'iam.roles', 'iam', 'Catalog permission: iam.roles'),
  ('Iam Security', 'iam.security', 'iam', 'Catalog permission: iam.security'),
  ('Iam Sessions', 'iam.sessions', 'iam', 'Catalog permission: iam.sessions'),
  ('Iam View', 'iam.view', 'iam', 'Catalog permission: iam.view'),
  ('Intg Manage', 'intg.manage', 'intg', 'Catalog permission: intg.manage'),
  ('Intg View', 'intg.view', 'intg', 'Catalog permission: intg.view'),
  ('Inventory Adjust', 'inventory.adjust', 'inventory', 'Catalog permission: inventory.adjust'),
  ('Inventory Grn', 'inventory.grn', 'inventory', 'Catalog permission: inventory.grn'),
  ('Inventory Qc', 'inventory.qc', 'inventory', 'Catalog permission: inventory.qc'),
  ('Inventory Transfer', 'inventory.transfer', 'inventory', 'Catalog permission: inventory.transfer'),
  ('Inventory Valuation', 'inventory.valuation', 'inventory', 'Catalog permission: inventory.valuation'),
  ('Inventory View', 'inventory.view', 'inventory', 'Catalog permission: inventory.view'),
  ('Invoices Manage', 'invoices.manage', 'invoices', 'Catalog permission: invoices.manage'),
  ('Invoices View', 'invoices.view', 'invoices', 'Catalog permission: invoices.view'),
  ('Lbl Admin', 'lbl.admin', 'lbl', 'Catalog permission: lbl.admin'),
  ('Lbl Ai', 'lbl.ai', 'lbl', 'Catalog permission: lbl.ai'),
  ('Lbl Approve', 'lbl.approve', 'lbl', 'Catalog permission: lbl.approve'),
  ('Lbl Design', 'lbl.design', 'lbl', 'Catalog permission: lbl.design'),
  ('Lbl Manage', 'lbl.manage', 'lbl', 'Catalog permission: lbl.manage'),
  ('Lbl Print', 'lbl.print', 'lbl', 'Catalog permission: lbl.print'),
  ('Lbl Security', 'lbl.security', 'lbl', 'Catalog permission: lbl.security'),
  ('Lbl View', 'lbl.view', 'lbl', 'Catalog permission: lbl.view'),
  ('Logistics Manage', 'logistics.manage', 'logistics', 'Catalog permission: logistics.manage'),
  ('Logistics View', 'logistics.view', 'logistics', 'Catalog permission: logistics.view'),
  ('Media Manage', 'media.manage', 'media', 'Catalog permission: media.manage'),
  ('Media Upload', 'media.upload', 'media', 'Catalog permission: media.upload'),
  ('Media View', 'media.view', 'media', 'Catalog permission: media.view'),
  ('Mes Admin', 'mes.admin', 'mes', 'Catalog permission: mes.admin'),
  ('Mes Ai', 'mes.ai', 'mes', 'Catalog permission: mes.ai'),
  ('Mes Cost', 'mes.cost', 'mes', 'Catalog permission: mes.cost'),
  ('Mes Manage', 'mes.manage', 'mes', 'Catalog permission: mes.manage'),
  ('Mes Operate', 'mes.operate', 'mes', 'Catalog permission: mes.operate'),
  ('Mes Plan', 'mes.plan', 'mes', 'Catalog permission: mes.plan'),
  ('Mes Quality', 'mes.quality', 'mes', 'Catalog permission: mes.quality'),
  ('Mes View', 'mes.view', 'mes', 'Catalog permission: mes.view'),
  ('Notifications Manage', 'notifications.manage', 'notifications', 'Catalog permission: notifications.manage'),
  ('Notifications Send', 'notifications.send', 'notifications', 'Catalog permission: notifications.send'),
  ('Notifications View', 'notifications.view', 'notifications', 'Catalog permission: notifications.view'),
  ('Packing Approve', 'packing.approve', 'packing', 'Catalog permission: packing.approve'),
  ('Packing Create', 'packing.create', 'packing', 'Catalog permission: packing.create'),
  ('Packing Manage', 'packing.manage', 'packing', 'Catalog permission: packing.manage'),
  ('Packing Operate', 'packing.operate', 'packing', 'Catalog permission: packing.operate'),
  ('Payroll Admin', 'payroll.admin', 'payroll', 'Catalog permission: payroll.admin'),
  ('Payroll Ai', 'payroll.ai', 'payroll', 'Catalog permission: payroll.ai'),
  ('Payroll Approve', 'payroll.approve', 'payroll', 'Catalog permission: payroll.approve'),
  ('Payroll Bank', 'payroll.bank', 'payroll', 'Catalog permission: payroll.bank'),
  ('Payroll Costing', 'payroll.costing', 'payroll', 'Catalog permission: payroll.costing'),
  ('Payroll Manage', 'payroll.manage', 'payroll', 'Catalog permission: payroll.manage'),
  ('Payroll Pay', 'payroll.pay', 'payroll', 'Catalog permission: payroll.pay'),
  ('Payroll Process', 'payroll.process', 'payroll', 'Catalog permission: payroll.process'),
  ('Payroll Self', 'payroll.self', 'payroll', 'Catalog permission: payroll.self'),
  ('Payroll Tax', 'payroll.tax', 'payroll', 'Catalog permission: payroll.tax'),
  ('Payroll View', 'payroll.view', 'payroll', 'Catalog permission: payroll.view'),
  ('Pkg Ai', 'pkg.ai', 'pkg', 'Catalog permission: pkg.ai'),
  ('Pkg Approve', 'pkg.approve', 'pkg', 'Catalog permission: pkg.approve'),
  ('Pkg Manage', 'pkg.manage', 'pkg', 'Catalog permission: pkg.manage'),
  ('Pkg Operate', 'pkg.operate', 'pkg', 'Catalog permission: pkg.operate'),
  ('Pkg View', 'pkg.view', 'pkg', 'Catalog permission: pkg.view'),
  ('Platform Admin', 'platform.admin', 'platform', 'Catalog permission: platform.admin'),
  ('Platform Events', 'platform.events', 'platform', 'Catalog permission: platform.events'),
  ('Platform Flags', 'platform.flags', 'platform', 'Catalog permission: platform.flags'),
  ('Platform Provision', 'platform.provision', 'platform', 'Catalog permission: platform.provision'),
  ('Platform View', 'platform.view', 'platform', 'Catalog permission: platform.view'),
  ('Ppm Admin', 'ppm.admin', 'ppm', 'Catalog permission: ppm.admin'),
  ('Ppm Ai', 'ppm.ai', 'ppm', 'Catalog permission: ppm.ai'),
  ('Ppm Approve', 'ppm.approve', 'ppm', 'Catalog permission: ppm.approve'),
  ('Ppm Execute', 'ppm.execute', 'ppm', 'Catalog permission: ppm.execute'),
  ('Ppm Finance', 'ppm.finance', 'ppm', 'Catalog permission: ppm.finance'),
  ('Ppm Manage', 'ppm.manage', 'ppm', 'Catalog permission: ppm.manage'),
  ('Ppm Plan', 'ppm.plan', 'ppm', 'Catalog permission: ppm.plan'),
  ('Ppm Portal', 'ppm.portal', 'ppm', 'Catalog permission: ppm.portal'),
  ('Ppm View', 'ppm.view', 'ppm', 'Catalog permission: ppm.view'),
  ('Print Admin', 'print.admin', 'print', 'Catalog permission: print.admin'),
  ('Print Ai', 'print.ai', 'print', 'Catalog permission: print.ai'),
  ('Print Design', 'print.design', 'print', 'Catalog permission: print.design'),
  ('Print Manage', 'print.manage', 'print', 'Catalog permission: print.manage'),
  ('Print Operate', 'print.operate', 'print', 'Catalog permission: print.operate'),
  ('Print Security', 'print.security', 'print', 'Catalog permission: print.security'),
  ('Print Submit', 'print.submit', 'print', 'Catalog permission: print.submit'),
  ('Print View', 'print.view', 'print', 'Catalog permission: print.view'),
  ('Printers Manage', 'printers.manage', 'printers', 'Catalog permission: printers.manage'),
  ('Printing Create', 'printing.create', 'printing', 'Catalog permission: printing.create'),
  ('Printing Manage', 'printing.manage', 'printing', 'Catalog permission: printing.manage'),
  ('Printing Reprint', 'printing.reprint', 'printing', 'Catalog permission: printing.reprint'),
  ('Procurement Approve', 'procurement.approve', 'procurement', 'Catalog permission: procurement.approve'),
  ('Procurement Manage', 'procurement.manage', 'procurement', 'Catalog permission: procurement.manage'),
  ('Procurement Suppliers', 'procurement.suppliers', 'procurement', 'Catalog permission: procurement.suppliers'),
  ('Procurement View', 'procurement.view', 'procurement', 'Catalog permission: procurement.view'),
  ('Production Approve', 'production.approve', 'production', 'Catalog permission: production.approve'),
  ('Production Create', 'production.create', 'production', 'Catalog permission: production.create'),
  ('Production Manage', 'production.manage', 'production', 'Catalog permission: production.manage'),
  ('Production View', 'production.view', 'production', 'Catalog permission: production.view'),
  ('Products View', 'products.view', 'products', 'Catalog permission: products.view'),
  ('Profile Ai', 'profile.ai', 'profile', 'Catalog permission: profile.ai'),
  ('Profile Analytics', 'profile.analytics', 'profile', 'Catalog permission: profile.analytics'),
  ('Profile Documents', 'profile.documents', 'profile', 'Catalog permission: profile.documents'),
  ('Profile Manage', 'profile.manage', 'profile', 'Catalog permission: profile.manage'),
  ('Profile Manager', 'profile.manager', 'profile', 'Catalog permission: profile.manager'),
  ('Profile Payroll', 'profile.payroll', 'profile', 'Catalog permission: profile.payroll'),
  ('Profile Security', 'profile.security', 'profile', 'Catalog permission: profile.security'),
  ('Profile Self', 'profile.self', 'profile', 'Catalog permission: profile.self'),
  ('Profile View', 'profile.view', 'profile', 'Catalog permission: profile.view'),
  ('Qr View', 'qr.view', 'qr', 'Catalog permission: qr.view'),
  ('Reports Ai', 'reports.ai', 'reports', 'Catalog permission: reports.ai'),
  ('Reports Assistant', 'reports.assistant', 'reports', 'Catalog permission: reports.assistant'),
  ('Reports Classify', 'reports.classify', 'reports', 'Catalog permission: reports.classify'),
  ('Reports Dashboards', 'reports.dashboards', 'reports', 'Catalog permission: reports.dashboards'),
  ('Reports Documents', 'reports.documents', 'reports', 'Catalog permission: reports.documents'),
  ('Reports Dwh', 'reports.dwh', 'reports', 'Catalog permission: reports.dwh'),
  ('Reports Export', 'reports.export', 'reports', 'Catalog permission: reports.export'),
  ('Reports Intelligence', 'reports.intelligence', 'reports', 'Catalog permission: reports.intelligence'),
  ('Reports Kpis', 'reports.kpis', 'reports', 'Catalog permission: reports.kpis'),
  ('Reports Manage', 'reports.manage', 'reports', 'Catalog permission: reports.manage'),
  ('Reports Regulatory', 'reports.regulatory', 'reports', 'Catalog permission: reports.regulatory'),
  ('Reports Schedule', 'reports.schedule', 'reports', 'Catalog permission: reports.schedule'),
  ('Reports Search', 'reports.search', 'reports', 'Catalog permission: reports.search'),
  ('Reports View', 'reports.view', 'reports', 'Catalog permission: reports.view'),
  ('Sales Admin', 'sales.admin', 'sales', 'Catalog permission: sales.admin'),
  ('Sales Ai', 'sales.ai', 'sales', 'Catalog permission: sales.ai'),
  ('Sales Commissions', 'sales.commissions', 'sales', 'Catalog permission: sales.commissions'),
  ('Sales Contracts', 'sales.contracts', 'sales', 'Catalog permission: sales.contracts'),
  ('Sales Credit', 'sales.credit', 'sales', 'Catalog permission: sales.credit'),
  ('Sales Forecast', 'sales.forecast', 'sales', 'Catalog permission: sales.forecast'),
  ('Sales Manage', 'sales.manage', 'sales', 'Catalog permission: sales.manage'),
  ('Sales Pipeline', 'sales.pipeline', 'sales', 'Catalog permission: sales.pipeline'),
  ('Sales Pricing', 'sales.pricing', 'sales', 'Catalog permission: sales.pricing'),
  ('Sales Quotes', 'sales.quotes', 'sales', 'Catalog permission: sales.quotes'),
  ('Sales Returns', 'sales.returns', 'sales', 'Catalog permission: sales.returns'),
  ('Sales View', 'sales.view', 'sales', 'Catalog permission: sales.view'),
  ('Scm Manage', 'scm.manage', 'scm', 'Catalog permission: scm.manage'),
  ('Scm Risk', 'scm.risk', 'scm', 'Catalog permission: scm.risk'),
  ('Scm Sop', 'scm.sop', 'scm', 'Catalog permission: scm.sop'),
  ('Scm View', 'scm.view', 'scm', 'Catalog permission: scm.view'),
  ('Sd Admin', 'sd.admin', 'sd', 'Catalog permission: sd.admin'),
  ('Sd Agent', 'sd.agent', 'sd', 'Catalog permission: sd.agent'),
  ('Sd Ai', 'sd.ai', 'sd', 'Catalog permission: sd.ai'),
  ('Sd Approve', 'sd.approve', 'sd', 'Catalog permission: sd.approve'),
  ('Sd Change', 'sd.change', 'sd', 'Catalog permission: sd.change'),
  ('Sd Field', 'sd.field', 'sd', 'Catalog permission: sd.field'),
  ('Sd Knowledge', 'sd.knowledge', 'sd', 'Catalog permission: sd.knowledge'),
  ('Sd Major', 'sd.major', 'sd', 'Catalog permission: sd.major'),
  ('Sd Manage', 'sd.manage', 'sd', 'Catalog permission: sd.manage'),
  ('Sd Portal', 'sd.portal', 'sd', 'Catalog permission: sd.portal'),
  ('Sd View', 'sd.view', 'sd', 'Catalog permission: sd.view'),
  ('Security Admin', 'security.admin', 'security', 'Catalog permission: security.admin'),
  ('Security Dual Control', 'security.dual_control', 'security', 'Catalog permission: security.dual_control'),
  ('Settings Branding', 'settings.branding', 'settings', 'Catalog permission: settings.branding'),
  ('Settings Integrations', 'settings.integrations', 'settings', 'Catalog permission: settings.integrations'),
  ('Settings Manage', 'settings.manage', 'settings', 'Catalog permission: settings.manage'),
  ('Settings Sequences', 'settings.sequences', 'settings', 'Catalog permission: settings.sequences'),
  ('Settings View', 'settings.view', 'settings', 'Catalog permission: settings.view'),
  ('Settings Workflows', 'settings.workflows', 'settings', 'Catalog permission: settings.workflows'),
  ('Srm Admin', 'srm.admin', 'srm', 'Catalog permission: srm.admin'),
  ('Srm Ai', 'srm.ai', 'srm', 'Catalog permission: srm.ai'),
  ('Srm Approve', 'srm.approve', 'srm', 'Catalog permission: srm.approve'),
  ('Srm Contracts', 'srm.contracts', 'srm', 'Catalog permission: srm.contracts'),
  ('Srm Manage', 'srm.manage', 'srm', 'Catalog permission: srm.manage'),
  ('Srm Portal', 'srm.portal', 'srm', 'Catalog permission: srm.portal'),
  ('Srm Quality', 'srm.quality', 'srm', 'Catalog permission: srm.quality'),
  ('Srm View', 'srm.view', 'srm', 'Catalog permission: srm.view'),
  ('Ta Admin', 'ta.admin', 'ta', 'Catalog permission: ta.admin'),
  ('Ta Ai', 'ta.ai', 'ta', 'Catalog permission: ta.ai'),
  ('Ta Approve', 'ta.approve', 'ta', 'Catalog permission: ta.approve'),
  ('Ta Manage', 'ta.manage', 'ta', 'Catalog permission: ta.manage'),
  ('Ta Portal', 'ta.portal', 'ta', 'Catalog permission: ta.portal'),
  ('Ta Recruit', 'ta.recruit', 'ta', 'Catalog permission: ta.recruit'),
  ('Ta View', 'ta.view', 'ta', 'Catalog permission: ta.view'),
  ('Tenant Admin', 'tenant.admin', 'tenant', 'Catalog permission: tenant.admin'),
  ('Tenant Manage', 'tenant.manage', 'tenant', 'Catalog permission: tenant.manage'),
  ('Tenant Switch', 'tenant.switch', 'tenant', 'Catalog permission: tenant.switch'),
  ('Tenant View', 'tenant.view', 'tenant', 'Catalog permission: tenant.view'),
  ('Users Manage', 'users.manage', 'users', 'Catalog permission: users.manage'),
  ('Users View', 'users.view', 'users', 'Catalog permission: users.view'),
  ('Uw Admin', 'uw.admin', 'uw', 'Catalog permission: uw.admin'),
  ('Uw Manage', 'uw.manage', 'uw', 'Catalog permission: uw.manage'),
  ('Uw Merge', 'uw.merge', 'uw', 'Catalog permission: uw.merge'),
  ('Uw View', 'uw.view', 'uw', 'Catalog permission: uw.view'),
  ('Verification View', 'verification.view', 'verification', 'Catalog permission: verification.view'),
  ('Wfm Approve', 'wfm.approve', 'wfm', 'Catalog permission: wfm.approve'),
  ('Wfm Field', 'wfm.field', 'wfm', 'Catalog permission: wfm.field'),
  ('Wfm Manage', 'wfm.manage', 'wfm', 'Catalog permission: wfm.manage'),
  ('Wfm Safety', 'wfm.safety', 'wfm', 'Catalog permission: wfm.safety'),
  ('Wfm View', 'wfm.view', 'wfm', 'Catalog permission: wfm.view'),
  ('Wid Manage', 'wid.manage', 'wid', 'Catalog permission: wid.manage'),
  ('Wid View', 'wid.view', 'wid', 'Catalog permission: wid.view')
ON CONFLICT (slug) DO NOTHING;

-- 2) Provision catalog roles and append module/level access
DO $$
DECLARE
  v_modules text[] := ARRAY['dashboard', 'production', 'mes', 'qr', 'lbl', 'printing', 'print', 'packing', 'pkg', 'ast', 'inventory', 'products', 'procurement', 'srm', 'scm', 'logistics', 'crm', 'sales', 'billing', 'invoices', 'dispatch', 'dsp', 'fleet', 'finance', 'payroll', 'hr', 'ta', 'wfm', 'att', 'profile', 'wid', 'di', 'uw', 'iam', 'users', 'sd', 'hc', 'comm', 'media', 'brand', 'reports', 'audit', 'eal', 'fraud', 'verification', 'notifications', 'settings', 'intg', 'ppm', 'ec', 'tenant', 'security', 'distributors'];
  v_levels  text[] := ARRAY['viewer', 'clerk', 'operator', 'specialist', 'supervisor', 'manager', 'director', 'admin'];
  v_variants text[] := ARRAY['core', 'east', 'west', 'central', 'remote'];
  v_company uuid;
  v_mod text;
  v_level text;
  v_variant text;
  v_slug text;
  v_name text;
  v_role_id uuid;
  v_created int := 0;
  v_links int := 0;
  v_prefix text;
BEGIN
  SELECT id INTO v_company
  FROM companies
  WHERE id = 'a0000000-0000-4000-8000-000000000001';

  FOREACH v_variant IN ARRAY v_variants LOOP
    FOREACH v_mod IN ARRAY v_modules LOOP
      FOREACH v_level IN ARRAY v_levels LOOP
        v_slug := 'catalog_' || v_mod || '_' || v_level || '_' || v_variant;
        v_name := initcap(replace(v_mod, '_', ' '))
          || ' '
          || initcap(v_level)
          || ' ('
          || initcap(v_variant)
          || ')';

        SELECT id INTO v_role_id
        FROM roles
        WHERE slug = v_slug
          AND deleted_at IS NULL
        LIMIT 1;

        IF v_role_id IS NULL THEN
          INSERT INTO roles (
            company_id, name, slug, description,
            is_system, is_active, role_category
          )
          VALUES (
            v_company,
            v_name,
            v_slug,
            'Catalog role — '
              || v_mod || ' ' || v_level || ' (' || v_variant
              || '). Seeded for RBAC least-privilege assignment.',
            true,
            true,
            'system'
          )
          RETURNING id INTO v_role_id;
          v_created := v_created + 1;
        END IF;

        -- Baseline access every catalog role gets
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT v_role_id, p.id
        FROM permissions p
        WHERE p.slug IN (
          'dashboard.view',
          'notifications.view',
          'profile.self',
          'profile.view'
        )
        ON CONFLICT DO NOTHING;

        -- Module prefix for permission matching
        v_prefix := v_mod;

        -- Module-scoped access by level
        IF v_level IN ('viewer', 'clerk') THEN
          INSERT INTO role_permissions (role_id, permission_id)
          SELECT v_role_id, p.id
          FROM permissions p
          WHERE p.slug NOT LIKE 'platform.%'
            AND (
              p.slug = v_prefix || '.view'
              OR p.slug LIKE v_prefix || '.%.view'
              OR (v_mod = 'reports' AND p.slug IN ('reports.view', 'reports.export'))
              OR (v_mod = 'audit' AND p.slug IN ('audit.view', 'eal.view'))
              OR (v_mod = 'printing' AND p.slug IN ('print.view', 'printing.create'))
              OR (v_mod = 'print' AND p.slug = 'print.view')
            )
          ON CONFLICT DO NOTHING;

        ELSIF v_level IN ('operator', 'specialist') THEN
          INSERT INTO role_permissions (role_id, permission_id)
          SELECT v_role_id, p.id
          FROM permissions p
          WHERE p.slug NOT LIKE 'platform.%'
            AND (
              p.slug LIKE v_prefix || '.%'
            )
            AND (
              p.slug LIKE '%.view'
              OR p.slug LIKE '%.create'
              OR p.slug LIKE '%.operate'
              OR p.slug LIKE '%.clock'
              OR p.slug LIKE '%.field'
              OR p.slug LIKE '%.submit'
              OR p.slug LIKE '%.print'
              OR p.slug LIKE '%.move'
              OR p.slug LIKE '%.track'
              OR p.slug LIKE '%.design'
              OR p.slug LIKE '%.agent'
              OR p.slug LIKE '%.recruit'
            )
          ON CONFLICT DO NOTHING;

        ELSIF v_level IN ('supervisor', 'manager') THEN
          INSERT INTO role_permissions (role_id, permission_id)
          SELECT v_role_id, p.id
          FROM permissions p
          WHERE p.slug NOT LIKE 'platform.%'
            AND p.slug LIKE v_prefix || '.%'
            AND (
              p.slug LIKE '%.view'
              OR p.slug LIKE '%.manage'
              OR p.slug LIKE '%.operate'
              OR p.slug LIKE '%.create'
              OR p.slug LIKE '%.approve'
              OR p.slug LIKE '%.export'
              OR p.slug LIKE '%.edit'
              OR p.slug LIKE '%.process'
              OR p.slug LIKE '%.post'
              OR p.slug LIKE '%.collect'
            )
          ON CONFLICT DO NOTHING;

        ELSIF v_level = 'director' THEN
          INSERT INTO role_permissions (role_id, permission_id)
          SELECT v_role_id, p.id
          FROM permissions p
          WHERE p.slug NOT LIKE 'platform.%'
            AND (
              p.slug LIKE v_prefix || '.%'
              OR p.slug IN ('reports.view', 'reports.dashboards', 'reports.kpis')
            )
          ON CONFLICT DO NOTHING;

        ELSIF v_level = 'admin' THEN
          INSERT INTO role_permissions (role_id, permission_id)
          SELECT v_role_id, p.id
          FROM permissions p
          WHERE p.slug NOT LIKE 'platform.%'
            AND (
              p.slug LIKE v_prefix || '.%'
              OR p.slug IN ('settings.view', 'reports.view')
            )
          ON CONFLICT DO NOTHING;
        END IF;

      END LOOP;
    END LOOP;
  END LOOP;

  -- 3) Super administrator gets every non-platform permission (append)
  INSERT INTO role_permissions (role_id, permission_id)
  SELECT r.id, p.id
  FROM roles r
  CROSS JOIN permissions p
  WHERE r.slug = 'super_administrator'
    AND p.slug NOT LIKE 'platform.%'
  ON CONFLICT DO NOTHING;

  -- 4) Every active role has dashboard.view (append baseline)
  INSERT INTO role_permissions (role_id, permission_id)
  SELECT r.id, p.id
  FROM roles r
  CROSS JOIN permissions p
  WHERE COALESCE(r.is_active, true) = true
    AND r.deleted_at IS NULL
    AND p.slug = 'dashboard.view'
  ON CONFLICT DO NOTHING;

  -- 5) Existing seed system roles: append module-aligned access where empty-ish
  --    (managing_director gets broad view/manage across business modules)
  INSERT INTO role_permissions (role_id, permission_id)
  SELECT r.id, p.id
  FROM roles r
  CROSS JOIN permissions p
  WHERE r.slug = 'managing_director'
    AND p.slug NOT LIKE 'platform.%'
    AND (
      p.slug LIKE '%.view'
      OR p.slug LIKE '%.manage'
      OR p.slug LIKE '%.approve'
      OR p.slug LIKE '%.export'
      OR p.slug IN ('dashboard.view', 'reports.dashboards', 'reports.kpis')
    )
  ON CONFLICT DO NOTHING;

  INSERT INTO role_permissions (role_id, permission_id)
  SELECT r.id, p.id
  FROM roles r
  CROSS JOIN permissions p
  WHERE r.slug IN ('auditor', 'read_only')
    AND (
      p.slug LIKE '%.view'
      OR p.slug IN (
        'dashboard.view',
        'reports.view',
        'reports.export',
        'audit.view',
        'eal.view'
      )
    )
    AND p.slug NOT LIKE 'platform.%'
  ON CONFLICT DO NOTHING;

  GET DIAGNOSTICS v_links = ROW_COUNT;
  RAISE NOTICE 'Catalog roles created this run: % (target total catalog slugs: %)',
    v_created, 2120;
END $$;

-- Optional verification (commented):
-- SELECT count(*) AS catalog_roles FROM roles WHERE slug LIKE 'catalog_%';
-- SELECT count(*) AS catalog_access
-- FROM role_permissions rp
-- JOIN roles r ON r.id = rp.role_id
-- WHERE r.slug LIKE 'catalog_%';
