export type AttEntityConfig = {
  title: string;
  description: string;
  table: string;
  numberField?: string;
  numberPrefix?: string;
  searchCols?: string[];
  columns: Array<{ key: string; label: string }>;
  fields: Array<{
    key: string;
    label: string;
    type?: "text" | "number" | "date" | "datetime" | "select" | "textarea";
    options?: string[];
    required?: boolean;
    createOnly?: boolean;
    autoNumber?: string;
  }>;
  statusField?: string;
  statusOptions?: string[];
  defaults?: Record<string, unknown>;
};

function cfg(p: AttEntityConfig): AttEntityConfig {
  return {
    searchCols: p.searchCols || ["code", "name", "title", "status", "employee_name", "location_code"],
    ...p,
  };
}

export const ATT_ENTITIES: Record<string, AttEntityConfig> = {
  locations: cfg({
    title: "Attendance Locations",
    description: "HQ, branches, factories, warehouses, project sites with geofence radius",
    table: "att_locations",
    numberField: "location_code",
    numberPrefix: "LOC",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "location_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "location_type", label: "Type" },
      { key: "radius_m", label: "Radius m" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "location_code", label: "Code", required: true, autoNumber: "LOC", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "location_type", label: "Type", type: "select", options: ["hq", "branch", "factory", "warehouse", "project_site", "customer_site", "temporary"] },
      { key: "branch_name", label: "Branch" },
      { key: "building", label: "Building" },
      { key: "department_name", label: "Department" },
      { key: "lat", label: "Latitude", type: "number", required: true },
      { key: "lng", label: "Longitude", type: "number", required: true },
      { key: "radius_m", label: "Radius (m)", type: "number" },
      { key: "wifi_ssids", label: "Wi-Fi SSIDs (comma)" },
      { key: "wifi_bssids", label: "Wi-Fi BSSIDs" },
      { key: "beacon_ids", label: "Beacon IDs" },
      { key: "max_gps_accuracy_m", label: "Max GPS accuracy m", type: "number" },
      { key: "owner_name", label: "Owner" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", location_type: "branch", radius_m: 100, max_gps_accuracy_m: 25 },
  }),

  geofences: cfg({
    title: "Geo-Fencing",
    description: "Circular geofences for clock authorization",
    table: "att_geofences",
    numberField: "fence_code",
    numberPrefix: "GF",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "fence_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "location_code", label: "Location" },
      { key: "radius_m", label: "Radius" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "fence_code", label: "Code", required: true, autoNumber: "GF", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "location_code", label: "Location code" },
      { key: "center_lat", label: "Center lat", type: "number", required: true },
      { key: "center_lng", label: "Center lng", type: "number", required: true },
      { key: "radius_m", label: "Radius m", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", radius_m: 100 },
  }),

  devices: cfg({
    title: "Biometric / Attendance Devices",
    description: "ZKTeco, Suprema, HID, Hikvision and compatible terminals",
    table: "att_devices",
    numberField: "device_code",
    numberPrefix: "DEV",
    statusField: "status",
    statusOptions: ["online", "offline", "error", "maintenance"],
    columns: [
      { key: "device_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "vendor", label: "Vendor" },
      { key: "model", label: "Model" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "device_code", label: "Code", required: true, autoNumber: "DEV", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "vendor", label: "Vendor", type: "select", options: ["zkteco", "suprema", "hikvision", "dahua", "anviz", "fingertec", "essl", "idemia", "hid", "biotime", "generic"] },
      { key: "model", label: "Model" },
      { key: "firmware", label: "Firmware" },
      { key: "serial_number", label: "Serial" },
      { key: "ip_address", label: "IP" },
      { key: "mac_address", label: "MAC" },
      { key: "branch_name", label: "Branch" },
      { key: "building", label: "Building" },
      { key: "door_gate", label: "Door/Gate" },
      { key: "status", label: "Status", type: "select", options: ["online", "offline", "error", "maintenance"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "offline", vendor: "generic" },
  }),

  events: cfg({
    title: "Attendance Events",
    description: "Raw clock punches with verification metadata",
    table: "att_events",
    numberField: "event_code",
    numberPrefix: "EVT",
    statusField: "verification_status",
    statusOptions: ["pending", "approved", "rejected", "flagged"],
    columns: [
      { key: "event_code", label: "Code" },
      { key: "employee_name", label: "Employee" },
      { key: "event_type", label: "Type" },
      { key: "location_name", label: "Location" },
      { key: "method", label: "Method" },
      { key: "verification_status", label: "Status" },
    ],
    fields: [
      { key: "event_code", label: "Code", autoNumber: "EVT", createOnly: true },
      { key: "employee_name", label: "Employee", required: true },
      { key: "event_type", label: "Type", type: "select", options: ["clock_in", "clock_out", "break_start", "break_end"] },
      { key: "work_date", label: "Date", type: "date" },
      { key: "location_name", label: "Location" },
      { key: "method", label: "Method", type: "select", options: ["app", "web", "gps", "wifi", "beacon", "qr", "nfc", "rfid", "biometric", "terminal", "manual"] },
      { key: "lat", label: "Lat", type: "number" },
      { key: "lng", label: "Lng", type: "number" },
      { key: "gps_accuracy_m", label: "GPS accuracy", type: "number" },
      { key: "distance_m", label: "Distance m", type: "number" },
      { key: "verification_status", label: "Verification", type: "select", options: ["pending", "approved", "rejected", "flagged"] },
      { key: "project_code", label: "Project" },
      { key: "notes", label: "Reject reason", type: "textarea" },
    ],
    defaults: { event_type: "clock_in", verification_status: "approved", method: "manual" },
  }),

  policies: cfg({
    title: "Attendance Policies",
    description: "Grace, geofence, OT, remote/field rules",
    table: "att_policies",
    numberField: "policy_code",
    numberPrefix: "POL",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "policy_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "grace_minutes", label: "Grace" },
      { key: "require_geofence", label: "Geofence" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "policy_code", label: "Code", required: true, autoNumber: "POL", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "grace_minutes", label: "Grace minutes", type: "number" },
      { key: "overtime_threshold_hours", label: "OT after hours", type: "number" },
      { key: "max_gps_accuracy_m", label: "Max GPS accuracy", type: "number" },
      { key: "assignment_scope", label: "Scope", type: "select", options: ["company", "branch", "department", "position", "shift", "employee"] },
      { key: "scope_value", label: "Scope value" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", grace_minutes: 10, assignment_scope: "company", overtime_threshold_hours: 8 },
  }),

  rotations: cfg({
    title: "Shift Rotations",
    description: "Multi-day rotation patterns",
    table: "att_shift_rotations",
    numberField: "rotation_code",
    numberPrefix: "ROT",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "rotation_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "cycle_days", label: "Cycle days" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "rotation_code", label: "Code", autoNumber: "ROT", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "cycle_days", label: "Cycle days", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", cycle_days: 7 },
  }),

  swaps: cfg({
    title: "Shift Swaps",
    description: "Employee shift swap requests",
    table: "att_shift_swaps",
    numberField: "swap_number",
    numberPrefix: "SWP",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected", "cancelled"],
    columns: [
      { key: "swap_number", label: "Number" },
      { key: "requester_name", label: "Requester" },
      { key: "partner_name", label: "Partner" },
      { key: "work_date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "swap_number", label: "Number", autoNumber: "SWP", createOnly: true },
      { key: "requester_name", label: "Requester", required: true },
      { key: "partner_name", label: "Partner" },
      { key: "work_date", label: "Date", type: "date" },
      { key: "shift_code", label: "Shift code" },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected", "cancelled"] },
    ],
    defaults: { status: "pending" },
  }),

  breaks: cfg({
    title: "Break Management",
    description: "Paid and unpaid break types",
    table: "att_breaks",
    numberField: "break_code",
    numberPrefix: "BRK",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "break_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "duration_minutes", label: "Minutes" },
      { key: "is_paid", label: "Paid" },
    ],
    fields: [
      { key: "break_code", label: "Code", autoNumber: "BRK", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "duration_minutes", label: "Duration minutes", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
    defaults: { status: "active", duration_minutes: 30 },
  }),

  holidays: cfg({
    title: "Holiday Calendar",
    description: "Public and company holidays",
    table: "att_holidays",
    numberField: "holiday_code",
    numberPrefix: "HOL",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "holiday_code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "holiday_date", label: "Date" },
      { key: "is_paid", label: "Paid" },
    ],
    fields: [
      { key: "holiday_code", label: "Code", autoNumber: "HOL", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "holiday_date", label: "Date", type: "date", required: true },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active" },
  }),

  corrections: cfg({
    title: "Attendance Corrections",
    description: "Correction requests with digital approval",
    table: "att_corrections",
    numberField: "correction_number",
    numberPrefix: "COR",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected"],
    columns: [
      { key: "correction_number", label: "Number" },
      { key: "employee_name", label: "Employee" },
      { key: "work_date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "correction_number", label: "Number", autoNumber: "COR", createOnly: true },
      { key: "employee_name", label: "Employee", required: true },
      { key: "work_date", label: "Work date", type: "date", required: true },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected"] },
      { key: "digital_signature", label: "Signature token" },
    ],
    defaults: { status: "pending" },
  }),

  approvals: cfg({
    title: "Attendance Approvals",
    description: "Corrections, remote work, field approvals",
    table: "att_approvals",
    numberField: "approval_number",
    numberPrefix: "AAP",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected"],
    columns: [
      { key: "approval_number", label: "Number" },
      { key: "title", label: "Title" },
      { key: "entity_type", label: "Type" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "approval_number", label: "Number", autoNumber: "AAP", createOnly: true },
      { key: "title", label: "Title", required: true },
      { key: "entity_type", label: "Entity type", required: true },
      { key: "entity_code", label: "Entity code" },
      { key: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected"] },
      { key: "decision_notes", label: "Decision notes", type: "textarea" },
    ],
    defaults: { status: "pending" },
  }),

  qr: cfg({
    title: "QR Attendance Tokens",
    description: "Time-limited rotating QR checkpoint tokens",
    table: "att_qr_tokens",
    numberField: "token_code",
    numberPrefix: "QR",
    statusField: "status",
    statusOptions: ["active", "expired", "revoked"],
    columns: [
      { key: "token_code", label: "Token" },
      { key: "location_code", label: "Location" },
      { key: "valid_until", label: "Valid until" },
      { key: "use_count", label: "Uses" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "token_code", label: "Token", required: true, autoNumber: "QR", createOnly: true },
      { key: "location_code", label: "Location code" },
      { key: "valid_until", label: "Valid until", type: "datetime", required: true },
      { key: "max_uses", label: "Max uses", type: "number" },
      { key: "status", label: "Status", type: "select", options: ["active", "expired", "revoked"] },
    ],
    defaults: { status: "active", max_uses: 0 },
  }),

  beacons: cfg({
    title: "Bluetooth Beacons",
    description: "BLE beacon IDs for site verification",
    table: "att_beacons",
    numberField: "beacon_code",
    numberPrefix: "BCN",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "beacon_code", label: "Code" },
      { key: "uuid_value", label: "UUID" },
      { key: "location_name", label: "Location" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "beacon_code", label: "Code", autoNumber: "BCN", createOnly: true },
      { key: "uuid_value", label: "UUID" },
      { key: "major_id", label: "Major", type: "number" },
      { key: "minor_id", label: "Minor", type: "number" },
      { key: "location_name", label: "Location" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
    defaults: { status: "active" },
  }),

  nfc: cfg({
    title: "NFC Checkpoints",
    description: "NFC tags at entrances and zones",
    table: "att_nfc_tags",
    numberField: "tag_code",
    numberPrefix: "NFC",
    statusField: "status",
    statusOptions: ["active", "inactive"],
    columns: [
      { key: "tag_code", label: "Code" },
      { key: "tag_uid", label: "UID" },
      { key: "location_name", label: "Location" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "tag_code", label: "Code", autoNumber: "NFC", createOnly: true },
      { key: "tag_uid", label: "Tag UID", required: true },
      { key: "location_name", label: "Location" },
      { key: "status", label: "Status", type: "select", options: ["active", "inactive"] },
    ],
    defaults: { status: "active" },
  }),

  rfid: cfg({
    title: "RFID Badges",
    description: "Employee RFID badge mapping",
    table: "att_rfid_badges",
    numberField: "badge_code",
    numberPrefix: "RFID",
    statusField: "status",
    statusOptions: ["active", "lost", "revoked"],
    columns: [
      { key: "badge_code", label: "Badge" },
      { key: "rfid_uid", label: "UID" },
      { key: "employee_name", label: "Employee" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "badge_code", label: "Badge code", autoNumber: "RFID", createOnly: true },
      { key: "rfid_uid", label: "RFID UID", required: true },
      { key: "employee_name", label: "Employee" },
      { key: "status", label: "Status", type: "select", options: ["active", "lost", "revoked"] },
    ],
    defaults: { status: "active" },
  }),

  remote: cfg({
    title: "Remote Work Requests",
    description: "Approved remote/hybrid attendance exceptions",
    table: "att_remote_work",
    numberField: "request_number",
    numberPrefix: "RMT",
    statusField: "status",
    statusOptions: ["pending", "approved", "rejected"],
    columns: [
      { key: "request_number", label: "Number" },
      { key: "employee_name", label: "Employee" },
      { key: "work_date", label: "Date" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "request_number", label: "Number", autoNumber: "RMT", createOnly: true },
      { key: "employee_name", label: "Employee", required: true },
      { key: "work_date", label: "Date", type: "date" },
      { key: "reason", label: "Reason", type: "textarea" },
      { key: "status", label: "Status", type: "select", options: ["pending", "approved", "rejected"] },
    ],
    defaults: { status: "pending" },
  }),

  "field-assignments": cfg({
    title: "Field Assignments",
    description: "Authorized off-site work locations",
    table: "att_field_assignments",
    numberField: "assignment_code",
    numberPrefix: "FLD",
    statusField: "status",
    statusOptions: ["active", "completed", "cancelled"],
    columns: [
      { key: "assignment_code", label: "Code" },
      { key: "employee_name", label: "Employee" },
      { key: "project_code", label: "Project" },
      { key: "customer_name", label: "Customer" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "assignment_code", label: "Code", autoNumber: "FLD", createOnly: true },
      { key: "employee_name", label: "Employee", required: true },
      { key: "project_code", label: "Project" },
      { key: "work_order_ref", label: "Work order" },
      { key: "customer_name", label: "Customer" },
      { key: "site_lat", label: "Site lat", type: "number" },
      { key: "site_lng", label: "Site lng", type: "number" },
      { key: "radius_m", label: "Radius m", type: "number" },
      { key: "start_date", label: "Start", type: "date" },
      { key: "end_date", label: "End", type: "date" },
      { key: "status", label: "Status", type: "select", options: ["active", "completed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "active", radius_m: 200 },
  }),

  violations: cfg({
    title: "Fraud & Policy Violations",
    description: "Geofence, mock GPS, duplicate, buddy punch",
    table: "att_violations",
    numberField: "violation_code",
    numberPrefix: "VIO",
    statusField: "status",
    statusOptions: ["open", "investigating", "closed"],
    columns: [
      { key: "violation_code", label: "Code" },
      { key: "employee_name", label: "Employee" },
      { key: "violation_type", label: "Type" },
      { key: "severity", label: "Severity" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "violation_code", label: "Code", autoNumber: "VIO", createOnly: true },
      { key: "employee_name", label: "Employee" },
      { key: "violation_type", label: "Type", type: "select", options: ["outside_geofence", "mock_gps", "duplicate", "buddy_punch", "time_tamper", "impossible_travel"], required: true },
      { key: "details", label: "Details", type: "textarea" },
      { key: "severity", label: "Severity", type: "select", options: ["low", "medium", "high", "critical"] },
      { key: "status", label: "Status", type: "select", options: ["open", "investigating", "closed"] },
    ],
    defaults: { status: "open", severity: "medium" },
  }),

  notifications: cfg({
    title: "Attendance Notifications",
    description: "Missed clock, approvals, device alerts",
    table: "att_notifications",
    columns: [
      { key: "title", label: "Title" },
      { key: "severity", label: "Severity" },
      { key: "employee_name", label: "Employee" },
      { key: "created_at", label: "When" },
    ],
    fields: [
      { key: "title", label: "Title", required: true },
      { key: "body", label: "Body", type: "textarea" },
      { key: "severity", label: "Severity", type: "select", options: ["info", "warning", "critical"] },
      { key: "category", label: "Category" },
      { key: "employee_name", label: "Employee" },
    ],
    defaults: { severity: "info", category: "general" },
  }),

  settings: cfg({
    title: "Attendance Settings",
    description: "Company attendance configuration",
    table: "att_settings",
    columns: [
      { key: "setting_key", label: "Key" },
      { key: "setting_value", label: "Value" },
      { key: "description", label: "Description" },
    ],
    fields: [
      { key: "setting_key", label: "Key", required: true, createOnly: true },
      { key: "setting_value", label: "Value (JSON)", required: true },
      { key: "description", label: "Description" },
    ],
  }),

  audit: cfg({
    title: "Attendance Audit Logs",
    description: "Immutable attendance actions",
    table: "att_audit_log",
    columns: [
      { key: "action", label: "Action" },
      { key: "entity_type", label: "Entity" },
      { key: "details", label: "Details" },
      { key: "created_at", label: "When" },
    ],
    fields: [
      { key: "action", label: "Action", required: true },
      { key: "entity_type", label: "Entity type" },
      { key: "details", label: "Details", type: "textarea" },
    ],
  }),

  history: cfg({
    title: "Attendance History",
    description: "Daily attendance records",
    table: "attendance_records",
    statusField: "status",
    statusOptions: ["present", "absent", "late", "completed", "on_leave"],
    columns: [
      { key: "work_date", label: "Date" },
      { key: "check_in", label: "In" },
      { key: "check_out", label: "Out" },
      { key: "hours_worked", label: "Hours" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { key: "work_date", label: "Date", type: "date", required: true },
      { key: "status", label: "Status", type: "select", options: ["present", "absent", "late", "completed", "on_leave"] },
      { key: "location_name", label: "Location" },
      { key: "hours_worked", label: "Hours", type: "number" },
      { key: "late_minutes", label: "Late min", type: "number" },
      { key: "overtime_minutes", label: "OT min", type: "number" },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "present" },
  }),

  "shift-assignments": cfg({
    title: "Shift Assignments",
    description: "Employee shift schedule",
    table: "shift_assignments",
    statusField: "status",
    statusOptions: ["scheduled", "confirmed", "completed", "cancelled"],
    columns: [
      { key: "work_date", label: "Date" },
      { key: "status", label: "Status" },
      { key: "location", label: "Location" },
    ],
    fields: [
      { key: "work_date", label: "Work date", type: "date", required: true },
      { key: "location", label: "Location" },
      { key: "status", label: "Status", type: "select", options: ["scheduled", "confirmed", "completed", "cancelled"] },
      { key: "notes", label: "Notes", type: "textarea" },
    ],
    defaults: { status: "scheduled" },
  }),

  shifts: cfg({
    title: "Shift Templates",
    description: "Fixed and flexible shift definitions",
    table: "shift_templates",
    numberField: "code",
    numberPrefix: "SHF",
    columns: [
      { key: "code", label: "Code" },
      { key: "name", label: "Name" },
      { key: "start_time", label: "Start" },
      { key: "end_time", label: "End" },
      { key: "is_night", label: "Night" },
    ],
    fields: [
      { key: "code", label: "Code", required: true, autoNumber: "SHF", createOnly: true },
      { key: "name", label: "Name", required: true },
      { key: "start_time", label: "Start time", required: true },
      { key: "end_time", label: "End time", required: true },
      { key: "break_minutes", label: "Break min", type: "number" },
      { key: "grace_minutes", label: "Grace min", type: "number" },
    ],
    defaults: { break_minutes: 60, grace_minutes: 10 },
  }),
};

export const ATT_ENTITY_ALIASES: Record<string, string> = {
  calendar: "history",
  my: "history",
  rules: "policies",
  "working-hours": "policies",
  overtime: "policies",
  field: "field-assignments",
  gps: "locations",
  wifi: "locations",
  machines: "devices",
  "device-monitor": "devices",
  "device-sync": "devices",
  payroll: "history",
  compliance: "violations",
};
