/** Complete Workforce Attendance navigation */

export const ATT_MENU = [
  { title: "Attendance Dashboard", href: "/dashboard/attendance", group: "Overview" },
  { title: "Live Attendance", href: "/dashboard/attendance/live", group: "Overview" },
  { title: "Clock In / Clock Out", href: "/dashboard/attendance/clock", group: "Overview" },
  { title: "My Attendance", href: "/dashboard/attendance/my", group: "Overview" },
  { title: "Attendance Calendar", href: "/dashboard/attendance/calendar", group: "Records" },
  { title: "Attendance History", href: "/dashboard/attendance/history", group: "Records" },
  { title: "Attendance Events", href: "/dashboard/attendance/events", group: "Records" },
  { title: "Attendance Corrections", href: "/dashboard/attendance/corrections", group: "Records" },
  { title: "Attendance Approvals", href: "/dashboard/attendance/approvals", group: "Records" },
  { title: "Attendance Policies", href: "/dashboard/attendance/policies", group: "Policies" },
  { title: "Attendance Rules", href: "/dashboard/attendance/rules", group: "Policies" },
  { title: "Working Hours", href: "/dashboard/attendance/working-hours", group: "Policies" },
  { title: "Overtime", href: "/dashboard/attendance/overtime", group: "Policies" },
  { title: "Holiday Calendar", href: "/dashboard/attendance/holidays", group: "Policies" },
  { title: "Break Management", href: "/dashboard/attendance/breaks", group: "Policies" },
  { title: "Shift Management", href: "/dashboard/attendance/shifts", group: "Shifts" },
  { title: "Shift Rotations", href: "/dashboard/attendance/rotations", group: "Shifts" },
  { title: "Shift Assignments", href: "/dashboard/attendance/shift-assignments", group: "Shifts" },
  { title: "Shift Swaps", href: "/dashboard/attendance/swaps", group: "Shifts" },
  { title: "Remote Work", href: "/dashboard/attendance/remote", group: "Field" },
  { title: "Field Workforce", href: "/dashboard/attendance/field", group: "Field" },
  { title: "Field Assignments", href: "/dashboard/attendance/field-assignments", group: "Field" },
  { title: "Geo-Fencing", href: "/dashboard/attendance/geofences", group: "Locations" },
  { title: "Attendance Locations", href: "/dashboard/attendance/locations", group: "Locations" },
  { title: "GPS Verification", href: "/dashboard/attendance/gps", group: "Locations" },
  { title: "Wi-Fi Verification", href: "/dashboard/attendance/wifi", group: "Locations" },
  { title: "Bluetooth Beacons", href: "/dashboard/attendance/beacons", group: "Locations" },
  { title: "QR Attendance", href: "/dashboard/attendance/qr", group: "Locations" },
  { title: "NFC Attendance", href: "/dashboard/attendance/nfc", group: "Locations" },
  { title: "RFID Badges", href: "/dashboard/attendance/rfid", group: "Locations" },
  { title: "Machine Integrations", href: "/dashboard/attendance/integrations", group: "Devices" },
  { title: "ZKTeco Setup", href: "/dashboard/attendance/integrations/zkteco", group: "Devices" },
  { title: "Hikvision Setup", href: "/dashboard/attendance/integrations/hikvision", group: "Devices" },
  { title: "Biometric Devices", href: "/dashboard/attendance/devices", group: "Devices" },
  { title: "Device User Mapping", href: "/dashboard/attendance/device-users", group: "Devices" },
  { title: "Device Punch Queue", href: "/dashboard/attendance/device-punches", group: "Devices" },
  { title: "Integration Settings", href: "/dashboard/attendance/device-integrations", group: "Devices" },
  { title: "Device Synchronization", href: "/dashboard/attendance/device-sync", group: "Devices" },
  { title: "Attendance Machines", href: "/dashboard/attendance/machines", group: "Devices" },
  { title: "Device Monitoring", href: "/dashboard/attendance/device-monitor", group: "Devices" },
  { title: "Fraud Violations", href: "/dashboard/attendance/violations", group: "Compliance" },
  { title: "Payroll Integration", href: "/dashboard/attendance/payroll", group: "Integration" },
  { title: "Attendance Reports", href: "/dashboard/attendance/reports", group: "Analytics" },
  { title: "Compliance Reports", href: "/dashboard/attendance/compliance", group: "Analytics" },
  { title: "AI Attendance Insights", href: "/dashboard/attendance/ai", group: "Analytics" },
  { title: "Notifications", href: "/dashboard/attendance/notifications", group: "System" },
  { title: "Audit Logs", href: "/dashboard/attendance/audit", group: "System" },
  { title: "Attendance Settings", href: "/dashboard/attendance/settings", group: "System" },
] as const;
