/** Secure PDF / document print generation for security paper products */

import { hashPayload, buildSecurityOverlay, type SecurityOptions } from "./security";

export interface SecurePdfInput {
  title: string;
  companyName?: string;
  documentType?: string;
  bodyHtml?: string;
  watermark?: string;
  microtext?: string;
  antiCopyBg?: boolean;
  serial?: string;
  pages?: number;
  signature?: boolean;
  fields?: Record<string, string>;
}

export function generateSecureDocumentHtml(input: SecurePdfInput): {
  html: string;
  verificationCode: string;
  signatureHash: string;
} {
  const company = input.companyName || "SecureTrack ERP";
  const serial = input.serial || `SEC-${Date.now().toString(36).toUpperCase()}`;
  const watermark = input.watermark || "AUTHENTIC · SECURETRACK GROUP";
  const microtext = input.microtext || "HOPE-SECURE-TRACK-MICRO-ANTI-COPY";
  const secOpts: SecurityOptions = {
    watermark,
    microtext,
    tamperQr: true,
    digitalSignature: input.signature !== false,
    hologramZone: true,
    uvPlaceholder: true,
    serialPrefix: "SEC",
    backgroundPattern: "guilloche",
  };
  const overlay = buildSecurityOverlay(secOpts);
  const signatureHash = hashPayload(`${serial}|${input.title}|${company}`);
  const verificationCode = `QR-PDF-${signatureHash.slice(0, 8)}`;

  const fieldRows = Object.entries(input.fields || {})
    .map(([k, v]) => `<tr><td style="padding:4px 8px;border:1px solid #e5e5e5;font-size:12px;color:#555">${k}</td><td style="padding:4px 8px;border:1px solid #e5e5e5;font-size:12px">${v}</td></tr>`)
    .join("");

  const antiCopy = input.antiCopyBg !== false
    ? `
    .anti-copy{
      background-image:
        repeating-linear-gradient(45deg, transparent, transparent 8px, rgba(13,115,119,0.03) 8px, rgba(13,115,119,0.03) 16px),
        repeating-linear-gradient(-45deg, transparent, transparent 10px, rgba(27,38,59,0.025) 10px, rgba(27,38,59,0.025) 20px);
    }
    .void-copy{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;
      font-size:72px;font-weight:900;color:rgba(200,0,0,0.04);transform:rotate(-30deg);pointer-events:none;letter-spacing:8px}
    `
    : "";

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"/>
<title>${input.title}</title>
<style>
  @page { size: A4; margin: 18mm; }
  body{font-family:Inter,system-ui,sans-serif;color:#1a1a1a;margin:0;position:relative}
  ${overlay.css}
  ${antiCopy}
  .page{min-height:260mm;padding:24px;position:relative;box-sizing:border-box}
  h1{color:#0D7377;font-size:20px;margin:0 0 4px}
  .sub{font-size:11px;color:#666;margin-bottom:16px}
  .body{font-size:13px;line-height:1.5;position:relative;z-index:1}
  table{border-collapse:collapse;width:100%;margin:12px 0}
  .footer{position:absolute;bottom:16px;left:24px;right:24px;font-size:9px;color:#666;
    border-top:1px solid #ddd;padding-top:8px;display:flex;justify-content:space-between}
  .serial{font-family:ui-monospace,monospace;font-size:10px}
</style></head>
<body>
<div class="page anti-copy">
  ${overlay.html.replace("{{hash}}", signatureHash)}
  ${input.antiCopyBg !== false ? `<div class="void-copy">VOID IF COPIED</div>` : ""}
  <h1>${company}</h1>
  <div class="sub">${input.title} · ${input.documentType || "security"} · ${serial}</div>
  <div class="body">
    ${input.bodyHtml || "<p>Security document generated by SecureTrack ERP Print Platform.</p>"}
    ${fieldRows ? `<table>${fieldRows}</table>` : ""}
  </div>
  <div class="footer">
    <span class="serial">${serial} · Verify ${verificationCode}</span>
    <span>SIG:${signatureHash} · Confidential</span>
  </div>
</div>
</body></html>`;

  return { html, verificationCode, signatureHash };
}

export function generateProductLabelVars(input: {
  productName: string;
  sku?: string;
  serial: string;
  batch?: string;
  mfgDate?: string;
  expiryDate?: string;
  line?: string;
  quality?: string;
  verifyBase?: string;
}): Record<string, string> {
  const base = input.verifyBase || "https://hope-securetrack.vercel.app/verify";
  return {
    product_name: input.productName,
    sku: input.sku || "",
    serial: input.serial,
    batch: input.batch || "",
    mfg_date: input.mfgDate || "",
    expiry_date: input.expiryDate || "",
    production_line: input.line || "",
    quality_status: input.quality || "approved",
    qr_payload: `${base}?s=${encodeURIComponent(input.serial)}`,
  };
}

export function generateIdCardVars(input: {
  fullName: string;
  employeeNumber?: string;
  department?: string;
  title?: string;
  rfid?: string;
  expiry?: string;
}): Record<string, string> {
  return {
    full_name: input.fullName,
    employee_number: input.employeeNumber || "",
    department: input.department || "",
    title: input.title || "",
    job_title: input.title || "",
    rfid_number: input.rfid || "",
    expiry_date: input.expiry || "",
    id_token: JSON.stringify({
      t: "wid",
      id: input.employeeNumber,
      n: input.fullName,
      exp: input.expiry,
    }),
  };
}

export function estimatePrintCost(params: {
  pages?: number;
  labels?: number;
  color?: boolean;
  pageCost?: number;
  labelCost?: number;
}): number {
  const pageCost = params.pageCost ?? (params.color ? 0.15 : 0.04);
  const labelCost = params.labelCost ?? 0.02;
  return Number(
    ((params.pages || 0) * pageCost + (params.labels || 0) * labelCost).toFixed(4)
  );
}
